### ISSUE TITLE
AQL: Could not extract custom attribute

### ISSUE THREAD

**Issue by Queatz** [arangodb/arangodb#10062]
It said to please report, so here it is.

Here's my version string:

`arangosh (ArangoDB 3.4.8 [linux] 64bit, using jemalloc, build tags/v3.4.8-0-g0952837c2a, VPack 0.1.33, RocksDB 5.16.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.1.0k  28 May 2019)`

Bug:

```
Error: 4 - AQL: Could not extract custom attribute. (exception location: /work/ArangoDB/lib/Basics/VelocyPackHelper.cpp:808). Please report this error to arangodb.com (while executing) (exception location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:228). Please report this error to arangodb.com
	at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:53)
	at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:149)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:128)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:42)
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:132)
	at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:47)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:73)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:53)
	at com.arangodb.internal.ArangoDatabaseImpl.query(ArangoDatabaseImpl.java:197)
```

Note: Same error after upgrading to `ArangoDB 3.5.0 [linux] 64bit`

This is interesting, if the ArangoDB instance is on the same thread as the query, I get the error above.  If they're on separate threads, that query locks up and never returns (I let it run for 10 minutes).  If I log into `arangosh` and profile the query it runs in just a few ms.  There's only 23k objects in my database.

Here is the explain if it helps:

```aql
Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
 14   SubqueryNode           1     - LET #4 = ...   /* const subquery */
  2   SingletonNode          1       * ROOT
 39   IndexNode             47         - FOR x IN entities   /* hash index scan */
 10   SubqueryNode          47           - LET #2 = ...   /* subquery */
  4   SingletonNode          1             * ROOT
 40   IndexNode             10               - FOR member IN entities   /* hash index scan */
 43   CalculationNode       10                 - LET #13 = (((member.`muted` != true) && (member.`kind` == "group.member")) && (member.`from` == x.`_id`))   /* simple expression */   /* collections used: member : entities, x : entities */
  7   FilterNode            10                 - FILTER #13
 37   LimitNode              1                 - LIMIT 0, 1
  8   CalculationNode        1                 - LET #15 = member.`subscribed`   /* attribute expression */   /* collections used: member : entities */
  9   ReturnNode             1                 - RETURN #15
 42   CalculationNode       47           - LET #17 = (FIRST(#2) == true)   /* simple expression */
 12   FilterNode            47           - FILTER #17
 13   ReturnNode            47           - RETURN x
 32   SubqueryNode           1     - LET #10 = ...   /* const subquery */
 15   SingletonNode          1       * ROOT
 38   IndexNode            335         - FOR x IN entities   /* geo1 index scan */
 25   SubqueryNode         335           - LET #8 = ...   /* subquery */
 19   SingletonNode          1             * ROOT
 41   IndexNode             10               - FOR member IN entities   /* hash index scan */
 44   CalculationNode       10                 - LET #21 = ((member.`kind` == "group.member") && (member.`from` == x.`_id`))   /* simple expression */   /* collections used: member : entities, x : entities */
 22   FilterNode            10                 - FILTER #21
 36   LimitNode              1                 - LIMIT 0, 1
 23   CalculationNode        1                 - LET #23 = member.`muted`   /* attribute expression */   /* collections used: member : entities */
 24   ReturnNode             1                 - RETURN #23
 26   CalculationNode      335           - LET #25 = ((x.`kind` == "phone") && (FIRST(#8) != true))   /* simple expression */   /* collections used: x : entities */
 27   FilterNode           335           - FILTER #25
 28   CalculationNode      335           - LET #27 = DATE_TIMESTAMP(x.`updated`)   /* simple expression */   /* collections used: x : entities */
 29   SortNode             335           - SORT #27 DESC
 30   LimitNode            335           - LIMIT 0, 2000
 31   ReturnNode           335           - RETURN x
 33   CalculationNode        1     - LET #29 = APPEND(#4, #10, true)   /* simple expression */
 34   EnumerateListNode    100     - FOR phone IN #29   /* list iteration */
 35   ReturnNode           100       - RETURN phone

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields       Ranges
 39   hash   entities     false    false         2.09 %   [ `kind` ]   (x.`kind` == "phone")
 40   hash   entities     false    false         9.25 %   [ `to` ]     (member.`to` == 46402742)
 38   geo1   entities     false    true             n/a   [ `geo` ]    (GEO_DISTANCE([ -97.7267489, 30.2628376 ], [ x.`geo`[1], x.`geo`[0] ]) < 4)
 41   hash   entities     false    false         9.25 %   [ `to` ]     (member.`to` == 46402742)

Functions used:
 Name             Deterministic   Cacheable   Uses V8
 FIRST            true            true        false  
 DATE_TIMESTAMP   true            true        false  
 APPEND           true            true        false  

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   optimize-subqueries
  4   move-calculations-up-2
  5   move-filters-up-2
  6   geo-index-optimizer
  7   use-indexes
  8   remove-filter-covered-by-index
  9   remove-unnecessary-calculations-2
 10   move-calculations-down
```

**Comment by jsteemann** [comment]
@queatz: Thanks for reporting this.
Is it possible to create a debug package of that query and post it here? That would provide us with the actual query string and some (anonymized) example data plus the index setup.
A debug package can be created in ArangoDB's web UI, in the query editor.

**Comment by Queatz** [comment]
Here it is from my local.  I have only been able to reproduce the bug on the server instance. The query actually works fine on the server when there's a small number of results. Only in groups with ~10+ members (that will be returned by the query) does the bug appear.

[debugDump.zip](https://github.com/arangodb/arangodb/files/3645063/debugDump.zip)

Here's a screenshot of the indexes:

![Screenshot from 2019-09-23 22-23-24](https://user-images.githubusercontent.com/540620/65478823-ced00500-de50-11e9-992f-1d0558e5f5ad.png)

**Comment by jsteemann** [comment]
Fixed via the above PRs, targeting ArangoDB versions 3.4.9 and 3.5.2.
