### ISSUE TITLE
Corrupted collection by creating indices programtically

### ISSUE THREAD

**Issue by imtrobin** [arangodb/arangodb#10172]
Hi, I found a reproducible case where I can corrupt a collection. When I startup, I programtically check the database and create the collection/indices like so (using arangodoclient C#)

```
db.CreateCollection (collectionName, collectionType, waitForSync: true);
db.Advanced.EnsureIndex (collectionName, indicesData);

```
In Debug build, it runs fine, the indices is created properly. 

![image](https://user-images.githubusercontent.com/531606/66279140-fd82bc80-e8e1-11e9-88d8-94cedd50441f.png)

In release build, the EnsureIndex will throw

```
 Exception ServerSystem setup:Input string '0.5' is not a valid integer. Path 'selectivityEstimate', line 1, position 117.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at ArangoDB.Client.Serialization.DocumentSerializer.Deserialize[T](Stream stream) in D:\XXX\ThirdParty\arangoclient.net\src\ArangoDB.Client\Serialization\DocumentSerializer.cs:line 30
   at ArangoDB.Client.Http.HttpCommand.RequestMergedResult[T](Object data) in D:\XXX\ThirdParty\arangoclient.net\src\ArangoDB.Client\Http\HttpCommand.cs:line 196
   at ArangoDB.Client.Advanced.AdvancedOperation.EnsureIndexAsync(String collection, EnsureIndexData data, Action`1 baseResult) in D:\XXX\ThirdParty\arangoclient.net\src\ArangoDB.Client\Advanced\AdvancedOperation.cs:line 82
   at ArangoDB.Client.Utility.TaskUtils.ResultSynchronizer[T](Task`1 task) in D:\XXX\ThirdParty\arangoclient.net\src\ArangoDB.Client\Utility\SynchronizionUtils.cs:line 33
   at ArangoDB.Client.Advanced.AdvancedOperation.EnsureIndex(String collection, EnsureIndexData data, Action`1 baseResult) in D:\XXX\ThirdParty\arangoclient.net\src\ArangoDB.Client\Advanced\AdvancedOperation.cs:line 61
```
 
After I run the release build with above error, the error will persist even after switching back to Debug build. I need to delete the collection.

* __ArangoDB Version__:        3.4.4
* __Storage Engine__:          MMFile
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start |
* __Infrastructure__:               own
* __Operating System__:       Centos 7

**Comment by jsteemann** [comment]
@imtrobin : it looks like the collection is created fine, but that the c# connector has a problem reading the serialized collection data. If that's true then working with the collection in ArangoDB (e.g. via the web interface - not using it from c#) doesn't exhibit any problems. Is that correct?

**Comment by ObiWahn** [comment]
It looks like your json parser expects an int, looks more like a c# driver problem to me.

**Comment by ObiWahn** [comment]
https://github.com/ra0o0f/arangoclient.net/blob/master/src/ArangoDB.Client/Data/EnsureIndexResult.cs#L35. Maybe you can try to switch the type to a floating point type.

**Comment by imtrobin** [comment]
Sorry, I think the above fixes it. The error with the collection is another collection with wrong indices, and it's throwing another error.
