### ISSUE TITLE
AQL: internal error - in index

### ISSUE THREAD

**Issue by Kurtas** [arangodb/arangodb#10572]
## My Environment

* __ArangoDB Version__:        3.4.8
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       SingleServer
* __Deployment Strategy__:   ManualStart
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        Debian GNU/Linux 9.11 (stretch)
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD

__AQL query (if applicable)__:
```javascipt
2019-11-27T21:39:07+01:00 - debug: {query: "FOR r IN vSite FILTER r._key == @filters._key  LIMIT 1 UPDATE r WITH @data IN vSite OPTIONS {mergeObjects: false} RETURN NEW", bindVars: {"filters":{"_key":"1510319258"},"data":{"name":"HWLAB2"}}}
```
## Steps to reproduce

Above query failed on below error :) We had this problem more than 3x for different queries

__Problem__:
```javascript
{ ArangoError: AQL: internal error - in index 1602510398 of type hash over ["uid"] (exception location: /work/ArangoDB/arangod/Aql/ModificationBlocks.cpp:378). Please report this error to arangodb.com (while executing) (exception location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:228). Please report this error to arangodb.com
    at new ArangoError (/home/autoboss/api/node_modules/arangojs/lib/async/error.js:71:21)
    at Object.resolve (/home/autoboss/api/node_modules/arangojs/lib/async/connection.js:247:32)
    at _hosts.(anonymous function) (/home/autoboss/api/node_modules/arangojs/lib/async/connection.js:131:26)
    at IncomingMessage.res.on (/home/autoboss/api/node_modules/arangojs/lib/async/util/request.node.js:78:21)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  isArangoError: true,
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: { end: [Array], data: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     socket: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        _bytesDispatched: 23467,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: null,
        [Symbol(asyncId)]: -1,
        [Symbol(bytesRead)]: 0 },
     connection: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        _bytesDispatched: 23467,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: null,
        [Symbol(asyncId)]: -1,
        [Symbol(bytesRead)]: 0 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { 'x-content-type-options': 'nosniff',
        server: 'ArangoDB',
        connection: 'Keep-Alive',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '386' },
     rawHeaders: 
      [ 'X-Content-Type-Options',
        'nosniff',
        'Server',
        'ArangoDB',
        'Connection',
        'Keep-Alive',
        'Content-Type',
        'application/json; charset=utf-8',
        'Content-Length',
        '386' ],
     trailers: {},
     rawTrailers: [],
     aborted: false,
     upgrade: false,
     url: '',
     method: null,
     statusCode: 500,
     statusMessage: 'Internal Server Error',
     client: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        _bytesDispatched: 23467,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: null,
        [Symbol(asyncId)]: -1,
        [Symbol(bytesRead)]: 0 },
     _consuming: true,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /_db/nimpee/_api/cursor HTTP/1.1\r\nauthorization: Basic aXBmYWJyaWM6aXBmbmV0MDBkYg==\r\ncontent-type: application/json\r\nx-arango-version: 30000\r\ncontent-length: 206\r\nHost: localhost:8529\r\nConnection: keep-alive\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/_db/nimpee/_api/cursor',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     read: [Function],
     request: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /_db/nimpee/_api/cursor HTTP/1.1\r\nauthorization: Basic aXBmYWJyaWM6aXBmbmV0MDBkYg==\r\ncontent-type: application/json\r\nx-arango-version: 30000\r\ncontent-length: 206\r\nHost: localhost:8529\r\nConnection: keep-alive\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/_db/nimpee/_api/cursor',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     body: 
      { error: true,
        errorMessage: 'AQL: internal error - in index 1602510398 of type hash over ["uid"] (exception location: /work/ArangoDB/arangod/Aql/ModificationBlocks.cpp:378). Please report this error to arangodb.com (while executing) (exception location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:228). Please report this error to arangodb.com',
        code: 500,
        errorNum: 4 },
     host: 0 },
  statusCode: 500,
  errorNum: 4,
  code: 500 }
```

**Comment by OmarAyo** [comment]
Hi @Kurtas 

Can you provide us a simple dataset that we can run the above aql against it and see what we get

Best

**Comment by Kurtas** [comment]
@OmarAyo 

Sorry, no I can't it seems that indexes are somehow corrupted by time -  unload/load collections or restart DB server will "fix" this problem.

But you got an exact line in your code from error so you should identify the problem. 

**I have now version 3.5.3 with MMFILES and I got some error today :(**
`{ ArangoError: AQL: internal error - in index idx_1655659577294716928 of type hash over 'username' (exception location: /work/ArangoDB/arangod/Aql/ModificationExecutorTraits.cpp:181). Please report this error to arangodb.com (while executing) (exception location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:283). Please report this error to arangodb.com
`

**Comment by jsteemann** [comment]
Revisiting this: I was just revisiting recent MMFiles issues and saw that both 3.4.8 and 3.5.3 were affected by a memory initialization order issue in the MMFiles engine's hash index implementation. That issue was fixed in both 3.4.9 and 3.5.4. Looking at the reported issue, it seemed to have happened with 3.4.8 and 3.5.3, which were both affected. So I first thought this could be a candidate.

However, the issue I am referring to here would potentially lead to indexed elements not found via an AQL query that does an equality lookup on a hash index. The above query however does a lookup by primary key and then performs an update on the document. Only here the hash index comes into play and can throw an exception. The query in question will not do any lookups via the hash index from AQL, so unfortunately it doesn't explain the misbehavior.

The place where the exception is thrown in the source code is actually a place that reacts only on errors generated at different source code positions. There are 4 places in the hash index code that can create an "internal error", and the error message for all these will be the same ("internal error"). So far I haven't found an obvious error in the code, but I will read the entire index code again tomorrow in search for something wrong.

**Comment by jsteemann** [comment]
On a side note, the above query can be simplified from
```
FOR r IN vSite FILTER r._key == @filters._key  LIMIT 1 UPDATE r WITH @data IN vSite OPTIONS {mergeObjects: false} RETURN NEW
```
to just
``` 
UPDATE @filters._key WITH @data IN vSite OPTIONS {mergeObjects: false} RETURN NEW
```
This will not help with the internal error issue though, but it could make the query slightly more efficient.

**Comment by jsteemann** [comment]
I didn't find any obvious issues in the index code, so I am still wondering what could be causing the problem. I have created a PR https://github.com/arangodb/arangodb/pull/11049 that adds extra error logging in case things go wrong, plus more assertions. I have started a PR run and hope it shows something interesting.

**Comment by dothebart** [comment]
Hi, 
did this issue occur again for you? 
Please note that the MMFiles storage engine is deprecated, and has been removed with [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/), you should migrate your installation to RocksDB.
