### ISSUE TITLE
AQL: internal error in index

### ISSUE THREAD

**Issue by gurisko** [arangodb/arangodb#10573]
## My Environment

* __ArangoDB Version__:        3.4.8
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               single server
* __Infrastructure__:               local
* __Operating System__:        Debian 9
* __Total RAM in your machine__:        8GB
* __Disks in use__:        HDD
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__LOG__:
```
2019-11-21T18:06:51+01:00 - error: ArangoError: AQL: internal error - in index 460021897 of type hash over ["vIntL2Id"] (exception location: /work/{{[[-ArangoDB-]]}}/arangod/MMFiles/MMFilesCollection.cpp:3708). Please report this error to arangodb.com (exception loc{{[[-ation: /-]]}}work/ArangoDB/arangod/Aql/ModificationBlocks.cpp:378). Please report this error to arangodb.com (while executing) ({{[[-exceptio-]]}}n location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:228). Please report this error to arangodb.com
```

## Steps to reproduce

Unknown

__Problem__:
ArangoDB exception

__Expected result__:
No exception?

**Comment by gurisko** [comment]
Actually, this looks like the exception originates in the same file as in #10572

**Comment by gurisko** [comment]
Any thoughts? I got this error 2 times again today...

**Comment by OmarAyo** [comment]
Hi @gurisko 

Can you please give us some more context, as having just the error message would not help that much

Thanks,

**Comment by gurisko** [comment]
@OmarAyo There is the stack trace - exact file and line number where the exception was thrown. What other information would you expect?

**Comment by gurisko** [comment]
I just reproduced this again. The query is very basic:
```
  FOR newGroup IN @groups
    LET group = FIRST(FOR g IN vReportGroup FILTER g._id == newGroup._id LIMIT 1 RETURN g)
    UPSERT {_id: newGroup._id}
    INSERT newGroup 
    REPLACE MERGE(newGroup, {children: (FOR name IN UNION_DISTINCT(group.children[*].name, newGroup.children[*].name) RETURN {name, weight: 1})})
    IN vReportGroup
```
The test I conducted:
1) remove the first record from `@groups` array,
2) try the query with the new `@groups` array in the arango UI,
3) go to step 1 if it fails on the error

I got to the point when I had 2 last records in `@groups`. I removed the first record (step 1) and the query worked fine (there was only the last record left). So I put back the previously removed record into `@groups` and the query passed (??? Bear in mind that just 30 seconds before it failed). I continued putting the records in the same order to the same query and everything worked fine again. The question is - for how long? 

The error in question (when run with arangojs):
```
error:  ArangoError: AQL: internal error - in index 474351902 of type hash over ["name"] (exception location: /work/ArangoDB/arangod/Aql/ModificationBlocks.cpp:378). Please report this error to arangodb.com (while executing) (exception location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:228). Please report this error to arangodb.com
    at new ArangoError (/home/autoboss/nimpeeMigrate/node_modules/arangojs/src/error.ts:76:17)
    at Object.resolve (/home/autoboss/nimpeeMigrate/node_modules/arangojs/src/connection.ts:350:20)
    at _hosts.(anonymous function) (/home/autoboss/nimpeeMigrate/node_modules/arangojs/src/connection.ts:209:16)
    at IncomingMessage.res.on (/home/autoboss/nimpeeMigrate/node_modules/arangojs/src/util/request.node.ts:117:15)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at Connection.request (/home/autoboss/nimpeeMigrate/node_modules/arangojs/src/connection.ts:288:12)
    at Database.query (/home/autoboss/nimpeeMigrate/node_modules/arangojs/src/database.ts:435:29)
...
```

This seems not to be collection based (When I made this work with my tests, I ran our script again and it crashed in a different query with the same error (different collection and different index)). 

This is all the time I can put into this aside of migrating into a different database.

**Comment by jsteemann** [comment]
This looks very much like a duplicate of #10572. I just left [a comment there](https://github.com/arangodb/arangodb/issues/10572#issuecomment-581493938) and will update that issue tomorrow should there be any findings.

**Comment by gurisko** [comment]
This is 5 years old and it uses MMFiles. Closing
