### ISSUE TITLE
Agency referring to deleted coordinator, will not remove it

### ISSUE THREAD

**Issue by rocketraman** [arangodb/arangodb#10617]
## My Environment

* __ArangoDB Version__:       3.5.3
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Kubernetes (not using operator)
* __Configuration__:               2 x coord, 3 x agency, 3 x db
* __Infrastructure__:               Azure
* __Operating System__:       Ubuntu 18.04
* __Total RAM in your machine__:        32 GB
* __Disks in use__:       SSD
* __Used Package__:              Docker - official Docker library

## Component, Query & Data

__Affected feature__:
Various things fail because ArangoDB is looking for a coordinator that does not exist. For example:

```
arangodb-coord-0 arangodb 2019-12-03T12:52:21.314104341Z 2019-12-03T12:52:21Z [1] ERROR [32152] {cluster} did not find endpoint of server 'CRDN-b9aeac48-0102-413e-8f64-7264647f1af5'
arangodb-coord-0 arangodb 2019-12-03T12:52:21.314294942Z 2019-12-03T12:52:21Z [1] ERROR [30467] {cluster} cannot create connection to server: 'CRDN-b9aeac48-0102-413e-8f64-7264647f1af5' at endpoint '', timeout: -1.000000
arangodb-coord-0 arangodb 2019-12-03T12:52:21.314492742Z 2019-12-03T12:52:21Z [1] ERROR [24213] Service "/_admin/aardvark" encountered error 500 while handling GET http://arangodb.k8s-prod.azure.xyz.com:8529/_db/prod-cms/_admin/aardvark/statistics/coordshort 
arangodb-coord-0 arangodb 2019-12-03T12:52:21.314516042Z 2019-12-03T12:52:21Z [1] ERROR [24213] via ArangoError: couldn't queue async request
arangodb-coord-0 arangodb 2019-12-03T12:52:21.314522442Z 2019-12-03T12:52:21Z [1] ERROR [24213]     at coordinators.map.coordinator (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:502:36)
arangodb-coord-0 arangodb 2019-12-03T12:52:21.314529342Z 2019-12-03T12:52:21Z [1] ERROR [24213]     at Array.map (<anonymous>)
arangodb-coord-0 arangodb 2019-12-03T12:52:21.314672642Z 2019-12-03T12:52:21Z [1] ERROR [24213]     at Route._handler (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:501:37)
arangodb-coord-0 arangodb 2019-12-03T12:52:21.314718942Z 2019-12-03T12:52:21Z [1] ERROR [24213]     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:412:15)
arangodb-coord-0 arangodb 2019-12-03T12:52:21.314785042Z 2019-12-03T12:52:21Z [1] ERROR [24213]     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:10052:25
arangodb-coord-0 arangodb 2019-12-03T12:52:21.314801542Z 2019-12-03T12:52:21Z [1] ERROR [24213]     at Middleware.router.use (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:405:3)
arangodb-coord-0 arangodb 2019-12-03T12:52:21.314989742Z 2019-12-03T12:52:21Z [1] ERROR [24213]     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:414:15)
arangodb-coord-0 arangodb 2019-12-03T12:52:21.315009642Z 2019-12-03T12:52:21Z [1] ERROR [24213]     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
arangodb-coord-0 arangodb 2019-12-03T12:52:21.315016442Z 2019-12-03T12:52:21Z [1] ERROR [24213]     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
arangodb-coord-0 arangodb 2019-12-03T12:52:21.315212043Z 2019-12-03T12:52:21Z [1] ERROR [24213]     at dispatch (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:426:3)
```

## Steps to reproduce

I don't know how the cluster got into this state, but I suspect it was due to some issues I had during an update to 3.5.2, which prevented the coordinator nodes from starting up. That's likely a different issue but the coordinator node would not bootstrap due to a missing transaction. I tried various things, including creating new coordinators and deleting the old ones, however nothing worked. The only way I was able to solve it was to update to 3.5.3, but this update was done with all the coordinator nodes down, so the agency nodes were unable to connect to the coordinator nodes when they were updated and recycled.

__Problem__:

The agency nodes think a coordinator still exists even though it does not. This "zombie" coordinator is not listed in the `_admin/cluster/health` endpoint, which shows all coordinator and db nodes as status `GOOD` and SyncStatus as `SERVING`.

The zombie node is `CRDN-b9aeac48-0102-413e-8f64-7264647f1af5`.

I have attached an agency dump as well as the health output:

Agency dump: 

[agency-dump.txt](https://github.com/arangodb/arangodb/files/3916701/agency-dump.txt)

Health: 

```
{
  "Health": {
    "PRMR-eb3e1eb9-f705-46ce-b4a3-e9197c0ca770": {
      "SyncTime": "2019-12-03T11:58:32Z",
      "Timestamp": "2019-12-03T11:58:32Z",
      "SyncStatus": "SERVING",
      "LastAckedTime": "2019-12-03T11:58:32Z",
      "Host": "arangodb-db-1.arangodb-dbs.default.svc.cluster.local",
      "Engine": "rocksdb",
      "Version": "3.5.3",
      "Status": "GOOD",
      "ShortName": "DBServer0002",
      "Endpoint": "tcp://arangodb-db-1.arangodb-dbs.default.svc.cluster.local:8529",
      "Role": "DBServer",
      "CanBeDeleted": false
    },
    "PRMR-e6e30ee8-02f5-4707-8361-89cbc0f69c69": {
      "SyncTime": "2019-12-03T12:00:10Z",
      "Timestamp": "2019-12-03T12:00:11Z",
      "SyncStatus": "SERVING",
      "LastAckedTime": "2019-12-03T12:00:10Z",
      "Host": "arangodb-db-2.arangodb-dbs.default.svc.cluster.local",
      "Engine": "rocksdb",
      "Version": "3.5.3",
      "Status": "GOOD",
      "ShortName": "DBServer0003",
      "Endpoint": "tcp://arangodb-db-2.arangodb-dbs.default.svc.cluster.local:8529",
      "Role": "DBServer",
      "CanBeDeleted": false
    },
    "PRMR-506337a5-06f5-4064-9c08-4b3fcb0c7edf": {
      "SyncTime": "2019-12-03T11:52:23Z",
      "Engine": "rocksdb",
      "Timestamp": "2019-12-03T11:52:24Z",
      "SyncStatus": "SERVING",
      "Host": "arangodb-db-0.arangodb-dbs.default.svc.cluster.local",
      "LastAckedTime": "2019-12-03T11:52:24Z",
      "Version": "3.5.3",
      "Endpoint": "tcp://arangodb-db-0.arangodb-dbs.default.svc.cluster.local:8529",
      "Status": "GOOD",
      "ShortName": "DBServer0001",
      "Role": "DBServer",
      "CanBeDeleted": false
    },
    "CRDN-37cdeaa3-3241-40fd-9515-4b88b5a46b9a": {
      "SyncTime": "2019-12-03T12:02:17Z",
      "Timestamp": "2019-12-03T12:02:18Z",
      "SyncStatus": "SERVING",
      "LastAckedTime": "2019-12-03T12:02:18Z",
      "Host": "arangodb-coord-0.arangodb.default.svc.cluster.local",
      "Engine": "rocksdb",
      "Version": "3.5.3",
      "Status": "GOOD",
      "ShortName": "Coordinator0015",
      "Endpoint": "tcp://arangodb-coord-0.arangodb.default.svc.cluster.local:8529",
      "Role": "Coordinator",
      "CanBeDeleted": false
    },
    "CRDN-897d62cd-ba11-4584-8c6e-500642e4d192": {
      "SyncTime": "2019-12-03T12:06:29Z",
      "Timestamp": "2019-12-03T12:06:30Z",
      "SyncStatus": "SERVING",
      "LastAckedTime": "2019-12-03T12:06:30Z",
      "Host": "arangodb-coord-1.arangodb.default.svc.cluster.local",
      "Engine": "rocksdb",
      "Version": "3.5.3",
      "Status": "GOOD",
      "ShortName": "Coordinator0016",
      "Endpoint": "tcp://arangodb-coord-1.arangodb.default.svc.cluster.local:8529",
      "Role": "Coordinator",
      "CanBeDeleted": false
    },
    "AGNT-b80b0bdc-cbee-4e64-99db-aefdc808118a": {
      "Endpoint": "tcp://arangodb-agent-1.arangodb-agents.default.svc.cluster.local:8529",
      "Role": "Agent",
      "CanBeDeleted": false,
      "Version": "3.5.3",
      "Engine": "rocksdb",
      "Leader": "AGNT-b80b0bdc-cbee-4e64-99db-aefdc808118a",
      "Leading": true,
      "LastAckedTime": 0,
      "Status": "GOOD"
    },
    "AGNT-adc2a3dc-e202-4957-930f-979aadd2f16e": {
      "LastAckedTime": 0.082,
      "Endpoint": "tcp://arangodb-agent-2.arangodb-agents.default.svc.cluster.local:8529",
      "Role": "Agent",
      "CanBeDeleted": false,
      "Version": "3.5.3",
      "Engine": "rocksdb",
      "Leader": "AGNT-b80b0bdc-cbee-4e64-99db-aefdc808118a",
      "Status": "GOOD"
    },
    "AGNT-1753c286-c1da-49b2-807a-d71ce5b955e6": {
      "LastAckedTime": 0.082,
      "Endpoint": "tcp://arangodb-agent-0.arangodb-agents.default.svc.cluster.local:8529",
      "Role": "Agent",
      "CanBeDeleted": false,
      "Version": "3.5.3",
      "Engine": "rocksdb",
      "Leader": "AGNT-b80b0bdc-cbee-4e64-99db-aefdc808118a",
      "Status": "GOOD"
    }
  },
  "ClusterId": "f6d21d14-d06d-46f6-a734-7fca519ac449",
  "error": false,
  "code": 200
}
```

__Expected result__:

The agency nodes should update the active coordinators correctly.

**Comment by maxkernbach** [comment]
Hi @rocketraman,

You can use our to remove the "zombie" coordinator. First of all you need to clone the repository https://github.com/arangodb/debug-scripts.

Next the provided agency dump can be **analyze**d with the following command from the cloned github repository. It is required to pass the path of a valid `arangosh` binary.
```
arangosh --javascript.execute debugging/index.js analyze /path/to/agency-dump.txt
```

The debug script reports, that zombie coordinators are found and suggests to run the **remove-zombie-coordinators** against the leader Agent endpoint.

```
Good: Your cluster does not have any zombies

Bad: Your cluster has zombie coordinators

...
...

To remedy the zombie coordinators issue please run the task `remove-zombie-coordinators` against the leader AGENT, e.g.:
 ./debugging/index.js <options> remove-zombie-coordinators /home/max/Git/debug-scripts/zombie-coordinators.json
```

Please run **remove-zombie-coordinators** and let us know if this fixed your issue.

**Comment by rocketraman** [comment]
@maxkernbach The `remove-zombie-coordinators` script ran but it did not remove the zombie coordinator. It produced this output:

```
reading file '/home/raman/source_ext/arangodb-debug-scripts/debugging/zombie-coordinators.json'
INFO: {"results":[17474]}
```

**Comment by rocketraman** [comment]
Ok, I ran it again on the agency node directly and this time it seemed to work. Thanks!
