### ISSUE TITLE
 error: 'transaction ID already used' (while optimizing plan)

### ISSUE THREAD

**Issue by pengshuangbao** [arangodb/arangodb#10794]
## My Environment

* __ArangoDB Version__:        3.5.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               own
* __Operating System__:        Centos7
* __Total RAM in your machine__:        64
* __Disks in use__:        10%
* __Used Package__:              rpm

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
```
Caused by: com.arangodb.ArangoDBException: Response: 500, Error: 1590 - AQL: error, cluster node: 'PRMR-c338134b-023c-438d-b672-d5f954c2882c', endpoint: 'tcp://xxx:8530', error: 'transaction ID already used' (while optimizing plan)
        at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:53)
        at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:149)
        at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:128)
        at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:42)
        at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:132)
        at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:47)
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:53)
        at com.arangodb.internal.ArangoDatabaseImpl.query(ArangoDatabaseImpl.java:197)
```

__Expected result__:

**Comment by OmarAyo** [comment]
Hi @pengshuangbao,

We have already fixed this issue with the following PR https://github.com/arangodb/arangodb/pull/9928 
- see changelog as well: https://github.com/arangodb/arangodb/blob/f2e933eb06caf670c608f4af9af4b59a167fdad0/CHANGELOG#L259

Please upgrade to our latest ArangoDB 3.5 Version and let us know if you are still facing the same error message

Best,

**Comment by pengshuangbao** [comment]
Thank you very much. What code does the client need to change to upgrade? I used skiplist index and hash index, does it have any impact?

**Comment by maxkernbach** [comment]
Hi @pengshuangbao,

Instructions on how to perform upgrades of various deployments can be found in the [Upgrading section](https://www.arangodb.com/docs/3.5/upgrading.html) of our documentation.

You reported that a CentOS7 Cluster is in use in the issue template, the "Deployment Strategy" is missing though.

Which of the following options is it?
Manual Start | Manual Start in Docker | ArangoDB Starter | ArangoDB Starter in Docker | Kubernetes | DCOS

Existing indexes persist when performing the upgrade. You do not need to worry about them.

**Comment by pengshuangbao** [comment]
Hi @maxkernbach ,Thank you for your answer， I use ArangoDB Starter model, my cluster has three nodes

**Comment by maxkernbach** [comment]
Hi @pengshuangbao,

have you been able to upgrade your deployment according to the documentation. Also, are you still observing the reported error message?

**Comment by OmarAyo** [comment]
Hi @pengshuangbao,

Any update on this ? We also invite you to have a look at this linke [here](https://www.arangodb.com/docs/stable/upgrading-starter.html)

Best,

**Comment by Simran-B** [comment]
Hi @pengshuangbao,
we haven't heard from you recently if you succeeded with the upgrade.
Closing this ticket now. Feel free to re-open if you still have issues.
