### ISSUE TITLE
Reverse Proxy setting 'frontend.trusted-proxy' address parsing broken

### ISSUE THREAD

**Issue by hamc17** [arangodb/arangodb#11258]
## My Environment

* __ArangoDB Version__:        3.6.1
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Active Failover
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               3 hosts in Active Failover
* __Infrastructure__:               AWS
* __Operating System__:        Amazon Linux 2
* __Total RAM in your machine__:        4GB
* __Disks in use__:        SSD, 8GB
* __Used Package__:              .rpm

## Component, Query & Data

__Affected feature__:
Reverse proxy fails because IPv4 addresses are incorrectly parsed

## Steps to reproduce

1. Create 3 nodes, connect them together with starter command via --starter.join "IP1, IP2, IP3"
2. Specify the following in the starter command:
    --all.frontend.proxy-request-check=true
    --all.frontend.trusted-proxy=$(StarterProxyIP)
3. After starting ArangoDB on all 3 nodes, run the following command on the leader:
  `curl http://localhost:8529/_db/_system/_admin/aardvark.index.html`.

__Problem__:
Server returns 500 internal server error.

__Expected result__:
Server returns 200, along with the default page.

## Explanation and Potential Solution
The following error appears in the log file 'arangod.log' under 'resilientsingle8529' in the specified data directory:

```
2020-03-11T16:49:55Z [17473] ERROR [24213] Service "/_admin/aardvark" encountered error 500 while handling GET http://localhost:8529/_db/_system/_admin/aardvark/index.html
2020-03-11T16:49:55Z [17473] ERROR [24213] via Error: Invalid byte: ::ffff:127
2020-03-11T16:49:55Z [17473] ERROR [24213]     at ip2long (/usr/share/arangodb3/js/node/node_modules/netmask/lib/netmask.js:23:15)
2020-03-11T16:49:55Z [17473] ERROR [24213]     at Netmask.contains (/usr/share/arangodb3/js/node/node_modules/netmask/lib/netmask.js:106:17)
2020-03-11T16:49:55Z [17473] ERROR [24213]     at trustedProxyBlocks.some (/opt/arangodb/data0/resilientsingle8529/data/js/server/modules/@arangodb/foxx/router/request.js:64:30)
2020-03-11T16:49:55Z [17473] ERROR [24213]     at Array.some (<anonymous>)
2020-03-11T16:49:55Z [17473] ERROR [24213]     at shouldTrustProxy (/opt/arangodb/data0/resilientsingle8529/data/js/server/modules/@arangodb/foxx/router/request.js:64:8)
2020-03-11T16:49:55Z [17473] ERROR [24213]     at new SyntheticRequest (/opt/arangodb/data0/resilientsingle8529/data/js/server/modules/@arangodb/foxx/router/request.js:89:13)
2020-03-11T16:49:55Z [17473] ERROR [24213]     at Tree.dispatch (/opt/arangodb/data0/resilientsingle8529/data/js/server/modules/@arangodb/foxx/router/tree.js:133:19)
2020-03-11T16:49:55Z [17473] ERROR [24213]     at callback (/opt/arangodb/data0/resilientsingle8529/data/js/server/modules/@arangodb/foxx/service.js:346:35)
2020-03-11T16:49:55Z [17473] ERROR [24213]     at execute (/opt/arangodb/data0/resilientsingle8529/data/js/server/modules/@arangodb/actions.js:1234:7)
2020-03-11T16:49:55Z [17473] ERROR [24213]     at routeRequest (/opt/arangodb/data0/resilientsingle8529/data/js/server/modules/@arangodb/actions.js:1253:3)
```

We can see `Error: Invalid byte: ::ffff:127` being the main problem here.

Adding a print statement to '_resilientsingle8529/data/js/server/modules/@arangodb/foxx/router/request.js_' within the function '_shouldTrustProxy_' to print out the address gives us '_::ffff:127.0.0.1_'.

The IPv6 prefix is not being removed from the incoming request address.
Modifying the function 'shouldTrustProxy' to that below solves the issue;

```
function shouldTrustProxy (address) {
  if (address.substr(0, 7) == "::ffff:") {
    address = address.substr(7)
  }
  if (trustedProxyBlocks === undefined) {
    trustedProxyBlocks = generateTrustedProxyBlocks();
  }
  return !trustedProxyBlocks || trustedProxyBlocks
      .some((block) => block.contains(address));
}
```

After updating the function as above, I can access the default page via my reverse proxy with no issues and no errors in the log as before.

**Comment by hamc17** [comment]
[Link to the function itself within the project](https://github.com/arangodb/arangodb/blob/devel/js/server/modules/%40arangodb/foxx/router/request.js#L57)
