### ISSUE TITLE
error with 1..1 INBOUND  joins

### ISSUE THREAD

**Issue by jgibart** [arangodb/arangodb#11626]
## My Environment

* __ArangoDB Version__:       3.6.3.1
* __Storage Engine__:              RocksDB 
* __Deployment Mode__:       Cluster 
* __Deployment Strategy__:    ArangoDB Starter 
* __Configuration__:               Cluster of 3 servers
* __Infrastructure__:               Iaaas on Azure 
* __Operating System__:        Debian 9
* __Total RAM in your machine__:        8Gb * 3. 

* __Disks in use__:        managed SSD 
* __Used Package__:              Debian .deb 

## Component, Query & Data

__Affected feature__:
AQL query

__AQL query (if applicable)__:
db._query('  FOR evse  IN evse   FOR cs IN 1..1 INBOUND evse._id infra_relationships return { evse, cs}') 

__AQL explain (if applicable)__:
get parents of evse item using edge evse._id infra_relationships 

__Dataset__:

 db._query('  FOR evse  IN evse  FILTER evse._id == "evse/CU-MIT-59DRA-2"  return evse ')
[object ArangoQueryCursor, count: 1, cached: false, hasMore: false]

[
  {
    "_key" : "CU-MIT-59DRA-2",
    "_id" : "evse/CU-MIT-59DRA-2",
    "_rev" : "_ZWvzlWK---",
    "connectors" : [
      {
        "amperage" : 32,
        "id" : 1,
        "type" : "T2",
        "value" : "SOCKET_IEC_62196_T2_SINGLE",
        "voltage" : 230
      },
      {
        "amperage" : 10,
        "id" : 2,
        "type" : "EF",
        "value" : "DOMESTIC_E",
        "voltage" : 230
      }
    ],
    "creationDate" : "2017-04-23T22:00:00.000Z",
    "emi3" : null,
    "emsps" : [
      {
        "enabled" : true,
        "name" : "Kiwhi"
      },
      {
        "enabled" : true,
        "name" : "G2M"
      },
      {
        "dduActivation" : false,
        "enabled" : false,
        "name" : "Gireve",
        "operatorId" : null
      }
    ],
    "externalId" : "",
    "inServiceDate" : "2017-04-23T22:00:00.000Z",
    "legacy" : {
      "bounds" : {
        "lower" : {
          "operator" : null,
          "value" : null
        },
        "upper" : {
          "operator" : null,
          "value" : null
        }
      },
      "connector1Type" : "T2,EF",
      "connectorId" : null,
      "energyMeterInternalId" : 3791,
      "internalId" : 3839
    },
    "maxPower" : 7,
    "name" : "CU-MIT-59DRA-2",
    "retiredDate" : null,
    "serviceStatus" : "IN_SERVICE",
    "staticUpdateDate" : "2017-06-27T16:48:08.000Z",
    "status" : "UNDEF",
    "sviName" : null
  }
]

 db._query('  FOR ir  IN infra_relationships  FILTER ir._to == "evse/CU-MIT-59DRA-2"  return ir ')
[object ArangoQueryCursor, count: 1, cached: false, hasMore: false]

[
  {
    "_key" : "44483733",
    "_id" : "infra_relationships/44483733",
    "_from" : "charging_station/MIT-59DRA-001_CU-MIT-59DRA-*",
    "_to" : "evse/CU-MIT-59DRA-2",
    "_rev" : "_XTYvoAa-_W"
  }
]

 db._query('  FOR cs  IN charging_station  FILTER cs._id == "charging_station/MIT-59DRA-001_CU-MIT-59DRA-*"  return cs ')
[object ArangoQueryCursor, count: 1, cached: false, hasMore: false]

[
  {
    "_key" : "MIT-59DRA-001_CU-MIT-59DRA-*",
    "_id" : "charging_station/MIT-59DRA-001_CU-MIT-59DRA-*",
    "_rev" : "_ZFUTPWK---",
    "emi3" : "",
    "model" : "evse_model/Diva"
  }
]

__Size of your Dataset on disk__:

db.infra_relationships.count()
28392

db.evse.count()
14085

db.charging_station.count()
9238

__Replication Factor & Number of Shards (Cluster only)__:
1 shard
rf 2

## Steps to reproduce

insert  data in respective collections
run the query
db._query('  FOR evse  IN evse   FOR cs IN 1..1 INBOUND evse._id infra_relationships return { evse, cs}') 

__Problem__:
query throws 
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 4: AQL: expected edge index not found (exception location: /work/ArangoDB/arangod/Graph/BaseOptions.cpp:252). Please report this error to arangodb.com (while optimizing plan) (exception location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:298). Please report this error to arangodb.com
!      throw error;
!      ^
stacktrace: ArangoError: AQL: expected edge index not found (exception location: /work/ArangoDB/arangod/Graph/BaseOptions.cpp:252). Please report this error to arangodb.com (while optimizing plan) (exception location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:298). Please report this error to arangodb.com
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:97:21)
    at ArangoStatement.execute (/usr/share/arangodb3/js/client/modules/@arangodb/arango-statement.js:172:12)
    at Proxy.ArangoDatabase._query (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:954:45)
    at <shell command>:1:4

__Expected result__:
Same as similar query
db._query('FOR evse IN evse FILTER evse._id == "evse/CU-MIT-59DRA-2" \
                          FOR ir IN  infra_relationships FILTER ir._to ==  evse._id   \
                            FOR cs IN charging_station  FILTER ir._from ==  cs._id \
                           RETURN {evse,  cs } ')
[object ArangoQueryCursor, count: 1, cached: false, hasMore: false]

[
  {
    "evse" : {
      "_key" : "CU-MIT-59DRA-2",
      "_id" : "evse/CU-MIT-59DRA-2",
      "_rev" : "_ZWvzlWK---",
      "connectors" : [
        {
          "amperage" : 32,
          "id" : 1,
          "type" : "T2",
          "value" : "SOCKET_IEC_62196_T2_SINGLE",
          "voltage" : 230
        },
        {
          "amperage" : 10,
          "id" : 2,
          "type" : "EF",
          "value" : "DOMESTIC_E",
          "voltage" : 230
        }
      ],
      "creationDate" : "2017-04-23T22:00:00.000Z",
      "emi3" : null,
      "emsps" : [
        {
          "enabled" : true,
          "name" : "Kiwhi"
        },
        {
          "enabled" : true,
          "name" : "G2M"
        },
        {
          "dduActivation" : false,
          "enabled" : false,
          "name" : "Gireve",
          "operatorId" : null
        }
      ],
      "externalId" : "",
      "inServiceDate" : "2017-04-23T22:00:00.000Z",
      "legacy" : {
        "bounds" : {
          "lower" : {
            "operator" : null,
            "value" : null
          },
          "upper" : {
            "operator" : null,
            "value" : null
          }
        },
        "connector1Type" : "T2,EF",
        "connectorId" : null,
        "energyMeterInternalId" : 3791,
        "internalId" : 3839
      },
      "maxPower" : 7,
      "name" : "CU-MIT-59DRA-2",
      "retiredDate" : null,
      "serviceStatus" : "IN_SERVICE",
      "staticUpdateDate" : "2017-06-27T16:48:08.000Z",
      "status" : "UNDEF",
      "sviName" : null
    },
    "cs" : {
      "_key" : "MIT-59DRA-001_CU-MIT-59DRA-*",
      "_id" : "charging_station/MIT-59DRA-001_CU-MIT-59DRA-*",
      "_rev" : "_ZFUTPWK---",
      "emi3" : "",
      "model" : "evse_model/Diva"
    }
  }
]

**Comment by Simran-B** [comment]
Hi @jgibart,
can you please try this slightly modified query and see if this also results in the same error?

    db._query('  FOR ev  IN evse  FILTER ev._id == "evse/CU-MIT-59DRA-2"  return ev ')

I could be that `evse._id` materializes the entire content of the `evse` collection as array then tries to access the virtual attribute `_id`, which I would expect to be `null` in this case. This might cause a subsequent error with the edge index. In general you should avoid using variable names which are called like collections to avoid confusion and potentially the materialization of a collection when you don't want to, but I'm not sure if this is actually causing the problem in this case.

Thanks,
Simran

**Comment by mchacki** [comment]
I think the query looks okay, I have just tried it locally with the information you provided.
There seems to be something off with the index definitions in your environment.

Could you please run the following commands:

```
db.evse.properties(true)
db.infra_relationships.properties(true)
db.charging_station.properties(true)
```

And share the output, this will help me to trace this down further.

How did you move the data from 3.2 to 3.6?
Dump/Restore data, or a upgrade with starter?
Or fresh install with clean data import?

Thanks
Michael

**Comment by jgibart** [comment]
> 
> 
> I think the query looks okay, I have just tried it locally with the information you provided.
> There seems to be something off with the index definitions in your environment.
> 
> Could you please run the following commands:
> 
> ```
> db.evse.properties(true)
> db.infra_relationships.properties(true)
> db.charging_station.properties(true)
> ```
> 
> And share the output, this will help me to trace this down further.
> 
> How did you move the data from 3.2 to 3.6?
> Dump/Restore data, or a upgrade with starter?
> Or fresh install with clean data import?
> 
> Thanks
> Michael



Hello Michael


As per your question:


> db.evse.properties(true)
{
  "isSmart" : false,
  "isSystem" : false,
  "waitForSync" : false,
  "shardKeys" : [
    "_key"
  ],
  "numberOfShards" : 1,
  "keyOptions" : {
    "allowUserKeys" : true,
    "type" : "traditional"
  },
  "replicationFactor" : 1,
  "minReplicationFactor" : 1,
  "writeConcern" : 1,
  "shardingStrategy" : "community-compat",
  "cacheEnabled" : false
}

> db.infra_relationships.properties(true)
{
  "isSmart" : false,
  "isSystem" : false,
  "waitForSync" : false,
  "shardKeys" : [
    "_key"
  ],
  "numberOfShards" : 1,
  "keyOptions" : {
    "allowUserKeys" : true,
    "type" : "traditional"
  },
  "replicationFactor" : 1,
  "minReplicationFactor" : 1,
  "writeConcern" : 1,
  "shardingStrategy" : "community-compat",
  "cacheEnabled" : false
}
> db.charging_station.properties(true)
{
  "isSmart" : false,
  "isSystem" : false,
  "waitForSync" : false,
  "shardKeys" : [
    "_key"
  ],
  "numberOfShards" : 1,
  "keyOptions" : {
    "allowUserKeys" : true,
    "type" : "traditional"
  },
  "replicationFactor" : 1,
  "minReplicationFactor" : 1,
  "writeConcern" : 1,
  "shardingStrategy" : "community-compat",
  "cacheEnabled" : false
}

The data was dumped from 3.2 using arangodump and restored to a 3.6 empty database using arangorestore.


The problem is specific to cluster mode. It doesnt occur in single server or active failover

**Comment by jgibart** [comment]
Hello Simran

The request you suggest produces same error.

AQL is not confused using as variable same name as the collection name, we use it all the time

Sincerely

Jocelyn
> 
> 
> Hi @jgibart,
> can you please try this slightly modified query and see if this also results in the same error?
> 
> ```
> db._query('FOR ev IN evse FOR cs IN 1..1 INBOUND ev._id infra_relationships return { ev, cs}')
> ```
> 
> It could be that `evse._id` materializes the entire content of the `evse` collection as array then tries to access the virtual attribute `_id`, which I would expect to be `null` in this case. This might cause a subsequent error with the edge index. In general you should avoid using variable names which are called like collections to avoid confusion and potentially the materialization of a collection when you don't want to, but I'm not sure if this is actually causing the problem in this case.
> 
> Thanks,
> Simran

**Comment by jgibart** [comment]
Also note that my database was created with 
db._properties(true)
{
  "id" : "22030002",
  "name" : "g2smart",
  "isSystem" : false,
  "sharding" : "",
  "replicationFactor" : 3,
  "writeConcern" : 1,
  "path" : ""
}

But the arango restore created collections with   "replicationFactor" : 1 ( maybe the is a property originating from the dump.

I modified collections to have RF  3 and minRF 2, but still same problem.

Is there a way to force indices rebuilt ? Those index are mostly automatic indexes.
> db.evse.getIndexes();
[
  {
    "fields" : [
      "_key"
    ],
    "id" : "evse/0",
    "name" : "primary",
    "selectivityEstimate" : 1,
    "sparse" : false,
    "type" : "primary",
    "unique" : true
  }
]

> db.infra_relationships.getIndexes();
[
  {
    "fields" : [
      "_key"
    ],
    "id" : "infra_relationships/0",
    "name" : "primary",
    "selectivityEstimate" : 1,
    "sparse" : false,
    "type" : "primary",
    "unique" : true
  },
  {
    "fields" : [
      "_from",
      "_to"
    ],
    "id" : "infra_relationships/1",
    "name" : "edge",
    "selectivityEstimate" : 0.5387752417286062,
    "sparse" : false,
    "type" : "edge",
    "unique" : false
  }
]

> db.charging_station.getIndexes();
[
  {
    "fields" : [
      "_key"
    ],
    "id" : "charging_station/0",
    "name" : "primary",
    "selectivityEstimate" : 1,
    "sparse" : false,
    "type" : "primary",
    "unique" : true
  }
]

**Comment by Simran-B** [comment]
@mchacki confirmed that variables still shadow collection names after the AQL refactoring in 3.6, but it's confusing nonetheless.
