### ISSUE TITLE
Arango Spark Connector Faliures

### ISSUE THREAD

**Issue by josephsahayaraj** [arangodb/arangodb#11993]
## My Environment

* __ArangoDB Version__:        3.6 (Community Edition)
* __Storage Engine__:              RocksDB 
* __Deployment Mode__:        Cluster 
* __Deployment Strategy__:     ArangoDB Starter 
* __Configuration__:                4 Nodes
* __Infrastructure__:                own 
* __Operating System__:        CentOs  
* __Total RAM in your machine__:  128GB
* __Disks in use__:         SSD
* __Used Package__:   

## Component, Query & Data

__Affected feature__:
Arango Spark Connector Fails to load Data From HDFS 
Size of Data : 180 GB
total Partitions in HDFS : 20000
spark settings: num-executors:70 executor-cores 4 executo- memory: 6g 

Exception:

------------------------------------------------------------------------------------------------------------------------------
**Initially the Job was run with 2200 partitions to load into arangodb so the error during that time was ****

**Lost task 504.0 in stage 0.0 (TID 503, datanode8, executor 68): com.arangodb.ArangoDBException: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.

 at com.arangodb.internal.velocystream.internal.VstConnectionSync.write(VstConnectionSync.java:92)

 at com.arangodb.internal.velocystream.VstCommunicationSync.send(VstCommunicationSync.java:138)

 at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:124)

 at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:40)

 at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:124)

 at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:46)

 at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)

 at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:61)

 at com.arangodb.internal.ArangoCollectionImpl.insertDocuments(ArangoCollectionImpl.java:70)

 at com.arangodb.internal.ArangoCollectionImpl.insertDocuments(ArangoCollectionImpl.java:62)

 at com.arangodb.spark.ArangoSpark$$anonfun$saveRDD$1.apply(ArangoSpark.scala:127)

 at com.arangodb.spark.ArangoSpark$$anonfun$saveRDD$1.apply(ArangoSpark.scala:121)

 at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)

 at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)

 at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2113)

 at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2113)

 at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)

 at org.apache.spark.scheduler.Task.run(Task.scala:121)

 at org.apache.spark.executor.Executor$TaskRunner$$anonfun$11.apply(Executor.scala:407)

 at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)

 at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:413)

 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

 at java.lang.Thread.run(Thread.java:748)

Caused by: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.

 at java.util.concurrent.FutureTask.report(FutureTask.java:122)

 at java.util.concurrent.FutureTask.get(FutureTask.java:192)

 at com.arangodb.internal.velocystream.internal.VstConnectionSync.write(VstConnectionSync.java:90)

 ... 23 more****

-----------------------------------------------------------------------------------------------------------------------------

After this i have increased the partitions to 20000 now getting a newer exeception:

==========================================================================================
com.arangodb.ArangoDBException: Response: 500, Error: 4 - internal error
--------------------------------------------------------------------------------------------------------------------------
Lost task 1489.0 in stage 1.0 (TID 3687, datanode1, executor 2): com.arangodb.ArangoDBException: Response: 500, Error: 4 - internal error

 at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:52)

 at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:141)

 at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:126)

 at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:40)

 at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:124)

 at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:46)

 at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)

 at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:61)

 at com.arangodb.internal.ArangoCollectionImpl.insertDocuments(ArangoCollectionImpl.java:70)

 at com.arangodb.internal.ArangoCollectionImpl.insertDocuments(ArangoCollectionImpl.java:62)

 at com.arangodb.spark.ArangoSpark$$anonfun$saveRDD$1.apply(ArangoSpark.scala:127)

 at com.arangodb.spark.ArangoSpark$$anonfun$saveRDD$1.apply(ArangoSpark.scala:121)

 at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)

 at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)

 at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2113)

 at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2113)

 at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)

 at org.apache.spark.scheduler.Task.run(Task.scala:121)

 at org.apache.spark.executor.Executor$TaskRunner$$anonfun$11.apply(Executor.scala:407)

 at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)

 at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:413)

 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

 at java.lang.Thread.run(Thread.java:748)

**Comment by rashtao** [comment]
`java.io.IOException: Reached the end of the stream` is thrown from
https://github.com/arangodb/arangodb-java-driver/blob/cfd813b421ecd70c2020e8ada834270942ec9d1a/src/main/java/com/arangodb/internal/velocystream/internal/VstConnection.java#L273
when the connection socket input stream reaches its end.

To investigate further please check if you have:
- related anomalies in the db logs
- db crashes (eg. checking the PIDs of `arangod` processes)
- connectivity problems in your network

**Comment by josephsahayaraj** [comment]
the first exception  **java.io.IOException: Reached the end of the stream** was fixed when i repartioned my dataframe to 20000

- I have checked the DB logs and i do not find any anomalies in the logs on the date of my job run

- partial of data is written into DB and the data size in HDFS is 180GB, job runs for 45 mins and then gets failed 
- in spark UI i can see atleast 3000  tasks are complete

**Comment by josephsahayaraj** [comment]
**SAMPLE JAVA CODE:**


public class ArangoDriver {

    public static void main (String args[]) {
        SparkConf conf = new SparkConf()
                .setMaster("yarn")
                .setAppName("ArangoInsert")
                .set("arangodb.hosts", **********,*********,********)
                .set("arangodb.user", *******)
                .set("arangodb.password", *******)
                .set("arangodb.acquireHostList","true")
                .set("arangodb.loadBalancingStrategy","ROUND_ROBIN");

        JavaSparkContext sc = new JavaSparkContext(conf);
        SQLContext sqlContext = new org.apache.spark.sql.SQLContext(sc);

        ArangoDB arangoDB = new ArangoDB.Builder().host(********).user("********").password("*********").build();
        try {
            final CollectionEntity collection = arangoDB.db("************").createCollection("**********");
            System.out.println("Collection Created");
        } catch (Exception ex) {
            System.out.println(ex);
        }


        Dataset<Row> ArangoDf = sqlContext.sql("Select * from db.profiled").repartition(20000);
        ArangoSpark.saveDF(ArangoDf, "profile", new WriteOptions().database("******"));
    }
    }

**Comment by josephsahayaraj** [comment]
> `java.io.IOException: Reached the end of the stream` is thrown from
> https://github.com/arangodb/arangodb-java-driver/blob/cfd813b421ecd70c2020e8ada834270942ec9d1a/src/main/java/com/arangodb/internal/velocystream/internal/VstConnection.java#L273
> when the connection socket input stream reaches its end.
> 
> To investigate further please check if you have:
> 
> * related anomalies in the db logs
> * db crashes (eg. checking the PIDs of `arangod` processes)
> * connectivity problems in your network


Any updates on the issue I have posted please ? quick response is appreciated

**Comment by rashtao** [comment]
Unfortunately I cannot reproduce your failure.
Can you please provide a way to reproduce it using spark in local mode and producing data from the code?
Also please specify the full ArangoDB Version (including patch version).

**Comment by josephsahayaraj** [comment]
> Unfortunately I cannot reproduce your failure.
> Can you please provide a way to reproduce it using spark in local mode and producing data from the code?
> Also please specify the full ArangoDB Version (including patch version).

I have Data residing in Hadoop cluster so i run spark in distributed mode and yarn is the resource manager

My config: **70 Executors 4 cores 6gb memory** , so the job runs without any issues for 45 minutes, but after that it gets lost .so even i am not sure how to recreate the scenario in local as this is problem with distributed mode and long running ones

can you please verify if all the parameters and settings that i am passing are correct for a CLUSTER mode of arangodb ?

**Comment by rashtao** [comment]
The parameters are correct. Your error `Response: 500, Error: 4 - internal error` is coming from the database and is not related to the Java driver (or to `arangodb-spark-connector`). 

`arangodb-spark-connector` creates a new connection for each RDD partition and sends insert, update or replace requests to the database: https://github.com/arangodb/arangodb-spark-connector/blob/58ddf7c16e3b3a0afa2693c1304fc7e48dcb7b90/src/main/scala/com/arangodb/spark/ArangoSpark.scala#L122-L132

I think the error should also happen to you when performing such operations directly without Spark. Could provide a way to reproduce it following such approach? 
In this way we would narrow down the possible causes and have something reproducible.

**Comment by Simran-B** [comment]
@josephsahayaraj Can you provide instructions to @rashtao how to reproduce the problem?

**Comment by dothebart** [comment]
Hi, 
we haven't heard back from you in a while, hence we will close this issue. 

Please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.
