### ISSUE TITLE
Arango cluster stuck on collection lock

### ISSUE THREAD

**Issue by leonidUH** [arangodb/arangodb#12310]
* __ArangoDB Version__:        3.6.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:        Cluster
* __Deployment Strategy__:   Kubernetes ArangoDeployment
* __Configuration__:                3 agents ,3 dbservers ,3 coordinators
* __Infrastructure__:               AWS

More than once it happens that the cluster stops working.
In the log I see something about waiting for lock and timeout for statistics.

**Comment by leonidUH** [comment]
LOGS
dbservers :
WARNING [4512c] {queries} timed out after 900 s waiting for exclusive-lock on collection 's8010020'
 WARNING [4512c] {queries} timed out after 900 s waiting for write-lock on collection 's8010020'
 WARNING [8bcee] {queries} slow query: 'FOR doc IN @@collection FILTER doc.@indexAttribute >= 0 && doc.@indexAttribute <= @stamp SORT doc.@indexAttribute LIMIT @limit REMOVE doc IN @@collection OPTIONS { ignoreErrors: true }', bind vars: {"@collection":"s8010020","indexAttribute":["createdAt"],"stamp":1.5957639941853433e+9,"limit":999717}, took: 900.006094 s
 WARNING [08300] {ttl} error during TTL document removal for collection 's8010020': AQL: lock timeout (while loading collections)
 WARNING [4512c] {queries} timed out after 900 s waiting for exclusive-lock on collection 's8010020'
 WARNING [4512c] {queries} timed out after 900 s waiting for exclusive-lock on collection 's8010020'

coordinators :
2020-07-27T11:55:22Z [1] ERROR [abcde] {communication} communication error: 'Request timeout' from destination 'shard:s4010024'
2020-07-27T11:55:22Z [1] WARNING [8bcee] {queries} slow query: 'FOR doc IN @@collection FILTER doc.`mount` == "/_api/foxx" LIMIT 0, 1  RETURN doc', bind vars: {"@collection":"_apps"}, took: 120.016846 s
2020-07-27T11:55:22Z [1] ERROR [24213] ArangoError 1457: AQL: timeout in cluster operation (while optimizing plan)
2020-07-27T11:55:22Z [1] ERROR [24213]     at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:84:16)
2020-07-27T11:55:22Z [1] ERROR [24213]     at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:102:45)
2020-07-27T11:55:22Z [1] ERROR [24213]     at SimpleQueryByExample.execute (/usr/share/arangodb3/js/server/modules/@arangodb/simple-query.js:136:42)
2020-07-27T11:55:22Z [1] ERROR [24213]     at SimpleQueryByExample.SimpleQuery.toArray (/usr/share/arangodb3/js/common/modules/@arangodb/simple-query-common.js:171:8)
2020-07-27T11:55:22Z [1] ERROR [24213]     at ArangoCollection.firstExample (/usr/share/arangodb3/js/server/modules/@arangodb/arango-collection.js:239:71)
2020-07-27T11:55:22Z [1] ERROR [24213]     at Object.getServiceDefinition (/usr/share/arangodb3/js/common/modules/@arangodb/foxx/manager-utils.js:178:23)
2020-07-27T11:55:22Z [1] ERROR [24213]     at initLocalServiceMap (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:439:39)
2020-07-27T11:55:22Z [1] ERROR [24213]     at ensureFoxxInitialized (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:459:5)
2020-07-27T11:55:22Z [1] ERROR [24213]     at Object.getMountPoints [as _mountPoints] (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:1068:3)
2020-07-27T11:55:22Z [1] ERROR [24213]     at buildRouting (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1055:33)
2020-07-27T11:56:13Z [1] ERROR [abcde] {communication} communication error: 'Request timeout' from destination 'shard:s8010020'
2020-07-27T11:56:13Z [1] ERROR [abcde] {communication} communication error: 'Request timeout' from destination 'shard:s8010020'
2020-07-27T11:56:33Z [1] ERROR [abcde] {communication} communication error: 'Request timeout' from destination 'shard:s8010020'
2020-07-27T11:56:33Z [1] ERROR [abcde] {communication} communication error: 'Request timeout' from destination 'shard:s8010020'
2020-07-27T11:57:01Z [1] ERROR [abcde] {communication} communication error: 'Request timeout' from destination 'shard:s8010020'
2020-07-27T11:57:01Z [1] ERROR [abcde] {communication} communication error: 'Request timeout' from destination 'shard:s8010020'
2020-07-27T11:57:11Z [1] ERROR [abcde] {communication} communication error: 'Request timeout' from destination 'shard:s4010024'
2020-07-27T11:57:11Z [1] WARNING [8bcee] {queries} slow query: '\n    FOR doc IN @@value0\n    FILTER LEFT(doc.mount, 2) != "/_"\n    LET bundleExists = DOCUMENT(@@value1, doc.checksum) != null\n    RETURN [doc.mount, doc.checksum, doc._rev, bundleExists]\n  ', bind vars: {"@value0":"_apps","@value1":"_appbundles"}, took: 120.014009 s
2020-07-27T11:57:52Z [1] ERROR [abcde] {communication} communication error: 'Request timeout' from destination 'shard:s8010020'

**Comment by leonidUH** [comment]
2020-07-13T14:20:54Z [1] ERROR [30467] {cluster} cannot create connection to server: 'CRDN-xxw8kgxw' at endpoint '', timeout: -1.000000
2020-07-13T14:20:54Z [1] ERROR [24213] Service "/_admin/aardvark" encountered error 500 while handling GET http://127.0.0.1:8529/_db/queries/_admin/aardvark/statistics/coordshort
2020-07-13T14:20:54Z [1] ERROR [24213] via ArangoError: couldn't queue async request
2020-07-13T14:20:54Z [1] ERROR [24213]     at coordinators.map.coordinator (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:502:36)
2020-07-13T14:20:54Z [1] ERROR [24213]     at Array.map (<anonymous>)
2020-07-13T14:20:54Z [1] ERROR [24213]     at Route._handler (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:501:37)
2020-07-13T14:20:54Z [1] ERROR [24213]     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:412:15)
2020-07-13T14:20:54Z [1] ERROR [24213]     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:10052:25
2020-07-13T14:20:54Z [1] ERROR [24213]     at Middleware.router.use (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:405:3)
2020-07-13T14:20:54Z [1] ERROR [24213]     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:414:15)
2020-07-13T14:20:54Z [1] ERROR [24213]     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
2020-07-13T14:20:54Z [1] ERROR [24213]     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
2020-07-13T14:20:54Z [1] ERROR [24213]     at dispatch (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:426:3)

**Comment by kvahed** [comment]
What you are experiencing here is something like this: A long running transaction is preventing the replication to finish. To explain a little bit: The replication process on a follower shard, when it first wants to catch up with the leader after a restart or after an adjustment to the collection to raise the replication level gets from the leader whatever it is missing. And to finish it off, gets a read lock on the shard to get whatever has been added in the meantime. Followed by the release of the lock and normal replicating operation from the leader. 

What you are seeing it that the finalisation of the catchup is not able to acquire said lock. 

There are a couple of things that you could do to start with in this order
* Check all your queries for potential veeeeeery long holds of locks. Try to identify it and rewrite it in a way, where the lock could be handled more gracefully. There really is not much we can do there on the side of the database code. 
* Restart the leader db server for the shard in question to kill the lock.
* Restart all coordinators one after the other. 

If you don't identify the problematic query, this situation will come up again.,

**Comment by leonidUH** [comment]
We still have the same problem. We check all our requests and simplified them as much as possible, plus removed all transactions from the code
Yesterday it locked on our collection when try to remove old data:

2020-08-09T11:34:41Z [1] ERROR [abcde] {communication} communication error: 'Request timeout' from destination 'shard:s4010867'
2020-08-09T11:47:52Z [1] WARNING [d728e] {queries} slow query: 'FOR doc IN @@collection FILTER doc.@indexAttribute >= 0 && doc.@indexAttribute <= @stamp SORT doc.@indexAttribute LIMIT @limit REMOVE doc IN @@collection OPTIONS { ignoreErrors: true }', bind vars: {"@collection":"s4010867","indexAttribute":["createdAt"],"stamp":1.5968863889096797e+9,"limit":1000000}, took: 883.309665 s, loading took: 883.309155 s

Today it locks on system collection '_graphs' .
2020-08-11T10:45:26Z [1] ERROR [abcde] {communication} communication error: 'Request timeout' from destination 'shard:s10010043'' . I check that problem shard 10010043==_graphs

**Comment by leonidUH** [comment]
one more question . Now we have all our collections with
 Replication factor: 1 
 Write concern: 1 
Wait for sync:	No
Maybe you need to change something for the cluster to avoid locking?
