### ISSUE TITLE
2.4.2 breaks my Foxx app

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1233]
making a request against my controller against returns a 500 with the following trace:
```
INFO { "error" : "undefined is not a function", "stack" : "TypeError: undefined is not a function
  at routingInfo.middleware.push.action.callback (/usr/local/Cellar/arangodb/2.4.2/share/arangodb/js/server/modules/org/arangodb/foxx/controller.js:380:13)
  at Function.<anonymous> (/usr/local/Cellar/arangodb/2.4.2/share/arangodb/js/server/modules/org/arangodb/foxx/manager.js:775:13)
  at execute (/usr/local/Cellar/arangodb/2.4.2/share/arangodb/js/server/modules/org/arangodb/actions.js:977:7)
  at next (/usr/local/Cellar/arangodb/2.4.2/share/arangodb/js/server/modules/org/arangodb/actions.js:994:7)
  at [object Object]:386:5
  at execute (/usr/local/Cellar/arangodb/2.4.2/share/arangodb/js/server/modules/org/arangodb/actions.js:977:7)
  at Object.routeRequest (/usr/local/Cellar/arangodb/2.4.2/share/arangodb/js/server/modules/org/arangodb/actions.js:998:3)
  at Function.actions.defineHttp.callback (/usr/local/Cellar/arangodb/2.4.2/share/arangodb/js/actions/api-system.js:55:15)
" }

```

When I switch back to 2.4.1, my app works again.

Even if I reduce my app to a bare minimum of code, it still breaks with 2.4.2.

**Comment by fceller** [comment]
Is fixed in the current 2.4 branch. We will release 2.4.3 shortly.

**Comment by mchacki** [comment]
Hi Christian, thanks for reporting.
This issue has already been reported to us in person and is already fixed.
We will build a 2.4.3 version containing the fix.

**Comment by pekeler** [comment]
Thanks guys :)
