### ISSUE TITLE
Generated Foxx app invalid?

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1244]
I updated to 2.4.3, created a new foxx app in Aardvark with two collections (*objects*, *projects*) and uploaded the resulting zip to install the app.

All I get is a disabled `Open` button, `unknown path` json responses at the mount path and this:

    Sorry the code is not documented properly
    "Please specify the protocol for /_db/_system/_admin/aardvark/docu/1576415447351?api_key=false"

Moreover, there is an error printed to the server console:

	2015-02-12T18:51:46Z [9832] ERROR Error in foxx route: 'document not found', Stacktrace: Error: document not found
	at Error (native)
	at [object Object].listOne (c:/Users/Public/Documents/ArangoDB/share/arangodb/js/apps/system/aardvark/lib/swagger.js:71:18)
	at c:\Users\Public\Documents\ArangoDB\share\arangodb\js\apps\system\aardvark\aardvark.js:378:18
	at action.callback (c:/Users/Public/Documents/ArangoDB/share/arangodb/js/server/modules/org/arangodb/foxx/internals.js:125:9)
	at Function.<anonymous> (c:/Users/Public/Documents/ArangoDB/share/arangodb/js/server/modules/org/arangodb/foxx/manager.js:77
	5:13)
	at execute (c:/Users/Public/Documents/ArangoDB/share/arangodb/js/server/modules/org/arangodb/actions.js:977:7)
	at next (c:/Users/Public/Documents/ArangoDB/share/arangodb/js/server/modules/org/arangodb/actions.js:994:7)
	at [object Object]:386:5
	at execute (c:/Users/Public/Documents/ArangoDB/share/arangodb/js/server/modules/org/arangodb/actions.js:977:7)
	at Object.routeRequest (c:/Users/Public/Documents/ArangoDB/share/arangodb/js/server/modules/org/arangodb/actions.js:998:3)
	at Function.actions.defineHttp.callback (c:\Users\Public\Documents\ArangoDB\share\arangodb\js\actions\api-system.js:55:15)

And a bunch of deprecation warnings:

    INFO RequestContext#pathParam({type: string}) is deprecated, use RequestContext#pathParam({type: joi}) instead

Shouldn't a generated Foxx app work out of the box?

**Comment by CoDEmanX** [comment]
The documentation error also occurs with foxx-aye-aye, the app itself appears to be functional nonetheless.

**Comment by mchacki** [comment]
Hi @CoDEmanX 
we are revisting all apps in the Store in preparation for 2.5. They should all be functional by the release.
The failing template is fixed now and will be included in the next bugfix release.
In 2.5 a major upgrade of Foxx will be released.

**Comment by CoDEmanX** [comment]
Thanks mchacki. Is the references commit the only one required to fix the issue? I'd like to test it before 2.5 comes out (is end of February still realistic?)

**Comment by mchacki** [comment]
Hi @CoDEmanX yes i think it is the only commit necessary to fix the App generation.

2.5 by end of February is still realistic, we are right now building and testing a technical preview version containing most of the improvements.
We would be very happy to get some feedback through this version ahead of the final 2.5 release.
