### ISSUE TITLE
AQL: Error message received from cluster node \'PRMR-4a56965c-b847-4e19-b00a-7a13a35845d3\': std::bad_alloc (while executing)

### ISSUE THREAD

**Issue by max-yue** [arangodb/arangodb#12550]
Can you please explain what's the reason for it?

Traceback (most recent call last):\n  File "/data1/pyapp/graphdbapipy/graphdbapipy/service.py", line 20, in run\n    outputs = [DBOp.run(inp) for inp in inps]\n  File "/data1/pyapp/graphdbapipy/graphdbapipy/service.py", line 20, in <listcomp>\n    outputs = [DBOp.run(inp) for inp in inps]\n  File "/data1/pyapp/graphdbapipy/graphdbapipy/dbop.py", line 710, in run\n    return f(d)\n  File "/data1/pyapp/graphdbapipy/graphdbapipy/dbop.py", line 603, in get_graph_statistics\n    return_relations)\n  File "/data1/pyapp/graphdbapipy/graphdbapipy/dbop.py", line 433, in _get_single_module_statistics\n    for node in node_col:\n  File "/usr/local/lib/python3.6/site-packages/arango/collection.py", line 84, in __iter__\n    return self.all()\n  File "/usr/local/lib/python3.6/site-packages/arango/collection.py", line 641, in all\n    return self._execute(request, response_handler)\n  File "/usr/local/lib/python3.6/site-packages/arango/api.py", line 66, in _execute\n    return self._executor.execute(request, response_handler)\n  File "/usr/local/lib/python3.6/site-packages/arango/executor.py", line 82, in execute\n    return response_handler(resp)\n  File "/usr/local/lib/python3.6/site-packages/arango/collection.py", line 638, in response_handler\n    raise DocumentGetError(resp, request)\narango.exceptions.DocumentGetError: [HTTP 500][ERR 500] AQL: Error message received from cluster node \'PRMR-4a56965c-b847-4e19-b00a-7a13a35845d3\': std::bad_alloc (while executing)\n

**Comment by dothebart** [comment]
`std::bad_alloc` means that you outdid the available memory on one of your DB-Servers.
