### ISSUE TITLE
Bulk Imports: Remote end closed connection without response

### ISSUE THREAD

**Issue by mathsyouth** [arangodb/arangodb#12718]
## My Environment

* __ArangoDB Version__:        3.6.6
* __Storage Engine__:             RocksDB
* __Deployment Mode__:        Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:              3 machines
* __Infrastructure__:               own
* __Operating System__:        CentOS 7.3
* __Total RAM in your machine__:        64Gb each
* __Disks in use__:        HDD

## Component, Query & Data

__Affected feature__:
python-arango import_bulk function

__AQL query (if applicable)__:

__AQL explain and/or profile (if applicable)__:

__Dataset__:
1 million

__Size of your Dataset on disk__:
30G

__Replication Factor & Number of Shards (Cluster only)__:
3

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
2020-09-26 02:07:32,740 - test.py[line:42] - ERROR - When importing 60: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/test.py", line 40, in test
    builder.import_updated()
  File "/work/test.py", line 1199, in import_updated
    result = this_collection.import_bulk(self.grab_batch(elements, batch_size), on_duplicate='ignore', halt_on_error=False, details=True)
  File "/usr/local/lib/python3.7/site-packages/arango/collection.py", line 2257, in import_bulk
    return self._execute(request, response_handler)
  File "/usr/local/lib/python3.7/site-packages/arango/api.py", line 66, in _execute
    return self._executor.execute(request, response_handler)
  File "/usr/local/lib/python3.7/site-packages/arango/executor.py", line 81, in execute
    resp = self._conn.send_request(request)
  File "/usr/local/lib/python3.7/site-packages/arango/connection.py", line 161, in send_request
    auth=self._auth
  File "/usr/local/lib/python3.7/site-packages/arango/http.py", line 109, in send_request
    auth=auth
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

__Expected result__:

**Comment by maxkernbach** [comment]
Hi @mathsyouth,

Did the server crash during the bulk import?
If so, could you please provide the server log of that time interval?

**Comment by mathsyouth** [comment]
@maxkernbach Thanks for your reply. The server didn't crash during the bulk import. However, the server's 98% memory was utilized when the error happened. There wasn't any information in the server log during the time interval.

**Comment by Simran-B** [comment]
We expected a segfault or OOM crash on the server-side, but if it's still up and running after your bulk import request, then it must be something else. How large is the payload that you try to send? Any very large documents? There's a limit around 750MB at which I would expect the server to reject the request. Did you try to import the data by other means, i.e. without python-arango? We wonder if it's driver related or something more generic.

**Comment by mathsyouth** [comment]
@Simran-B The overall payload is nearly 800 MB. However, even though I tried to split the large documents into 4 or 5 batches of small documents and the first 3 or 4 batches could be sent successfully, the last one or two would make the error reproduced again. I just used python-arango, not other drivers.

**Comment by Simran-B** [comment]
I assume this is related: #12896
