### ISSUE TITLE
Folder Name "app" creates loading issues in 2.5

### ISSUE THREAD

**Issue by anjanrao** [arangodb/arangodb#1276]
Any folder with the name "app" say under a directory "frontend/js/app/somecode.js" creates issues. Directory "frontend" contains html/js for frontend of the application and is mapped to "/" in manifest.json for the app under the "files" key.

ERROR LOG
======================================================================
2015-03-15T01:31:31Z [3788] ERROR Cannot find manifest file '/home/devuser/notes/app/_db/fa/fasnm/APP/frontend/js/APP/manifest.json'
2015-03-15T01:31:31Z [3788] ERROR JavaScript exception in file '/usr/share/arangodb/js/server/bootstrap/foxxes.js' at 63,15: [ArangoError 14: file not found: Cannot find manifest file '/home/devuser/notes/app/_db/fa/fasnm/APP/frontend/js/APP/manifest.json']
2015-03-15T01:31:31Z [3788] ERROR !        throw err;
2015-03-15T01:31:31Z [3788] ERROR !              ^
2015-03-15T01:31:31Z [3788] ERROR stacktrace: Error: \n  at exports.throwFileNotFound (/usr/share/arangodb/js/common/modules/org/arangodb-common.js:482:9)\n  at validateManifestFile (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/manager.js:288:7)\n  at appConfig (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/manager.js:420:17)\n  at createApp (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/manager.js:434:18)\n  at _scanFoxx (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/manager.js:713:15)\n  at transAction (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/manager.js:1321:7)\n  at [object ArangoDatabase].ArangoDatabase._executeTransaction (/usr/share/arangodb/js/server/modules/org/arangodb/arango-database.js:142:10)\n  at syncWithFolder (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/manager.js:1324:10)\n  at Object.initializeFoxx (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/manager.js:1204:5)\n  at Object.foxxes (/usr/share/arangodb/js/server/bootstrap/foxxes.js:58:48)\n  at server/server.js:59:56\n  at server/server.js:74:2\n
2015-03-15T01:31:31Z [3788] FATAL error during execution of JavaScript utilities from file 'server/server.js'

**Comment by mchacki** [comment]
Hi @anjanrao ,
This seems to be a bug, i will take a look.

**Comment by mchacki** [comment]
Fixed it in 2.5 and Devel (could not occur earlier)
Thanks for reporting it.
The fix will be contained in the next 2.5 bugfix release.
