### ISSUE TITLE
upgrading to 2.5 fails due to use of harmony features

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1277]
I'm using some ES6 syntax in my 2.4.3 app, which I'm typically launching with
```
arangod --javascript.v8-options='--harmony' --javascript.dev-app-path foxx --log.file + db
```
I've just installed 2.5 and tried to upgrade with
```
arangod --javascript.v8-options='--harmony' --javascript.dev-app-path foxx --log.file + db --upgrade
```
which can't seem to handle arrow functions anymore and fails
```
2015-03-16T17:14:47Z [10733] INFO ArangoDB 2.5.0 64bit -- ICU 52.1, V8 3.31.74.1, OpenSSL 1.0.2 22 Jan 2015
2015-03-16T17:14:47Z [10733] INFO using default language 'en'
2015-03-16T17:14:47Z [10733] INFO loaded database '_system' from 'db/databases/database-70841'
2015-03-16T17:14:47Z [10733] INFO running WAL recovery (1 logfiles)
2015-03-16T17:14:47Z [10733] INFO replaying WAL logfile 'db/journals/logfile-208939014605.db' (1 of 1)
2015-03-16T17:14:47Z [10733] INFO WAL recovery finished successfully
2015-03-16T17:14:47Z [10733] INFO using endpoint 'tcp://127.0.0.1:8529' for non-encrypted requests
2015-03-16T17:14:47Z [10733] INFO using default API compatibility: 20500
2015-03-16T17:14:47Z [10733] INFO JavaScript using startup '/usr/local/Cellar/arangodb/2.5.0/share/arangodb/js', application '/usr/local/var/lib/arangodb-apps', dev application 'foxx'
2015-03-16T17:14:47Z [10733] INFO using V8 options '--harmony'
2015-03-16T17:14:48Z [10733] INFO In database '_system': Found 24 defined task(s), 2 task(s) to run
2015-03-16T17:14:48Z [10733] INFO In database '_system': state prod/standalone/upgrade, tasks moveFoxxApps, dropAal
2015-03-16T17:14:50Z [10733] WARNING collection 'dev_wdt_packs' already exists. Leaving it untouched.
2015-03-16T17:14:50Z [10733] WARNING collection 'dev_wdt_timers' already exists. Leaving it untouched.
2015-03-16T17:14:50Z [10733] ERROR JavaScript exception in file '/usr/local/var/lib/arangodb-apps/_db/_system/dev/wdt/APP/controllers/timers.js' at 74,50: SyntaxError: Unexpected token =>
2015-03-16T17:14:50Z [10733] ERROR !  packForClient.timers = _.map(packTimers, timer => timer.forClient());
2015-03-16T17:14:50Z [10733] ERROR !                                                 ^^
2015-03-16T17:14:50Z [10733] ERROR stacktrace: SyntaxError: Unexpected token =>\n  at [object Object].ArangoApp.loadAppScript (/usr/local/Cellar/arangodb/2.5.0/share/arangodb/js/server/modules/org/arangodb/foxx/arangoApp.js:411:22)\n  at routeApp (/usr/local/Cellar/arangodb/2.5.0/share/arangodb/js/server/modules/org/arangodb/foxx/routing.js:531:15)\n  at _install (/usr/local/Cellar/arangodb/2.5.0/share/arangodb/js/server/modules/org/arangodb/foxx/manager.js:863:7)\n  at Object.install (/usr/local/Cellar/arangodb/2.5.0/share/arangodb/js/server/modules/org/arangodb/foxx/manager.js:904:15)\n  at Object.addTask.task (server/upgrade-database.js:1379:23)\n  at runTasks (server/upgrade-database.js:358:27)\n  at upgradeDatabase (server/upgrade-database.js:487:20)\n  at upgrade (server/upgrade-database.js:1428:12)\n  at server/upgrade-database.js:1434:10\n  at server/upgrade-database.js:1435:2\n
```
...
```
2015-03-16T17:14:50Z [10733] ERROR In database '_system': Executing task #1 (moveFoxxApps: move foxx applications from name-based to mount-based folder.) failed. Aborting upgrade procedure.
2015-03-16T17:14:50Z [10733] ERROR In database '_system': Please fix the problem and try starting the server again.
2015-03-16T17:14:50Z [10733] FATAL Database '_system' upgrade failed. Please inspect the logs from the upgrade procedure
```

**Comment by jsteemann** [comment]
I quickly compared `arangod db --javascript.v8-options="--help" | grep harmony` for 2.4 and 2.5, and it seems that the meaning of V8's internal options has changed. 

In the previous version (2.4, V8 3.29.59), V8's `--harmony` options had the meaning: 
`enable all harmony features (except proxies)`.

In the current version (2.5, V8 3.31.74.1), according the help text it now means: 
`enable all completed harmony features`.

So I think the `--javascript.options` should be adjusted in your case.

As the behavioral change is inside V8, I think there is not much we can do about it apart from pointing this out in the docs.

**Comment by pekeler** [comment]
Thanks @jsteemann `--javascript.v8-options='--harmony --harmony_arrow_functions'` made it work for me.

**Comment by jsteemann** [comment]
Thanks. I have added a hint in the *upgrading* section of the docs.
