### ISSUE TITLE
Foxx Model Joi schema default with function

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb#1284]
Consider the following model:
````javascript
var MyModel = Foxx.Model.extend({
    schema: {
        createdAt: Joi.date().iso().default(Date.now, 'createdAt'),
        updatedAt: Joi.date().iso().default(null)
    }
});
````

Trying to save this model will always fail, because the default is never interpreted, but kept as JS function:
````
2015-03-23T16:03:32Z [3626] ERROR Error in foxx route ...' :<data> cannot be converted into JSON shape: could not shape document', Stacktrace: Error: <data> cannot be converted into JSON shape: could not shape document
2015-03-23T16:03:32Z [3626] ERROR   at Error (native)
2015-03-23T16:03:32Z [3626] ERROR   at [object Object]._.extend.save (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/repository.js:160:38)
````
This is the object just before save:
````javascript
{ "attributes" : { "createdAt" : function now() { [native code] }, "updatedAt" : null, "_key" : "1297" }, "isValid" : true, "errors" : { }, "domain" : null, "_events" : { }, "_maxListeners" : 10 }
````
If I would pass `new Date()` there, it will be the same date all the time, as long as the file is kept in memory. Here is the Joi documentation about this:
https://github.com/hapijs/joi#anydefaultvalue-description

The second part of the problem is already described in #1257 (automatic updatedAt attribute).

**Comment by pluma** [comment]
I recall having a WIP branch that rewrote the attribute initialisation behaviour in a way that would avoid this problem, but either I never pushed it or it vanished.

Either way, I'll look into this.

**Comment by razvanphp** [comment]
Just wanted to mention, that this works:
````javascript
model.set({
    'modifiedAt': String(new Date().toISOString()) // 2015-03-24T13:29:27.486Z
});
````
but this does not:
````javascript
model.set({
    'modifiedAt': String(Date.new) // function now() { [native code] }
});
````

For me, it seems inconsistent and I don't understand why are not the functions run, instead of having to specify them as String object?

Also for some reason, after all those tries, I always get the `Error: <data> cannot be converted into JSON shape: could not shape document` all the time when I replace the document, even if I change nothing in it. All I do is `repository.byId()` and `repository.replace(model)`. I guess the problem is that model.attributes has this inside:
````javascript
"_PRINT" : function (context) {\n  if (this instanceof ShapedJson) {\n    internal.printObject(this, context);\n  }\n  else {\n    context.output += this.toString();\n  }\n}
````

**Comment by pluma** [comment]
The "could not shape document" message typically indicates that the object contains functions, which matches your original problem.

**Comment by razvanphp** [comment]
Ok, so I figured it out with the date, but I found something else:

````javascript
var AppModel = Foxx.Model.extend({
    schema: {
        createdAt: Joi.date().iso().default(null),
        updatedAt: Joi.date().iso().default(null)
    }
});
````

The first save of the document works, puts the data string there, but when constructing the model again it fails somewhere in `moment.js`

````javascript
var app;
        
try {
    app = repository.byId('' + appId);
} catch (e) {
    app = new AppModel({
        _key: '' + appId,
        createdAt: new Date()
    });
    repository.save(app);
}

app = repository.byId('' + appId);
````

````
 ERROR Error in foxx route '{ "match" : "/user/:id/follow", "methods" : [ "post" ], "constraint" : { "id" : "/[0-9]+/" } }': 'undefined is not a function', Stacktrace: TypeError: undefined is not a function
 ERROR   at expandFormat (/usr/share/arangodb/js/node/node_modules/moment/moment.js:954:29)
 ERROR   at makeDateFromStringAndFormat (/usr/share/arangodb/js/node/node_modules/moment/moment.js:1309:18)
 ERROR   at makeMoment (/usr/share/arangodb/js/node/node_modules/moment/moment.js:1605:17)
 ERROR   at moment (/usr/share/arangodb/js/node/node_modules/moment/moment.js:1632:16)
 ERROR   at Object.internals.toDate (/usr/share/arangodb/js/node/node_modules/joi/lib/date.js:63:24)
 ERROR   at [object Object].internals.Date._base (/usr/share/arangodb/js/node/node_modules/joi/lib/date.js:28:46)
 ERROR   at [object Object].internals.Any._validate (/usr/share/arangodb/js/node/node_modules/joi/lib/any.js:371:31)
 ERROR   at [object Object].internals.Any.validate (/usr/share/arangodb/js/node/node_modules/joi/lib/any.js:438:23)
 ERROR   at [object Object]._.extend.set (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/model.js:213:11)
 ERROR   at /usr/share/arangodb/js/server/modules/org/arangodb/foxx/model.js:120:18
 ERROR   at Array.forEach (native)
 ERROR   at Function._.each._.forEach (/usr/share/arangodb/js/node/node_modules/underscore/underscore.js:79:11)
 ERROR   at [object Object].Model (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/model.js:117:7)
 ERROR   at new child (/usr/share/arangodb/js/common/modules/org/arangodb/extend.js:28:41)
 ERROR   at [object Object]._.extend.byId (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/repository.js:191:13)
 ERROR   at [object Object].Foxx.Repository.extend.increaseNumFollowers (/home/vagrant/cms/current/foxx/_db/bi_stage/app_follow/APP/repositories/AppRepository.js:26:14)
 ERROR   at /home/vagrant/cms/current/foxx/_db/bi_stage/app_follow/APP/controllers/UserController.js:78:31
 ERROR   at Object.res.action.callback (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/internals.js:108:5)
 ERROR   at /usr/share/arangodb/js/server/modules/org/arangodb/foxx/routing.js:323:19
 ERROR   at execute (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1291:7)
 ERROR   at next (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1308:7)
 ERROR   at [object Object]:386:5
 ERROR   at execute (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1291:7)
 ERROR   at routeRequest (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1312:3)
 ERROR   at foxxRouting (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1082:7)
 ERROR   at execute (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1291:7)
 ERROR   at Object.routeRequest (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1312:3)
 ERROR   at Function.actions.defineHttp.callback (/usr/share/arangodb/js/actions/api-system.js:51:15)
````

If I remove `.iso()` from the schema, it works correctly.

**Comment by razvanphp** [comment]
Ok, about the function inside of the object, it is this `_PRINT` prototype function from `shaped-json.js:60` as you can see in my previous comment.

This function appears in the attributes of the object, and if I remove it with `delete customer.attributes['_PRINT'];` before saving the document back, it works perfectly fine.

**Comment by razvanphp** [comment]
Unfortunately I cannot reproduce this with a new collection, just with one that I exported and imported from ArangoDB 2.4.6, before upgrading to 2.5.1.

Here is the strange thing:
````javascript
console.log(new Foxx.Repository(db._collection("customers")).byId('143243').attributes);
// 2015-03-24T18:54:44Z [4124] INFO { "_id" : "customers/143243", "_rev" : "17850799654836", "_key" : "143243", "updatedAt" : null, "lastLoginAt" : null, "_PRINT" : function (context) {\n  if (this instanceof ShapedJson) {\n    internal.printObject(this, context);\n  }\n  else {\n    context.output += this.toString();\n  }\n} }
console.log(db._collection("customers").document('143243'));
// 2015-03-24T18:54:44Z [4124] INFO { "_id" : "customers/143243", "_rev" : "17850799654836", "_key" : "143243", "updatedAt" : null, "lastLoginAt" : null }
````
Both lines are executed in the same time, just that one is through the repository, where the bug must be. Also, the _rev is the same, so that function is clearly not in the document. If I change anything in this document in the web interface and save it, the problem goes away in Foxx too.

This code snipped comes from `/usr/share/arangodb/js/server/modules/org/arangodb/shaped-json.js:58`, but I have no idea how it ends up in the document.

**Comment by pluma** [comment]
I can confirm that the `_PRINT` method is exposed in 2.4 and 2.5 but PR #1287 seems to remove that behaviour.

**Comment by pluma** [comment]
#1289 should do the trick until 2.6.
