### ISSUE TITLE
journals "Out of memory" exception

### ISSUE THREAD

**Issue by leonidUH** [arangodb/arangodb#13120]
## My Environment

* __ArangoDB Version__:        3.6.3-664
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Kubernetes ArangoDeployment
* __Configuration__:               3 agents ,3 dbservers ,3 coordinators
* __Infrastructure__:              AWS
* __Agent Requests__:       3X - cpu: 1500m, memory: 1536Mi
* __DbServer Requests__:   3X  -   cpu: 3, memory: 4G
* __Coordinator Requests__:   3X  -    cpu: 1500m, memory: 1536Mi
* __Arangodb-java-driver__:    6.4.1
* __Kube-arangodb-operator__:    1.0.5

__Problem__:

When i tried to add data to collection with arango java client  it failed  with arangodb "Out of memory" exception

**exception **:
```
ERROR [2020-12-01 09:43:27,967] com.test.Collection: Error while trying to add test object: Response: 500, Error: 1305 - IO error: While appending to file: /data/engine-rocksdb/journals/008379.log: Out of memory

! com.arangodb.ArangoDBException: Response: 500, Error: 1305 - IO error: While appending to file: /data/engine-rocksdb/journals/008379.log: Out of memory

! at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:52)

! at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:141)

! at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:126)

! at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:40)

! at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:124)

! at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:46)

! at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)

! at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:61)

! at com.arangodb.internal.ArangoVertexCollectionImpl.insertVertex(ArangoVertexCollectionImpl.java:57)

! at com.collection.querytracker.implementations.ArangoGraphDBTracker.addQuery(ArangoGraphDBTracker.java:201)

! at com.collection.resources.CollectionResource.startCollection(CollectionResource.java:186)

! at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)

! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

! at java.lang.reflect.Method.invoke(Method.java:498)

! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)

! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)

! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)

! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)

! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)

! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)

! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)

! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)

! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)

! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)

! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)

! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)

! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)

! at org.glassfish.jersey.internal.Errors.process(Errors.java:267)

! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)

! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)

! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)

! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)

! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)

! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)

! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)

! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)

! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)

! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)

! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)

! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)

! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)

! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)

! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)

! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)

! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)

! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)

! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)

! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)

! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)

! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)

! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)

! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)

! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)

! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)

! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:703)

! at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)

! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)

! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)

! at org.eclipse.jetty.server.Server.handle(Server.java:505)

! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)

! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)

! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)

! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)

! at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)

! at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)

! at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)

! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)

! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)

! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)

! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)

! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)

! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)

! at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)

! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)

! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)

! at java.lang.Thread.run(Thread.java:748)
```

![arango](https://user-images.githubusercontent.com/11331844/100743736-67fb9380-33e5-11eb-9869-b14851d4b136.jpg)

**Comment by dothebart** [comment]
whats `df -h` ? 
```
tripple-tics
```
are enough. no need for screenshots. 
Can you also upgrade to the latest bugfix release of 3.6 and see whether this behaviour persists?

**Comment by leonidUH** [comment]
No need upgrade to the latest release of 3.6 , because it was only once and no longer happens
```
/ # df -h 
Filesystem                Size      Used Available Use% Mounted on
overlay                  93.7G      5.1G     84.5G   6% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     3.7G         0      3.7G   0% /sys/fs/cgroup
/dev/nvme1n1             30.0G    348.7M     29.6G   1% /data
/dev/nvme0n1p2           93.7G      5.1G     84.5G   6% /dev/termination-log
/dev/nvme0n1p2           93.7G      5.1G     84.5G   6% /lifecycle/tools
/dev/nvme0n1p2           93.7G      5.1G     84.5G   6% /etc/resolv.conf
/dev/nvme0n1p2           93.7G      5.1G     84.5G   6% /etc/hostname
/dev/nvme0n1p2           93.7G      5.1G     84.5G   6% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                     3.7G      4.0K      3.7G   0% /secrets/cluster/jwt
tmpfs                     3.7G     12.0K      3.7G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                     3.7G         0      3.7G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     3.7G         0      3.7G   0% /sys/firmware
```

**Comment by dothebart** [comment]
Hi, 
this may very well be related to one of the fixes published in one of the subsequent versions. 
If you don't want to upgrade, I can't tell you no more than seems to be an OOM?

**Comment by leonidUH** [comment]
Hi
I can upgrade but  it will take time in our prod systems . The problem has not recurred yet
