### ISSUE TITLE
corrupt collection

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1333]
I somehow got a corrupt collection. I asked a generic question on http://stackoverflow.com/questions/30176068/how-to-repair-a-corrupted-collection-in-arangodb but just noticed something interesting in the arangod.log that might be too specific for StackOverflow:

```
2015-05-11T05:16:07Z [15927] INFO ArangoDB (version 2.5.3 [linux]) is ready for business. Have fun!
2015-05-11T05:17:02Z [15927] INFO control-c received, beginning shut down sequence
2015-05-11T05:17:09Z [16007] INFO ArangoDB 2.5.3 64bit -- ICU 52.1, V8 3.31.74.1, OpenSSL 1.0.1f 6 Jan 2014
2015-05-11T05:17:09Z [16007] INFO using default language 'en'
2015-05-11T05:17:10Z [16007] INFO loaded database '_system' from '/var/lib/arangodb/databases/database-115750'
2015-05-11T05:17:10Z [16007] INFO JavaScript using startup '/usr/share/arangodb/js', application '/var/lib/arangodb-apps'
2015-05-11T05:17:10Z [16007] INFO using V8 options '--harmony --harmony_arrow_functions'
2015-05-11T05:17:12Z [16017] INFO ArangoDB 2.5.3 64bit -- ICU 52.1, V8 3.31.74.1, OpenSSL 1.0.1f 6 Jan 2014
2015-05-11T05:17:12Z [16017] INFO using default language 'en'
2015-05-11T05:17:12Z [16017] INFO starting up in supervisor mode
2015-05-11T05:17:12Z [16019] INFO loaded database '_system' from '/var/lib/arangodb/databases/database-115750'
2015-05-11T05:17:12Z [16019] INFO running WAL recovery (1 logfiles)
2015-05-11T05:17:12Z [16019] INFO replaying WAL logfile '/var/lib/arangodb/journals/logfile-991553616778.db' (1 of 1)
2015-05-11T05:17:12Z [16019] INFO WAL recovery finished successfully
2015-05-11T05:17:12Z [16019] INFO using endpoint 'tcp://10.132.81.125:8529' for non-encrypted requests
2015-05-11T05:17:12Z [16019] INFO using endpoint 'tcp://127.0.0.1:8529' for non-encrypted requests
2015-05-11T05:17:12Z [16019] INFO using default API compatibility: 20500
2015-05-11T05:17:12Z [16019] INFO JavaScript using startup '/usr/share/arangodb/js', application '/var/lib/arangodb-apps'
2015-05-11T05:17:12Z [16019] INFO using V8 options '--harmony --harmony_arrow_functions'
2015-05-11T05:17:14Z [16019] INFO In database '_system': Database is up-to-date (20503/prod/standalone/existing)
2015-05-11T05:17:14Z [16019] WARNING collection 'wdt_packs' already exists. Leaving it untouched.
2015-05-11T05:17:14Z [16019] WARNING collection 'wdt_timers' already exists. Leaving it untouched.
2015-05-11T05:17:14Z [16019] WARNING collection 'wdt_timerLogs' already exists. Leaving it untouched.
2015-05-11T05:17:15Z [16019] INFO permanently changing the gid to 999
2015-05-11T05:17:15Z [16019] INFO permanently changing the uid to 999
2015-05-11T05:17:15Z [16019] INFO ArangoDB (version 2.5.3 [linux]) is ready for business. Have fun!
2015-05-11T16:22:09Z [16019] WARNING collection 'wdt_packs' already exists. Leaving it untouched.
2015-05-11T16:22:09Z [16019] WARNING collection 'wdt_timers' already exists. Leaving it untouched.
2015-05-11T16:22:09Z [16019] WARNING collection 'wdt_timerLogs' already exists. Leaving it untouched.
2015-05-11T16:22:31Z [16019] WARNING accept failed with 24 (Too many open files)
2015-05-11T16:22:31Z [16019] WARNING accept failed with 24 (Too many open files)
2015-05-11T16:22:31Z [16019] WARNING accept failed with 24 (Too many open files)
```
lot's of these and then
```
2015-05-11T16:22:31Z [16019] WARNING accept failed with 24 (Too many open files)
2015-05-11T16:22:31Z [16019] ERROR too many accept failures, stopping logging
2015-05-11T16:22:31Z [16019] WARNING accept failed with 24 (Too many open files)
```
...
```
2015-05-11T16:22:31Z [16019] WARNING accept failed with 24 (Too many open files)
2015-05-11T16:22:31Z [16019] ERROR too many accept failures, stopping logging
2015-05-11T16:22:31Z [16019] ERROR cannot open datafile '/var/lib/arangodb/databases/database-115750/collection-400775147359/datafile-400830197599.db': 'Too many open files'
2015-05-11T16:22:31Z [16019] ERROR cannot open datafile '/var/lib/arangodb/databases/database-115750/collection-400775147359/datafile-400830197599.db': Too many open files
2015-05-11T16:22:31Z [16019] ERROR cannot open document collection from path '/var/lib/arangodb/databases/database-115750/collection-400775147359'
2015-05-11T16:22:31Z [16019] WARNING accept failed with 24 (Too many open files)
2015-05-11T17:24:28Z [16019] ERROR Error in foxx route '{ "match" : "/timers/timers", "methods" : [ "post" ] }': 'corrupted collection', Stacktrace: Error: corrupted collection
2015-05-11T17:24:28Z [16019] ERROR   at Error (native)
2015-05-11T17:24:28Z [16019] ERROR   at /var/lib/arangodb-apps/_db/_system/wdt/APP/controllers/timers.js:113:22
2015-05-11T17:24:28Z [16019] ERROR   at Object.res.action.callback (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/internals.js:108:5)
2015-05-11T17:24:28Z [16019] ERROR   at /usr/share/arangodb/js/server/modules/org/arangodb/foxx/routing.js:323:19
2015-05-11T17:24:28Z [16019] ERROR   at execute (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1304:7)
2015-05-11T17:24:28Z [16019] ERROR   at next (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1321:7)
2015-05-11T17:24:28Z [16019] ERROR   at routingInfo.middleware.push.action.callback (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/controller.js:416:53)
2015-05-11T17:24:28Z [16019] ERROR   at execute (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1304:7)
2015-05-11T17:24:28Z [16019] ERROR   at next (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1321:7)
2015-05-11T17:24:28Z [16019] ERROR   at routingInfo.middleware.push.action.callback (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/controller.js:379:13)
2015-05-11T17:24:28Z [16019] ERROR   at execute (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1304:7)
2015-05-11T17:24:28Z [16019] ERROR   at next (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1321:7)
2015-05-11T17:24:28Z [16019] ERROR   at [object Object]:386:5
2015-05-11T17:24:28Z [16019] ERROR   at execute (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1304:7)
2015-05-11T17:24:28Z [16019] ERROR   at routeRequest (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1325:3)
2015-05-11T17:24:28Z [16019] ERROR   at foxxRouting (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1095:7)
2015-05-11T17:24:28Z [16019] ERROR   at execute (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1304:7)
2015-05-11T17:24:28Z [16019] ERROR   at Object.routeRequest (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1325:3)
2015-05-11T17:24:28Z [16019] ERROR   at Function.actions.defineHttp.callback (/usr/share/arangodb/js/actions/api-system.js:51:15)
2015-05-11T17:24:28Z [16019] ERROR 
```

**Comment by pekeler** [comment]
I just restarted arangod and it seems to be working again

```
2015-05-11T19:29:49Z [16019] INFO control-c received, beginning shut down sequence
2015-05-11T19:44:29Z [19847] INFO ArangoDB 2.5.3 64bit -- ICU 52.1, V8 3.31.74.1, OpenSSL 1.0.1f 6 Jan 2014
2015-05-11T19:44:29Z [19847] INFO using default language 'en'
2015-05-11T19:44:30Z [19847] INFO loaded database '_system' from '/var/lib/arangodb/databases/database-115750'
2015-05-11T19:44:30Z [19847] INFO JavaScript using startup '/usr/share/arangodb/js', application '/var/lib/arangodb-apps'
2015-05-11T19:44:30Z [19847] INFO using V8 options '--harmony --harmony_arrow_functions'
2015-05-11T19:44:33Z [19857] INFO ArangoDB 2.5.3 64bit -- ICU 52.1, V8 3.31.74.1, OpenSSL 1.0.1f 6 Jan 2014
2015-05-11T19:44:33Z [19857] INFO using default language 'en'
2015-05-11T19:44:33Z [19857] INFO starting up in supervisor mode
2015-05-11T19:44:34Z [19859] INFO loaded database '_system' from '/var/lib/arangodb/databases/database-115750'
2015-05-11T19:44:34Z [19859] INFO running WAL recovery (1 logfiles)
2015-05-11T19:44:34Z [19859] INFO replaying WAL logfile '/var/lib/arangodb/journals/logfile-991566571963.db' (1 of 1)
2015-05-11T19:44:34Z [19859] INFO WAL recovery finished successfully
2015-05-11T19:44:34Z [19859] INFO using endpoint 'tcp://10.132.81.125:8529' for non-encrypted requests
2015-05-11T19:44:34Z [19859] INFO using endpoint 'tcp://127.0.0.1:8529' for non-encrypted requests
2015-05-11T19:44:34Z [19859] INFO using default API compatibility: 20500
2015-05-11T19:44:34Z [19859] INFO JavaScript using startup '/usr/share/arangodb/js', application '/var/lib/arangodb-apps'
2015-05-11T19:44:34Z [19859] INFO using V8 options '--harmony --harmony_arrow_functions'
2015-05-11T19:44:37Z [19859] INFO In database '_system': Database is up-to-date (20503/prod/standalone/existing)
2015-05-11T19:44:37Z [19859] WARNING collection 'wdt_packs' already exists. Leaving it untouched.
2015-05-11T19:44:37Z [19859] WARNING collection 'wdt_timers' already exists. Leaving it untouched.
2015-05-11T19:44:37Z [19859] WARNING collection 'wdt_timerLogs' already exists. Leaving it untouched.
2015-05-11T19:44:37Z [19859] INFO permanently changing the gid to 999
2015-05-11T19:44:37Z [19859] INFO permanently changing the uid to 999
2015-05-11T19:44:37Z [19859] INFO ArangoDB (version 2.5.3 [linux]) is ready for business. Have fun!
```

I'll close that StackOverflow question again.

**Comment by fceller** [comment]
Basically it means that you ran out of file descriptors. You should raise the number of open files to something like 2000 or 4000. You could add 

  server.descriptors-minimum

to the arangod.conf to ensure that the number is available.

**Comment by fceller** [comment]
It normally happens if you open a lot of connections to the server. Each connections needs one file descriptor. If you eat up all allowed file descriptors, there is no way for ArangoDB to open its datafiles.

Therefore you need to raise the limit. ArangoDB can handle 10K or more connections.

**Comment by pekeler** [comment]
I don't think I did open a lot of connections. My app is still private and I'm the only user. According to my nginx log file, there was no unusual activity against my Foxx app. I'm also accessing the DB via arangojs from another server with only about 3 roundtrips per minute.

Also interesting, using aardvark I was still able to use the other 2 collections.

**Comment by fceller** [comment]
You could check the number of connections using netstat. Which OS are you using?

**Comment by pekeler** [comment]
Ubuntu 14.04.2 LTS
3.13.0-43-generic x86_64

**Comment by fceller** [comment]
And which node.js version? There seems to be some weird thing going on with node.js & connections. Can you try to issue a

    netstat -anpt

after a while? This should show how many connections are open. On my ubuntu the defaut limit is 1024.

**Comment by pekeler** [comment]
I'm using iojs v1.8.1

`netstat | grep ":8529" | wc -l` has been hovering between 8 and 18 since I've restarted 40 minutes ago. I'll keep an eye on it.

**Comment by jsteemann** [comment]
For info: it's not only the number of connections, but also the number of files opened by `arangod` that matter. That includes WAL logfiles (usually just a handful) but also collection datafiles. If there are many collections available with lots of files, then it might be sensible to raise the ulimit value for `max open files`.

**Comment by fceller** [comment]
Can you also check the open files? "lsof" should list them.

**Comment by pekeler** [comment]
`lsof | grep "arangodb" | wc -l`: 1570
Is that high or normal?

**Comment by fceller** [comment]
Can you post the output without the wc? Or send it to hackers (at) arangodb.com if it contains sensitive information.

**Comment by pekeler** [comment]
https://gist.github.com/pekeler/b2c657dde30d707ec20f

**Comment by fceller** [comment]
How many collections / database do you have?

**Comment by pekeler** [comment]
I have 3 collections in _system, no extra DB.

**Comment by fceller** [comment]
I thinks lsof is displaying each thread separately. Therefore the high numbers. So it is unclear why the file descriptors where used up. If the situation arises again, can you do the netstat and lsof?

**Comment by pekeler** [comment]
Perhaps I've structured one of my collections in a suboptimal way. The documents look like:

```
{
  "someFK": "123456789",
  "log": [
    [1, 1431416118000, "foo", "bar"],
    [8, 1431416119000, "baz", "uh"],
...
  ]
}
```
The "log" array is limited to 1000 elements. Every minute I slice and unshift the array with AQL:
```
'FOR tl IN myLogs FILTER tl.someFK == @aKey UPDATE tl WITH {log: SLICE(UNSHIFT(tl.log, @logEntry), 0, 1000)} IN myLogs
```

Any chance this structure contributed to the problem?

**Comment by fceller** [comment]
No, that should not cause such problems.

**Comment by pekeler** [comment]
OK, thanks. I'll make sure to netstat and lsof and report back when I see the problem again.

**Comment by CoDEmanX** [comment]
Couldn't you use a cap collection constraint instead to limit the number of entries? If there are plenty of such documents with their own doc key, then probably not...

**Comment by pekeler** [comment]
@CoDEmanX I have plenty of such documents, and will get more over time, so I don't think I should create a collection for each.
