### ISSUE TITLE
Can't use bindvars in UPSERT

### ISSUE THREAD

**Issue by sleepycat** [arangodb/arangodb#1341]
The UPSERT command does not seem to allow a bindvar, while the INSERT and UPDATE commands allow it. It would both useful and more consistent if bindvars could be used in all three places.

Is there any reason why UPSERT could not accept a bindvar as well?

```
arangosh [test]> db._query('UPSERT {"_id":"vertices/868273033179"} INSERT @insert UPDATE @update IN vertices', {"insert":{"sara_status":"EN","type":"listing"}, "update":{"sara_status":"EN", "type":"listing"}}).toArray()
[ ]

arangosh [test]> db._query('UPSERT @example INSERT @insert UPDATE @update IN vertices', {"example": {foo: "bar"}, "insert":{foo: "bar"}, "update":{}}).toArray()
JavaScript exception in file '/usr/share/arangodb/js/client/modules/org/arangodb/arangosh.js' at 106,13: [ArangoError 1501: expecting object literal for upsert search document near 'vertices' at position 1:50 (while parsing)]
!      throw new ArangoError(requestResult);
!            ^
stacktrace: Error
    at Object.exports.checkRequestResult (/usr/share/arangodb/js/client/modules/org/arangodb/arangosh.js:106:13)
    at ArangoStatement.execute (/usr/share/arangodb/js/client/modules/org/arangodb/arango-statement.js:184:12)
    at ArangoDatabase._query (/usr/share/arangodb/js/client/modules/org/arangodb/arango-database.js:823:42)
    at <shell command>:1:4


arangosh [test]> db._query('UPSERT {foo: "bar"} INSERT @insert UPDATE @update IN vertices', {"insert":{foo: "bar"}, "update":{}}).toArray()[ ]

```

Obviously using 2.6.0-devel.

P.S.: I really like UPSERT. Nice work!

**Comment by jsteemann** [comment]
Just fixed in devel.

**Comment by sleepycat** [comment]
Just pulled this and recompiled. Works perfectly.
Thanks Jan!
