### ISSUE TITLE
Intense operation over storing and loading operations resulted in a error

### ISSUE THREAD

**Issue by fmsouza** [arangodb/arangodb#1352]
MAC OS X Yosemite 10.10.4, installed through Homebrew.

2015-05-31T15:44:02Z [38151] INFO Authentication is turned off
2015-05-31T15:44:02Z [38151] INFO ArangoDB (version 2.5.3 [darwin]) is ready for business. Have fun!
2015-05-31T16:31:22Z [38151] ERROR Error in foxx route '{ "match" : "/query/result/download/:query", "methods" : [ "get" ] }': 'Invalid string length', Stacktrace: RangeError: Invalid string length
2015-05-31T16:31:22Z [38151] ERROR   at Object.stringify (native)
2015-05-31T16:31:22Z [38151] ERROR   at Object.responseFunctions.json ([object Object]:281:26)
2015-05-31T16:31:22Z [38151] ERROR   at /usr/local/Cellar/arangodb/2.5.3/share/arangodb/js/apps/system/_admin/aardvark/APP/aardvark.js:360:7
2015-05-31T16:31:22Z [38151] ERROR   at Object.res.action.callback (/usr/local/Cellar/arangodb/2.5.3/share/arangodb/js/server/modules/org/arangodb/foxx/internals.js:108:5)
2015-05-31T16:31:22Z [38151] ERROR   at /usr/local/Cellar/arangodb/2.5.3/share/arangodb/js/server/modules/org/arangodb/foxx/routing.js:323:19
2015-05-31T16:31:22Z [38151] ERROR   at execute (/usr/local/Cellar/arangodb/2.5.3/share/arangodb/js/server/modules/org/arangodb/actions.js:1304:7)
2015-05-31T16:31:22Z [38151] ERROR   at next (/usr/local/Cellar/arangodb/2.5.3/share/arangodb/js/server/modules/org/arangodb/actions.js:1321:7)
2015-05-31T16:31:22Z [38151] ERROR   at [object Object]:386:5
2015-05-31T16:31:22Z [38151] ERROR   at execute (/usr/local/Cellar/arangodb/2.5.3/share/arangodb/js/server/modules/org/arangodb/actions.js:1304:7)
2015-05-31T16:31:22Z [38151] ERROR   at routeRequest (/usr/local/Cellar/arangodb/2.5.3/share/arangodb/js/server/modules/org/arangodb/actions.js:1325:3)
2015-05-31T16:31:22Z [38151] ERROR   at foxxRouting (/usr/local/Cellar/arangodb/2.5.3/share/arangodb/js/server/modules/org/arangodb/actions.js:1095:7)
2015-05-31T16:31:22Z [38151] ERROR   at execute (/usr/local/Cellar/arangodb/2.5.3/share/arangodb/js/server/modules/org/arangodb/actions.js:1304:7)
2015-05-31T16:31:22Z [38151] ERROR   at Object.routeRequest (/usr/local/Cellar/arangodb/2.5.3/share/arangodb/js/server/modules/org/arangodb/actions.js:1325:3)
2015-05-31T16:31:22Z [38151] ERROR   at Function.actions.defineHttp.callback (/usr/local/Cellar/arangodb/2.5.3/share/arangodb/js/actions/api-system.js:51:15)

**Comment by jsteemann** [comment]
I can just guess what happened because the context is missing.
It looks like you used the "Download" button in the AQL editor of the web interface to download the results of a query. 
It also seems that the result of that query was big. The error shown in the logs `Invalid string length` is an error that V8 will throw when trying to assemble a string longer than 1 << 28 bytes (around 256 MB). So it looks like the whole query result, in is JSONified form was longer than that and serialization failed.

If the result is too big to download via the web interface, you might try to use a `LIMIT` clause for the query (which will decrease the query result size) or download the results via the cursor API (https://docs.arangodb.com/HttpAqlQueryCursor/QueryResults.html).

**Comment by fmsouza** [comment]
Yes. I don’t know exactly how large were my data store at the moment it occurred, but I’m certain it was over a million of documents in the collection. Also I did not used AQL editor. I’m not used to it, I just started trying the database for few days.
Ate the moment I stopped the database server, it had around 9 millions records in this collection, with around 2.5 GB of stored data.

Also, when I tried to list the data in that collection through web interface, it took around 5min. to complete the request consuming around 7GB of my RAM and 12GB of paginated files.

It doesn’t seems very performatic, at my sight...

**Comment by jsteemann** [comment]
When a collection is  not loaded (for example, this is the case after a server restart) the first action that uses a collection will fully load it. This may take some time given 2.5 GB of stored data. After the collection is loaded, responses should be fast however.
Regarding the 7 GB of RAM and 12 GB of paginated files, where does this measure come from and which request did you actually execute? 
Regarding the initial error in this issue, the stack trace shows the route "/query/result/download/:query". This is used in the AQL editor (when downloading query results) and in the list of documents of a collection, when downloading the whole collection data as a single JSON. I guess it was this action that didn't work and failed with the `Invalid string length` error.
So it looks like the data in the collection are too big to be sent to the browser using this method. I suggest using arangodump, which is a dedicated tool for dumping data. It will not have the size restrictions.

**Comment by fmsouza** [comment]
Oh, I see. Probably the error came from the "download" button in the list of documents.
About the execution consuming too much time and memory, I had a collection loaded with around 9 million documents (testing interaction with my js application, the collection.near() method didn't worked well and it got to replicate data lots of times).

Then I clicked the collection to open through the Web Interface. It took around 5-7min. to show the output. Seems like it loaded all the data in the collection before the exhibition, and then the screen came on. And for every filter I tried to apply after, it seemed to be requesting everything again to the database. How does this request exactly works?

The memory measures have came from ```htop``` UNIX application.

**Comment by jsteemann** [comment]
If the collection is not initially loaded, then listing its documents via the web interface will implicitly load it. The initial loading time of the collection may be high. After a collection is loaded however, this overhead should go away, and listing of documents should be instant.

Filtering for certain attribute/value combinations in the web interface will require a full scan of the collection if the filter condition does not contain any indexed attributes. I guess this was the case. In case of a full collection scan, each document in the collection will be checked for if it matches the specified filter criteria. This may take some time, but given a few million documents it shouldn't take minutes.

What is happening in your case is probably that the overall size of the collection(s) you are using is bigger than the available physical RAM, which will force the OS to constantly load and unload collection data pages from disk, making all accesses to the collection slow. My guess would be that when it gets slow, most of the machine's physical RAM is used and you will see disk activity and I/O wait. In this case, the dataset may be too big to fit into the available memory, or the indexes defined on the data may consume too much memory altogether. It's hard to tell from here given the limited information. How much RAM is available in total (and free), and what is the output of `db.collection.getIndexes();` and `db.collection.figures();` (where `collection` is the name of the collection in question) when run in the ArangoShell or the web interface's shell (**Tools** -> **JS Shell**)?

**Comment by fmsouza** [comment]
I kept testing these days and I noticed the access wasn’t that slow while I tried to search directly on the database. I think the real problem was that I tried to load all the 2.5GB of data to my browser instance.

I optimized my collections changing the data structure and it seems to be working very well now.

My PC have 8GB RAM. Usually it have half or a quarter of free RAM.

For now I’m good, thank you for the help. I think the problem was how I was handling the data.
You can close this issue now, and if I have some other problem I’ll come up here again.

**Comment by jsteemann** [comment]
Thanks for the feedback.
