### ISSUE TITLE
unittests-http-server failed with error kernel_require.rb:54:in `require': cannot load such file -- httparty (LoadError)

### ISSUE THREAD

**Issue by abelyaevskiy** [arangodb/arangodb#1371]
Hi!

I tried to setup unittests run for my dev environment.

I found that `unittests-http-server` failed with error `kernel_require.rb:54:in 'require': cannot load such file -- httparty (LoadError)`

Full log:

    2015-06-11T15:26:39Z [14831] INFO using no init file at all
    2015-06-11T15:26:39Z [14831] INFO ArangoDB 2.5.4 64bit -- ICU 52.1, V8 3.31.74.1, OpenSSL     1.0.1 14 Mar 2012
    2015-06-11T15:26:39Z [14831] INFO using default language 'en'
    2015-06-11T15:26:39Z [14831] INFO WAL directory '/tmp/vocdir.14551/journals' does not exist.  creating it...
    2015-06-11T15:26:39Z [14831] INFO loaded database '_system' from '/tmp/vocdir.14551/databases/database-77310'
    2015-06-11T15:26:39Z [14831] INFO collection '_users' does not exist, no authentication available
    2015-06-11T15:26:39Z [14831] INFO using endpoint 'tcp://127.0.0.1:34551' for non-encrypted requests
    2015-06-11T15:26:39Z [14831] INFO using default API compatibility: 20500
    2015-06-11T15:26:39Z [14831] INFO JavaScript using startup './js', application './js/apps'
    2015-06-11T15:26:41Z [14831] INFO In database '_system': No version information file found in database directory.
    2015-06-11T15:26:41Z [14831] INFO In database '_system': Found 24 defined task(s), 19 task(s) to run
    2015-06-11T15:26:41Z [14831] INFO In database '_system': state prod/standalone/init, tasks setupUsers, createUsersIndex, addDefaultUser, updateUserModel, setupGraphs, createModules, createRouting, createKickstarterConfiguration, insertRedirectionsAll, setupAal, createAalIndex, setupAqlFunctions, createStatistics, createConfiguration, systemAppEndpoints, setupQueues, setupJobs, moveFoxxApps, dropAal
    2015-06-11T15:26:41Z [14831] INFO In database '_system': init successfully finished
    2015-06-11T15:26:42Z [14831] INFO Authentication is turned off
    2015-06-11T15:26:42Z [14831] INFO ArangoDB (version 2.5.4 [linux]) is ready for business. Have fun!
    /var/lib/jenkins/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- httparty (LoadError)
        from /var/lib/jenkins/.rvm/rubies/ruby-1.9.3-  p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /var/lib/jenkins/workspace/BuildMeta4/UnitTests/HttpInterface/arangodb.rb:4:in `<top (required)>'
        from /var/lib/jenkins/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /var/lib/jenkins/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /var/lib/jenkins/workspace/BuildMeta4/UnitTests/HttpInterface/api-admin-spec.rb:4:in `<top (required)>'
        from /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
        from /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
        from /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
        from /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
        from /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
        from /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
        from /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
        from /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
        from /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
        from /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p551/bin/rspec:23:in `load'
        from /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p551/bin/rspec:23:in `<main>'
        from /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
        from /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
    make: *** [unittests-http-server] Error 1

My config:
    
    jenkins@jenkins:~/workspace/BuildMeta4$ ruby --version
    ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
    jenkins@jenkins:~/workspace/BuildMeta4$ rspec --version
    3.2.3
    jenkins@jenkins:~/workspace/BuildMeta4$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 12.04.4 LTS
    Release:        12.04
    Codename:       precise
    jenkins@jenkins:~/workspace/BuildMeta4$ cat VERSION
    2.5.4

I found solution [how-fix-this-error-kernel-require-rb45in-require-cannot-load-such-file](http://stackoverflow.com/questions/16924370/how-fix-this-error-kernel-require-rb45in-require-cannot-load-such-file) but not sure is it ok for the case and should I create patch for you or not because of ArangoDB version?

**Comment by fceller** [comment]
The unittests are using rspec (a ruby test framework). They require a few gems like "httparty" and IIRC "json". Can you try to install them with 

    gem install httparty

**Comment by abelyaevskiy** [comment]
Yes! Thank you! Just found it!
