### ISSUE TITLE
ArangoError: exception in 'lib/Dispatcher/DispatcherThread.cpp'

### ISSUE THREAD

**Issue by fmsouza** [arangodb/arangodb#1378]
I'm testing ArangoDB in a docker container linked to another container running a nodejs application which is doing huge requests to the database.

Sometimes this error appears on my console:

ArangoError: exception in 'lib/Dispatcher/DispatcherThread.cpp' at line 159: type = 'internal error' details = 'job failed with unknown in work: std::bad_alloc'
-----------------------------------------------------------
    at new ArangoError (/path/to/project/node_modules/arangojs/lib/error.js:10:13)
    at /path/to/project/node_modules/arangojs/lib/connection.js:91:71
    at /path/to/project/node_modules/arangojs/lib/util/request.js:58:12
    at /path/to/project/node_modules/arangojs/lib/util/once.js:7:15
    at IncomingMessage.<anonymous> (/path/to/project/node_modules/arangojs/lib/util/request.js:66:11)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by fmsouza** [comment]
The instance is stopping very often.

**Comment by fmsouza** [comment]
Checking the container log, this is the information it shows:

```
starting ArangoDB in stand-alone mode
2015-06-16T00:36:55Z [1] INFO ArangoDB 2.5.5 64bit -- ICU 52.1, V8 3.31.74.1, OpenSSL 1.0.1f 6 Jan 2014
2015-06-16T00:36:55Z [1] INFO using default language 'en'
2015-06-16T00:36:55Z [1] INFO loaded database '_system' from '/data/databases/database-77864'
2015-06-16T00:36:55Z [1] INFO loaded database 'riobus' from '/data/databases/database-126365736'
2015-06-16T00:36:55Z [1] INFO running WAL recovery (1 logfiles)
2015-06-16T00:36:55Z [1] INFO replaying WAL logfile '/data/journals/logfile-164111421415.db' (1 of 1)
2015-06-16T00:36:55Z [1] INFO WAL recovery finished successfully
2015-06-16T00:36:55Z [1] INFO using endpoint 'tcp://0.0.0.0:8529' for non-encrypted requests
2015-06-16T00:36:55Z [1] INFO using default API compatibility: 20500
2015-06-16T00:36:55Z [1] INFO JavaScript using startup '/usr/share/arangodb/js', application '/apps'
2015-06-16T00:36:57Z [1] INFO In database 'riobus': Database is up-to-date (20505/prod/standalone/existing)
2015-06-16T00:36:57Z [1] INFO In database '_system': Database is up-to-date (20505/prod/standalone/existing)
2015-06-16T00:36:57Z [1] INFO permanently changing the gid to 999
2015-06-16T00:36:57Z [1] INFO permanently changing the uid to 999
2015-06-16T00:36:57Z [1] INFO Authentication is turned off
2015-06-16T00:36:57Z [1] INFO ArangoDB (version 2.5.5 [linux]) is ready for business. Have fun!


#
# Fatal error in ../src/heap/mark-compact.cc, line 2137
# CHECK(success) failed
#

==== C stack trace ===============================

 1: (0xc1847d)/usr/sbin/arangod() [0xc1847d]
 2: (0x911109)/usr/sbin/arangod() [0x911109]
 3: (0x919382)/usr/sbin/arangod() [0x919382]
 4: (0x91a9c9)/usr/sbin/arangod() [0x91a9c9]
 5: (0x8e78a7)/usr/sbin/arangod() [0x8e78a7]
 6: (0x8e7b15)/usr/sbin/arangod() [0x8e7b15]
 7: (0x8e91bc)/usr/sbin/arangod() [0x8e91bc]
 8: (0x8e930d)/usr/sbin/arangod() [0x8e930d]
 9: (0x8206ed)/usr/sbin/arangod() [0x8206ed]
10: (0x6666e8)/usr/sbin/arangod() [0x6666e8]
11: (0x42f2fa)/usr/sbin/arangod() [0x42f2fa]
12: (0x6b4ace)/usr/sbin/arangod() [0x6b4ace]
13: (0x6b4c09)/usr/sbin/arangod() [0x6b4c09]
14: (0x6b4c5c)/usr/sbin/arangod() [0x6b4c5c]
15: (0x7f22a5f40182)/lib/x86_64-linux-gnu/libpthread.so.0(+0x8182) [0x7f22a5f40182]
16: (0x7f22a5c6cefd)

#
# Fatal error in ../src/heap/store-buffer.cc, line 134
# CHECK(old_virtual_memory_->Commit(reinterpret_cast<void*>(old_limit_), grow * kPointerSize, false)) failed
#
```

**Comment by jsteemann** [comment]
Both error messages indicate that the arangod instance ran out of memory.
Is there any particular request/query that triggers this behavior or does it happen non-deterministically? 
If this is triggered by AQL queries, it might be worth trying out version 2.6 (currently in beta), because it will reduce AQL memory usage for at least some queries. Whether it will help in your actual case is hard to tell without further information.

**Comment by fmsouza** [comment]
It was happening non-deterministically. I scaled up the memory for the container and it seems to be fixed now. I left it running through last night and worked very well.

Thank you!
