### ISSUE TITLE
Travis marked green, but Jasmine Tests are failing

### ISSUE THREAD

**Issue by aurelijusb** [arangodb/arangodb#1438]
https://travis-ci.org/arangodb/arangodb#L6215
https://s3.amazonaws.com/archive.travis-ci.org/jobs/75633976/log.txt
```
Running Jasmine Tests: ./js/common/tests/shell-foxx-manager-install-spec.js, ./js/common/tests/shell-query-timecritical-spec.js, ./js/server/tests/shell-foxx-manager-spec.js, ./js/server/tests/shell-foxx-model-events-spec.js, ./js/server/tests/shell-foxx-query-spec.js, ./js/server/tests/shell-foxx-repository-spec.js, ./js/server/tests/shell-foxx-repository-events-spec.js

2015-08-14T17:10:30Z [11444] ERROR Cannot parse app manifest "js/apps/_db/_system/unittest/broken/APP/manifest.json": SyntaxError: Unexpected token s
2015-08-14T17:10:30Z [11444] ERROR   at Object.parse (native)
2015-08-14T17:10:30Z [11444] ERROR   at validateManifestFile (./js/server/modules/org/arangodb/foxx/manager.js:424:15)
2015-08-14T17:10:30Z [11444] ERROR   at appConfig (./js/server/modules/org/arangodb/foxx/manager.js:553:15)
2015-08-14T17:10:30Z [11444] ERROR   at createApp (./js/server/modules/org/arangodb/foxx/manager.js:567:16)
2015-08-14T17:10:30Z [11444] ERROR   at _scanFoxx (./js/server/modules/org/arangodb/foxx/manager.js:882:13)
...
Finished in 64.437 seconds
95 example, 0 failures
```
You can search for `ERROR` in test results to find more examples of failures marked as passed.

**Comment by mchacki** [comment]
Hi @aurelijusb 
the Test is not failing, travis is flashing green light correctly.

The error log is an intentioned caused by the test suite `/js/common/tests/shell-foxx-manager-install-spec.js`.

This suite tries to install malformed Foxx services and tests if ArangoDB rejects them correctly.
The setup for this test is that a client application installs the Foxx services and expects an error (this is suppressed in the log) The server however prints this error in it's log as well (this is not suppressed the Server is not modified for client-side tests) and the output merges client/server logs together, that's why this "Error" is printed but has no effect.
