### ISSUE TITLE
Index out of bounds (while executing)

### ISSUE THREAD

**Issue by AntoineAA** [arangodb/arangodb#14762]
Hello,

We have an error related to the latest version of ArangoDB 3.8.0. (the related query worked with 3.7).

For your information, we have not upgraded from 3.7 but we made a fresh install directly in 3.8.

Best regards,

Antoine

## My Environment

* __ArangoDB Version__:        3.8.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               
* __Infrastructure__:               own
* __Operating System__:        Debian 9
* __Total RAM in your machine__:        128Gb
* __Disks in use__:        HDD
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
AQL query

__AQL query (if applicable)__:
```
let genera = [{ genus: 'Acer', referential: 'weurope' }]
				let data = (
					for g in genera
						let counts = (
							for tm in z_taxa_meta
								filter tm.images_count > 0
								filter tm.referential == g.referential
								and tm.genus_without_author == g.genus
								collect aggregate
									images_count = sum(tm.images_count),
									observations_count = sum(tm.observations_count),
									species_count = sum(1)
								return {
									images_count: images_count,
									observations_count: observations_count,
									species_count: species_count
								}
						)[0]
						let images = (
							for tm in z_taxa_meta
								filter tm.images_count > 0
								filter tm.referential == g.referential
								and tm.genus_without_author == g.genus
								for i in tm.tmp_best_images
									sort i.order, i.score desc, i.date desc
									limit 4
									return i
						)
						let best_images_ids = (
							(length(images) > 0)
							? (
								for b in images
									return b.id
							)
							: null
						)
						return {
							referential: g.referential,
							genus: g.genus,
							genus_species_count: counts.species_count,
							genus_images_count: counts.images_count,
							genus_observations_count: counts.observations_count,
							genus_best_images: best_images_ids
						}
				)
				for tm in z_taxa_meta
					for d in data
						filter tm.genus_without_author == d.genus
						and tm.referential == d.referential
						and (
							tm.genus_species_count != d.genus_species_count
							or tm.genus_images_count != d.genus_images_count
							or tm.genus_observations_count != d.genus_observations_count
							or tm.genus_best_images != d.genus_best_images
						)
						update tm with {
							genus_species_count: d.genus_species_count,
							genus_images_count: d.genus_images_count,
							genus_observations_count: d.genus_observations_count,
							genus_best_images: d.genus_best_images
						} in z_taxa_meta
```
__AQL explain and/or profile (if applicable)__:
```
Query String (1977 chars, cacheable: false):
 let genera = [{ genus: 'Acer', referential: 'weurope' }]
 				let data = (
 					for g in genera
 						let counts = (
 							for tm in z_taxa_meta
 								filter tm.images_count > 0
 								filter tm.referential == g.referential
 								and tm.genus_without_author == g.genus
 								collect aggregate
 									images_count = sum(tm.images_count),
 									observations_count = sum(tm.observations_count),
 									species_count = sum(1)
 								return {
 									images_count: images_count,
 									observations_count: observations_count,
 									species_count: species_count
 								}
 						)[0]
 						let images = (
 							for tm in z_taxa_meta
 								filter tm.images_count > 0
 								filter tm.referential == g.referential
 								and tm.genus_without_author == g.genus
 								for i in tm.tmp_best_images
 									sort i.order, i.score desc, i.date desc
 									limit 4
 									return i
 						)
 						let best_images_ids = (
 							(length(images) > 0)
 							? (
 								for b in im...

Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
 14   CalculationNode        1     - LET #35 = 1   /* json expression */   /* const assignment */
  2   CalculationNode        1     - LET genera = [ { "genus" : "Acer", "referential" : "weurope" } ]   /* json expression */   /* const assignment */
  5   EnumerateListNode      1     - FOR #65 IN genera   /* list iteration */
 58   SubqueryStartNode      1       - LET #62 = ( /* subquery begin */
 53   IndexNode              3         - FOR tm IN z_taxa_meta   /* hash index scan, projections: `images_count`, `tmp_best_images` */    FILTER (tm.`images_count` > 0)   /* early pruning */   
 26   CalculationNode        3           - LET #43 = tm.`tmp_best_images`   /* attribute expression */   /* collections used: tm : z_taxa_meta */
 27   EnumerateListNode    300           - FOR i IN #43   /* list iteration */
 28   CalculationNode      300             - LET #45 = i.`order`   /* attribute expression */
 29   CalculationNode      300             - LET #47 = i.`score`   /* attribute expression */
 30   CalculationNode      300             - LET #49 = i.`date`   /* attribute expression */
 31   SortNode             300             - SORT #45 ASC, #47 DESC, #49 DESC   /* sorting strategy: constrained heap */
 32   LimitNode              4             - LIMIT 0, 4
 59   SubqueryEndNode        1             - RETURN  i ) /* subquery end */
 56   SubqueryStartNode      1       - LET #61 = ( /* subquery begin */
 36   EnumerateListNode    100         - FOR b IN #62   /* list iteration */
 37   CalculationNode      100           - LET #51 = b.`id`   /* attribute expression */
 57   SubqueryEndNode        1           - RETURN  #51 ) /* subquery end */
 54   SubqueryStartNode      1       - LET #64 = ( /* subquery begin */
 52   IndexNode              3         - FOR tm IN z_taxa_meta   /* hash index scan, projections: `images_count`, `observations_count` */    FILTER (tm.`images_count` > 0)   /* early pruning */   
 12   CalculationNode        3           - LET #31 = tm.`images_count`   /* attribute expression */   /* collections used: tm : z_taxa_meta */
 13   CalculationNode        3           - LET #33 = tm.`observations_count`   /* attribute expression */   /* collections used: tm : z_taxa_meta */
 15   CollectNode            1           - COLLECT AGGREGATE images_count = SUM(#31), observations_count = SUM(#33), species_count = SUM(#35)   /* sorted */
 50   LimitNode              1           - LIMIT 0, 1
 16   CalculationNode        1           - LET #37 = { "images_count" : images_count, "observations_count" : observations_count, "species_count" : species_count }   /* simple expression */
 55   SubqueryEndNode        1           - RETURN  #37 ) /* subquery end */
 19   CalculationNode        1       - LET #63 = #64[0]   /* simple expression */
 40   CalculationNode        1       - LET #60 = ((LENGTH(#62) > 0) ? #61 : null)   /* simple expression */
 48   CalculationNode        1       - LET #57 = { "genus_species_count" : #63.`species_count`, "genus_images_count" : #63.`images_count`, "genus_observations_count" : #63.`observations_count`, "genus_best_images" : #60 }   /* simple expression */
 51   IndexNode             12       - FOR tm IN z_taxa_meta   /* hash index scan */    
 46   CalculationNode       12         - LET #55 = (((tm.`genus_without_author` == #65.`genus`) && (tm.`referential` == #65.`referential`)) && ((((tm.`genus_species_count` != #63.`species_count`) || (tm.`genus_images_count` != #63.`images_count`)) || (tm.`genus_observations_count` != #63.`observations_count`)) || (tm.`genus_best_images` != #60)))   /* simple expression */   /* collections used: tm : z_taxa_meta */
 47   FilterNode            12         - FILTER #55
 49   UpdateNode             0         - UPDATE tm WITH #57 IN z_taxa_meta 

Indexes used:
 By   Name              Type      Collection    Unique   Sparse   Selectivity   Fields                                      Ranges
 53   idx_11017026002   hash      z_taxa_meta   false    false        26.92 %   [ `genus_without_author`, `referential` ]   ((tm.`genus_without_author` == #65.`genus`) && (tm.`referential` == #65.`referential`))
 52   idx_11017026002   hash      z_taxa_meta   false    false        26.92 %   [ `genus_without_author`, `referential` ]   ((tm.`genus_without_author` == #65.`genus`) && (tm.`referential` == #65.`referential`))
 51   idx_11017026002   hash      z_taxa_meta   false    false        26.92 %   [ `genus_without_author`, `referential` ]   ((tm.`genus_without_author` == #65.`genus`) && (tm.`referential` == #65.`referential`))
 51   idx_11017026002   hash      z_taxa_meta   false    false        26.92 %   [ `genus_without_author`, `referential` ]   ((tm.`genus_without_author` == #65.`genus`) && (tm.`referential` == #65.`referential`))
 51   idx_11017026002   hash      z_taxa_meta   false    false        26.92 %   [ `genus_without_author`, `referential` ]   ((tm.`genus_without_author` == #65.`genus`) && (tm.`referential` == #65.`referential`))
 51   idx_11017026002   hash      z_taxa_meta   false    false        26.92 %   [ `genus_without_author`, `referential` ]   ((tm.`genus_without_author` == #65.`genus`) && (tm.`referential` == #65.`referential`))
 49   primary           primary   z_taxa_meta   true     false       100.00 %   [ `_key` ]                                  tm

Functions used:
 Name     Deterministic   Cacheable   Uses V8
 LENGTH   true            true        false  

Optimization rules applied:
 Id   RuleName
  1   inline-subqueries
  2   simplify-conditions
  3   move-calculations-up
  4   move-filters-up
  5   remove-redundant-calculations
  6   remove-unnecessary-calculations
  7   optimize-subqueries
  8   move-calculations-up-2
  9   move-filters-up-2
 10   remove-data-modification-out-variables
 11   use-indexes
 12   remove-filter-covered-by-index
 13   remove-unnecessary-calculations-2
 14   move-calculations-down
 15   sort-limit
 16   reduce-extraction-to-projection
 17   move-filters-into-enumerate
 18   splice-subqueries

Optimization rules with highest execution times:
 RuleName                                    Duration [s]
 use-indexes                                      0.00052
 inline-subqueries                                0.00027
 remove-filter-covered-by-index                   0.00019
 remove-redundant-calculations                    0.00018
 remove-unnecessary-calculations-2                0.00018

43 rule(s) executed, 1 plan(s) created

Write query options:
 Option                   Value
 waitForSync              false
 skipDocumentValidation   false
 keepNull                 true
 mergeObjects             true
 ignoreRevs               true
 isRestore                false
 ignoreErrors             false
 ignoreDocumentNotFound   false
 readCompleteInput        true
 consultAqlWriteFilter    false
 exclusive                false
```

__Dataset__:

Here is an example of a document from the collection:
```
{
  "species": "Silene vivianii Steud.",
  "referential": "bdtfx_sync_v1",
  "species_without_author": "Silene vivianii",
  "genus": "Silene L.",
  "genus_without_author": "Silene",
  "family": "Caryophyllaceae",
  "family_without_author": "Caryophyllaceae",
  "observations_count": 1,
  "images_count": 2,
  "images_count_flower": 1,
  "images_count_fruit": 1,
  "images_count_leaf": 0,
  "images_count_bark": 0,
  "images_count_habit": 0,
  "images_count_branch": 0,
  "images_count_scan": 0,
  "images_count_sheet": 0,
  "images_count_other": 0,
  "best_images": [
    "dc8da0c6a9c532cb4575cd2681a574e0fb403acd",
    "c3d216aabd144128908f7bffbb8889e5b6ec9867"
  ],
  "tmp_best_images": [
    {
      "id": "dc8da0c6a9c532cb4575cd2681a574e0fb403acd",
      "order": 0,
      "score": 3,
      "date": 1355241597000
    },
    {
      "id": "c3d216aabd144128908f7bffbb8889e5b6ec9867",
      "order": 1,
      "score": 3,
      "date": 1355241597000
    }
  ],
  "genus_observations_count": 2311,
  "genus_images_count": 4431,
  "genus_species_count": 65,
  "genus_best_images": [
    "294ad592cba741e4d65922871b629c37bf43f8ad",
    "4896947a989e20e94e742ede9dffb9a2edd02676",
    "d2b4bb7017e4ba80e6211c5b2a627cd8c7ecb684",
    "87a1d9fe783de0a7b991f48e6944cca6679c59f4"
  ],
  "family_species_count": 280,
  "family_genera_count": 37,
  "family_best_images": [
    "294ad592cba741e4d65922871b629c37bf43f8ad",
    "4896947a989e20e94e742ede9dffb9a2edd02676",
    "a559e92dbee0d193b9a5a06611b5437477d74603",
    "d2b4bb7017e4ba80e6211c5b2a627cd8c7ecb684"
  ],
  "family_observations_count": 9252,
  "family_images_count": 16875,
  "images_count_anatomy": 0,
  "images_count_exclude": 0,
  "images_count_seed": 0,
  "images_count_bud": 0,
  "images_count_drawing": 0,
  "images_count_landscape": 0
}
```

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Run the query

__Problem__:
```
{
	code: 500,
	error: true,
	errorMessage: 'Index out of bounds (while executing) (exception location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:289). Please report this error to arangodb.com',
	errorNum: 4
}

ArangoError: Index out of bounds (while executing) (exception location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:289). Please report this error to arangodb.com
    at new ArangoError (/home/admin/test-data-access-layer-read/node_modules/arangojs/error.js:115:21)
    at Object.resolve (/home/admin/test-data-access-layer-read/node_modules/arangojs/connection.js:410:37)
    at callback (/home/admin/test-data-access-layer-read/node_modules/arangojs/connection.js:192:26)
    at IncomingMessage.<anonymous> (/home/admin/test-data-access-layer-read/node_modules/arangojs/lib/request.node.js:108:21)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1331:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

__Expected result__:

**Comment by Simran-B** [comment]
Can you provide a minimal example to reproduce the issue, or potentially share the dataset (in private) so that we can try to reproduce it on our end?

**Comment by AntoineAA** [comment]
Hi,
Yes, I can share the dataset with you, what is the proper way to do it?

**Comment by maxkernbach** [comment]
Hi @AntoineAA,

As Simran-B mentioned, you can send us a mail to hackers@arangodb.com attaching a dump of your dataset (using [arangodump](https://www.arangodb.com/docs/stable/programs-arangodump.html)) and referencing the GitHub issue number. In case your dataset is too big for an attachment, please still send us a mail and we will provide you with an upload location.

**Comment by AntoineAA** [comment]
The email has been sent!
