### ISSUE TITLE
Error: Socket hang up while db.query

### ISSUE THREAD

**Issue by mahesth** [arangodb/arangodb#14836]
Hi, 

We have recently upgraded our arangodb to 3.6 and we are getting **ECONNRESET** error while running a query on specific collection. 

`error { Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketOnEnd (_http_client.js:426:23)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ECONNRESET'`

While executing the query manually in the query editor the query seems to ran fine without any issues. 

and we are getting this error only if the query execution time exceeds ~50 seconds. 

we get the ECONNRESET error in the code and strangely the **ArangoDB UI also logs out.** 

There were no **major page faults** happened and not much CPU hike also registered. 

_Need help on if any config change required in the code or in collections._

**Comment by dothebart** [comment]
Please note that arangodb 3.6.16 is available for download which is the last release of this release series. 
Please upgrade at least to this patch release, and check whether the behaviour persists.

You should however consider updating to arangodb 3.7 or better 3.8

**Comment by mohsinht** [comment]
> You should however consider updating to arangodb 3.7 or better 3.8
I'm still getting this ` socket hang up` error from ArangoDB. I have arangodb 3.10.

**Comment by fredarend** [comment]
I'm encountering the same issue with version 3.10.0  too. But, not in all requests, just some. For example, a request that search items in two collections.

Most of time, this request executes perfectly, but in some cases, an error occurs.

```
const cursor = await dbArango.query(
    aql`
      FOR sp IN sales_products
      FILTER TO_STRING(sp.cod_usuario) == ${user_id}
      FOR product IN products
      FILTER product._key == sp.ean_code
      SORT product.created_at DESC
      RETURN DISTINCT {
        ean: sp.ean_code,
        name: sp.nome_produto,
        image: product.imageUrl
      }
 `,
```

I've used nodejs 16, 18 and 20.
I'm using arangojs lib on 8.6 version.

**Comment by dothebart** [comment]
Hi, please upgrade to 3.10.13 and check whether the issue persists.

**Comment by fredarend** [comment]
> Hi, please upgrade to 3.10.13 and check whether the issue persists.

Hi, we upgraded to 3.10.13 and the error still happen.
Any other suggestion?

**Comment by dothebart** [comment]
please inspect the logfile, and see whether a PID-change / restart happenes. 
Next thing is to check the output of `netstat -alpnt` to see what happenes, or maybe even observe it with tcpdump.
