### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#1564]
JavaScript exception in file './js/common/bootstrap/modules.js' at 524,13: [ArangoError 3103: failed to invoke module
File: ./js/node/wut.js]
!      throw err;
!            ^
stacktrace: [ArangoError 3103: failed to invoke module
File: ./js/node/wut.js]
  at [object Object].Module.run (./js/common/bootstrap/modules.js:1429:20)
  at createModule (./js/common/bootstrap/modules.js:517:19)
  at requireModuleFrom (./js/common/bootstrap/modules.js:619:21)
  at requirePackage (./js/common/bootstrap/modules.js:777:21)
  at [object Object].Module.require (./js/common/bootstrap/modules.js:1214:21)
  at require (./js/common/bootstrap/modules.js:50:24)
  at <shell command>:1:1

The result is ok, but the the error is not inside of wut.js, but in hass.js, because of the undefined function func() is invoked. 
The exception doesn't tell that I'm calling an undefined function. So the user has no chance to find out what in the code (foxx app) is broken.
One should get to know the primary failure reason like here:

JavaScript exception in file './js/common/bootstrap/modules.js' at 524,13: [ArangoError 3103: failed to invoke module
File: ./js/node/hass.js, Root cause: ReferenceError: func is not defined]
!      throw err;
!            ^
stacktrace: [ArangoError 3103: failed to invoke module
File: ./js/node/hass.js, Root cause: ReferenceError: func is not defined]
  at [object Object].Module.run (./js/common/bootstrap/modules.js:1437:20)
  at createModule (./js/common/bootstrap/modules.js:517:19)
  at requireModuleFrom (./js/common/bootstrap/modules.js:619:21)
  at requirePackage (./js/common/bootstrap/modules.js:777:21)
  at [object Object].Module.require (./js/common/bootstrap/modules.js:1214:21)
  at require (./js/common/bootstrap/modules.js:50:24)
  at <shell command>:1:1

Sample patch to solve the problem, but has to be finalized: https://gist.github.com/d65406076f4b7fea26da

(on behalf of steemann)

**Comment by dothebart** [comment]
@pluma pls finalize and incooperate this patch.
