### ISSUE TITLE
some error message

### ISSUE THREAD

**Issue by realdog** [arangodb/arangodb#1569]
I installed arangodb 2.7 on my mac . 
I write my first foxx.
and ... when i refresh arangodb web interface, there are some error message  

```
{
"exception": "TypeError: Cannot read property 'errors' of undefined",
"stacktrace": [
"TypeError: Cannot read property 'errors' of undefined",
" at /Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/foxx/sessions.js:70:36",
" at callback (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/foxx/controller.js:612:24)",
" at execute (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:1309:7)",
" at next (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:1326:7)",
" at BaseMiddleware.middleware (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/foxx/base_middleware.js:424:5)",
" at execute (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:1309:7)",
" at next (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:1326:7)",
" at BaseMiddleware.middleware (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/foxx/base_middleware.js:424:5)",
" at execute (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:1309:7)",
" at routeRequest (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:1330:3)",
" at foxxRouting (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:1081:7)",
" at execute (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:1309:7)",
" at Object.routeRequest (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:1330:3)",
" at Function.actions.defineHttp.callback (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/actions/api-system.js:58:15)"
],
"error": true,
"code": 400,
"errorNum": 17,
"errorMessage": "failed to execute foxx mounted at '/_admin/aardvark'"
}
```

**Comment by dothebart** [comment]
did you alter your system as you asked in #1541 ? Or did you start with a fresh database with valid routes to the management interface?

**Comment by pluma** [comment]
For some reason the system session app isn't mounted, so the frontend ends up trying to use a session store that doesn't exist (`undefined`).

Could you provide more information on what exactly you did before this happened? And have you tried restarting arangod?

**Comment by pluma** [comment]
@realdog Can you provide any more details? We can't reproduce this problem otherwise.

**Comment by dothebart** [comment]
missing feedback.
