### ISSUE TITLE
arangosh: db._createDocumentCollection immediately after ArangoDB installation (deb) fails

### ISSUE THREAD

**Issue by baslr** [arangodb/arangodb#1584]
given script
```
wget -q https://www.arangodb.com/repositories/arangodb2/Debian_8.0/amd64/arangodb_2.7.1_amd64.deb
dpkg -i arangodb_2.7.1_amd64.deb
arangosh --javascript.execute-string "db._createDocumentCollection('testCollection');"
```

leads to
```
JavaScript exception in file '/usr/share/arangodb/js/client/modules/org/arangodb/arangosh.js' at 104,13: [ArangoError 2001: Could not connect to 'tcp://127.0.0.1:8529' 'connect() failed with #111 - Connection refused']
!      throw new ArangoError(requestResult);
!            ^
stacktrace: Error
    at Object.exports.checkRequestResult (/usr/share/arangodb/js/client/modules/org/arangodb/arangosh.js:104:13)
    at ArangoDatabase._create (/usr/share/arangodb/js/client/modules/org/arangodb/arango-database.js:331:12)
    at ArangoDatabase._createDocumentCollection (/usr/share/arangodb/js/client/modules/org/arangodb/arango-database.js:348:15)
```

I guess a deb script returns 0 before ArangoDB is ready

**Comment by dothebart** [comment]
Yes, the daemonizing can't tell when the daemon is completely operational and finished its startup.
You will get into similar problems with most other services that have to do startup preparation.

If you need to  you will have to detect this like we do it in [our unit testing framework](https://github.com/arangodb/arangodb/blob/devel/js/server/modules/org/arangodb/testing.js#L439): 
```javascript
var download = require("internal").download;
var wait = require("internal").wait;

while (true) {
  wait(0.5, false);
  var r = download("http://127.0.0.1:8529/_api/version", "");
  if (! r.error && r.code === 200) {
    break;
  }
}

print("ArangoDB startup completed!")
```
or some tiny bash script:
```bash
while /bin/true do
  if netstat -lpnt 2>/dev/null |grep -q ':8529'; then
    break
  fi
done
echo "ArangoDB is Up"
```
(for shure you can concatenate these with ;s)

**Comment by baslr** [comment]
Hi, thanks for your fast reply.
`while true ; do if netstat -lpnt 2>/dev/null | grep -q ':8529'; then break; fi; done`
solves it :-)

**Comment by dothebart** [comment]
you may want to add a sleep to it if you want to keep it from busy waiting ;-)
