### ISSUE TITLE
Aardvark 2.8 beta

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1611]
Just noticed that the "Advanced" collapsible can not be expanded in the Add Collection popup, neither in current Chrome, Firefox, nor IE.

A more cosmetic problem: if you add a database, there's already a very long password entered (probably [this](https://github.com/arangodb/arangodb/blob/05b45b166a3846f0a5b6474e1959f93b50ffa46a/CHANGELOG#L437)), which is irritating. Would be nicer if there were two radio buttons to switch between "Use default root password (environment variable)" and the password field, and have the field be disabled if the former is selected.

**Comment by hkernbach** [comment]
1. Yep, I can confirm this. 
2. Good idea.

**Comment by CoDEmanX** [comment]
Some more small things:

- If you click on the user icon in Tools > User management, two popups open at once (Edit User and Delete Database?!)

- A click on the database icon in Manage databases does not do anything, didn't it navigate you to the dashboard of the clicked DB in earlier versions?

- If you add users whose usernames consist of spaces only, it is accepted, but you can't delete them anymore in the GUI (you still can from the _users collection).

**Comment by hkernbach** [comment]
1. fixed
2. new ticket created: #1623
3. Can't reproduce, but will try...
4. fixed
5. fixed

**Comment by CoDEmanX** [comment]
<ol start="3">
<li>It occurred in multiple browsers, but it doesn't anymore in private browsing (2.8/devel) - maybe a temporary issue / cache related. You need to click near the icon to open the dialog though. It doesn't do anything if you click elsewhere (except the cog icon), e.g. the user name (gray background).</li></ol>

<ol start="6">
<li>If you expand a figure in the dashboard, the background isn't wide enough:
<img alt="aardvark_stats_28" src="https://cloud.githubusercontent.com/assets/1309249/11928992/f6a642a0-a7d7-11e5-8790-791e26d5c6da.png"/></li>
<li>If you expand a figure and the database is not _system, an error is raised:
<pre>2015-12-19T21:14:18Z [16324] ERROR Error in foxx route '{ "match" : "/statistics/long", "methods" : [ "get" ] }': 'collection not found (_statistics)', Stacktrace:
2015-12-19T21:14:18Z [16324] ERROR Error: collection not found (_statistics)
2015-12-19T21:14:18Z [16324] ERROR     at Error (native)
2015-12-19T21:14:18Z [16324] ERROR     at ArangoStatement.execute (h:\ArangoDB\arangodb\Build64\_CPack_Packages\win64\ZIP\ArangoDB-2.8.0-beta2-win64\share\arangodb\js\server\modules\org\arangodb\arango-statement.js:89:45)
2015-12-19T21:14:18Z [16324] ERROR     at ArangoDatabase._query (h:\ArangoDB\arangodb\Build64\_CPack_Packages\win64\ZIP\ArangoDB-2.8.0-beta2-win64\share\arangodb\js\server\modules\org\arangodb\arango-database.js:106:45)
2015-12-19T21:14:18Z [16324] ERROR     at computeStatisticsLong (H:\ArangoDB\arangodb\Build64\_CPack_Packages\win64\ZIP\ArangoDB-2.8.0-beta2-win64\share\arangodb\js\apps\system\_admin\aardvark\APP\statistics.js:377:21)
2015-12-19T21:14:18Z [16324] ERROR     at H:\ArangoDB\arangodb\Build64\_CPack_Packages\win64\ZIP\ArangoDB-2.8.0-beta2-win64\share\arangodb\js\apps\system\_admin\aardvark\APP\statistics.js:501:18
2015-12-19T21:14:18Z [16324] ERROR     at Object.res.action.callback (h:\ArangoDB\arangodb\Build64\_CPack_Packages\win64\ZIP\ArangoDB-2.8.0-beta2-win64\share\arangodb\js\server\modules\org\arangodb\foxx\internals.js:87:5)
2015-12-19T21:14:18Z [16324] ERROR     at h:\ArangoDB\arangodb\Build64\_CPack_Packages\win64\ZIP\ArangoDB-2.8.0-beta2-win64\share\arangodb\js\server\modules\org\arangodb\foxx\routing.js:320:17
2015-12-19T21:14:18Z [16324] ERROR     at execute (h:\ArangoDB\arangodb\Build64\_CPack_Packages\win64\ZIP\ArangoDB-2.8.0-beta2-win64\share\arangodb\js\server\modules\org\arangodb\actions.js:1309:7)
2015-12-19T21:14:18Z [16324] ERROR     at next (h:\ArangoDB\arangodb\Build64\_CPack_Packages\win64\ZIP\ArangoDB-2.8.0-beta2-win64\share\arangodb\js\server\modules\org\arangodb\actions.js:1326:7)
2015-12-19T21:14:18Z [16324] ERROR     at callback (h:\ArangoDB\arangodb\Build64\_CPack_Packages\win64\ZIP\ArangoDB-2.8.0-beta2-win64\share\arangodb\js\server\modules\org\arangodb\foxx\controller.js:646:42)</pre>
</li>
</ol>

**Comment by hkernbach** [comment]
3.1. fixed (the db management view was using a wrong id for a container which causes the problems)
3.2. fixed (the click event thing)
6. fixed
7. fixed

**Comment by CoDEmanX** [comment]
Hm, I pulled from devel, compiled, installed grunt/grunt-cli and deps, then grunted aardvark. Launched server, used private browsing to avoid caches, but still seeing the issues. Did I miss something?

**Comment by hkernbach** [comment]
Hm. I just pulled devel and grunted on my machine. Changes are visible. I just pushed the current grunt build. Could you pull and try again? Maybe something with your grunt process went wrong.

**Comment by CoDEmanX** [comment]
Doh, I compiled and then grunted, but did not copy the new files over to the proper build folder (I usually use the unpacked ZIP pack folder). I should had grunted first, then compile to make the build script use the updated JS files. All issues resolved, thank you!

Regarding 3.2: same issue exists for the tiles in Database Manager. A click on the icon takes you to the dashboard, the surrounding area does nothing. I didn't have luck with the jQuery selector, but it should be a simple fix:

https://github.com/arangodb/arangodb/blob/374bdde9e44a3c898174f96ef154c47d55803b52/js/apps/system/_admin/aardvark/APP/frontend/js/views/dbSelectionView.js#L11

**Comment by hkernbach** [comment]
Also fixed.
