### ISSUE TITLE
SIGSEGV after finished replication sync on slave

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb#1669]
Here is the core dump trace, version 2.7.2, Debian Jessie:

```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/ar'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004dbbc6 in EqualElementShape (left=0x7f78ae99ddb8, right=0x7f775295cf08)
    at arangod/VocBase/VocShaper.cpp:164
164 arangod/VocBase/VocShaper.cpp: No such file or directory.
(gdb) bt
#0  0x00000000004dbbc6 in EqualElementShape (left=0x7f78ae99ddb8, right=0x7f775295cf08)
    at arangod/VocBase/VocShaper.cpp:164
#1  0x00000000007819ce in TRI_InsertElementAssociativePointer (array=array@entry=0x18861ab0,
    element=element@entry=0x7f78ae99ddb8, overwrite=overwrite@entry=true) at lib/Basics/associative.cpp:299
#2  0x00000000004dc917 in VocShaper::moveMarker (this=0x18861800, marker=marker@entry=0x7f78ae99dda0,
    expectedOldPosition=expectedOldPosition@entry=0x7f790d8a5670) at arangod/VocBase/VocShaper.cpp:732
#3  0x0000000000637629 in triagens::wal::CollectorThread::processCollectionOperations (this=0x325a140,
    cache=0x81525acf0) at arangod/Wal/CollectorThread.cpp:789
#4  0x0000000000637eb3 in triagens::wal::CollectorThread::processQueuedOperations (this=0x325a140,
    worked=@0x7f78ae99ddb8: <error reading variable>) at arangod/Wal/CollectorThread.cpp:576
#5  0x000000000063a252 in triagens::wal::CollectorThread::run (this=0x325a140) at arangod/Wal/CollectorThread.cpp:389
#6  0x00000000007c1794 in runMe (this=0x325a140) at lib/Basics/Thread.cpp:311
#7  triagens::basics::Thread::startThread (arg=0x325a140) at lib/Basics/Thread.cpp:58
#8  0x00000000007c30ec in ThreadStarter (data=0x3d6b100) at lib/Basics/threads-posix.cpp:82
#9  0x00007f7a617820a4 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#10 0x00007f7a614b704d in clone () from /lib/x86_64-linux-gnu/libc.so.6
(gdb)
```

**Comment by wirtsi** [comment]
Some more info on this:
```
arangosh [bi_live]> require("org/arangodb/replication").sync({   endpoint: "<endpoint>",   username: "root",   password: "foo",   includeSystem: false });
1JavaScript exception in file '/usr/share/arangodb/js/client/modules/org/arangodb/arangosh.js' at 104,13: [ArangoError 2001: Error reading from: 'tcp://127.0.0.1:8529' 'timeout during read']
!      throw new ArangoError(requestResult);
!            ^
stacktrace: Error
    at Object.exports.checkRequestResult (/usr/share/arangodb/js/client/modules/org/arangodb/arangosh.js:104:13)
    at Object.sync (/usr/share/arangodb/js/client/modules/org/arangodb/replication.js:182:12)
    at <shell command>:1:37
```
So it appears at some point the replication slave stops responding.

**Comment by wirtsi** [comment]
Ok...so it is not quite clear if the client timed out because I was not using async. But still, the server crashed at pretty exactly that time

**Comment by wirtsi** [comment]
ok, so one more update: This time I ran the sync with async param set to true. But after about 20 minutes, the slave died
```
2016-01-21T14:14:03 [776] ERROR child 34781 died a horrible death, signal 11
2016-01-21T14:14:03 [776] INFO using logfiles: supervisor process: '/var/log/arangodb/arangod.log.daemon', child process: '/var/log/arangodb/arangod.log'
```
Last entry in the arangod.log was at 2016-01-21T14:13:17. So he managed to keep going for a few more seconds. Next line is at 14:14:15 when the server is starting up again

```
2016-01-21T14:14:15 [52568] INFO loaded database '_system' from '/var/lib/arangodb/databases/database-103204'
```
Error message on arangosh was the same as above

**Comment by razvanphp** [comment]
... and the core dump this time, looks similar:

```
Core was generated by `arangodb [supervisor]                                                         '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  EqualKeyShapeId (key=0x7f7a3c336978, element=0x7f724911d2a8) at arangod/VocBase/VocShaper.cpp:197
197	arangod/VocBase/VocShaper.cpp: No such file or directory.
(gdb) bt
#0  EqualKeyShapeId (key=0x7f7a3c336978, element=0x7f724911d2a8) at arangod/VocBase/VocShaper.cpp:197
#1  0x0000000000781805 in TRI_LookupByKeyAssociativePointer (array=array@entry=0x1d032b28, key=key@entry=0x7f7a3c336978)
    at lib/Basics/associative.cpp:233
#2  0x00000000004dbde2 in VocShaper::lookupShapeId (this=this@entry=0x1d032800, sid=sid@entry=34) at arangod/VocBase/VocShaper.cpp:411
#3  0x000000000049ea7a in KeysOfShapedJson (args=...) at arangod/V8Server/v8-wrapshapedjson.cpp:376
#4  0x0000000000d683ce in v8::internal::PropertyCallbackArguments::Call (this=this@entry=0x7f7a3c336ab0,
    f=f@entry=0x49e970 <KeysOfShapedJson(v8::PropertyCallbackInfo<v8::Array> const&)>) at ../src/arguments.cc:86
#5  0x0000000000bfd4c4 in v8::internal::JSObject::GetKeysForNamedInterceptor (object=object@entry=..., receiver=...,
    receiver@entry=...) at ../src/objects.cc:13856
#6  0x0000000000c2dc8d in v8::internal::JSReceiver::GetKeys (object=..., object@entry=...,
    type=type@entry=v8::internal::JSReceiver::OWN_ONLY) at ../src/objects.cc:6342
#7  0x0000000000c6eb22 in __RT_impl_Runtime_OwnKeys (isolate=0x101cc000, args=...) at ../src/runtime/runtime-object.cc:1102
#8  v8::internal::Runtime_OwnKeys (args_length=<optimized out>, args_object=<optimized out>, isolate=0x101cc000)
    at ../src/runtime/runtime-object.cc:1081
#9  0x000022bf998060bb in ?? ()
#10 0x00007f7a3c336d00 in ?? ()
```

**Comment by baslr** [comment]
Hi @razvanphp,

is this still an issue?

**Comment by razvanphp** [comment]
I think so, looking at the stack trace looks like a small bug in the code, maybe a quick check internally can decide if in the meantime it was fixed.

**Comment by razvanphp** [comment]
ah, no, 2.8 only, but I assumed the code was maybe inherited.

**Comment by baslr** [comment]
@razvanphp does this error occure with ArangoDB v2.8?
