### ISSUE TITLE
HMAC error after 2.7.3 -> 2.8.0 -> 2.7.3 with sessions-jwt

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1696]
```JSON
{"exception":"[ArangoError 10: usage: HMAC(<key>, <text>, <algorithm>)]","stacktrace":[
  "[ArangoError 10: usage: HMAC(<key>, <text>, <algorithm>)]",
  "  at Error (native)",
  "  at Object.exports.hmac (/usr/local/Cellar/arangodb/2.7.3/share/arangodb/js/common/modules/org/arangodb/crypto.js:65:19)",
  "  at Object.sign (/usr/local/Cellar/arangodb/2.7.3/share/arangodb/js/common/modules/org/arangodb/crypto.js:193:31)",
  "  at Object.exports.jwtEncode (/usr/local/Cellar/arangodb/2.7.3/share/arangodb/js/common/modules/org/arangodb/crypto.js:260:63)",
  "  at child._.extend.forClient (./foxx/_db/mydb/sessions/APP/storage.js:63:24)",
  "  at /usr/local/Cellar/arangodb/2.7.3/share/arangodb/js/server/modules/org/arangodb/foxx/sessions.js:82:29",
  "  at callback (/usr/local/Cellar/arangodb/2.7.3/share/arangodb/js/server/modules/org/arangodb/foxx/controller.js:649:50)",
  "  at execute (/usr/local/Cellar/arangodb/2.7.3/share/arangodb/js/server/modules/org/arangodb/actions.js:1309:7)",
  "  at next (/usr/local/Cellar/arangodb/2.7.3/share/arangodb/js/server/modules/org/arangodb/actions.js:1326:7)",
  "  at callback (/usr/local/Cellar/arangodb/2.7.3/share/arangodb/js/server/modules/org/arangodb/foxx/controller.js:613:13)",
  "  at execute (/usr/local/Cellar/arangodb/2.7.3/share/arangodb/js/server/modules/org/arangodb/actions.js:1309:7)",
  "  at next (/usr/local/Cellar/arangodb/2.7.3/share/arangodb/js/server/modules/org/arangodb/actions.js:1326:7)",
  "  at BaseMiddleware.middleware (/usr/local/Cellar/arangodb/2.7.3/share/arangodb/js/server/modules/org/arangodb/foxx/base_middleware.js:424:5)",
  "  at execute (/usr/local/Cellar/arangodb/2.7.3/share/arangodb/js/server/modules/org/arangodb/actions.js:1309:7)",
  "  at routeRequest (/usr/local/Cellar/arangodb/2.7.3/share/arangodb/js/server/modules/org/arangodb/actions.js:1330:3)",
  "  at foxxRouting (/usr/local/Cellar/arangodb/2.7.3/share/arangodb/js/server/modules/org/arangodb/actions.js:1081:7)",
  "  at execute (/usr/local/Cellar/arangodb/2.7.3/share/arangodb/js/server/modules/org/arangodb/actions.js:1309:7)",
  "  at Object.routeRequest (/usr/local/Cellar/arangodb/2.7.3/share/arangodb/js/server/modules/org/arangodb/actions.js:1330:3)",
  "  at Function.actions.defineHttp.callback (/usr/local/Cellar/arangodb/2.7.3/share/arangodb/js/actions/api-system.js:58:15)"
],"message":"usage: HMAC(<key>, <text>, <algorithm>)","error":true,"code":400,"errorNum":10,"errorMessage":"failed to execute foxx mounted at '/myapp'"}
```

Could it be that `brew upgrade arangodb` for 2.8.0 installed a new encryption lib, and `brew switch arangodb 2.7.3` did not downgrade the lib?

Now what?

**Comment by pekeler** [comment]
I think I need some help to get this running again. When I did `brew upgrade arangodb` to upgrade from 2.7.3 to 2.8.0, I remember that openssl was upgraded as well. Using `brew switch openssl <older version>` doesn't seem to work because when restarting arangod, it always logs "OpenSSL 1.0.2e 3 Dec 2015".

The "sessions" foxx app near the top of the stack trace is sessions-jwt of which I've been using the latest version for a while.

I'm on OS X 10.11.3.

**Comment by pekeler** [comment]
Figured it out: I didn't configure the sessions-jwt service with a value for jwtSecret. OK, now I'm officially extra annoyed about #1695 and closing this one in favour of a new issue for sessions-jwt.
