### ISSUE TITLE
Arango DB issue 

### ISSUE THREAD

**Issue by vaibhavgupta18** [arangodb/arangodb#17289]
Arango version 3.3.16 

We are creating connection trough java service as below 

		return new ArangoDB.Builder().host(host, port).user(user).password(password).useProtocol(Protocol.VST)
				.useSsl(ssl).maxConnections(1).connectionTtl(1000 * 60 * 3L).build();

below are the java driver versions used 

			arangodb-spring-data
			<version>3.2.0</version>

			arangodb-java-driver
			<version>4.7.0</version>

we are getting below error frequently is some requests  

 Could not connect to host[addr=XXXXXX,port=XXXX] or SSL Handshake failed. Try connecting to host[addr=XXXXXX,port=XXXX]

g.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
admit_erpservicescalendar.1.m84fuptatr8a@ADMIT-PROD-MEMBER2-NEW    |    at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:321)
admit_erpservicescalendar.1.m84fuptatr8a@ADMIT-PROD-MEMBER2-NEW    |    at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:284)
admit_erpservicescalendar.1.m84fuptatr8a@ADMIT-PROD-MEMBER2-NEW    |    at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:118)
admit_erpservicescalendar.1.m84fuptatr8a@ADMIT-PROD-MEMBER2-NEW    |    at com.fasterxml.jackson.core.json.UTF8JsonGenerator.flush(UTF8JsonGenerator.java:1100)
admit_erpservicescalendar.1.m84fuptatr8a@ADMIT-PROD-MEMBER2-NEW    |    at

**Comment by dothebart** [comment]
Hi, 
please note that ArangoDB 3.3 is out of Support for quiet a while. Please upgrade to Arangodb 3.8 or later. 
please note as well, that the mmfiles-storage engine is not supported anymore.

**Comment by vaibhavgupta18** [comment]
hi @dothebart  can i upgrade  from 3.3 to new stable.
If yes can you share the steps to do that without impacting running application and recommend the next stable version .

**Comment by Simran-B** [comment]
Have a look here:
- https://www.arangodb.com/docs/stable/upgrading-general-info.html
- https://www.arangodb.com/docs/stable/release-notes-upgrading-changes37.html#mmfiles-storage-engine
- https://www.arangodb.com/docs/3.7/administration-engine-switch-engine.html

An uninterrupted upgrade between 3.3 and 3.8+ is hardly possible. If you plan on upgrading anyway, consider to upgrade to 3.10, which is the latest stable version.
