### ISSUE TITLE
ArangoDB 3.10.0 "gauge arangodb_search_num_failed_commits already exists"

### ISSUE THREAD

**Issue by Sieabah** [arangodb/arangodb#17424]
Attempting to register the following index creates the following error. This is hitting server version 3.10.0 on docker. No logs on the server relating to this guage.

      {
        name: 'verification-attempt-identities',
        type: 'inverted',
        fields: ['attemptIdentities[*].value'],
      },

```
ArangoError: gauge arangodb_search_num_failed_commits already exists (exception location: /work/ArangoDB/arangod/Metrics/MetricsFeature.cpp:83). Please report this error to arangodb.com
2022-10-20T15:48:42.822273765Z     at new ArangoError (/srv/app/node_modules/src/error.ts:142:17)
2022-10-20T15:48:42.822277435Z     at callback (/srv/app/node_modules/src/connection.ts:671:19)
2022-10-20T15:48:42.822279905Z     at IncomingMessage.<anonymous> (/srv/app/node_modules/src/lib/request.node.ts:172:15)
2022-10-20T15:48:42.822281765Z     at IncomingMessage.emit (node:events:525:35)
2022-10-20T15:48:42.822283895Z     at IncomingMessage.emit (node:domain:489:12)
2022-10-20T15:48:42.822285395Z     at endReadableNT (node:internal/streams/readable:1358:12)
2022-10-20T15:48:42.822287005Z     at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-10-20T15:48:42.822580284Z 10/20/2022, 3:48:42 PM [ExceptionHandler] gauge arangodb_search_num_failed_commits already exists (exception location: /work/ArangoDB/arangod/Metrics/MetricsFeature.cpp:83). Please report this error to arangodb.com +0ms
2022-10-20T15:48:42.822600244Z ArangoError: gauge arangodb_search_num_failed_commits already exists (exception location: /work/ArangoDB/arangod/Metrics/MetricsFeature.cpp:83). Please report this error to arangodb.com
2022-10-20T15:48:42.822604434Z     at new ArangoError (/srv/app/node_modules/src/error.ts:142:17)
2022-10-20T15:48:42.822606384Z     at callback (/srv/app/node_modules/src/connection.ts:671:19)
2022-10-20T15:48:42.822608214Z     at IncomingMessage.<anonymous> (/srv/app/node_modules/src/lib/request.node.ts:172:15)
2022-10-20T15:48:42.822610354Z     at IncomingMessage.emit (node:events:525:35)
2022-10-20T15:48:42.822612004Z     at IncomingMessage.emit (node:domain:489:12)
2022-10-20T15:48:42.822613594Z     at endReadableNT (node:internal/streams/readable:1358:12)
2022-10-20T15:48:42.822614994Z     at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by dothebart** [comment]
do you have similar named indices on other databases or collections?

**Comment by MBkkt** [comment]
It means you try to create index with same name

**Comment by Sieabah** [comment]
Sorry for the delay, I ended up with covid and lost track of this. @MBkkt I'm using the "ensure index" exists, which just attempts  to register if it doesn't already exist.

```
async ensureIndexExists(arangoModel: ArangoModel<any>) {
    const { ensureIndexes = true } = readArangoMetadata(arangoModel.constructor);
    if (!ensureIndexes) {
      return;
    }

    const indexName = (name) => `${this.collection.name}_${name}`;

    const desiredIndexes = new Set(
      arangoModel.indexConfig.map(({ name }) => indexName(name))
    );
    desiredIndexes.add("primary");

    const indexesToRemove =
      ensureIndexes === "create-only"
        ? []
        : await arangoModel.collection
          .indexes()
          .then((indexes) =>
            indexes
              .filter((index) => !desiredIndexes.has(index.name || index.id))
              .map(({ id }) => id)
          );

    try {
      await Promise.all([
        ...indexesToRemove.map((id) => {
          this.logger.log(`Destroying index ${id}`);
          return arangoModel.collection.dropIndex({ id })
        }),
        ...arangoModel.indexConfig.map(({ ...index }: any) =>{
            this.logger.log(`Ensuring index ${index.name}`);
            return arangoModel.collection.ensureIndex(
              Object.assign(index, {
                name: indexName(index.name),
                inBackground: index.inBackground ?? true,
              })
            );
          }
        ),
      ]);
    } catch(err) {
      this.logger.error(`Error while ensuring indexes for ${arangoModel.collection.name}`);
      this.debug(err);
      throw err;
    }
  }
```

The array this is pulling from is just defining indexes like so, which are all uniquely named. All persistent indexes worked fine, but inverted indexes cause this gauge issue. Is this something unique to inverted indexes where calling ensureIndex() on an existing inverted index causes a prometheus gauge to be double defined? 

```
      {
        name: 'user-apex-ids',
        type: 'inverted',
        fields: ['apexIds'],
      },
      {
        name: 'user-auth-id',
        type: 'persistent',
        fields: ['authId'],
        unique: false,
      },
```

**Comment by MBkkt** [comment]
> This works with persistent indexes just fine it's only inverted indexes that cause this prometheus gauge issue.

Because only inverted have metrics per index now, if some other index will have it, it will be same error
But in general this problem not about metrics, it about implementation of index creation, for non inverted index it ensureIndex relies on current implementation (there is first init step indexes is stub (not true for inverted))

Anyway you right and it should be fixed

**Comment by Simran-B** [comment]
Internal ticket that tracks this issue: https://arangodb.atlassian.net/browse/SEARCH-385

**Comment by MBkkt** [comment]
Fixed in nightly https://download.arangodb.com/nightly/3.10/index.html

Will be available in 3.10.2
