### ISSUE TITLE
Javascript exception when commenting javadoc style in foxx apps

### ISSUE THREAD

**Issue by DonMartio** [arangodb/arangodb#1748]
When deploying an application which contains modules commented like this:

var FormstateCollector = {
    /**
     * @param session
     * @returns {FormstateCollector}
     */
    prepare: function(session) {

we get this exception:

2016-02-15T15:41:25Z [2445] ERROR SyntaxError: JavaScript exception in file '/var/tmp/arangod/apps/tmp-2445-937311944/lib/graph/collectors/formstate.js' at 16,19: SyntaxError: Unexpected token .

2016-02-15T15:41:25Z [2445] ERROR !applicationContext.comment("");

2016-02-15T15:41:25Z [2445] ERROR !                  ^

2016-02-15T15:41:25Z [2445] ERROR stacktrace: SyntaxError: Unexpected token .

2016-02-15T15:41:25Z [2445] ERROR     at Module._compile (/usr/share/arangodb/js/common/bootstrap/modules.js:550:17)

2016-02-15T15:41:25Z [2445] ERROR     at Object.Module._extensions..js (/usr/share/arangodb/js/common/bootstrap/modules.js:614:10)

2016-02-15T15:41:25Z [2445] ERROR     at Module.load (/usr/share/arangodb/js/common/bootstrap/modules.js:514:32)

2016-02-15T15:41:25Z [2445] ERROR     at Function.Module._load (/usr/share/arangodb/js/common/bootstrap/modules.js:462:14)

2016-02-15T15:41:25Z [2445] ERROR     at Module.require (/usr/share/arangodb/js/common/bootstrap/modules.js:534:17)

2016-02-15T15:41:25Z [2445] ERROR     at require (/usr/share/arangodb/js/common/bootstrap/modules.js:90:19)

2016-02-15T15:41:25Z [2445] ERROR     at Object.<anonymous> (/var/tmp/arangod/apps/tmp-2445-937311944/lib/graph/calculator.js:13:17)

2016-02-15T15:41:25Z [2445] ERROR     at Module._compile (/usr/share/arangodb/js/common/bootstrap/modules.js:584:8)

2016-02-15T15:41:25Z [2445] ERROR     at Object.Module._extensions..js (/usr/share/arangodb/js/common/bootstrap/modules.js:614:10)

2016-02-15T15:41:25Z [2445] ERROR     at Module.load (/usr/share/arangodb/js/common/bootstrap/modules.js:514:32)

2016-02-15T15:41:25Z [2445] ERROR

If we use comments like this (one instead of two stars):

    /*
     * @param session
     * @returns {FormstateCollector}
     */
the deployment succeeds. 

We are using arangodb 2.8.2 and i'm not sure if this problem is new. It's a little bit misleading if you get an error because of the comment style you are using. Is this fixable or aren't jdoc comments supported?

**Comment by pluma** [comment]
This problem is a result of the magical comments in ArangoDB 2.x and will go away in 3.0 (along with the support for magical comments).

I think it may have been triggered in 2.8 by the changes to the module loader though, so I think we can fix it for the time being.

**Comment by pluma** [comment]
This problem will no longer occur in future releases of 2.8 unless you are using jsdoc/javadoc style comments in controller/script/exports files directly (where they are expected to be interpreted as controller doc comments). Note that the magical comments are going away in 3.0 anyway.
