### ISSUE TITLE
[BUG] New coredump observed in Slice

### ISSUE THREAD

**Issue by sourabhedake-mm** [arangodb/arangodb#17930]
@dothebart Is there any update on the core dump mentioned in - https://github.com/arangodb/arangodb/issues/9302#issuecomment-504300956

I am facing a similar core in the prod -
```
(gdb) bt 
#0  0x0000556d1d209d0a in arangodb::velocypack::readIntegerNonEmpty<unsigned long> (start=0x7f364e208ae8 <error: Cannot access memory at address 0x7f364e208ae8>, length=4)
    at /c8db/3rdParty/velocypack/include/velocypack/velocypack-common.h:230
#1  0x0000556d1d209622 in arangodb::velocypack::Slice::getNthOffset (this=0x7f35ee9f5820, index=0) at /c8db/3rdParty/velocypack/src/Slice.cpp:495
#2  0x0000556d1be88709 in arangodb::velocypack::Slice::getNthKeyUntranslated (this=0x7f35ee9f5820, index=0) at /c8db/3rdParty/velocypack/include/velocypack/Slice.h:1080
#3  0x0000556d1bee4ea9 in arangodb::velocypack::ObjectIterator::operator* (this=0x7f35ee9f5820) at /c8db/3rdParty/velocypack/include/velocypack/Iterator.h:242
#4  0x0000556d1e8d222e in rice::needStrip (document=...) at /c8db/arangod/Rice/Rice.cpp:514
#5  0x0000556d1e8d22a9 in rice::strip (document=..., didStrip=0x7f35ee9f5a67, copyIfNotStrip=false) at /c8db/arangod/Rice/Rice.cpp:524
#6  0x0000556d1c78c3e7 in arangodb::RocksDBAllIndexIterator::nextDocument(std::function<void (arangodb::LocalDocumentId const&, arangodb::velocypack::Slice)> const&, unsigned long, bool) (this=0x7f358729c520, 
    cb=..., limit=1000, raw=false) at /c8db/arangod/RocksDBEngine/RocksDBIterators.cpp:128
#7  0x0000556d1c5d3f55 in arangodb::OperationCursor::nextDocument(std::function<void (arangodb::LocalDocumentId const&, arangodb::velocypack::Slice)> const&, unsigned long, bool) (this=0x7f353c7f0960, 
    callback=..., batchSize=1000, raw=false) at /c8db/arangod/Utils/OperationCursor.cpp:86
#8  0x0000556d1d00b60f in arangodb::aql::EnumerateCollectionExecutor::produceRows (this=0x7f35b28586a8, output=...) at /c8db/arangod/Aql/EnumerateCollectionExecutor.cpp:148
#9  0x0000556d1c9f9f0a in arangodb::aql::ExecutionBlockImpl<arangodb::aql::EnumerateCollectionExecutor>::getSomeWithoutTrace (this=0x7f35b2858400, atMost=1000) at /c8db/arangod/Aql/ExecutionBlockImpl.cpp:169
#10 0x0000556d1c9f9a47 in arangodb::aql::ExecutionBlockImpl<arangodb::aql::EnumerateCollectionExecutor>::getSome (this=0x7f35b2858400, atMost=1000) at /c8db/arangod/Aql/ExecutionBlockImpl.cpp:119
#11 0x0000556d1cfdf462 in arangodb::aql::DependencyProxy<true>::prefetchBlock (this=0x7f35f9608a08, atMost=1000) at /c8db/arangod/Aql/DependencyProxy.cpp:35
#12 0x0000556d1cfdf1c8 in arangodb::aql::DependencyProxy<true>::fetchBlockForPassthrough (this=0x7f35f9608a08, atMost=1000) at /c8db/arangod/Aql/DependencyProxy.cpp:211
#13 0x0000556d1cb87d73 in arangodb::aql::SingleRowFetcher<true>::fetchBlockForPassthrough (this=0x7f35f9608ae8, atMost=1000) at /c8db/arangod/Aql/SingleRowFetcher.cpp:66
#14 0x0000556d1ca2062c in arangodb::aql::CalculationExecutor<(arangodb::aql::CalculationType)0>::fetchBlockForPassthrough (this=0x7f35f9608bb0, atMost=1000) at /c8db/arangod/Aql/CalculationExecutor.h:114
#15 0x0000556d1ca19bc9 in arangodb::aql::RequestWrappedBlock<(arangodb::aql::RequestWrappedBlockVariant)1>::run<arangodb::aql::CalculationExecutor<(arangodb::aql::CalculationType)0> > (executor=..., 
    engine=..., nrItems=1000, nrRegs=2) at /c8db/arangod/Aql/ExecutionBlockImpl.cpp:572
#16 0x0000556d1c9f5b5a in arangodb::aql::ExecutionBlockImpl<arangodb::aql::CalculationExecutor<(arangodb::aql::CalculationType)0> >::requestWrappedBlock (this=0x7f35f9608900, nrItems=1000, nrRegs=2)
    at /c8db/arangod/Aql/ExecutionBlockImpl.cpp:677
#17 0x0000556d1c9f578c in arangodb::aql::ExecutionBlockImpl<arangodb::aql::CalculationExecutor<(arangodb::aql::CalculationType)0> >::getSomeWithoutTrace (this=0x7f35f9608900, atMost=1000)
    at /c8db/arangod/Aql/ExecutionBlockImpl.cpp:144
#18 0x0000556d1c9f5461 in arangodb::aql::ExecutionBlockImpl<arangodb::aql::CalculationExecutor<(arangodb::aql::CalculationType)0> >::getSome (this=0x7f35f9608900, atMost=1000)
    at /c8db/arangod/Aql/ExecutionBlockImpl.cpp:119
#19 0x0000556d1cfdfd62 in arangodb::aql::DependencyProxy<false>::prefetchBlock (this=0x7f3601fe2008, atMost=1000) at /c8db/arangod/Aql/DependencyProxy.cpp:35
#20 0x0000556d1cfdf702 in arangodb::aql::DependencyProxy<false>::fetchBlock (this=0x7f3601fe2008, atMost=1000) at /c8db/arangod/Aql/DependencyProxy.cpp:78
#21 0x0000556d1cb87be0 in arangodb::aql::SingleRowFetcher<false>::fetchBlock (this=0x7f3601fe20e8, atMost=1000) at /c8db/arangod/Aql/SingleRowFetcher.cpp:52
#22 0x0000556d1ca16a29 in arangodb::aql::SingleRowFetcher<false>::preFetchNumberOfRows (this=0x7f3601fe20e8, atMost=1000) at /c8db/arangod/Aql/SingleRowFetcher.h:98
#23 0x0000556d1ca743de in arangodb::aql::FilterExecutor::expectedNumberOfRows (this=0x7f3601fe2170, atMost=1000) at /c8db/arangod/Aql/FilterExecutor.cpp:94
#24 0x0000556d1ca1b30a in arangodb::aql::RequestWrappedBlock<(arangodb::aql::RequestWrappedBlockVariant)2>::run<arangodb::aql::FilterExecutor> (executor=..., engine=..., nrItems=1000, nrRegs=2)
    at /c8db/arangod/Aql/ExecutionBlockImpl.cpp:629
#25 0x0000556d1c9fb99c in arangodb::aql::ExecutionBlockImpl<arangodb::aql::FilterExecutor>::requestWrappedBlock (this=0x7f3601fe1f00, nrItems=1000, nrRegs=2) at /c8db/arangod/Aql/ExecutionBlockImpl.cpp:677
#26 0x0000556d1c9fb594 in arangodb::aql::ExecutionBlockImpl<arangodb::aql::FilterExecutor>::getSomeWithoutTrace (this=0x7f3601fe1f00, atMost=1000) at /c8db/arangod/Aql/ExecutionBlockImpl.cpp:144
#27 0x0000556d1c9fb301 in arangodb::aql::ExecutionBlockImpl<arangodb::aql::FilterExecutor>::skipSome (this=0x7f3601fe1f00, atMost=1000) at /c8db/arangod/Aql/ExecutionBlockImpl.cpp:320
#28 0x0000556d1cfdfc04 in arangodb::aql::DependencyProxy<false>::skipSome (this=0x7f35f9608408, toSkip=1000000000) at /c8db/arangod/Aql/DependencyProxy.cpp:178
#29 0x0000556d1cb87b1a in arangodb::aql::SingleRowFetcher<false>::skipRows (this=0x7f35f96084e8, atMost=1000000000) at /c8db/arangod/Aql/SingleRowFetcher.cpp:74
#30 0x0000556d1c9f4808 in arangodb::aql::CountCollectExecutor::produceRows (this=0x7f35f9608570, output=...) at /c8db/arangod/Aql/CountCollectExecutor.h:106
#31 0x0000556d1c9f8786 in arangodb::aql::ExecutionBlockImpl<arangodb::aql::CountCollectExecutor>::getSomeWithoutTrace (this=0x7f35f9608300, atMost=1000) at /c8db/arangod/Aql/ExecutionBlockImpl.cpp:169
#32 0x0000556d1c9f826b in arangodb::aql::ExecutionBlockImpl<arangodb::aql::CountCollectExecutor>::getSome (this=0x7f35f9608300, atMost=1000) at /c8db/arangod/Aql/ExecutionBlockImpl.cpp:119
#33 0x0000556d1cfdf462 in arangodb::aql::DependencyProxy<true>::prefetchBlock (this=0x7f35f9608708, atMost=1000) at /c8db/arangod/Aql/DependencyProxy.cpp:35
#34 0x0000556d1cfdf1c8 in arangodb::aql::DependencyProxy<true>::fetchBlockForPassthrough (this=0x7f35f9608708, atMost=1000) at /c8db/arangod/Aql/DependencyProxy.cpp:211
#35 0x0000556d1cb87d73 in arangodb::aql::SingleRowFetcher<true>::fetchBlockForPassthrough (this=0x7f35f96087e8, atMost=1000) at /c8db/arangod/Aql/SingleRowFetcher.cpp:66
#36 0x0000556d1ca2062c in arangodb::aql::CalculationExecutor<(arangodb::aql::CalculationType)0>::fetchBlockForPassthrough (this=0x7f35f96088b0, atMost=1000) at /c8db/arangod/Aql/CalculationExecutor.h:114
#37 0x0000556d1ca19bc9 in arangodb::aql::RequestWrappedBlock<(arangodb::aql::RequestWrappedBlockVariant)1>::run<arangodb::aql::CalculationExecutor<(arangodb::aql::CalculationType)0> > (executor=..., 
    engine=..., nrItems=1000, nrRegs=4) at /c8db/arangod/Aql/ExecutionBlockImpl.cpp:572
#38 0x0000556d1c9f5b5a in arangodb::aql::ExecutionBlockImpl<arangodb::aql::CalculationExecutor<(arangodb::aql::CalculationType)0> >::requestWrappedBlock (this=0x7f35f9608600, nrItems=1000, nrRegs=4)
    at /c8db/arangod/Aql/ExecutionBlockImpl.cpp:677
#39 0x0000556d1c9f578c in arangodb::aql::ExecutionBlockImpl<arangodb::aql::CalculationExecutor<(arangodb::aql::CalculationType)0> >::getSomeWithoutTrace (this=0x7f35f9608600, atMost=1000)
    at /c8db/arangod/Aql/ExecutionBlockImpl.cpp:144
#40 0x0000556d1c9f5461 in arangodb::aql::ExecutionBlockImpl<arangodb::aql::CalculationExecutor<(arangodb::aql::CalculationType)0> >::getSome (this=0x7f35f9608600, atMost=1000)
    at /c8db/arangod/Aql/ExecutionBlockImpl.cpp:119
#41 0x0000556d1ca3d946 in arangodb::aql::ExecutionBlockImpl<arangodb::aql::IdExecutor<void> >::getSome (this=0x7f35f961a3c0, atMost=1000) at /c8db/arangod/Aql/IdExecutor.h:92
--Type <RET> for more, q to quit, c to continue without paging--c
#42 0x0000556d1ca279f6 in arangodb::aql::ExecutionEngine::getSome (this=0x7f35b2853300, atMost=1000) at /c8db/arangod/Aql/ExecutionEngine.cpp:519
#43 0x0000556d1c18f9fd in arangodb::aql::Query::execute (this=0x7f35ee9f7b00, registry=0x7f360f5d4640, queryResult=...) at /c8db/arangod/Aql/Query.cpp:746
#44 0x0000556d1c191bfd in arangodb::aql::Query::executeSync (this=0x7f35ee9f7b00, registry=0x7f360f5d4640) at /c8db/arangod/Aql/Query.cpp:1027
#45 0x0000556d1c02e00e in c8db_db::queryFetch (aql="FOR entry IN _collections FILTER entry.tenant == \"qa_amol_test.com\" AND entry.type == 2 AND SUBSTRING(entry.topic, 0, 1) != \"_\" COLLECT WITH COUNT INTO count RETURN {\"count\": count}", vars=std::shared_ptr<arangodb::velocypack::Builder> (empty) = {...}, vocbase=0x7f35c7d82200) at /c8db/arangod/C8DBFeatures/query_helper.cpp:84
#46 0x0000556d1c02d4eb in c8db_db::queryFetchSingle (aql="FOR entry IN _collections FILTER entry.tenant == \"qa_amol_test.com\" AND entry.type == 2 AND SUBSTRING(entry.topic, 0, 1) != \"_\" COLLECT WITH COUNT INTO count RETURN {\"count\": count}", vars=std::shared_ptr<arangodb::velocypack::Builder> (empty) = {...}, builder=..., vocbase=0x7f35c7d82200) at /c8db/arangod/C8DBFeatures/query_helper.cpp:51
#47 0x0000556d1c52f10e in getCount (c8ql="FOR entry IN _collections FILTER entry.tenant == \"qa_amol_test.com\" AND entry.type == 2 AND SUBSTRING(entry.topic, 0, 1) != \"_\" COLLECT WITH COUNT INTO count RETURN {\"count\": count}", tenant="qa_amol_test.com", database="QATest23_24") at /c8db/arangod/Statistics/StatisticsWorker.cpp:262
#48 0x0000556d1c53a626 in arangodb::StatisticsWorker::updateDatabaseStats (this=0x7f360f451500, tenant="qa_amol_test.com", database="QATest23_24") at /c8db/arangod/Statistics/StatisticsWorker.cpp:1592
#49 0x0000556d1c5372cc in arangodb::StatisticsWorker::updateTenantStatistics (this=0x7f360f451500) at /c8db/arangod/Statistics/StatisticsWorker.cpp:1252
#50 0x0000556d1c53be05 in arangodb::StatisticsWorker::run (this=0x7f360f451500) at /c8db/arangod/Statistics/StatisticsWorker.cpp:1691
#51 0x0000556d1d2684ab in arangodb::Thread::runMe (this=0x7f360f451500) at /c8db/lib/Basics/Thread.cpp:317
#52 0x0000556d1d265f8b in arangodb::Thread::startThread (arg=0x7f360f451500) at /c8db/lib/Basics/Thread.cpp:96
#53 0x0000556d1d30d3fa in ThreadStarter (data=0x7f360e22b330) at /c8db/lib/Basics/threads-posix.cpp:78
```

_Originally posted by @sourabhedake-mm in https://github.com/arangodb/arangodb/issues/9302#issuecomment-1370529047_

**Comment by dothebart** [comment]
Hi, can you please edit your post and add the version and setup you're using?

**Comment by sourabhedake-mm** [comment]
@dothebart updated the post.

I also have a core dump file, if required.

**Comment by dothebart** [comment]
Ok, please note that 3.4.5 has been long EOLed: https://www.arangodb.com/subscriptions/end-of-life-notice/
You may want to try to upgrade to the latest 3.4 release as a test: 3.4.11 it may contain fixes for this.

I would advise to at least upgrade to 3.9 after testing your product with that.
