### ISSUE TITLE
v8 SIGSEGV with gcc6

### ISSUE THREAD

**Issue by Sfinx** [arangodb/arangodb#1817]
The -fno-delete-null-pointer-checks option must be added to CXXFLAGS if gcc6 is used or arangodb will SIGSEGV at v8 just after accessing http://localhost:8529 :

```
hread 31 "[dispat_std]" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xcd7ffb40 (LWP 24158)]
v8::internal::IncrementalMarking::ActivateIncrementalWriteBarrier (this=0xdb212078)
    at ../src/heap/incremental-marking.cc:402
402	    SetOldSpacePageFlags(lop, true, is_compacting_);
(gdb) backtrace 
#0  v8::internal::IncrementalMarking::ActivateIncrementalWriteBarrier (this=0xdb212078)
    at ../src/heap/incremental-marking.cc:402
#1  0x08746382 in v8::internal::IncrementalMarking::StartMarking (this=0xdb212078, 
    flag=v8::internal::IncrementalMarking::ALLOW_COMPACTION) at ../src/heap/incremental-marking.cc:517
#2  0x087464fa in v8::internal::IncrementalMarking::Start (this=0xdb212078, 
    flag=v8::internal::IncrementalMarking::ALLOW_COMPACTION) at ../src/heap/incremental-marking.cc:486
#3  0x0872f5bb in v8::internal::Heap::CollectGarbage (this=<optimized out>, collector=<optimized out>, 
    gc_reason=<optimized out>, collector_reason=<optimized out>, gc_callback_flags=<optimized out>)
    at ../src/heap/heap.cc:908
#4  0x086e44c1 in v8::internal::Heap::CollectGarbage (this=this@entry=0xdb20de88, space=<optimized out>, 
    callbackFlags=v8::kNoGCCallbackFlags, gc_reason=0x9543630 "allocation failure")
    at .././src/heap/heap-inl.h:569
```

**Comment by jsteemann** [comment]
Could you check whether this commit by @fceller fixes it?
```
commit 1119ceada6d749dcb11940f33f39b05808afd31e
Author: Frank Celler <frank@arangodb.com>
Date:   Wed May 11 17:39:33 2016 +0200

    added -fno-delete-null-pointer-checks
```

**Comment by Sfinx** [comment]
I've checked the v2.8.8 with manually added -fno-delete-null-pointer-checks - all is ok. Compiling devel ...

**Comment by Sfinx** [comment]
devel is ok too
