### ISSUE TITLE
Foxx app unmounted during execution

### ISSUE THREAD

**Issue by ggendel** [arangodb/arangodb#18192]
## My Environment

* __ArangoDB Version__:  3.10:3 and 3.8.7       
* __Deployment Mode__:   Single server    
* __Deployment Strategy__:   Manual Start 
* __Configuration__:  Standalone             
* __Infrastructure__:  Standalone and docker             
* __Operating System__:  Ubuntu 22.04 and others      
* __Total RAM in your machine__:  16Gb      
* __Disks in use__:  SSD      
* __Used Package__:   deb from repository           

## Component, Query & Data

__Affected feature__: Foxx

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Run app
2. Pound with insert and update requests

__Problem__:
I start a single Foxx queue job that runs in the  background and never stops.  It's function is to offload a secondary task that records changes to objects. when a document in the current collections is created, updated, or modified, the relevant information is put in collection pmpending.  The background job pops these off to manage an event history tree in the pmevent collection.  The purpose is to divorce this auxiliary task from delaying responses.

Sometimes my test script runs successfully,but most of the time it fails because the Foxx app becomes virtually missing. It never stops at the same place and  I don't see it in the webui "service", but later it shows up again.  It's like it's become non-responsive. There isn't much in the logs. The WARNING is from the app while I'm debugging and just lets me know it started.

2023-02-24T20:20:04Z [2188] WARNING [514da] {general} ### histWorker started 1677270004.3046248 [ "_jobs/266240643691" ]
2023-02-24T20:29:25Z [2188] ERROR [24213] {general} Service "/_admin/aardvark" encountered error 404 while handling GET http://192.168.1.9:8529/_db/gdp/_admin/aardvark/foxxes/deps?mount=%252Fpmmodel 
2023-02-24T20:29:25Z [2188] ERROR [24213] {general} via ArangoError: service not found
2023-02-24T20:29:25Z [2188] ERROR [24213] {general} Mount path: "/pmmodel".
2023-02-24T20:29:25Z [2188] ERROR [24213] {general}     at reloadInstalledService (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:506:11)
2023-02-24T20:29:25Z [2188] ERROR [24213] {general}     at Object.getServiceInstance [as lookupService] (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:486:15)
2023-02-24T20:29:25Z [2188] ERROR [24213] {general}     at Route._handler (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/foxxes.js:279:31)
2023-02-24T20:29:25Z [2188] ERROR [24213] {general}     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:419:15)
2023-02-24T20:29:25Z [2188] ERROR [24213] {general}     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:417:7)
2023-02-24T20:29:25Z [2188] ERROR [24213] {general}     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:10118:25
2023-02-24T20:29:25Z [2188] ERROR [24213] {general}     at Middleware.<anonymous> (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/foxxes.js:54:3)
2023-02-24T20:29:25Z [2188] ERROR [24213] {general}     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:421:15)
2023-02-24T20:29:25Z [2188] ERROR [24213] {general}     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:417:7)
2023-02-24T20:29:25Z [2188] ERROR [24213] {general}     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:417:7)

I'm missing something important. The only thing that writes to the event collection is the background task and the pmpending collection objects are pushed by the main flow and popped by the background task.  I originally had sequential jobs instead of a single job, but that had the same issue.

This process was devised so, if ArangodB unexpectedly terminated, it will pick up where it left off when it is restarted.

__Expected result__:
The Foxx app continues handle requests.

**Comment by ggendel** [comment]
I need to close this issue.  It took me a few days of experimentation, but the crash was caused by too aggressively truncating collections when calling the function to clean up everything to start fresh.  I accidentally truncated the '_xxx' collections.  If you do this, all bets are off and the foxx app can crash without any information.  The app is unmounted, disappears from the services and sometimes needs to be reinstalled.

**Comment by dothebart** [comment]
hm, so you're missing a feedback to better indetify this incident? How did it occur to you? did it show foxx tracebacks in the logfiles?

**Comment by ggendel** [comment]
The only relevant thing in the log I pasted above.  I blame my ignorance of the "hidden" collections that ArangoDB includes in the database.  I'm not sure which collection I truncated caused the problem, but I should have been more explicit on the collections to truncate.  This is not a normal situation, I truncate the tables so we can do independent regression tests from a startup condition.  The production environment is protected from anyone doing this.  It took me so long to track it down because I assumed that it was in the job queue management code, not this function that was untouched for quite a while.  This is a cool addition to our application as it keeps a record of all changes and let's us go back in history for new functionality and forensics.  It keeps track of what was changed where and by who.  We can do things like difference objects and segments of a graph and will allow us to retrieve deleted object.  I tried RecallGraph originally, which is a pretty impressive implementation and very broad in it's applicability, but the performance in our application was abysmal.  This was designed so historical retrieval is close to native ones.

**Comment by dothebart** [comment]
ah, nice.
You should use the respective APIs to manipulate the contents of system collections ;)
