### ISSUE TITLE
ArangoError 2001: Content-Length > max packet size found

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#1864]
Hello Team,

  I am getting the below error when trying to traverse very large graph.

2016-06-10T11:35:21Z [45926] WARNING Content-Length > max packet size found
JavaScript exception in file '/app/arangodb_rpm/usr/share/arangodb/js/common/modules/org/arangodb/graph/traversal.js' at 1774,13: ArangoError 2001: Content-Length > max packet size found
!      throw err3;
!            ^
stacktrace: ArangoError: Content-Length > max packet size found
    at Object.exports.checkRequestResult (/app/arangodb_rpm/usr/share/arangodb/js/client/modules/org/arangodb/arangosh.js:104:21)
    at ArangoCollection._edgesQuery (/app/arangodb_rpm/usr/share/arangodb/js/client/modules/org/arangodb/arango-collection.js:216:12)
    at ArangoCollection.outEdges (/app/arangodb_rpm/usr/share/arangodb/js/client/modules/org/arangodb/arango-collection.js:1268:15)
    at Graph._OUTEDGES (/app/arangodb_rpm/usr/share/arangodb/js/common/modules/org/arangodb/general-graph.js:2723:58)
    at Object.getOutEdges (/app/arangodb_rpm/usr/share/arangodb/js/common/modules/org/arangodb/graph/traversal.js:285:25)
    at Object.outboundExpander [as expander] (/app/arangodb_rpm/usr/share/arangodb/js/common/modules/org/arangodb/graph/traversal.js:358:29)
    at Object.run (/app/arangodb_rpm/usr/share/arangodb/js/common/modules/org/arangodb/graph/traversal.js:1099:36)
    at ArangoTraverser.traverse (/app/arangodb_rpm/usr/share/arangodb/js/common/modules/org/arangodb/graph/traversal.js:1770:14)
    at ADExplosion ((command-line):70:13)
    at (command-line):77:31

Any help would be much useful.

Regards,
Sajeev

**Comment by jsteemann** [comment]
What I can already say from looking at the code that triggers the error is that it will happen when the client (arangosh) receives a single packet larger than 128 MB from the server.
At the moment the max packet size is hard-coded to 128 MB. If it's intentional to receive such a big chunk at once, it may be sensible to make it configurable in arangosh.

**Comment by sajeevpr** [comment]
Thank you for your response.
Can you please advise how I can modify this?

Regards,
Sajeev

**Comment by jsteemann** [comment]
The max packet value is hard-coded in all yet released versions of ArangoDB. 
Changing it is not possible until 28e8e64. From the commit on, the client tools provide the option `--server.max-packet-size`. 
The only way to circumvent fetching too large results from the server in previous versions is to restrict the query to less documents/edges, e.g. by limiting traversal depths, selecting specific attributes and not complete documents etc.

**Comment by sajeevpr** [comment]
Thank you jsteemann for the quick resolution. So when can I expect this to be released?

Regards,
Sajeev

**Comment by jsteemann** [comment]
It's in the devel branch already, so you could use it already if you build ArangoDB from source. However, I won't recommend to use devel at the moment as it is by definition unstable. 
The feature will also be incorporated into the next 3.0 release candidate, which is planned to be released this week.

**Comment by sajeevpr** [comment]
That's really great. I will test this in 3.0.

Thanks & Regards,
Sajeev

**Comment by dothebart** [comment]
RC2 is now available via: https://www.arangodb.com/download-preview/

**Comment by sajeevpr** [comment]
Ok. Thank you

**Comment by dothebart** [comment]
ArangoDB 3.0 is released, closing.
