### ISSUE TITLE
Foxx: replace service

### ISSUE THREAD

**Issue by fceller** [arangodb/arangodb#1896]
When using "--temp.path frank" and replacing a service, the following errors occurs:

```
Cannot remove temporary folder "frank/zip/tmp-20503-3644857462"
 Stack: ArangoError: temporary directory name is too short. will not remove directory
    at Error (native)
    at extractServiceToPath (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:746:10)
    at installServiceFromRemote (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:809:3)
    at _buildServiceInPath (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:1043:7)
    at _validateService (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:1064:5)
    at Object.upgrade (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:1389:3)
    at Middleware.<anonymous> (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb3/js/apps/system/_admin/aardvark/APP/foxxes.js:93:29)
    at next (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:388:15)
    at next (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:384:7)
    at next (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:384:7)2016-06-24T08:48:30Z [20503] ERROR Cannot execute Foxx service at /internal: ArangoError: failed to invoke module
2016-06-24T08:48:30Z [20503] ERROR File: /Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/var/lib/arangodb3-apps/_db/_system/frank/apps/tmp-20503-1769440380/ayeaye.js
2016-06-24T08:48:30Z [20503] ERROR Cause: ArangoError: No such file or directory: system error
2016-06-24T08:48:30Z [20503] ERROR     at Error (native)
2016-06-24T08:48:30Z [20503] ERROR     at Object.global.DEFINE_MODULE.exports.readFileSync (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb3/js/common/bootstrap/modules/fs.js:466:23)
2016-06-24T08:48:30Z [20503] ERROR     at Object.Module._extensions..js (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb3/js/common/bootstrap/modules.js:612:20)

```

**Comment by pluma** [comment]
This seems like a filesystem I/O issue on macOS. The function throwing the error is `fs.remove`. The error itself seems to stem from `JS_RemoveRecursiveDirectory` in `v8-utils.cpp`, specifically the result of `TRI_GetUserTempPath()` seems to be a string shorter than 6 characters.

The bit that throws the error could be avoided using `force` but that doesn't seem like the right solution because it doesn't explain the underlying problem. I'm not on macOS and don't know our internals. Could someone else please take a look at this? (cc @dothebart?)

**Comment by dothebart** [comment]
`JS_RemoveRecursiveDirectory()` will check for the path length and will refuse to remove it if its shorter than 6 characters, introduced by @fceller in d3330bdf
