### ISSUE TITLE
How we change the server id of Arnagodb 3.0 server?

### ISSUE THREAD

**Issue by lalitlogical** [arangodb/arangodb#1932]
Version: Arangodb 3.0
OS: Ubuntu 14.04 (AWS EC2 instance)

I am working on replication feature of Arangodb. So first I have setup and start a new server on AWS EC2 instance. It is working fine.

Then for replication feature, I have created an AMI (image) of the previous instance and launch it. Now both server is working properly.

When I want to start replication between two servers, I am getting the following issue as below.

```
JavaScript exception in file '/usr/local/share/arangodb3/js/client/modules/@arangodb/replication.js' at 181,7: ArangoError 1405: got same server id (101328670761541) from endpoint 'tcp://******:8529' as the local applier server's id
!      throw err;
!      ^
stacktrace: ArangoError: got same server id (101328670761541) from endpoint 'tcp://******:8529' as the local applier server's id
    at Object.exports.checkRequestResult (/usr/local/share/arangodb3/js/client/modules/@arangodb/arangosh.js:98:21)
    at waitForResult (/usr/local/share/arangodb3/js/client/modules/@arangodb/replication.js:178:14)
    at Object.sync (/usr/local/share/arangodb3/js/client/modules/@arangodb/replication.js:228:10)
    at <shell command>:1:34
```

I have found the answer for same on [stackoverflow](http://stackoverflow.com/questions/24076463/arangodb-replication-serverid-duplicate-between-different-servers). So this issue due to same AMI. So I want to edit server-id. 

But I want to know, where I find this file to edit server id?

**Comment by lalitlogical** [comment]
I have found the SERVER file at `/usr/local/var/lib/arangodb3`.
