### ISSUE TITLE
ArangoDB stops responding

### ISSUE THREAD

**Issue by joowani** [arangodb/arangodb#2012]
**I observed the issue I am about to describe with:**
- ArangoDB 3.0.3, 3.0.4, 3.0.5 (using the HTTP REST API)

**On the following operating systems:**
- Ubuntu 16.04 (using the docker image)
- OS X 10.11.6 (using the docker image) 

I have a set of tests that makes HTTP requests ArangoDB, creating and removing databases in rapid succession. During the tests ArangoDB seems to stop responding and I am forced to restart the docker instance. This is the logging I see on docker:

```
2016-08-22T18:13:47Z [1] WARNING catch error in historian: ArangoError: write-throttling timeout\n    at Error (native)\n    at Object.exports.historian (/usr/share/arangodb3/js/server/modules/@arangodb/statistics.js:490:8)\n    at eval (eval at undefined, <anonymous>:3:54)\n    at eval (eval at undefined, <anonymous>:3:70)
2016-08-22T18:13:58Z [1] WARNING {collector} got unexpected error code while applying queued operations: write-throttling timeout
2016-08-22T18:14:00Z [1] ERROR In database 'test_database_970304': Executing task #5 (insertRedirectionsAll: insert default routes for admin interface) failed with exception: ArangoError 1236: write-throttling timeout ArangoError: write-throttling timeout
2016-08-22T18:14:00Z [1] ERROR     at Error (native)
2016-08-22T18:14:00Z [1] ERROR     at /usr/share/arangodb3/js/server/upgrade-database.js:670:19
2016-08-22T18:14:00Z [1] ERROR     at Array.forEach (native)
2016-08-22T18:14:00Z [1] ERROR     at Object.addTask.task (/usr/share/arangodb3/js/server/upgrade-database.js:669:58)
2016-08-22T18:14:00Z [1] ERROR     at runTasks (/usr/share/arangodb3/js/server/upgrade-database.js:274:27)
2016-08-22T18:14:00Z [1] ERROR     at upgradeDatabase (/usr/share/arangodb3/js/server/upgrade-database.js:421:14)
2016-08-22T18:14:00Z [1] ERROR     at upgrade (/usr/share/arangodb3/js/server/upgrade-database.js:776:12)
2016-08-22T18:14:00Z [1] ERROR     at /usr/share/arangodb3/js/server/upgrade-database.js:783:10
2016-08-22T18:14:00Z [1] ERROR     at /usr/share/arangodb3/js/server/upgrade-database.js:784:2
2016-08-22T18:14:00Z [1] ERROR     at Object.exports.loadStartup (/usr/share/arangodb3/js/server/bootstrap/modules/internal.js:320:18)
2016-08-22T18:14:00Z [1] ERROR In database 'test_database_970304': Executing task #5 (insertRedirectionsAll: insert default routes for admin interface) failed. Aborting init procedure.
2016-08-22T18:14:00Z [1] ERROR In database 'test_database_970304': Please fix the problem and try starting the server again.
2016-08-22T18:14:00Z [1] ERROR cannot initialize database 'test_database_970304', upgrade script failed
```

When I try to terminate the docker instance I get:
```
2016-08-22T18:14:02Z [1] INFO control-c received, beginning shut down sequence
2016-08-22T18:14:07Z [1] WARNING catch error in historian: ArangoError: write-throttling timeout\n    at Error (native)\n    at Object.exports.historian (/usr/share/arangodb3/js/server/modules/@arangodb/statistics.js:490:8)\n    at eval (eval at undefined, <anonymous>:3:54)\n    at eval (eval at undefined, <anonymous>:3:70)
2016-08-22T18:14:15Z [1] WARNING {collector} got unexpected error code while applying queued operations: write-throttling timeout
2016-08-22T18:14:31Z [1] WARNING {collector} got unexpected error code while applying queued operations: write-throttling timeout
2016-08-22T18:14:48Z [1] WARNING {collector} got unexpected error code while applying queued operations: write-throttling timeout
2016-08-22T18:15:05Z [1] WARNING {collector} got unexpected error code while applying queued operations: write-throttling timeout
2016-08-22T18:15:21Z [1] WARNING {collector} got unexpected error code while applying queued operations: write-throttling timeout
```

I've also noticed this problem using the apt-get package on ubuntu, where after sigkilling the server I am unable to start it up again unless I nuke the `/var/lib/arangodb3/databases` directory and use the "upgrade" command.

Thanks,
Joohwan

**Comment by jsteemann** [comment]
This looks like write-throttling is enabled for server instance. It should be turned off by default.
There are startup options `--wal.throttle-when-pending` and `--wal.throttle-wait` to control it. `--wal.throttle-when-pending` should have a value of 0 to deactivate throttling. Throttling can also be enabled at runtime by using `require("internal").wal.properties({ throttleWhenPending: 1234 });` and setting it to some non-zero value.
 
If throttling is not set in any configuration file or on the command-line, and is not set at runtime, then the write-throttling should be turned off and not kick in. If throttling is enabled there should also occur some more warnings in the log files.
Any chance there is write-throttling configured for your instance or is it activated by client code?

**Comment by joowani** [comment]
Hi Jan,

Yes I do activate write-throttling in one of my tests. The problem is that the server becomes completely unreponsive when the throttling kicks in. I am unable to, for example, shut down the instance gracefully nor start it up again (seems sigkilling leaves the database at a broken state where it is unable to pick itself back up). 

Thank you,
Joohwan

**Comment by jsteemann** [comment]
I think it says `upgrade script` because the problem seems to happen at server start. At server start there is an automatic upgrade procedure that will look for the state of system collections and perform necessary migration. If any error occurs during this upgrade procedure, the server may fail with an error indicating that the upgrade failed.

Though I think it shouldn't fail here due to write-throttling.
Can you let me know to what value you set the write-throttling configuration values? That may help diagnosing the issue.

**Comment by joowani** [comment]
I am using the `PUT /_admin/wal/properties` API endpoint to set the following WAL values:
```
{ 
  "allowOversizeEntries" : false, 
  "logfileSize" : 30000000, 
  "historicLogfiles" : 15 
  "reserveLogfiles" : 5, 
  "throttleWait" : 16000, 
  "throttleWhenPending" : 1000, 
}
```

**Comment by jsteemann** [comment]
Should be fixed in 3.0.6 and the devel branch.

**Comment by joowani** [comment]
Awesome. Thanks!

**Comment by dothebart** [comment]
3.0.10 is available for download now.
