### ISSUE TITLE
cookie transport issue with algorithm and secret

### ISSUE THREAD

**Issue by solisoft** [arangodb/arangodb#2041]
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [X] 3.0

On this operating system:
- [X] MacOS, version:
### Foxx

I'm trying to use cookieStorage like that : 

```
'use strict';
const db = require('@arangodb').db;
const joi = require('joi');
const createRouter = require('@arangodb/foxx/router');
const sessionsMiddleware = require('@arangodb/foxx/sessions');
const cookieTransport = require('@arangodb/foxx/sessions/transports/cookie');

const router = createRouter();
const collection = db._collection(collName);

const sessions = sessionsMiddleware({
  storage: 'sessions',
  transport: cookieTransport({
    name: 'DEMO',
    ttl: 60 * 60 * 24 * 7, // one week in seconds
    algorithm: 'sha256',
    secret: 'mysupersecret'
  })
});
module.context.use(sessions);
module.context.use(router);
```

But it raise this error 

```
{
error: true,
errorNum: 500,
errorMessage: "Internal Server Error",
code: 500,
exception: "ArangoError 10: usage: HMAC(<key>, <text>, <algorithm>)",
stacktrace: [
"ArangoError: usage: HMAC(<key>, <text>, <algorithm>)",
" at Error (native)",
" at Object.exports.hmac (/usr/local/opt/arangodb/share/arangodb3/js/common/modules/@arangodb/crypto.js:53:19)",
" at SyntheticResponse.cookie (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/router/response.js:283:32)",
" at Object.set (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/sessions/transports/cookie.js:47:11)",
" at Middleware._handler (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/sessions/index.js:117:25)",
" at next (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:388:15)",
" at next (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:384:7)",
" at dispatch (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:400:3)",
" at Tree.dispatch (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:131:5)",
" at callback (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/service.js:207:28)"
]
}
```

**Comment by solisoft** [comment]
If I remove algorithm and secret, everything is working fine!

**Comment by solisoft** [comment]
By the way, 
````
const sessions = sessionsMiddleware({
  storage: 'sessions',
  transport: cookieTransport({
    ttl: 60 * 60 * 24 * 7, // one week in seconds
  })
});
````

Don't work as expected, sessions are closed before one week !
In the browser I can see that the cookie expiration date is fine, but in fact, session is closed before cookie expiration

**Comment by solisoft** [comment]
@dothebart any thought about this TTL issue ?

**Comment by pluma** [comment]
I've addressed the TTL issue in the documentation: the TTL value only applies to the cookie, not the session itself. So unless you also set the session's TTL explicitly to the same value, the two might expire differently.

I can't reproduce your hmac woes, however. Can you provide a minimal Foxx service with a throwaway secret that reproduces this problem on your end?

**Comment by solisoft** [comment]
It's an old one and I think it was because of documentation lack.
Now it's OK.
