### ISSUE TITLE
A while after upgrade to v3.12.0, unable to create documents: "Corruption: Compaction sees out-of-order keys"

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#20841]
## My Environment

* __ArangoDB Version__:        3.12.0 Enterprise
* __Deployment Mode__:      Single Server
* __Deployment Strategy__:  sytemd
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 22.04
* __Total RAM in your machine__:        64GB
* __Disks in use__:        SSD
* __Used Package__:             Ubuntu .deb

## Component, Query & Data

__Affected feature__:
RocksDB integrity.

For some reason, after upgrading from 3.11.8 Enterprise to 3.12.0 Enterprise, the database went suddenly corrupt so that any attempt to add a new document to any collection triggers an error: `Corruption: Compaction sees out-of-order keys.`

Upgrade took place on April 8th. For a few days the database worked as usual, until April 11 (yesterday) when the error appeared.

Restarting the server had no effect. Triggering compaction on a collection then trying to write to it had no effect either.

Example with collection `pro_queries`:
```
127.0.0.1:8529@mydb> db.pro_queries.save({ "_key": "test_key_01", "test": true });
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 90,7: ArangoError 1100: Corruption: Compaction sees out-of-order keys.
!      throw error;
!      ^
stacktrace: ArangoError: Corruption: Compaction sees out-of-order keys.
    at exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:88:21)
    at ArangoCollection.save.ArangoCollection.insert (/usr/share/arangodb3/js/client/modules/@arangodb/arango-collection.js:869:14)
    at <shell command>:1:16
```

__Dataset__:
30 collections,  having from 10 documents to 200M documents.

__Size of your Dataset on disk__:
700G

## Steps to reproduce

1. Try to add a document to any collection, for ex. `pro_queries`, either using `arangosh`, `aardvark` or `arangojs`
2. Get the error `Corruption: Compaction sees out-of-order keys`
3. Try to run a compaction on the collection via `arangosh`, wait 1 hour, still get the error
4. Try to restart ArangoDB, still get the error

__Problem__:
Database is read-only: impossible to add a document to any collection.

__Expected result__:
A way to repair the corrupted DB?

Thank you,
Best regards

**Comment by dothebart** [comment]
Hi, 
we are already working on this. An ICU upgrade had unexpected side effects a hot fix will soon be available. 
At the moment the quickest known way to get out of this is to dump the database using arangodump and restore it to a 3.11.8.

**Comment by matcho** [comment]
Hi, thank you for your quick answer. We'll do that and wait for the fix.

**Comment by dothebart** [comment]
3.12.0.2 containing a fix for this has been released; closing as solved.

**Comment by matcho** [comment]
Hello @dothebart 

Unfortunately I have to reopen this ticket: same error happened with v3.12.0.2-1 (Ubuntu 22.04).

A few days after updating v3.11.8 to v3.12.0.2-1 (appears as 3.12.0-2 in aardvark), trying to add a document to any collection results in: `Error: Corruption: Compaction sees out-of-order keys.`

**Comment by dothebart** [comment]
how's your system locale configuration? is it consistent?

**Comment by jsteemann** [comment]
> Hello @dothebart
> 
> Unfortunately I have to reopen this ticket: same error happened with v3.12.0.2-1 (Ubuntu 22.04).
> 
> A few days after updating v3.11.8 to v3.12.0.2-1 (appears as 3.12.0-2 in aardvark), trying to add a document to any collection results in: `Error: Corruption: Compaction sees out-of-order keys.`

@matcho : just to confirm, the version that is now running v3.12.0.2-1 was recently upgraded from v3.11.8 and has never been on version 3.12.0 (any 3.12.0s before 3.12.0.2-1)?

**Comment by matcho** [comment]
Hello @dothebart 

Here's the output of `locale`. Is that what you were asking for? If not, could you please suggest a command that would allow to verify consistency of the locale configuration?

```
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

Hello @jsteemann 

To be as accurate as possible, here's what happened on this test machine since we tried updating to 3.12. This all happened using Enterprise version (`arangodb3e` Ubuntu package).

 - 2024-04: running 3.11.8 with success
 - 2024-04-10: upgrade to 3.12.0, running fine for a little time
 - 2024-04-12: data corruption, opening of this GitHub ticket
 - 2024-04-15: rollback
    - dump data using `arangodump`
    - uninstall 3.12.0 using `apt remove --purge arangodb3e`
    - delete data in `/var/lib/arangodb3`
    - change apt repository config back to 3.11 Enterprise
    - install 3.11 using `apt install arangodb3e`
    - restore data using `arangorestore`
 - running 3.11.8 again with success
 - 2024-07-08: as a patch was released in May, try to upgrade to 3.12.0.2
 - 2024-07-10: data corruption, reopening this ticket

Hope this helps.
Many thanks

**Comment by neunhoef** [comment]
Hi @matcho ,
thanks for the information. We have now discovered a second problem - totally independent from the previous one - which can lead to corruption with out-of-order keys. This problem is present in 3.11 as well as in 3.12, so it might be just a coincidence that it occurs on upgrade. Let me quickly explain:
When we compare numbers in an index, we have to deal with signed integers, unsigned integers and doubles, since the database allows to represent numbers internally in all three formats. Unfortunately, when we compare numbers and the representation is different, we always cast to double. In case of very large integers (greater than 2^53 or so) this can lead to wrong comparisons, since our comparator is not transitive.
I now wonder whether your issue is related to this new problem or to the previous ICU/unicode related one (which we think to have fixed in 3.12.0-2).
Do you know if any large numbers (> 2^53) occur in your data and are indexed, maybe alongside other attributes?
Best regards,
  Max.

**Comment by matcho** [comment]
Hi @neunhoef ,

Thank you for your reactivity.
Actually I forgot to mention that unlike the previous time (when we first opened this ticket), the corruption occurred after experimenting with ArangoSearch views, creating / removing a few of them (probably between 5 or 10).
I noticed the corruption problem when trying to remove the latest of those experimental views.
All the said views were fed by the same collection, the largest we have; the numbers it stores are mainly geospatial coordinates (lat, lon, elevation) and accuracy, document IDs (integers in strings), dates (standard millisecond timestamps) and a few other floating numbers that are not supposed to be higher than 1 nor to have more than 10 decimals.
We use an analyzer derived from GeoPoint, could it be related ?
Anyway we'll look for numbers > 2^53 just to be sure.

Best regards,
Mathias

**Comment by matcho** [comment]
Hi again,

Here's what we found after a short investigation.

We indeed have documents that contain 40-character long hexadecimal strings, in fields `doc.request.images[*].id`.

Excerpt of the document structure:
```json
{
  "session": "b7f7b2d0-3f97-11ef-b4a4-43a95b7a1b6b",
  "user_id": null,
  "date": 1720710633086,
  "geoloc": null,
  "request": {
    "images": [
      {
        "id": "9795000448541640037819392250613947712091",
        "organ": "flower"
      }
    ]
  },
  "result": {
    "date": 1720710633142,
    "status_code": 200
  }
}
```

What if this hex ID contains only digits and no letter, as in the example above, that comes from an existing document:
```
RETURN (TO_NUMBER("9795000448541640037819392250613947712091") > POW(2, 53))

[
    true
]
```

The field containing this value is indeed indexed :
```
49171	hash	false	false	deduplicate: true, estimates: true, cacheEnabled: false	83.37%	request.images[*].id		idx_49171
```

But this index has been existing for a long time and running fine up to v3.11 included. The document in question is recent, but is certainly not the only one having a digits-only hex. ID (looked for the 1st one > 2^53 by date decreasing, that one was found in 2mn among a 1B documents collection). No data corruption ever occurred before v3.12

What is new though is the experiments we conducted on ArangoSearch views, notably one looking like this (excerpt):

```json
{
    "storedValues": [
      {
        "fields": [
          "date",
          "geoloc",
          "new_result.first_result",
          "_key",
          "request.images.organ"
        ],
        "compression": "lz4"
      }
    ],
    "links": {
      "z_queries": {
        "analyzers": [
          "identity"
        ],
        "fields": {
          "new_result": {
            "fields": {
              "status": {},
              "first_result": {
                "fields": {
                  "score": {},
                  "name": {}
                }
              }
            }
          },
          "user_id": {},
          "request": {
            "fields": {
              "images": {
                "fields": {
                  "organ": {}
                }
              }
            }
          },
```

Fields `request.images[*].id` are not explicitly indexed, but `request.images` is mentioned in the link's fields. Could it be the source of the issue?

Also, before getting an answer to #21152 (that we got from another channel), we tried configuring the view's `sotredValues` like the following (storing the whole `request.images` objects):

```json
{
    "storedValues": [
      {
        "fields": [
          "date",
          "geoloc",
          "new_result.first_result",
          "_key",
          "request.images"
        ],
        "compression": "lz4"
      }
    ],
```

Maybe that's where the bug occurred?

We're now looking for values exceeding 2^53 in other fields of our documents, and will stay in touch if we find something.

Best regards,
Mathias

**Comment by matcho** [comment]
Actually the document mentioned above is present on a different dataset on a different server, not on the one that got its data corrupted after update to v3.12 − my mistake, too many databases around ^^

Still, this might be relevant to notice, in case it might lead to data corruption by another way. The server this document is present on will some day need to be updated as well, and is part of our production setup.

After a first pass of investigation, no number exceeding 2^53 was found in the dataset of the server that got its data corrupted. Maybe you have another clue? We'll keep on investigating.

Thank you

**Comment by MaPatWork** [comment]
@neunhoef @matcho Is there any update on the issue here?
We have the same issue on our production env now (haven't seen the error on the test env, but it is smaller with less data) and need to decide to stay on 3.10 or 3.11 or if it would be ok to try again with a fresh 3.12.1

**Comment by dothebart** [comment]
since the change will be pretty deep inside such a change doesn't come easy. We are working on it and hope it to be part of 3.12.2.

**Comment by matcho** [comment]
@MaPatWork we're working on building a minimal test dataset to reproduce the issue, but it takes time as we're not sure which data and which operations chain leads to the bug…

**Comment by matcho** [comment]
Hello @dothebart 
This is great news, we'll try that as soon as possible !
Thank you very much

**Comment by matcho** [comment]
Hello again @dothebart . Tried calling the API route `vpackSortMigration/check` but got an error.

The local database has a root account with no password, hence the `-u root:` option of cURL.

```
curl -u root: "http://localhost:8529/_admin/cluster/vpackSortMigration/check"
{"code":403,"error":true,"errorMessage":"only superusers may run vpack index migration","errorNum":11}
```

Other API routes work with the same superuser credentials, for ex. `curl -u root: "http://localhost:8529/_admin/metrics` works.

Did I miss something?

Thank you

**Comment by dothebart** [comment]
hm, do you have JWT configured? I guess that one is needed?

**Comment by Simran-B** [comment]
The root user is not superuser, you either need to use a superuser JWT token or temporarily run ArangoDB with authentication disabled.

**Comment by MaPatWork** [comment]
@dothebart We have check now our system and we have ~6 collection with ~8-10 Indexes affected. (Out of 200+ collection overall)
Therefore, if we remove these Indexes before upgrade , do the upgrade, then reconfigure the indexes, can we then prevent then to dump and restore the data?
Or are the removed indexes still affecting the data directory?

This would prevent us from a downtime of 1 or 2 days due to the dump and restore procedure....

**Comment by dothebart** [comment]
For your situation you need to:
- drop the index
- restart everything
- trigger a rocksdb compaction
- run the migration
- restart everything again
- then recreate these indices.

**Comment by neunhoef** [comment]
Adding to what @dothebart wrote:

I understand you have a single server and the `arangodump/arangorestore` way means too much downtime for you. I sympathize with this view. So let me give some more hints and explanations:

After the upgrade the server runs in legacy mode and so does the sorting exactly as before. You have already run the diagnostics, so you know which indexes are affected.

I am afraid, you indeed need to drop all these indexes. Unfortunately, this does not guarantee that all wrongly sorted data is flushed out of the system. It is possible that old RocksDB keys are still there in the lower levels of RocksDB and could lead to problems down the line after we switch to the new sorting order. This is where the compaction step comes in. After a restart, we know no transaction can still keep the old data. Then we do a full compaction using this API:

https://docs.arangodb.com/3.11/develop/http-api/administration/#compact-all-databases

Make sure you set the option `compactBottomMostLevel` or else the compaction might not be complete! Note that this will anyway rewrite all data on disk, so it can take significant amounts of time and a lot of I/O. This does not interrupt your service but might have an impact on performance!

One this is done, you know that all bad keys are flushed out of the system. Then you can run the migration, and after the next restart, the system will use the new sorting order.

Only then can you recreate the indexes.

We understand that running without these indexes for the duration of the compaction might be a service interruption in its own right, but currently we do not know of a different way to perform the migration without any risks.

**Comment by matcho** [comment]
Hello @Simran-B 

> The root user is not superuser

That's an interesting thing to know :slightly_smiling_face: thank you. Using JWT authorization works fine.

To @dothebart and @neunhoef ,

I'm now trying to simulate the migration process on a test machine, using a reduced dataset that proved to be subject to corruption, as explained in [this previous message](https://github.com/arangodb/arangodb/issues/20841#issuecomment-2222291141) − summary: import the test dataset into a fresh 3.11.8, runs fine; upgrade to 3.12.0.2 → corruption.

After the data was corrupted, running the `vpackSortMigration/check` returned a list of numerous affected indexes (more than 10). But they cannot be removed as the data is corrupted. So here's what I tried:
 * remove all data
 * install a fresh 3.11.8 in a new data directory
 * import the same test dataset
 * run the  `vpackSortMigration/check`

But this time, the check returns `{"error":false,"code":200,"result":{"affected":[],"error":false,"errorCode":0,"errorMessage":"all good with sorting order"}}`

So the question is: how can I check which indexes will be affected by the corruption **before** I update to 3.12 ? If this is not possible, does this mean that I have to update to 3.12 but interrupt the production so that no operation at all is performed, then quickly check the affected indexes and remove them ? But in that case what is the point of backporting the `vpackSortMigration/check` in 3.11 ? Did I miss something again ?

Thank you very much,
Best regards,

Mathias

**Comment by matcho** [comment]
Seems fixed in `3.12.4` 👍

Pointers to documentation for anyone concerned:
 * https://docs.arangodb.com/3.12/release-notes/version-3.12/incompatible-changes-in-3-12/#resolving-known-issues-with-versions-prior-to-3124
 * https://docs.arangodb.com/3.12/release-notes/version-3.12/incompatible-changes-in-3-12/#corrected-sorting-order-for-strings-in-velocypack-indexes
