### ISSUE TITLE
Foxx legacy: does not show route in error message

### ISSUE THREAD

**Issue by bangert** [arangodb/arangodb#2110]
3.0.10 on fedora 23. this is a minor/cosmetic issue!

```
2016-10-13T08:16:19Z [5417] ERROR Error in foxx route "[object Object]": TypeError: x.forClient is not a function
2016-10-13T08:16:19Z [5417] ERROR     at /var/lib/arangodb3-apps/_db/_system/tsprovision/APP/controllers/generators.js:170:15
2016-10-13T08:16:19Z [5417] ERROR     at Object.res.action.callback (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/legacy/internals.js:87:5)
2016-10-13T08:16:19Z [5417] ERROR     at /usr/share/arangodb3/js/server/modules/@arangodb/foxx/legacy/routing.js:238:17
2016-10-13T08:16:19Z [5417] ERROR     at execute (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1280:7)
2016-10-13T08:16:19Z [5417] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1297:7)
2016-10-13T08:16:19Z [5417] ERROR     at BaseMiddleware.middleware (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/legacy/base_middleware.js:249:5)
2016-10-13T08:16:19Z [5417] ERROR     at execute (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1280:7)
2016-10-13T08:16:19Z [5417] ERROR     at routeRequest (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1301:3)
2016-10-13T08:16:19Z [5417] ERROR     at foxxRouting (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1055:7)
2016-10-13T08:16:19Z [5417] ERROR     at execute (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1280:7)
```

Basically, when an error occurs in legacy mode, the foxx route is printed as "[object Object]" instead of the real foxx route.

**Comment by pluma** [comment]
I'm not quite sure why this produces different output than in 2.8, actually. It looks like `route.url` was an object before already. Can you confirm that the error message did display correctly in ArangoDB 2.8.x?

**Comment by pluma** [comment]
I've fixed this in the 3.0, 3.1 and devel branches. The next releases should contain the fix.

**Comment by bangert** [comment]
```
2016-07-06T11:35:21Z [36870] ERROR Error in foxx route '{ "match" : "/dashboard_builder/v1/:name", "methods" : [ "get" ], "constraint" : { "name" : "/[^/]+/" } }': 'DashboardWithFatalErrors is not defined', Stacktrace:
```
so apparently it did work, although perhaps not as intended?

**Comment by pluma** [comment]
The fix just uses the `match` property. I'm guessing the old code used implicit inspection.
