### ISSUE TITLE
Install from ZIP-file on Cluster Coordinator fails

### ISSUE THREAD

**Issue by servusoft** [arangodb/arangodb#2189]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1.1
On this operating system:
- [x] Linux 
  - [x] Debian .deb

These are the steps to reproduce:

*1. Install Cluster on locale maschine with `startLocalCluster.sh  -a 1 -c 2 -d 2` as:
  1 Agent 4001
  2 Masters 8629 8630
  2 Coordinator 8530 8531

*2. start Coordinator 8530 and install service.
*2.1. install 'evento' from github: 
mount: /test1
repository: diegogub/arangodb-es
vesion: master
the installation works fine

*2.2. install 'evento' as ZIP-file: 
download evento from github: 
https://github.com/diegogub/arangodb-es
mount: /test2
drag & drop 'arangodb-es-master.zip'
the installation fails with `Services: 500. Internal Server Error`

Logfile:
```
2016-11-28T00:15:02Z [29634] ERROR Service "/_admin/aardvark" encountered error 500 while handling PUT http://localhost:8530/_db/_system/_admin/aardvark/foxxes/zip$
2016-11-28T00:15:02Z [29634] ERROR ArangoError: No such file or directory: system error
2016-11-28T00:15:02Z [29634] ERROR     at Error (native)
2016-11-28T00:15:02Z [29634] ERROR     at uploadToPeerCoordinators (/mnt/cluster/2a/js/server/modules/@arangodb/foxx/manager.js:607:16)
2016-11-28T00:15:02Z [29634] ERROR     at Object.install (/mnt/cluster/2a/js/server/modules/@arangodb/foxx/manager.js:1169:20)
2016-11-28T00:15:02Z [29634] ERROR     at Middleware.<anonymous> (/mnt/cluster/2a/js/apps/system/_admin/aardvark/APP/foxxes.js:101:29)
2016-11-28T00:15:02Z [29634] ERROR     at next (/mnt/cluster/2a/js/server/modules/@arangodb/foxx/router/tree.js:387:15)
2016-11-28T00:15:02Z [29634] ERROR     at next (/mnt/cluster/2a/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
2016-11-28T00:15:02Z [29634] ERROR     at next (/mnt/cluster/2a/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
```
after  error is the service `test2` from 8530, accessable. but from 8531 not.  the reason is probely, 
that the service-app is not replicated to the second coordinator (installed only on the first)

**Comment by servusoft** [comment]
since 3.1.5 it works fine and the ZIP-file will be uploaded.
