### ISSUE TITLE
Query export in web frontend not working

### ISSUE THREAD

**Issue by crs-** [arangodb/arangodb#2196]
The export button in the web frontend of ArangoDB is not working. Tested with Firefox and Opera on Windows 10 using ArangoDB version 3.1.2 on Debian 8. The log shows:
`Error 	2016-11-30 10:37:30 	Service "/_admin/aardvark" encountered error 500 while handling GET http://192.168.1.5:8529/_db/MyDB/_admin/aardvark/query/download/crs`

**Comment by hkernbach** [comment]
Note: Fails if not _system database is used.

`2016-11-30T11:03:52Z [54661] ERROR Service "/_admin/aardvark" encountered error 500 while handling GET http://localhost:8529/_db/heiko/_admin/aardvark/query/download/root
2016-11-30T11:03:52Z [54661] ERROR ArangoError: users can only be used in _system database
2016-11-30T11:03:52Z [54661] ERROR     at getStorage (/Users/hkernbach/Git/arangodb/devel/js/server/modules/@arangodb/users.js:93:17)
2016-11-30T11:03:52Z [54661] ERROR     at Object.exports.document (/Users/hkernbach/Git/arangodb/devel/js/server/modules/@arangodb/users.js:291:17)
2016-11-30T11:03:52Z [54661] ERROR     at Route._handler (/Users/hkernbach/Git/arangodb/devel/js/apps/system/_admin/aardvark/APP/aardvark.js:194:18)
2016-11-30T11:03:52Z [54661] ERROR     at next (/Users/hkernbach/Git/arangodb/devel/js/server/modules/@arangodb/foxx/router/tree.js:385:15)
2016-11-30T11:03:52Z [54661] ERROR     at /Users/hkernbach/Git/arangodb/devel/js/node/node_modules/lodash/lodash.js:10029:25
2016-11-30T11:03:52Z [54661] ERROR     at Middleware.authRouter.use (/Users/hkernbach/Git/arangodb/devel/js/apps/system/_admin/aardvark/APP/aardvark.js:83:3)
2016-11-30T11:03:52Z [54661] ERROR     at next (/Users/hkernbach/Git/arangodb/devel/js/server/modules/@arangodb/foxx/router/tree.js:387:15)
2016-11-30T11:03:52Z [54661] ERROR     at next (/Users/hkernbach/Git/arangodb/devel/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
2016-11-30T11:03:52Z [54661] ERROR     at next (/Users/hkernbach/Git/arangodb/devel/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
2016-11-30T11:03:52Z [54661] ERROR     at next (/Users/hkernbach/Git/arangodb/devel/js/server/modules/@arangodb/foxx/router/tree.js:383:7)`

**Comment by crs-** [comment]
Yes I can confirm that it works with the _system database.

The same behavior is shown if a query file is imported. If also fails if another db as _system is used.
The log message is:
`Error 	2016-12-01 10:41:51 	Service "/_admin/aardvark" encountered error 500 while handling POST http://192.168.221.25:8529/_db/MyDB/_admin/aardvark/query/upload/root`

**Comment by hkernbach** [comment]
Short update: This issue will be fixed within the next days.

**Comment by Thijxx** [comment]
This did not make it into 3.1?

**Comment by jsteemann** [comment]
3.2.1 has been released and is [available for download](https://www.arangodb.com/download-major/).
