### ISSUE TITLE
Can't upload foxx application

### ISSUE THREAD

**Issue by DanielPorter** [arangodb/arangodb#2223]
Hi, we're trying to write a foxx plugin, but we're unable to get the hello world application to work when uploading the example as a zip file. When I upload the zip file and set the mount path to /foxxtest I get a 500 error. Then I go to services and the service does appear, but when I use the generated swagger docs to query the endpoint I get the error "{
  "error": true,
  "code": 404,
  "errorNum": 404,
  "errorMessage": "unknown path '/foxtest/hello-world?_=1481750296728'"
}"

Is this a known issue? I'm not sure what I could be getting wrong. I don't have easy access to the logs because ops left for the day. Gonna try to recreate the issue at home and see if there are interesting logs from the 500 error.

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 3.1.2

On this operating system:
  - [ ] Debian .deb

The issue can be reproduced using this dataset:
manifest.json:
{
  "engines": {
    "arangodb": "^3.0.0"
  },
  "main": "index.js"
}

index.js:
'use strict';
const createRouter = require('@arangodb/foxx/router');
const router = createRouter();

module.context.use(router);
router.get('/hello-world', function (req, res) {
  res.send('Hello World!');
})
.response(['text/plain'], 'A generic greeting.')
.summary('Generic greeting')
.description('Prints a generic greeting.');

**Comment by mchacki** [comment]
hi @DanielPorter ,
I tried to reproduce the issue locally and could not get into the bad state you describe, so i guess the Foxx itself is okay and there is something else around throw this error.

Could you give me some more information please:
* Which tool are you using to install the .zip file? `foxx-manager` or `web-ui` 
* Is there a body of the 500 error when you try to install the app?
* Could you get some log-output when the Ops is back?

thank you,
Michael

**Comment by DanielPorter** [comment]
Hi @mchacki 

Talked to ops, they got me into the box. We're actually using the official docker image, not a .deb package. We're running a clustered setup, we have a coordinator, an agency, and 3 databases. The coordinator, the agency, and 1 database all run on the same box. The other two databases live on different boxes. We use docker networking.

Answers to your questions:

1. we're using the web-ui.
2. the body of the 500 response is not very interesting: {"error":true,"errorNum":500,"errorMessage":"Internal Server Error","code":500}
3. The logs are more interesting:


2016-12-15T14:17:35Z [1] ERROR Service "/_admin/aardvark" encountered error 500 while handling PUT http://usazu2octdlv001.uscloud.ad.pwcinternal.com:8090/_db/theos2/_admin/aardvark/foxxes/zip?mount=%2Fffff3
2016-12-15T14:17:35Z [1] ERROR ArangoError: No such file or directory: system error
2016-12-15T14:17:35Z [1] ERROR     at Error (native)
2016-12-15T14:17:35Z [1] ERROR     at uploadToPeerCoordinators (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:608:16)
2016-12-15T14:17:35Z [1] ERROR     at Object.install (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:1170:20)
2016-12-15T14:17:35Z [1] ERROR     at Middleware.<anonymous> (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/foxxes.js:101:29)
2016-12-15T14:17:35Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:387:15)
2016-12-15T14:17:35Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
2016-12-15T14:17:35Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
2016-12-15T14:17:35Z [1] ERROR     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:9378:25
2016-12-15T14:17:35Z [1] ERROR     at Middleware.router.use (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/foxxes.js:53:3)
2016-12-15T14:17:35Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:387:15)

**Comment by mchacki** [comment]
Hi @DanielPorter thanks a lot for the insight, that will help me to reproduce it.
I will keep in touch here to report my progress.

**Comment by mchacki** [comment]
Ok reproduced i'm on it

**Comment by mchacki** [comment]
Ok this has been fixed in devel already, the fix is now also included in 3.1 and will be published with the next bugfix release. Thank you for spotting it.

**Comment by DanielPorter** [comment]
We were able to work around it by installing a version on our local boxes. Thanks so much for the prompt help!
