### ISSUE TITLE
[cluster setup]But the first setup 3 agency is failed. I don't know how to fix it.

### ISSUE THREAD

**Issue by brucejee** [arangodb/arangodb#2225]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series: 3.1.4, official docker library.
I use the latest image.

## my issue
I want setup a cluster to test. But the first setup 3 agency is failed. I don't know how to fix it.

## agency setup cmds
agency1
docker run -d -e ARANGO_NO_AUTH=1 -p 192.168.1.81:15001:5001 --name agency1 arangodb/arangodb arangod --server.endpoint tcp://0.0.0.0:5001 --agency.my-address=tcp://192.168.1.81:15001 --server.authentication false --agency.activate true --agency.size 3 --agency.endpoint tcp://192.168.1.81:15001 --agency.supervision true

agency2
docker run -d -e ARANGO_NO_AUTH=1 -p 192.168.1.81:15002:5001 --name agency2 arangodb/arangodb arangod --server.endpoint tcp://0.0.0.0:5001 --agency.my-address=tcp://192.168.1.81:15002 --server.authentication false --agency.activate true --agency.size 3 --agency.endpoint tcp://192.168.1.81:15001  --agency.supervision true

agency3
docker run -d -e ARANGO_NO_AUTH=1 -p 192.168.1.76:15001:5001 --name agency3 arangodb/arangodb arangod --server.endpoint tcp://0.0.0.0:5001 --agency.my-address=tcp://192.168.1.76:15001 --server.authentication false --agency.activate true --agency.size 3 --agency.endpoint tcp://192.168.1.81:15001  --agency.endpoint tcp://192.168.1.81:15002 --agency.supervision true

## agency1 log
[root@host81 ~]# docker logs -f agency1
2016/12/15 10:27:07 Error resolving syscall name execveat: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:27:07 Error resolving syscall name getrandom: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:27:07 Error resolving syscall name memfd_create: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:27:07 Error resolving syscall name renameat2: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:27:07 Error resolving syscall name sched_getattr: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:27:07 Error resolving syscall name sched_setattr: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:27:07 Error resolving syscall name seccomp: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:27:07 Error resolving syscall name breakpoint: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:27:07 Error resolving syscall name cacheflush: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:27:07 Error resolving syscall name set_tls: could not resolve name to syscall - ignoring syscall.
Initializing database...Hang on...
Database initialized...Starting System...
2016-12-15T10:27:14Z [1] INFO ArangoDB 3.1.4 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.1t  3 May 2016
2016-12-15T10:27:14Z [1] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
2016-12-15T10:27:14Z [1] INFO file-descriptors (nofiles) hard limit is 1048576, soft limit is 1048576
2016-12-15T10:27:14Z [1] INFO JavaScript using startup '/usr/share/arangodb3/js', application '/var/lib/arangodb3-apps'
2016-12-15T10:27:15Z [1] INFO In database '_system': Found 14 defined task(s), 1 task(s) to run
2016-12-15T10:27:15Z [1] INFO In database '_system': state standalone/existing, tasks updateUserModels
2016-12-15T10:27:15Z [1] INFO In database '_system': existing cleanup successfully finished
2016-12-15T10:27:15Z [1] INFO using endpoint 'http+tcp://0.0.0.0:5001' for non-encrypted requests
2016-12-15T10:27:16Z [1] INFO ArangoDB (version 3.1.4 [linux]) is ready for business. Have fun!
2016-12-15T10:27:17Z [1] INFO {agency} Entering gossip phase ...
2016-12-15T10:29:22Z [1] INFO {agency} Adding c25876a4-532d-4eef-915b-4cb4c47f9100(tcp://192.168.1.76:15001) to agent pool
2016-12-15T10:34:06Z [1] INFO {agency} Adding 07ca864b-ba46-4e7f-97f9-920a1230254c(tcp://192.168.1.81:15002) to agent pool
2016-12-15T11:27:21Z [1] INFO {agency} Estimating RAFT timeouts ...
2016-12-15T11:27:37Z [1] INFO {cluster} cannot create connection to server '' at endpoint 'tcp://192.168.1.81:15002'
2016-12-15T11:27:52Z [1] WARNING {agency} Timed out waiting for other measurements. Auto-adaptation failed!Will stick to command line arguments
2016-12-15T11:27:52Z [1] INFO {agency} Activating agent.

## agency2 log
[root@host81 ~]# docker logs -f agency2
2016/12/15 10:33:55 Error resolving syscall name execveat: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:33:55 Error resolving syscall name getrandom: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:33:55 Error resolving syscall name memfd_create: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:33:55 Error resolving syscall name renameat2: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:33:55 Error resolving syscall name sched_getattr: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:33:55 Error resolving syscall name sched_setattr: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:33:55 Error resolving syscall name seccomp: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:33:55 Error resolving syscall name breakpoint: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:33:55 Error resolving syscall name cacheflush: could not resolve name to syscall - ignoring syscall.
2016/12/15 10:33:55 Error resolving syscall name set_tls: could not resolve name to syscall - ignoring syscall.
Initializing database...Hang on...
Database initialized...Starting System...
2016-12-15T10:34:02Z [1] INFO ArangoDB 3.1.4 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.1t  3 May 2016
2016-12-15T10:34:02Z [1] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
2016-12-15T10:34:02Z [1] INFO file-descriptors (nofiles) hard limit is 1048576, soft limit is 1048576
2016-12-15T10:34:02Z [1] INFO JavaScript using startup '/usr/share/arangodb3/js', application '/var/lib/arangodb3-apps'
2016-12-15T10:34:02Z [1] INFO In database '_system': Found 14 defined task(s), 1 task(s) to run
2016-12-15T10:34:02Z [1] INFO In database '_system': state standalone/existing, tasks updateUserModels
2016-12-15T10:34:02Z [1] INFO In database '_system': existing cleanup successfully finished
2016-12-15T10:34:02Z [1] INFO using endpoint 'http+tcp://0.0.0.0:5001' for non-encrypted requests
2016-12-15T10:34:04Z [1] INFO ArangoDB (version 3.1.4 [linux]) is ready for business. Have fun!
2016-12-15T10:34:05Z [1] INFO {agency} Entering gossip phase ...
2016-12-15T10:34:05Z [1] INFO {agency} Adding 61dd4bac-f642-4054-990e-a9b07888e9b6(tcp://192.168.1.81:15001) to agent pool
2016-12-15T10:34:05Z [1] INFO {agency} Adding c25876a4-532d-4eef-915b-4cb4c47f9100(tcp://192.168.1.76:15001) to agent pool
2016-12-15T11:34:09Z [1] INFO {agency} Estimating RAFT timeouts ...
2016-12-15T11:34:25Z [1] INFO {cluster} cannot create connection to server '' at endpoint 'tcp://192.168.1.81:15001'
2016-12-15T11:34:40Z [1] WARNING {agency} Timed out waiting for other measurements. Auto-adaptation failed!Will stick to command line arguments
2016-12-15T11:34:40Z [1] INFO {agency} Activating agent.

## agency3 log
Initializing database...Hang on...
Database initialized...Starting System...
2016-12-15T10:29:20Z [1] INFO ArangoDB 3.1.4 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.1t  3 May 2016
2016-12-15T10:29:20Z [1] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
2016-12-15T10:29:20Z [1] INFO file-descriptors (nofiles) hard limit is 65536, soft limit is 65536
2016-12-15T10:29:20Z [1] INFO JavaScript using startup '/usr/share/arangodb3/js', application '/var/lib/arangodb3-apps'
2016-12-15T10:29:20Z [1] INFO In database '_system': Found 14 defined task(s), 1 task(s) to run
2016-12-15T10:29:20Z [1] INFO In database '_system': state standalone/existing, tasks updateUserModels
2016-12-15T10:29:20Z [1] INFO In database '_system': existing cleanup successfully finished
2016-12-15T10:29:20Z [1] INFO using endpoint 'http+tcp://0.0.0.0:5001' for non-encrypted requests
2016-12-15T10:29:22Z [1] INFO ArangoDB (version 3.1.4 [linux]) is ready for business. Have fun!
2016-12-15T10:29:23Z [1] INFO {agency} Entering gossip phase ...
2016-12-15T10:29:23Z [1] INFO {agency} Adding 61dd4bac-f642-4054-990e-a9b07888e9b6(tcp://192.168.1.81:15001) to agent pool
2016-12-15T10:34:05Z [1] INFO {agency} Adding 07ca864b-ba46-4e7f-97f9-920a1230254c(tcp://192.168.1.81:15002) to agent pool
2016-12-15T10:34:10Z [1] INFO {agency} Agent pool completed. Stopping active gossipping. Starting RAFT process.
2016-12-15T10:34:10Z [1] INFO {agency} Estimating RAFT timeouts ...
2016-12-15T10:34:26Z [1] WARNING {agency} Timed out waiting for other measurements. Auto-adaptation failed!Will stick to command line arguments
2016-12-15T10:34:26Z [1] INFO {agency} Activating agent.

**Comment by brucejee** [comment]
I change agency2 and agency3 to 192.168.1.76, It seems work now. And these web information seems ok. It seems 192.168.1.81, this machine has some limit for connecting to itself.

##These logs are very strange.
2016-12-15T11:27:37Z [1] INFO {cluster} cannot create connection to server '' at endpoint 'tcp://192.168.1.81:15002'
2016-12-15T11:34:25Z [1] INFO {cluster} cannot create connection to server '' at endpoint 'tcp://192.168.1.81:15001'

##agency1: http://192.168.1.81:15001/_db/_system/_admin/aardvark/index.html#collection/configuration/0
{
  "cfg": {
    "active": [
      "d4671072-9f84-4043-8956-ce7bda254046",
      "da963085-1daa-4e06-be14-a9203590a6dd",
      "e99e947b-45ef-4bb6-9db4-78a57ca3bd07"
    ],
    "agency size": 3,
    "compaction step size": 1000,
    "endpoint": "tcp://192.168.1.81:15001",
    "id": "da963085-1daa-4e06-be14-a9203590a6dd",
    "max ping": 2.5,
    "min ping": 0.5,
    "pool": {
      "da963085-1daa-4e06-be14-a9203590a6dd": "tcp://192.168.1.81:15001",
      "e99e947b-45ef-4bb6-9db4-78a57ca3bd07": "tcp://192.168.1.76:15002",
      "d4671072-9f84-4043-8956-ce7bda254046": "tcp://192.168.1.76:15001"
    },
    "pool size": 3,
    "startup": "origin",
    "supervision": true,
    "supervision frequency": 5,
    "supervision grace period": 15,
    "version": 1
  }
##agency2: http://192.168.1.76:15001/_db/_system/_admin/aardvark/index.html#collection/configuration/0
{
  "cfg": {
    "active": [
      "d4671072-9f84-4043-8956-ce7bda254046",
      "da963085-1daa-4e06-be14-a9203590a6dd",
      "e99e947b-45ef-4bb6-9db4-78a57ca3bd07"
    ],
    "agency size": 3,
    "compaction step size": 1000,
    "endpoint": "tcp://192.168.1.76:15001",
    "id": "d4671072-9f84-4043-8956-ce7bda254046",
    "max ping": 2.5,
    "min ping": 0.5,
    "pool": {
      "d4671072-9f84-4043-8956-ce7bda254046": "tcp://192.168.1.76:15001",
      "e99e947b-45ef-4bb6-9db4-78a57ca3bd07": "tcp://192.168.1.76:15002",
      "da963085-1daa-4e06-be14-a9203590a6dd": "tcp://192.168.1.81:15001"
    },
    "pool size": 3,
    "startup": "origin",
    "supervision": true,
    "supervision frequency": 5,
    "supervision grace period": 15,
    "version": 1
  }
}
##agency3: http://192.168.1.76:15002/_db/_system/_admin/aardvark/index.html#collection/configuration/0
{
  "cfg": {
    "active": [
      "d4671072-9f84-4043-8956-ce7bda254046",
      "da963085-1daa-4e06-be14-a9203590a6dd",
      "e99e947b-45ef-4bb6-9db4-78a57ca3bd07"
    ],
    "agency size": 3,
    "compaction step size": 1000,
    "endpoint": "tcp://192.168.1.76:15002",
    "id": "e99e947b-45ef-4bb6-9db4-78a57ca3bd07",
    "max ping": 2.5,
    "min ping": 0.5,
    "pool": {
      "e99e947b-45ef-4bb6-9db4-78a57ca3bd07": "tcp://192.168.1.76:15002",
      "da963085-1daa-4e06-be14-a9203590a6dd": "tcp://192.168.1.81:15001",
      "d4671072-9f84-4043-8956-ce7bda254046": "tcp://192.168.1.76:15001"
    },
    "pool size": 3,
    "startup": "origin",
    "supervision": true,
    "supervision frequency": 5,
    "supervision grace period": 15,
    "version": 1
  }

**Comment by brucejee** [comment]
So many error, when i restart a db, and then move shard between the two dbs, one coordinator is broken, i can't get data from my test collection now.

2016-12-16T02:11:38Z [1] ERROR {cluster} cannot create connection to server 'DBServer001' at endpoint 'tcp://192.168.1.81:18529'
2016-12-16T02:11:38Z [1] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s101434:/_db/_system/_api/collection/s101434/count
2016-12-16T02:11:49Z [1] ERROR {cluster} cannot create connection to server 'DBServer001' at endpoint 'tcp://192.168.1.81:18529'
2016-12-16T02:11:49Z [1] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s101434:/_db/_system/_api/collection/s101434/count

**Comment by brucejee** [comment]
tcp        0      0 192.168.1.81:18529      0.0.0.0:*               LISTEN      12233/docker-proxy

**Comment by brucejee** [comment]
Recreate the coordinator also failed. Log ouput this error all the time:

2016-12-16T02:30:22Z [1] ERROR Service "/_admin/aardvark" encountered error 500 while handling GET http://192.168.1.81:18531/_db/_system/_admin/aardvark/statistics/coordshort
2016-12-16T02:30:22Z [1] ERROR SyntaxError: Unexpected token u in JSON at position 0
2016-12-16T02:30:22Z [1] ERROR     at Object.parse (native)
2016-12-16T02:30:22Z [1] ERROR     at coordinators.map.e (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:504:19)
2016-12-16T02:30:22Z [1] ERROR     at Array.map (native)
2016-12-16T02:30:22Z [1] ERROR     at Route._handler (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:499:39)
2016-12-16T02:30:22Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:385:15)
2016-12-16T02:30:22Z [1] ERROR     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:9378:25
2016-12-16T02:30:22Z [1] ERROR     at Middleware.router.use (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:405:3)
2016-12-16T02:30:22Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:387:15)
2016-12-16T02:30:22Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
2016-12-16T02:30:22Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
2016-12-16T02:30:26Z [1] ERROR Couldn't read statistics response: undefined

**Comment by brucejee** [comment]
https://www.arangodb.com/2016/12/starting-arangodb-cluster-easy-way/  Tool in this article simplified test deployment.

**Comment by brucejee** [comment]
iptables prohibit docker container and host connection.
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

10:58:18.288121 IP 172.17.0.4.36624 > host81.18529: Flags [S], seq 290103964, win 14600, options [mss 1460,sackOK,TS val 3319782884 ecr 0,nop,wscale 7], length 0
10:58:18.288121 IP 172.17.0.4.36624 > host81.18529: Flags [S], seq 290103964, win 14600, options [mss 1460,sackOK,TS val 3319782884 ecr 0,nop,wscale 7], length 0
10:58:18.288145 IP host81 > 172.17.0.4: ICMP host host81 unreachable - admin prohibited, length 68
10:58:18.288147 IP host81 > 172.17.0.4: ICMP host host81 unreachable - admin prohibited, length 68
