### ISSUE TITLE
Foxx getInEdges() throws type error

### ISSUE THREAD

**Issue by vlabmichl** [arangodb/arangodb#2261]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: 
- [ ] MacOS, version:

### Foxx
I'm trying to implement a custom expander for the graph traverser in file `traverseAssetOwner.js`.

The expander method looks like:
`function myExpander (config, vertex, path) {
    var connected = [];
    var datasource = config.datasource;
 
    console.log(vertex._id);
    datasource.getInEdges(vertex).forEach(function (edge) {
        connected.push({ edge: edge, vertex: (edge._from) });
    });
    return connected;
}`

The traverser config looks like:
`var config = {
    datasource: traversal.collectionDatasourceFactory(db.Owners), // e is my edge collection
    strategy: "depthfirst",
    order: "preorder",
    filter: vertexFilter,
    expandFilter: edgeFilter,
    expander: myExpander,
    visitor: traversal.trackingVisitor
};`

When I execute the script in ADB I get the following error:
`{
  "error": true,
  "errorNum": 500,
  "errorMessage": "Internal Server Error",
  "code": 500,
  "exception": "ArangoError 10: invalid value type. expecting string or object value",
  "stacktrace": [
    "ArangoError: invalid value type. expecting string or object value",
    "    at Error (native)",
    "    at Object.getInEdges (c:\\ArangoDB\\program\\ArangoDB3-3.1.7-1_win64\\usr\\share\\arangodb3\\js\\common\\modules\\@arangodb\\graph\\traversal.js:187:36)",
    "    at Object.myExpander [as expander] (C:\\ArangoDB\\program\\ArangoDB3-3.1.7-1_win64\\var\\lib\\arangodb3-apps\\_db\\orgraph\\orgraph\\APP\\scripts\\traverser\\traverseAssetOwner.js:59:16)",
    "    at Object.run (c:\\ArangoDB\\program\\ArangoDB3-3.1.7-1_win64\\usr\\share\\arangodb3\\js\\common\\modules\\@arangodb\\graph\\traversal.js:990:36)",
    "    at ArangoTraverser.traverse (c:\\ArangoDB\\program\\ArangoDB3-3.1.7-1_win64\\usr\\share\\arangodb3\\js\\common\\modules\\@arangodb\\graph\\traversal.js:1632:14)",
    "    at Object.traverse (C:\\ArangoDB\\program\\ArangoDB3-3.1.7-1_win64\\var\\lib\\arangodb3-apps\\_db\\orgraph\\orgraph\\APP\\scripts\\traverser\\traverseAssetOwner.js:83:23)",
    "    at Route._handler (C:\\ArangoDB\\program\\ArangoDB3-3.1.7-1_win64\\var\\lib\\arangodb3-apps\\_db\\orgraph\\orgraph\\APP\\routes\\assets.js:50:24)",
    "    at next (c:\\ArangoDB\\program\\ArangoDB3-3.1.7-1_win64\\usr\\share\\arangodb3\\js\\server\\modules\\@arangodb\\foxx\\router\\tree.js:385:15)",
    "    at next (c:\\ArangoDB\\program\\ArangoDB3-3.1.7-1_win64\\usr\\share\\arangodb3\\js\\server\\modules\\@arangodb\\foxx\\router\\tree.js:383:7)",
    "    at next (c:\\ArangoDB\\program\\ArangoDB3-3.1.7-1_win64\\usr\\share\\arangodb3\\js\\server\\modules\\@arangodb\\foxx\\router\\tree.js:383:7)"
  ]
}`

The output of `console.log(vertex._id);` shows me the correct vertex which should be looked up:
`Assets/PERSON-MS`

It doesn't matter if I change the getInEdges() value to one of the following:
`datasource.getInEdges(vertex_id).forEach(function (edge) {`
`datasource.getInEdges("Assets/PERSON-MS").forEach(function (edge) {`
The result is always the same.

**Comment by vlabmichl** [comment]
Seems like a bug when using strings as vertex._id. Could temporarily fix it with:
`datasource.edgeCollection.INEDGES(toString(vertex._id)).forEach(function (edge) {`

Please confirm and fix it.

Thanks.

**Comment by vlabmichl** [comment]
Sorry, this is actually NOT a BUG - Please close this ticket.

Solution:
I was turned into the wrong direction by the first example in the docs https://docs.arangodb.com/3.1/Manual/Graphs/Traversals/UsingTraversalObjects.html#writing-custom-expanders
`
var config = {
  ...
  expander: function (config, vertex, path) {
    var connected = [ ];
    var datasource = config.datasource;
    datasource.getInEdges(vertex._id).forEach(function (edge) {
      if (Math.random() >= 0.5) {
        connected.push({ edge: edge, vertex: (edge._from) });
      }
    });
    return connected;
  }
};
`
The line `connected.push({ edge: edge, vertex: (edge._from) });` doesn't add the original vertex to the "connected" object rather than its "vertex._id" value.

The problem occurs in the next iteration step where the expander expects an full vertex object.

I fixed my code with pulling the original vertex from the datasource:
`connected.push({ edge: edge, vertex: datasource.getInVertex(edge) });`

Probably the docs should be clarified as the other examples use all this technique.
