### ISSUE TITLE
[coordinator] "Couldn't read statistics response: undefined"

### ISSUE THREAD

**Issue by bigmyx** [arangodb/arangodb#2296]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ x] 3.1.9

On this operating system:
- AWS ECS, Amazon EC2 ECS Optimized AMI **ami-d69c74c0**
  Using **arangodb/arangodb** docker container.

Installed 3 Clusters on AWS ECS, one for each role: Agency, Primary, Coordinator.
Running one container per host.
All containers have a direct connectivity to each other, available hosts/ports are discovered via Consul.

When accessing the Web UI via SSH tunneling `ssh -L 8531:<HOST_IP>:8531 <HOST_IP>`, the Web UI shows up, but the Cluster tab fails to show the stats.
The following exception pops up in the Coordinator's log:

```
2017-02-01T20:22:09Z [9] ERROR Couldn't read statistics response: undefined
2017-02-01T20:22:09Z [9] ERROR Service "/_admin/aardvark" encountered error 500 while handling GET http://localhost:8531/_db/_system/_admin/aardvark/statistics/coordshort
2017-02-01T20:22:09Z [9] ERROR SyntaxError: Unexpected token u in JSON at position 0
2017-02-01T20:22:09Z [9] ERROR     at Object.parse (native)
2017-02-01T20:22:09Z [9] ERROR     at coordinators.map.e (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:503:21)
2017-02-01T20:22:09Z [9] ERROR     at Array.map (native)
2017-02-01T20:22:09Z [9] ERROR     at Route._handler (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:499:41)
2017-02-01T20:22:09Z [9] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:385:15)
2017-02-01T20:22:09Z [9] ERROR     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:9378:25
2017-02-01T20:22:09Z [9] ERROR     at Middleware.router.use (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:405:3)
2017-02-01T20:22:09Z [9] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:387:15)
2017-02-01T20:22:09Z [9] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
2017-02-01T20:22:09Z [9] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
```
Furthermore, an operation, like adding service times out (getting `Services: 500. Internal Server Error`)

**Comment by m0ppers** [comment]
Do you have authentication turned on? Can you provide detailed startup parameteres?

**Comment by hellomanjack** [comment]
yes. I turn on the authentication. And meet the same problems. And it always repeat that error report.
Also I wonder the user name and password, when I open the web sites: http://master.mesos/service/arangodb. 
How can I solve it ? thanks.@m0ppers

**Comment by m0ppers** [comment]
this is currently unfortunately a known bug which is only frontend related. we are currently tackling some higher priority bugs but it is definately on our radar. As to username and password. This depends on how you deployed the cluster. You could try "root" with no password as this is the default.

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing lots of improvements to the clustering.
One of them was fixing this Issue. 

Closing.
