### ISSUE TITLE
Wrong Chunk received & Socket closed

### ISSUE THREAD

**Issue by leejaku17** [arangodb/arangodb#2305]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [*] 3.1.10
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [*] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### I don't know what's the problem.

I used ArangoDB 3.0.9 very well, after I upgrade to ArangoDB 3.1.10 and Java Driver 4.1.9, I suffer annoying exception.  It occurs from time to time. Exceptions are...

```
[23:48:57] ERROR c.v.p.o.n.NaoDatabase:159 com.arangodb.ArangoDBException: com.arangodb.ArangoDBException: Wrong Chunk recieved! Expected first Chunk.
com.arangodb.ArangoDBException: com.arangodb.ArangoDBException: Wrong Chunk recieved! Expected first Chunk.
        at com.arangodb.internal.velocystream.ConnectionSync.write(ConnectionSync.java:111)
        at com.arangodb.internal.velocystream.CommunicationSync.send(CommunicationSync.java:133)
        at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:117)
        at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:40)
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:58)
        at com.arangodb.ArangoCollection.insertDocument(ArangoCollection.java:79)
        at com.voce.protoss.obixmap.naopush.NaoDatabase.writeDevice(NaoDatabase.java:155)
        at com.voce.protoss.obixmap.naopush.NaoDataItem.setLastReport(NaoDataItem.java:226)
        at com.voce.protoss.obixmap.naopush.NaoPushClient.messageReceived(NaoPushClient.java:135)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:854)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943)
        at com.voce.protoss.obixmap.naopush.NaoPushFilter.messageReceived(NaoPushFilter.java:49)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943)
        at com.voce.protoss.obixmap.naopush.NaoPushCryptFilter.messageReceived(NaoPushCryptFilter.java:109)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943)
        at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:535)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:714)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:668)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:657)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1121)
        at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.arangodb.ArangoDBException: Wrong Chunk recieved! Expected first Chunk.
        at com.arangodb.internal.velocystream.ConnectionSync.write(ConnectionSync.java:102)
        ... 32 common frames omitted
```

and 

```
[23:48:57] ERROR c.v.p.o.n.NaoDatabase:159 com.arangodb.ArangoDBException: java.net.SocketException: Socket closed
com.arangodb.ArangoDBException: java.net.SocketException: Socket closed
        at com.arangodb.internal.velocystream.ConnectionSync.write(ConnectionSync.java:111)
        at com.arangodb.internal.velocystream.CommunicationSync.send(CommunicationSync.java:133)
        at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:117)
        at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:40)
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:58)
        at com.arangodb.ArangoCollection.insertDocument(ArangoCollection.java:79)
        at com.voce.protoss.obixmap.naopush.NaoDatabase.writeDevice(NaoDatabase.java:155)
        at com.voce.protoss.obixmap.naopush.NaoDataItem.setLastRecord(NaoDataItem.java:279)
        at com.voce.protoss.obixmap.naopush.NaoPushClient.writeHistoryDemand(NaoPushClient.java:292)
        at com.voce.protoss.obixmap.naopush.NaoPushClient.messageReceived(NaoPushClient.java:173)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:854)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943)
        at com.voce.protoss.obixmap.naopush.NaoPushFilter.messageReceived(NaoPushFilter.java:49)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943)
        at com.voce.protoss.obixmap.naopush.NaoPushCryptFilter.messageReceived(NaoPushCryptFilter.java:109)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943)
        at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:535)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:714)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:668)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:657)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1121)
        at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at com.arangodb.internal.velocystream.Connection.readBytesIntoBuffer(Connection.java:210)
        at com.arangodb.internal.velocystream.ConnectionSync.write(ConnectionSync.java:107)
        ... 33 common frames omitted

```

I never saw these exception while using 3.0.9.  Can you help me?

**Comment by baslr** [comment]
I @leejaku17,

with version 4 the java driver replaced http with VelocyStream as the communication protocol.
Unit the bug is fixed, is it possible to use version 3.1.0?

**Comment by leejaku17** [comment]
Thanks for reply. I can work-around this issue by retrying. 
Addition to this issue, I found new problem.  That's **inconsistent result of documentExists** function. 
Code is ...

```Java
    public void writeDevice(int addr, String name, String value) {
        String key = String.valueOf(addr);        
        try {
            if (this.db.collection(NaoDatabase.COLLMETERS).documentExists(key)) {
                BaseDocument doc = this.db.collection(NaoDatabase.COLLMETERS).getDocument(key, BaseDocument.class);
                doc.addAttribute(name, value);
                this.db.collection(NaoDatabase.COLLMETERS).updateDocument(key, doc);
            } else {
                log.info("key {} is not exist, create new", key);
                BaseDocument doc = new BaseDocument(key);
                doc.addAttribute(name, value);
                this.db.collection(NaoDatabase.COLLMETERS).insertDocument(doc);
            }
        } catch (Exception e) {
            log.error("key is {}", key);
            log.error(e.toString(), e);
        }
    }
```

Usually documentExists work fine. but sometimes documentExists failed for same key. So code try to insertDocument but failed with "com.arangodb.ArangoDBException: Response: 409, Error: 1210 - cannot create document, unique constraint violated". 

I don't know this is related to upper issues...

**Comment by jsteemann** [comment]
Regarding the last mentioned issue (`Error: 1210 - cannot create document, unique constraint violated"`): 
This error may happen "naturally" with all drivers when the "if documentExists then updateDocument else insertDocument" is run in multiple client threads. The check-and-then-update-or-insert procedure is not atomic as a whole, only the individual check, update and insert methods are. For example, two parallel client threads may get a result of `false` back from the `documentExists` method and then both try to create the same document in parallel. In this case only one client will succeed and the other will fail with the reported error message. So in case multiple client threads are executing the code, I think this is a data race.
It can be fixed by modifying the code as follows (pseudocode):
```
try {
  // try insert first
  insertDocument(doc);
  // insert succeeded, document did not exist before
} catch (uniqueConstraintViolatedError) {
  // document already existed, now update it
  while (true) {
    doc = getDocument(doc);
    doc.addAttribute(...);
    try {
      updateDocument(doc);
      // if we get here, we have successfully updated the document
      break;
    } catch (PreconditionFailedError) {
      // got a version conflict. someone else has updated the document in parallel
      // try again to avoid lost updates
    }
  }
}
```

**Comment by leejaku17** [comment]
Thank you for advice. 
But problem is... documentExists on apparent existing key is failed infrequently. 
For your information, I used ArangoDB 3.0.9 and Java Driver 3.x with this source code and never saw that error message.  In short, I suffer these issues after upgrade to ArangoDB 3.1.10 and JavaDriver 4.1.9.

**Comment by mpv1989** [comment]
Hi,
the exception `com.arangodb.ArangoDBException: com.arangodb.ArangoDBException: Wrong Chunk recieved! Expected first Chunk.` can be thrown if you use an instance of `ArangoDB` in multiple threads. The class `ArangoDB` is currently not thread-safe, so every thread of yours should instanciate its own instance of it. In addition this give the advantage of a separate socket-connection for each thread which result in a better throughput.

**Comment by mpv1989** [comment]
Ok, I changed the java driver and the class `ArangoDB` is now thread-safe. I will release a new driver version within this week. You can already use the snapshot version `4.1.9-SNAPSHOT` which already includes the change.

**Comment by leejaku17** [comment]
Thank you Mark!
I will build and apply new Java driver ASAP (tonight) and let you know result.

**Comment by leejaku17** [comment]
Perfect.  I replaced Java Driver with recent version and my server application is running well without error. 
Thank you very much !
