### ISSUE TITLE
Crash in Arango DB

### ISSUE THREAD

**Issue by arikhalperin** [arangodb/arangodb#2339]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 3.1.1
- [ ] docker - official docker library
- [ ] MacOS, version:10.2
### this is an AQL-related issue:
[ ] I'm using graph features
- [ ] this Driver: go driver

2017-03-02T09:02:55Z [1] ERROR Service "/_api/gharial" encountered error 500 while handling POST http://localhost:8529/_db/RouteNetwork/_api/gharial
2017-03-02T09:02:55Z [1] ERROR TypeError: Cannot read property 'edgeDefinitions' of undefined
2017-03-02T09:02:55Z [1] ERROR     at gdb.toArray.forEach (/usr/share/arangodb3/js/common/modules/@arangodb/general-graph.js:1929:30)
2017-03-02T09:02:55Z [1] ERROR     at Array.forEach (native)
2017-03-02T09:02:55Z [1] ERROR     at Object.exports._create (/usr/share/arangodb3/js/common/modules/@arangodb/general-graph.js:1927:17)
2017-03-02T09:02:55Z [1] ERROR     at Route._handler (/usr/share/arangodb3/js/apps/system/_api/gharial/APP/gharial.js:238:17)
2017-03-02T09:02:55Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:412:15)
2017-03-02T09:02:55Z [1] ERROR     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:10029:25
2017-03-02T09:02:55Z [1] ERROR     at Middleware.router.use.e (/usr/share/arangodb3/js/apps/system/_api/gharial/APP/gharial.js:72:5)
2017-03-02T09:02:55Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:414:15)
2017-03-02T09:02:55Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
2017-03-02T09:02:55Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)

**Comment by jsteemann** [comment]
With "crash" do you mean that the server crashed and was not reachable anymore, or do you mean that the server logged the above errors?

**Comment by jsteemann** [comment]
Can you also provide the HTTP POST data that you sent to http://localhost:8529/_db/RouteNetwork/_api/gharial when the problem occurred? Thanks!

**Comment by dothebart** [comment]
Hi, Any news on this? or can we close this?

**Comment by dothebart** [comment]
Closing due to missing feedback. If the problem persists, feel free to comment.
