### ISSUE TITLE
Double running / `internal_`

### ISSUE THREAD

**Issue by stockholmux** [arangodb/arangodb#2408]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:

- [x] 3.1

On this operating system:
- [x] MacOS, version:

### Foxx
Apologies if this is just something I don't understand about ArangoDB/Foxx, but I was trying to integrate the session middleware and kept coming up with odd errors saying that my 'sessions' collection didn't exist.

I started placing `console.log`s in my code and pouring over the output of `arangod` and noticed that, for some reason, my code was being run twice, first as `module.context.collectionPrefix` set to `internal_` then set to the actual value. I was able to work around this issue by using a if statement on the `collectionPrefix` to avoid setting up sessions on the first / `internal_` version.

The relevant bit of my code:
```
const
  arango          = require('@arangodb'),
  createRouter    = require('@arangodb/foxx/router'),
  joi             = require('joi'),
  db              = arango.db,
  errors          = arango.errors,
  aql             = arango.aql,
  router          = createRouter(),
  sessionsMiddle  = require('@arangodb/foxx/sessions'),
  users           = module.context.collectionName('users'),
  DOC_NOT_FOUND   = errors.ERROR_ARANGO_DOCUMENT_NOT_FOUND.code;

console.log("Starting...");

console.log('PREFIX',module.context.collectionPrefix);

if (module.context.collectionPrefix !== 'internal_') {
  const sessions = sessionsMiddle({
    storage: module.context.collection('sessions'),
    transport: ['header', 'cookie']
  });

  module.context.use(sessions);

}
module.context.use(router);
```

Output in `arangod`:
```
2017-03-31T19:43:21Z [28640] INFO Starting...
2017-03-31T19:43:21Z [28640] INFO PREFIX internal_

.. some irrelevant logging ..

2017-03-31T19:43:21Z [28640] INFO Starting...
2017-03-31T19:43:21Z [28640] INFO PREFIX midcentury_dev_
```

If I remove the `if` around the sessions bit I get the following error:
```
Cause: AssertionError: No session storage specified
    at sessionMiddleware (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/sessions/index.js:42:3)
    at Object.<anonymous> (/var/folders/_v/s9jvdb0x1753l8b1v4_yyf_m0000gn/T/arangod_dgqkbz/apps/tmp-28640-901218078/index.js:23:20)
    at Module._compile (/usr/local/opt/arangodb/share/arangodb3/js/common/bootstrap/modules.js:586:8)
    at Object.Module._extensions..js (/usr/local/opt/arangodb/share/arangodb3/js/common/bootstrap/modules.js:604:12)
    at Module.load (/usr/local/opt/arangodb/share/arangodb3/js/common/bootstrap/modules.js:539:36)
    at FoxxService.run (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/service.js:435:14)
    at exports.routeService (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/routing.js:153:40)
    at _validateService (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:1087:7)
    at Object.upgrade (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:1418:3)
    at Object.actions.defineHttp.callback.easyPostCallback.callback [as callback] (/usr/local/opt/arangodb/share/arangodb3/js/actions/_admin/foxx/app.js:146:26)
```
And in `arangod`

```
2017-03-31T19:47:07Z [28640] INFO Starting...
2017-03-31T19:47:07Z [28640] INFO PREFIX internal_
2017-03-31T19:47:07Z [28640] ERROR Cannot execute Foxx service at /internal: ArangoError: failed to invoke module
2017-03-31T19:47:07Z [28640] ERROR File: /var/folders/_v/s9jvdb0x1753l8b1v4_yyf_m0000gn/T/arangod_dgqkbz/apps/tmp-28640-901218078/index.js
2017-03-31T19:47:07Z [28640] ERROR Cause: AssertionError: No session storage specified
```

I'm 'restarting' my foxx app with `foxx-manager` as so:
```
foxx-manager upgrade [name] [mount point] --server.password [password] --server.username [username] --server.database [db]
```

What am I doing wrong / is there something wrong here?

**Comment by pluma** [comment]
You're right that this is a bug in the Foxx Manager. The service is currently being "validated" before each upgrade/replace to guarantee that it will work before the existing service is overwritten. Part of the validation is that the service is executed as if it would actually be mounted (i.e. the main file is loaded and executed). This is why you see errors about the "/internal" mount path -- that's where the service thinks it's mounted during the "validation".

Normally the main file does not perform any database access so this used to work fine throughout 2.x. However as you've noticed the session middleware we introduced in 3.0 performs a sanity check that the collection you're using actually exists, which throws an error at mount time.

We're already in the process of heavily rewriting the service management logic as part of the cluster resilience improvements for 3.2 so this problem should be fixed with the upcoming 3.2 release (note that alpha releases currently are still affected by this behaviour).

In the meantime you can continue using the `if` workaround to avoid running into this problem. I apologise for the inconvenience.

**Comment by stockholmux** [comment]
Thanks for verifying that I found a bug! I thought I was going crazy.

**Comment by pluma** [comment]
You're definitely not crazy. The "validation" logic will be removed in 3.2 and replaced with some less intrusive sanity checks. I'm keeping this issue open until the feature branch (`vulpine-resilience`) is merged.

**Comment by pluma** [comment]
Will be part of the next 3.2 release.

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing this is now available for download - Closing.
