### ISSUE TITLE
ArangoError: no match after delete document

### ISSUE THREAD

**Issue by tthil** [arangodb/arangodb#2410]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [x] MacOS, version: 10.11.6

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [x] this Driver: arangojs

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 

After deleting a document I get this error:

{ ArangoError: no match
    at new ArangoError (/Users/thomas/development/uncircled/quickplan/node_modules/arangojs/lib/error.js:30:15)
    at /Users/thomas/development/uncircled/quickplan/node_modules/arangojs/lib/connection.js:203:21
    at callback (/Users/thomas/development/uncircled/quickplan/node_modules/arangojs/lib/util/request.js:51:12)
    at IncomingMessage.<anonymous> (/Users/thomas/development/uncircled/quickplan/node_modules/arangojs/lib/util/request.js:62:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  errorNum: 404,
  code: 404,
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: { end: [Object], data: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     socket: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 9,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 37026,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: [Object],
        _httpMessage: [Object],
        read: [Function],
        _consuming: true },
     connection: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 9,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 37026,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: [Object],
        _httpMessage: [Object],
        read: [Function],
        _consuming: true },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { 'content-type': 'application/json; charset=utf-8',
        server: 'ArangoDB',
        connection: 'Keep-Alive',
        'content-length': '66' },
     rawHeaders: 
      [ 'Content-Type',
        'application/json; charset=utf-8',
        'Server',
        'ArangoDB',
        'Connection',
        'Keep-Alive',
        'Content-Length',
        '66' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 404,
     statusMessage: 'Not Found',
     client: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 9,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 37026,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: [Object],
        _httpMessage: [Object],
        read: [Function],
        _consuming: true },
     _consuming: true,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: [Object],
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'PUT /_db/exo-dev/_api/simple/first-example HTTP/1.1\r\ncontent-type: application/json\r\ncontent-length: 73\r\nx-arango-version: 30000\r\nauthorization: Basic cm9vdDo=\r\nHost: localhost:8529\r\nConnection: keep-alive\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'PUT',
        path: '/_db/exo-dev/_api/simple/first-example',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null },
     read: [Function],
     body: 
      { error: true,
        code: 404,
        errorNum: 404,
        errorMessage: 'no match' } } }
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

If I leave the document and just delate all edges to it all is fine but as soon I delete the document I end up in this ArangoError: no match.

**Comment by dothebart** [comment]
from what I see there, it didn't find a document to delete that matched your filters?

**Comment by tthil** [comment]
I use it like this:

const cb = await cityBookings.document(args.cityBookingKey.toString());
console.log(`cityBooking: ${JSON.stringify(cb)}`);
await cityBookings.removeByExample({ _id: cb._id })
      .then(() => {
        console.log(`cityBooking: ${cb._id} ....DELETED!....`);
      }).catch((error) => {
        console.log(`ERROR: ${error}`);
      });

Wrong?

**Comment by pluma** [comment]
I'm not sure what you are expecting.

The object you dumped indicates you're doing a `firstExample` query, not `removeByExample`, and that you're getting a "no match" error. This is what you'd expect if the collection no longer contains any matching documents because you deleted them.

Can you clarify:

1. What your code actually does (i.e. include the part using `firstExample`)
2. What you are expecting to happen
3. What you are seeing instead

From all I can see the error is not related to the code you're showing and the error is the expected outcome for what it looks like what triggered it.

**Comment by fceller** [comment]
closing as there is no activity for over a month
