### ISSUE TITLE
More Error info

### ISSUE THREAD

**Issue by Thijxx** [arangodb/arangodb#2436]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X] 3.1

On this operating system:
  - [X] other: Arch

It would be nice to have more information here. For example what exactly is failing.

![screenshot from 2017-04-19 10-27-02](https://cloud.githubusercontent.com/assets/3355823/25170483/f91eb4b8-24ea-11e7-8120-b3ee4f1f0770.png)

**Comment by dothebart** [comment]
this seems like a frame from a backtrace. Aren't there any other lines next to this one?

**Comment by Thijxx** [comment]
Yes, like these:

```
Error	2017-04-19 13:47:30	at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/route.js:47:28)
Error	2017-04-19 13:47:30	at prepareServiceRequestBody (/usr/share/arangodb3/js/apps/system/_api/foxx/APP/index.js:76:3)
Error	2017-04-19 13:47:30	at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/route.js:53:24)
Error	2017-04-19 13:47:30	at serviceRouter.put (/usr/share/arangodb3/js/apps/system/_api/foxx/APP/index.js:197:6)
```

It would be nice if there was a singular 'object' for the error containing all relevant information. it's all there, probably but the UI could make it much simpler to interpret. It needs some love  :)

**Comment by pluma** [comment]
There's no obvious way to fix this right now. For the frontend it would be nice to have stacktraces as single items but in the log files that would result in unreadable `\nat ...\nat ...\nat ...` stacktraces which we explicitly don't want.

Part of the problem is of course that the order in the frontend is inversed (unless we changed this?), making stacktraces unreadable.
