### ISSUE TITLE
Foxx service upload fails in El Capitan installed via Homebrew (ArangoDB 3.2)

### ISSUE THREAD

**Issue by eyan** [arangodb/arangodb#2906]
Installed via Homebrew, running OSX El Capitan. Stack trace follows:

```
Eel:~ sinaleyan$ /usr/local/opt/arangodb/sbin/arangod
2017-07-30T13:29:15Z [7909] INFO ArangoDB 3.2.0 [darwin] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.0.0, OpenSSL 1.0.2l  25 May 2017
2017-07-30T13:29:15Z [7909] INFO using storage engine rocksdb
2017-07-30T13:29:15Z [7909] INFO {cluster} Starting up with role SINGLE
2017-07-30T13:29:15Z [7909] INFO {syscall} file-descriptors (nofiles) hard limit is unlimited, soft limit is 8192
2017-07-30T13:29:15Z [7909] INFO Authentication is turned on (system only), authentication for unix sockets is turned on
2017-07-30T13:29:16Z [7909] INFO using endpoint 'http+tcp://127.0.0.1:8529' for non-encrypted requests
2017-07-30T13:29:20Z [7909] INFO ArangoDB (version 3.2.0 [darwin]) is ready for business. Have fun!
Updated local repository information with 29 service(s)
2017-07-30T13:30:03Z [7909] ERROR Service "/_admin/aardvark" encountered error 500 while handling PUT http://127.0.0.1:8529/_db/redacted/_admin/aardvark/foxxes/zip?mount=%2Fv
2017-07-30T13:30:03Z [7909] ERROR via ArangoError: read only
2017-07-30T13:30:03Z [7909] ERROR     at _install (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:669:22)
2017-07-30T13:30:03Z [7909] ERROR     at Object.install (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:829:19)
2017-07-30T13:30:03Z [7909] ERROR     at Middleware.<anonymous> (/usr/local/opt/arangodb/share/arangodb3/js/apps/system/_admin/aardvark/APP/foxxes.js:94:29)
2017-07-30T13:30:03Z [7909] ERROR     at next (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:414:15)
2017-07-30T13:30:03Z [7909] ERROR     at next (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
2017-07-30T13:30:03Z [7909] ERROR     at next (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
2017-07-30T13:30:03Z [7909] ERROR     at /usr/local/opt/arangodb/share/arangodb3/js/node/node_modules/lodash/lodash.js:10029:25
2017-07-30T13:30:03Z [7909] ERROR     at Middleware.router.use (/usr/local/opt/arangodb/share/arangodb3/js/apps/system/_admin/aardvark/APP/foxxes.js:55:3)
2017-07-30T13:30:03Z [7909] ERROR     at next (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:414:15)
2017-07-30T13:30:03Z [7909] ERROR     at next (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
```

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [x] MacOS, version: El Capitan

### this is a web interface-related issue:
I'm using the web interface with this browser: Safari     running on this OS: OSX El Capitan
- [x] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

**Comment by eyan** [comment]
Same is true for Ubuntu 16.04 with ArangoDB 3.2 installed via apt.

**Comment by mpv1989** [comment]
In 3.2.0 you need write access to the system collections `_apps` and `_appbundles` with the user who want to install a foxx service. We fixed this with 3.2.1, where you now need admin access for the database with the user.

**Comment by eyan** [comment]
I'll give this a swing in the next [hours|days]. Will close when I have confirmed success. Thank you.

**Comment by eyan** [comment]
Confirmed the fix. Thank you.
