### ISSUE TITLE
Arangoimp crashes on version 3.2 community during dataimport

### ISSUE THREAD

**Issue by pjesudhas** [arangodb/arangodb#3053]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- 3.2

Mode:
- Cluster

Storage-Engine:
- mmfiles

On this operating system:
- DCOS on
  - own infrastructure
- Linux 
  - other: CentOS

### Arangoimp

We've recently migrated ArangoDB from version 3.0.10 to 3.2 community version. During the data import process using Arangoimp we often end up observing the below error and the system crashes

2017-08-17T07:07:14Z [10109] ERROR error message:
2017-08-17T07:07:14Z [10109] ERROR cluster internal HTTP connection broken

When we restart the process the data import happens properly, it doesn't look like its data dependent.

**Comment by stuxuhai** [comment]
the same problem:

`
com.arangodb.ArangoDBException: Response: 500, Error: 1465 - cluster internal HTTP connection broken
	at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:106)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:134)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:46)
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:96)
	at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:46)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:58)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:47)
	at com.arangodb.ArangoCollection.importDocuments(ArangoCollection.java:167)
`

**Version:**
3.2.1

**Mode:**
Cluster

**Storage-Engine:**
rocksdb

**Comment by dothebart** [comment]
Hi,
 ArangoDB 3.2.8 containing many improvements to the clustering and memory management are available for download. 
Can you please upgrade and test whether the issue persists?

**Comment by dothebart** [comment]
Closing as solved with 3.2.8

**Comment by talkabhishek** [comment]
Hi, I am using arango 3.3.8 but getting the same error, using data from an older version by creating a dump and then restoring the dump

**Comment by dothebart** [comment]
please try to specify a smaller `--batch-size` than the default of 8388608  and check whether this fixes the incident for you.

**Comment by lidaling** [comment]
the same error.
Here are the command lines and  log

cluster startup command

> nohup arangodb --starter.join 192.168.100.40,192.168.100.41,192.168.100.42 > ./logs &

imp command

> nohup arangoimp --file ./180504_trans_100m.csv --type tsv --collection trans --create-collection true --server.database test --server.username test --server.password dtise123 --batch-size 5242880 > ./log &

the imp log
```
[root@arango_0 data]# head -n 30 log
Connected to ArangoDB 'http+tcp://127.0.0.1:8529', version 3.3.8, database: 'test', username: 'test'
----------------------------------------
database:               test
collection:             trans
create:                 yes
source filename:        ./180504_trans_100m.csv
file type:              tsv
separator:
threads:                2
connect timeout:        5
request timeout:        1200
----------------------------------------
Starting TSV import...
2018-05-13T15:01:25Z [22409] INFO processed 609779712 bytes (3%) of input file
2018-05-13T15:03:00Z [22409] INFO processed 1219526656 bytes (6%) of input file
2018-05-13T15:07:16Z [22409] INFO processed 1829273600 bytes (9%) of input file

2018-05-13T15:28:22Z [22409] ERROR error message(s):
2018-05-13T15:28:22Z [22409] ERROR cluster internal HTTP connection broken
2018-05-13T15:28:22Z [22409] ERROR cluster internal HTTP connection broken
2018-05-13T15:28:22Z [22409] ERROR cluster internal HTTP connection broken
2018-05-13T15:28:22Z [22409] ERROR cluster internal HTTP connection broken
2018-05-13T15:28:22Z [22409] ERROR cluster internal HTTP connection broken
2018-05-13T15:28:22Z [22409] ERROR cluster internal HTTP connection broken
2018-05-13T15:28:22Z [22409] ERROR cluster internal HTTP connection broken
2018-05-13T15:28:22Z [22409] ERROR cluster internal HTTP connection broken
2018-05-13T15:28:22Z [22409] ERROR cluster internal HTTP connection broken
2018-05-13T15:28:22Z [22409] ERROR cluster internal HTTP connection broken
2018-05-13T15:28:22Z [22409] ERROR cluster internal HTTP connection broken
2018-05-13T15:28:22Z [22409] ERROR cluster internal HTTP connection broken
...
```

**Comment by dothebart** [comment]
Hi, please have a look at https://github.com/arangodb/arangodb/issues/4912 wich contains more discussions about this topic.
