### ISSUE TITLE
Database collections restored using arangorestore are only accessible using root account

### ISSUE THREAD

**Issue by kashifpk** [arangodb/arangodb#3420]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X] 3.2

Mode:
- [X] Single-Server

Storage-Engine:
- [X] rocksdb

On this operating system:
- [X] Linux 
  - [X] Ubuntu .deb

## Steps to reproduce

1. Took a dump using arangodump on a linux (Ubuntu 16.10) machine running arangodb 3.2.2
2. Uploaded the dump to another linux machine (Ubuntu 16.10) with a freshly installed arangodb 3.2.4
3. Ran arangorestore on the second machine using same username and database (already created from the web interface) as in the first machine. Dump imported without any errors 

```bash
$ arangorestore --create-collection true --import-data true --server.database quranref --server.username kashif --server.password password --input-directory quranref_14-Oct-2017
Server version: 3.2.4
# Connected to ArangoDB 'http+tcp://127.0.0.1:8529'
# Re-creating document collection 'ayas'...
# Loading data into document collection 'ayas'...
# Creating indexes for collection 'ayas'...
# Re-creating document collection 'surahs'...
# Loading data into document collection 'surahs'...
# Re-creating document collection 'texts'...
# Loading data into document collection 'texts'...
# Re-creating document collection 'words'...
# Loading data into document collection 'words'...
# Creating indexes for collection 'words'...
# Re-creating edge collection 'aya_texts'...
# Loading data into edge collection 'aya_texts'...
# Re-creating edge collection 'has'...
# Loading data into edge collection 'has'...
Processed 6 collection(s), read 53847161 byte(s) from datafiles, sent 10 batch(es)
```
When I login either via arangosh or web interface with the user that I created for the database, I don't see any of the imported/restored collections. I am able to create new collections and trying to create a collection with the same name as one of the imported collections results in an error.

```bash
$ arangosh --server.database quranref --server.username kashif --server.password password 

                                       _     
  __ _ _ __ __ _ _ __   __ _  ___  ___| |__  
 / _` | '__/ _` | '_ \ / _` |/ _ \/ __| '_ \ 
| (_| | | | (_| | | | | (_| | (_) \__ \ | | |
 \__,_|_|  \__,_|_| |_|\__, |\___/|___/_| |_|
                       |___/                 

arangosh (ArangoDB 3.2.4 [linux] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.0.0, OpenSSL 1.0.2g  1 Mar 2016)
Copyright (c) ArangoDB GmbH

Pretty printing values.
Connected to ArangoDB 'http+tcp://127.0.0.1:8529' version: 3.2.4 [server], database: 'quranref', username: 'kashif'

Type 'tutorial' for a tutorial or 'help' to see common examples
127.0.0.1:8529@quranref> db._collections()
[ 
  [ArangoCollection 2447, "_apps" (type document, status loaded)], 
  [ArangoCollection 2123, "_aqlfunctions" (type document, status loaded)], 
  [ArangoCollection 2126, "_frontend" (type document, status loaded)], 
  [ArangoCollection 2107, "_graphs" (type document, status loaded)], 
  [ArangoCollection 2132, "_jobs" (type document, status loaded)], 
  [ArangoCollection 2110, "_modules" (type document, status loaded)], 
  [ArangoCollection 2129, "_queues" (type document, status loaded)], 
  [ArangoCollection 2113, "_routing" (type document, status loaded)] 
]

127.0.0.1:8529@quranref> db._collection('ayas')
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 98,7: ArangoError 11: No access to collection
!      throw error;
!      ^
stacktrace: ArangoError: No access to collection
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:96:21)
    at ArangoDatabase._collection (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:326:12)
    at <shell command>:1:4


127.0.0.1:8529@quranref> 
```

If I login using the root account, I am able to access the collections

```bash
$ arangosh --server.database quranref --server.username root
Please specify a password: 

                                       _     
  __ _ _ __ __ _ _ __   __ _  ___  ___| |__  
 / _` | '__/ _` | '_ \ / _` |/ _ \/ __| '_ \ 
| (_| | | | (_| | | | | (_| | (_) \__ \ | | |
 \__,_|_|  \__,_|_| |_|\__, |\___/|___/_| |_|
                       |___/                 

arangosh (ArangoDB 3.2.4 [linux] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.0.0, OpenSSL 1.0.2g  1 Mar 2016)
Copyright (c) ArangoDB GmbH

Pretty printing values.
Connected to ArangoDB 'http+tcp://127.0.0.1:8529' version: 3.2.4 [server], database: 'quranref', username: 'root'

Type 'tutorial' for a tutorial or 'help' to see common examples
127.0.0.1:8529@quranref> db._collections()
[ 
  [ArangoCollection 2447, "_apps" (type document, status loaded)], 
  [ArangoCollection 2123, "_aqlfunctions" (type document, status loaded)], 
  [ArangoCollection 2126, "_frontend" (type document, status loaded)], 
  [ArangoCollection 2107, "_graphs" (type document, status loaded)], 
  [ArangoCollection 2132, "_jobs" (type document, status loaded)], 
  [ArangoCollection 2110, "_modules" (type document, status loaded)], 
  [ArangoCollection 2129, "_queues" (type document, status loaded)], 
  [ArangoCollection 2113, "_routing" (type document, status loaded)], 
  [ArangoCollection 465, "aya_texts" (type edge, status loaded)], 
  [ArangoCollection 437, "ayas" (type document, status loaded)], 
  [ArangoCollection 459, "has" (type edge, status loaded)], 
  [ArangoCollection 444, "surahs" (type document, status loaded)], 
  [ArangoCollection 455, "texts" (type document, status loaded)], 
  [ArangoCollection 448, "words" (type document, status loaded)] 
]

127.0.0.1:8529@quranref> db._collection('ayas')
[ArangoCollection 437, "ayas" (type document, status loaded)]
```

Both import and restore was done using the user kashif and kashif has administer rights on the quranref database.

**Comment by kashifpk** [comment]
This issue also persists if trying to access the collections via the API using language specific drivers like python's arango driver. Seems like arangorestore doesn't respect the username and password given to it when storing data???

**Comment by graetzer** [comment]
Hi, yes this is a known bug currently. Will fix it next week

**Comment by maxkernbach** [comment]
Versions 3.2.8 and 3.2.9 containing the fix for this bug are available for download.
Closing the issue.
