### ISSUE TITLE
Crashed ArangoDB is not restarted been run under the `--supervisor`

### ISSUE THREAD

**Issue by luav** [arangodb/arangodb#3735]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [X] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [X] Single-Server

Storage-Engine:
- [X] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [X] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[X] I'm using graph features

I'm issuing AQL via:
- [X] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 

Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

#### The following problem occurs: [Screenshot?] 

ArangoDB process crashed and did NOT automatically restart though the ` --supervisor` flag was enabled:
```sh
$ sudo ps -afx | grep arango 
/usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --log.foreground-tty false --supervisor
```

The problem is that *Transparent Hugepage Support* was turned on and ArangoDB process was killed by the system because went out of memory, but I still expect the automatic restart of the process when the `--supervisor` flag is supplied to the `arangod`. However the crashed ArangoDB service (daemon process) was NOT restarted.

**Logs:** 
arangod.log:
```
2017-11-16T19:49:39Z [4559] INFO ArangoDB 3.2.6 [linux] 64bit, using jemalloc, 
VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.0.0, OpenSSL 1.0.1f 6 Jan 2014
2017-11-16T19:49:39Z [4559] WARNING {memory} /sys/kernel/mm/transparent_hugepag
e/enabled is set to 'always'. It is recommended to set it to a value of 'never'
 or 'madvise'
2017-11-16T19:49:39Z [4559] WARNING {memory} /sys/kernel/mm/transparent_hugepag
e/defrag is set to 'always'. It is recommended to set it to a value of 'never' 
or 'madvise'
2017-11-16T19:49:39Z [4559] WARNING {memory} execute 'sudo bash -c "echo madvis
e > /sys/kernel/mm/transparent_hugepage/enabled"'
2017-11-16T19:49:39Z [4559] WARNING {memory} execute 'sudo bash -c "echo madvis
e > /sys/kernel/mm/transparent_hugepage/defrag"'
2017-11-16T19:49:39Z [4559] INFO using storage engine mmfiles
2017-11-16T19:49:39Z [4559] INFO {cluster} Starting up with role SINGLE
2017-11-16T19:49:39Z [4559] INFO {syscall} file-descriptors (nofiles) hard limi
t is 131072, soft limit is 131072
2017-11-16T19:49:39Z [4559] INFO Authentication is turned on (system only), aut
hentication for unix sockets is turned on
2017-11-16T19:49:40Z [4559] INFO running WAL recovery (1 logfiles)
2017-11-16T19:49:40Z [4559] INFO replaying WAL logfile '/var/lib/arangodb3/jour
nals/logfile-266196471486.db' (1 of 1)
2017-11-16T19:49:40Z [4559] INFO WAL recovery finished successfully
2017-11-16T19:49:41Z [4559] INFO using endpoint 'http+tcp://0.0.0.0:8529' for n
on-encrypted requests
2017-11-16T19:49:44Z [4559] INFO ArangoDB (version 3.2.6 [linux]) is ready for business. Have fun!
2017-11-16T19:52:50Z [4705] INFO ArangoDB 3.2.6 [linux] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.0.0, OpenSSL 1.0.1f 6 Jan 2014
2017-11-16T19:52:50Z [4705] WARNING {memory} /sys/kernel/mm/transparent_hugepage/enabled is set to 'always'. It is recommended to set it to a value of 'never' or 'madvise'
2017-11-16T19:52:50Z [4705] WARNING {memory} /sys/kernel/mm/transparent_hugepage/defrag is set to 'always'. It is recommended to set it to a value of 'never' or 'madvise'
2017-11-16T19:52:50Z [4705] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/enabled"'
2017-11-16T19:52:50Z [4705] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/defrag"'
2017-11-16T19:52:50Z [4705] INFO using storage engine mmfiles
2017-11-16T19:52:50Z [4705] INFO {cluster} Starting up with role SINGLE
2017-11-16T19:52:50Z [4705] INFO {syscall} file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
2017-11-16T19:52:50Z [4705] INFO Authentication is turned on (system only), authentication for unix sockets is turned on
2017-11-16T19:52:50Z [4705] INFO running WAL recovery (1 logfiles)
2017-11-16T19:52:50Z [4705] INFO replaying WAL logfile '/var/lib/arangodb3/journals/logfile-266197705810.db' (1 of 1)
2017-11-16T19:52:51Z [4705] INFO WAL recovery finished successfully
2017-11-16T19:52:52Z [4705] INFO using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
2017-11-16T19:52:54Z [4705] INFO ArangoDB (version 3.2.6 [linux]) is ready for business. Have fun!
2017-11-16T19:58:05Z [4705] WARNING reached heap-size limit, interrupting V8 execution (heap size limit 3254779904, used 3083774840)
2017-11-16T19:58:05Z [4705] ERROR encountered out-of-memory error
2017-11-16T19:58:05Z [4705] WARNING {queries} slow query: 'FOR v, e, p IN 1..10 ANY "users/266194696833" GRAPH "community" RETURN p', took: 247.832256, loading took: 0.189047
2017-11-17T06:59:51Z [4705] WARNING {queries} slow query: 'FOR posFriend IN users\nSORT RAND()\nFILTER users._id != posFriend._id\nLIMIT 20\nRETURN {\n_id : posFriend._id\n}', took: 43.819094
2017-11-17T07:01:51Z [4705] WARNING {queries} slow query: 'FOR user in users\n    FOR posFriend IN users\n    SORT RAND()\n    FILTER user._id != posFriend._id\n    LIMIT 20\n    RETURN {\n        _id : posFriend._id\n    }', took: 119.165186
2017-11-17T07:05:24Z [4705] WARNING {queries} slow query: 'FOR x IN @@collection LET att = APPEND(SLICE(ATTRIBUTES(x), 0, 25), "_key", true) LIMIT @offset, @count RETURN KEEP(x, att)', bind vars: {"@collection":"friend_relations","count":10,"offset":0}, took: 49.168123, loading took: 49.167858
2017-11-17T07:05:24Z [4705] WARNING {queries} slow query: 'FOR user IN users\n    LET times = FLOOR( RAND()*19 + 2 )\n    \n    LET possibleFriends = (\n        FOR posFriend IN users\n        SORT RAND()\n        FILTER user._id != posFriend._id\n        LIMIT 20\n        RETURN {\n            _id : posFriend._id\n        }\n    )\n    \n    LET friends = (\n      FOR friend IN OUTBOUND user friend_relations\n      RETURN friend._id\n    )\n    \n    FOR repTimes IN 1..times\n        // 1) Check for self linking\n        // 2) Check for linking by friend\n        FILTER friends[*]._id != possibleFriends[ repTimes-1 ]._id\n        INSERT {\n            _from : user._id,\n            _to : possibleFriends[ repTimes-1 ]._id,\n            $label : "friend_with"\n        } IN friend_relations\n        \n', took: 55.649074
2017-11-17T07:14:02Z [4705] WARNING {queries} slow query: 'LET groups = (\n    FOR user IN users\n        FILTER user.property[0].car.color == 'black'\n        FOR friendOfFriend IN 2..2 ANY user GRAPH 'community'\n            FILTER friendOfFriend.property[0].car.color == 'black'\n            RETURN {\n                _id: friendOfFriend._id,\n                name: friendOfFriend.name\n            }\n)\n    \nRETURN groups \n\n', took: 65.735530
2017-11-17T07:15:13Z [4705] WARNING {queries} slow query: 'FOR times IN 1..5 \n    LET user = (\n        FOR user IN users\n            LIMIT 2\n            SORT RAND()\n            RETURN user\n        /*[\n         { _id : "users/266194702377" },\n         { _id : "users/266194694859" }\n        ]*/\n    )\n    \n    LET path = (\n        FOR v IN ANY SHORTEST_PATH\n            user[0]._id 
TO user[1]._id\n            GRAPH 'community'\n            // OPTIONS {bfs: true, uniqueVertices: 'global'} \n            // only weightAttribute and defaultWeigth possible\n            // https://docs.arangodb.com/3.2/AQL/Graphs/ShortestPath.html\n            RETURN {\n                key: v._key,\n                label: v.name\n            }\n    )\n    \n    RETURN {\n        src: CONCAT(user[0].id, ':', user[0].name),\n        dst: CONCAT(user[1].id, ':', user[1].name),\n        path: SHIFT( POP(path) ), // First vertex in path ist src node, last vertex in the path is the dest node => remove it\n        length: LENGTH(path)-2  // Number of friends\n    }\n\n', took: 10.681977
```

arangod.log.supervisor:
```
2017-11-16T19:52:50Z [15310] INFO {startup} supervisor has forked a child process with pid 4705
2017-11-17T07:22:31Z [15310] INFO {startup} waitpid woke up with return value 4705 and status 9 and DONE = false
2017-11-17T07:22:31Z [15310] INFO {startup} child process 4705 terminated normally, exit status 9 (SIGKILL). will intentionally not start a new child process
```

#### Instead I would be expecting: 

1. Graceful restart of ArangoDB service in case of any internal [crash]/external termination if the ArangoDB is started in the *daemon mode* with the  `--supervisor` flag
2. During the installation the ArangoDB should also check the [*Transparent Hugepage*](https://www.kernel.org/doc/Documentation/vm/transhuge.txt) VM configuration if the `mmfile` storage is selected and interactively *suggest to update* the values to `madvise` or `defer+madvise` if required since it's **critical** for the DB service execution.

The permanent configuration of the `/sys/kernel/mm/transparent_hugepage/*` on Ubuntu can be performed using `sysfsutils`.  
Note: Similar requirements for the *Transparent Hugepage* exists for the MongoDB, so you want to check their solution/recommendation(s).

**Environment:**  
```sh
$ arangodb --version
Version 0.10.2, build 7f0affe

$ arangosh --version
3.2.6

architecture: 64bit
arm: false
asan: false
asm-crc32: true
assertions: false
boost-version: 1.62.0
build-date: 2017-10-26 20:44:28
build-repository: tags/v3.2.6-0-g8c59daf
compiler: gcc [5.4.0]
cplusplus: 201103
debug: false
endianness: little
failure-tests: false
fd-client-event-handler: poll
fd-setsize: 1024
full-version-string: ArangoDB 3.2.6 [linux] 64bit, using jemalloc, VPack 0.1.30
, RocksDB 5.6.0, ICU 58.1, V8 5.7.0.0, OpenSSL 1.0.1f 6 Jan 2014
icu-version: 58.1
jemalloc: true
maintainer-mode: false
openssl-version: OpenSSL 1.0.1f 6 Jan 2014
platform: linux
reactor-type: epoll
rocksdb-version: 5.6.0
server-version: 3.2.6
sizeof int: 4
sizeof void*: 8
sse42: false
unaligned-access: true
v8-version: 5.7.0.0
vpack-version: 0.1.30
zlib-version: 1.2.11

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

**Comment by luav** [comment]
One more crash of the ArangoDB service without the expected automatic recovery under `--supervisor`. This time `/sys/kernel/mm/transparent_hugepage/*` were set to `madvise`.

**Logs:**
arangod.log
```sh
2017-11-17T21:55:36Z [9342] ERROR Service "/_admin/aardvark" encountered error 
500 while handling GET http://srv.exascale.info:8529/_db/db2/_admin/aardvark/qu
ery/download/bdi17_02 via ArangoError: forbidden
2017-11-17T21:55:36Z [9342] ERROR     at Route._handler (/usr/share/arangodb3/j
s/apps/system/_admin/aardvark/APP/aardvark.js:210:18)
2017-11-17T21:55:36Z [9342] ERROR     at next (/usr/share/arangodb3/js/server/m
odules/@arangodb/foxx/router/tree.js:412:15)
2017-11-17T21:55:36Z [9342] ERROR     at /usr/share/arangodb3/js/node/node_modu
les/lodash/lodash.js:10029:25
2017-11-17T21:55:36Z [9342] ERROR     at Middleware.authRouter.use (/usr/share/
arangodb3/js/apps/system/_admin/aardvark/APP/aardvark.js:99:3)
2017-11-17T21:55:36Z [9342] ERROR     at next (/usr/share/arangodb3/js/server/m
odules/@arangodb/foxx/router/tree.js:414:15)
2017-11-17T21:55:36Z [9342] ERROR     at next (/usr/share/arangodb3/js/server/m
odules/@arangodb/foxx/router/tree.js:410:7)
2017-11-17T21:55:36Z [9342] ERROR     at next (/usr/share/arangodb3/js/server/m
odules/@arangodb/foxx/router/tree.js:410:7)
2017-11-17T21:55:36Z [9342] ERROR     at next (/usr/share/arangodb3/js/server/m
odules/@arangodb/foxx/router/tree.js:410:7)
2017-11-17T21:55:36Z [9342] ERROR     at dispatch (/usr/share/arangodb3/js/serv
er/modules/@arangodb/foxx/router/tree.js:426:3)
2017-11-17T21:55:36Z [9342] ERROR     at Tree.dispatch (/usr/share/arangodb3/js
/server/modules/@arangodb/foxx/router/tree.js:135:7)
2017-11-17T21:55:59Z [9342] ERROR Service "/_admin/aardvark" encountered error 500 while handling GET http://srv.exascale.info:8529/_db/db2/_admin/aardvark/query/download/bdi17_02 via ArangoError: forbidden
2017-11-17T21:55:59Z [9342] ERROR     at Route._handler (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/aardvark.js:210:18)
2017-11-17T21:55:59Z [9342] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:412:15)
2017-11-17T21:55:59Z [9342] ERROR     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:10029:25
2017-11-17T21:55:59Z [9342] ERROR     at Middleware.authRouter.use (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/aardvark.js:99:3)
2017-11-17T21:55:59Z [9342] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:414:15)
2017-11-17T21:55:59Z [9342] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
2017-11-17T21:55:59Z [9342] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
2017-11-17T21:55:59Z [9342] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
2017-11-17T21:55:59Z [9342] ERROR     at dispatch (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:426:3)
2017-11-17T21:55:59Z [9342] ERROR     at Tree.dispatch (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:135:7)
```
arangod.log.supervisor
```sh
2017-11-17T19:30:20Z [28649] INFO {startup} waitpid woke up with return value 28650 and status 0 and DONE = true
2017-11-17T19:30:26Z [9341] INFO {startup} supervisor has forked a child process with pid 9342
2017-11-17T23:27:43Z [9341] INFO {startup} waitpid woke up with return value 9342 and status 9 and DONE = false
2017-11-17T23:27:43Z [9341] INFO {startup} child process 9342 terminated normally, exit status 9 (SIGKILL). will intentionally not start a new child process
```

**Comment by dothebart** [comment]
Hi, 
signal 9 is a forcefull kill signal to the process. Whoever issues it, *INTENDS* the process to die instantly without cleanup. 

Thus restarting it is not an option in this case. 

Did you check who sent this signal? do you see any output in dmesg? NB, you really should upgrade, lots of bugs have been fixed with 3.2.8.

**Comment by luav** [comment]
The only suspecting message in both `syslog` and `kernlog` is:
```
Nov 17 23:27:55 <server> kernel: [4572308.590850] do_IRQ: 0.197 No irq handler for vector (irq -1)
```
Nobody was logged in there and the server has not been rebooted:
```
$ top
top - 15:59:43 up 56 days, 13:56,  1 user,  load average: 0.00, 0.03, 0.05
Tasks: 185 total,   2 running, 183 sleeping,   0 stopped,   0 zombie
```
So, the process termination was caused either internally by some bug in ArangoDB or by the Linux kernel because of some issues with the arangodb process.


ArangoDB log:
```
2017-11-17T23:27:43Z [9341] INFO {startup} child process 9342 terminated normally, exit status 9 (SIGKILL). will intentionally not start a new child process
```
According to my understanding of the arandodb log, it says that the supervisor process is `9341`, the arangodb service process was `9342` and terminated with the exit status 9 (was killed).  
The questions are why the supervisor process does not start another service process, why the supervisor is completed/terminated and what is the completion/termination code of the supervisor?  
PS  You definitely should write less ambiguous and more clear logs. Probably, it makes sense to name the supervisor and arangodb service processes differently to clearly distinguish signals sent to the supervisor and service processes.

I ended up running ArangoDB under 2 supervisors: external and internal one, which is an ugly but the only gracefully working solution.

As for the ArangoDB version then it was installed a week ago as [specified in the ArangoDB website](https://www.arangodb.com/download-major/ubuntu/). It would be nice to install the latest stable version according to the website instructions out of the box...

**Comment by luav** [comment]
*Additional note:* some queries were very heavy and consumed all available RAM, which probably caused termination of the arangodb service process, but the arangodb supervisor is expected to recover the service process instead of just terminating it.

**Comment by dothebart** [comment]
Again, we don't send ourself a `SIGKILL` (which causes instant death of processes without any cleanup or shutdown - possibly data loss of non-sealed data), and whoever does send a `SIGKILL` whants the process to die instantly and not to respawn - else he would send a `SIGTERM`. For more details on signals please see https://en.wikipedia.org/wiki/Signal_(IPC) 

Since 3.2.8 brought a bunch of memory releated bugfixes, can you try to upgrade and see whether the error occurs again?

**Comment by luav** [comment]
I know the  meaning of nix signals and also have not sent any signals to ArangoDB and have not called the service termination.

DB is updated to 3.2.8. Thanks for the outlining this. The new logs will be shown in several days...

As for the 3.2.6 then the supervisor reported plenty of issues and looking at it's pid ([28649], etc.) the arangodb supervisor has been restarted several times without reporting the termination issues:
```sh
2017-11-17T19:30:15Z [28649] INFO {startup} received SIGINT for supervisor; commanding client [28650] to shut down.
2017-11-17T19:30:20Z [28649] INFO {startup} waitpid woke up with return value 28650 and status 0 and DONE = true
2017-11-17T19:30:26Z [9341] INFO {startup} supervisor has forked a child process with pid 9342
2017-11-17T23:27:43Z [9341] INFO {startup} waitpid woke up with return value 9342 and status 9 and DONE = false
2017-11-17T23:27:43Z [9341] INFO {startup} child process 9342 terminated normally, exit status 9 (SIGKILL). will intentionally not start a new child process
2017-11-18T07:13:18Z [26996] INFO {startup} supervisor has forked a child process with pid 26997
2017-11-19T15:56:25Z [26996] INFO {startup} waitpid woke up with return value 26997 and status 11 and DONE = false
2017-11-19T15:56:25Z [26996] ERROR {startup} child process 26997 terminated unexpectedly, signal 11 (SIGSEGV). will now start a new child process
2017-11-19T15:56:25Z [26996] INFO {startup} supervisor has forked a child proces
```

**Comment by dothebart** [comment]
ok, SIG_SEGV is better in terms of recovering, but still an indicator that somethings still wrong. 
can you enable core dumping and share the produced core file with us? 
(We've written up howto over at https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#linux-coredumps - just in case ;) )

**Comment by luav** [comment]
Sure. By the way, you should extend this manual with the following information:  
*Use `$ sudo sysctl -p` to apply the changes made in the `/etc/sysctl.conf` without the system restart.*

**Comment by dothebart** [comment]
added via https://github.com/arangodb/arangodb/pull/3770

**Comment by luav** [comment]
ArangoDB 3.8 consumes much less RAM than 3.6 and is much more robust! The internal supervisor has worked fine!

However, some service issues still occur with the service process, `arangod.log.supervisor`:
```
2017-11-23T16:40:01Z [21543] INFO {startup} waitpid woke up with return value 21544 and status 11 and DONE = false
2017-11-23T16:40:01Z [21543] ERROR {startup} child process 21544 terminated unexpectedly, signal 11 (SIGSEGV). will now start a new child process
2017-11-23T16:40:01Z [21543] INFO {startup} supervisor has forked a child process with pid 23579
```
Kernel dump was not generated and `syslog`, `kern.log` do not contain anything suspecting or relevant to ArangoDB.

 `arangod.log` for the time of the `SIGSEGV` reported above:
```
2017-11-23T16:39:54Z [21544] WARNING {queries} slow query: 'LET T = (\r\n FOR u
 IN users\r\n                SORT RAND()\r\n                LIMIT 2\r\n        
        RETURN  u._id\r\n)\r\n\r\nFOR target, unused, path \r\n    IN @depth OU
TBOUND "users/266202055575" friend_relations\r\n    OPTIONS {bfs: true, uniqueE
dges: "path",uniqueVertices: 'path'}\r\n  FILTER target._id == "users/266202059
033"\r\n  \r\n  RETURN path', bind vars: {"depth":6}, took: 71.712847
2017-11-23T16:40:01Z [23579] INFO ArangoDB 3.2.8 [linux] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.1f 6 Jan 2014
2017-11-23T16:40:01Z [23579] INFO using storage engine mmfiles
2017-11-23T16:40:01Z [23579] INFO {cluster} Starting up with role SINGLE
2017-11-23T16:40:01Z [23579] INFO {syscall} file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
2017-11-23T16:40:01Z [23579] INFO Authentication is turned on (system only), authentication for unix sockets is turned on
2017-11-23T16:40:01Z [23579] INFO running WAL recovery (1 logfiles)
2017-11-23T16:40:01Z [23579] INFO replaying WAL logfile '/var/lib/arangodb3/journals/logfile-266201426421.db' (1 of 1)
2017-11-23T16:40:01Z [23579] INFO WAL recovery finished successfully
```

**Comment by maxkernbach** [comment]
Hi @luav,

does this problem still occur in recent versions (3.2.11). Do you have a chance to test it?

Thanks

**Comment by luav** [comment]
Hi @maxkernbach, the crash occurred only on the high loading workflow, which physically happens here pretty seldom here (once or twice per year during 1-2 weeks).
However, you can and should perform the smoke (loading) tests internally before the stable release. Just import or generate the database of >= {5 K vertices, 100 K edges} and query it from a dozen(s) of concurrent clients using various heavy queries (including graph traversal queries) that consume several seconds of the processing time (to have simultaneously executing queries). It would correspond the case where that crashes occurred here.

**Comment by maxkernbach** [comment]
Thanks for the feedback, we will try to reproduce it.

**Comment by dothebart** [comment]
Hi, 
we did several load tests to try to reproduce your scenario, however ArangoDB didn't fail for us. 
If you can provide a coredump for such a situation it would be great, 
For now I will close this as can't reproduce.
