### ISSUE TITLE
Runtime error: distributeShardsLike pointing to an unknown collection

### ISSUE THREAD

**Issue by Gerrel** [arangodb/arangodb#3867]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser:safari     running on this OS: macosx
- [x] authentication is enabled?
- [x] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
0) deploy cluster
1) open the browser on http://127.0.0.1:8529
2) log in as root empty password
3) set password
4) create database with <name>
5) goto change database screen
6) select new database
7) error occurs:
...

The following problem occurs: 
{"error":true,"code":500,"errorNum":500,"errorMessage":"A runtime error occurred while executing an action\nArangoError: must not have a distributeShardsLike attribute pointing to an unknown collection\n    at getStorage (/usr/share/arangodb3/js/common/modules/@arangodb/foxx/manager-utils.js:59:14)\n    at Object.getServiceDefinition (/usr/share/arangodb3/js/common/modules/@arangodb/foxx/manager-utils.js:214:10)\n    at initLocalServiceMap (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:403:37)\n    at ensureFoxxInitialized (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:420:5)\n    at Object.getMountPoints [as _mountPoints] (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:967:3)\n    at buildRouting (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1055:33)\n    at Object.routeRequest (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1162:7)\n    at Function.callback (/usr/share/arangodb3/js/actions/api-system.js:54:15)"}

Instead I would be expecting: 
Dashboard page with new database selected.

Hitting refresh later on and the new database works as it should.

**Comment by Gerrel** [comment]
Solved: Reason was that my replicationFactor for dbservers was to high.

**Comment by dothebart** [comment]
Hi, 
I feel that we shouldn't close this now. 
You did some action on the webui which lead into an errneous state that the webui should eventually protect the user from running into. 

What was the consequence of the high replication factor? did database creation only take to long?

**Comment by Gerrel** [comment]
My docker swarm constraints we're not properly set. So the agency and primary we're put on the same host. Once that happens you get the replicationFactor warning in the console. Creating a database will result in that runtime error.
