### ISSUE TITLE
Internal failure: JavaScript exception in file 'arangosh.js' at 98,7: ArangoError 4: Expecting type String

### ISSUE THREAD

**Issue by yurivict** [arangodb/arangodb#4199]
Failed script:

```
db._query(' \
  FOR inst IN instructions \
    FILTER \
      inst NOT IN ( \
        FOR inst1 IN instructions \
          RETURN inst1.arg0 \
      ) \
      AND \
      inst._func IN ( \
        FOR c IN consts \
          FILTER c.str like "%i32 @close(i32)%" \
        RETURN c \
      ) \
    RETURN inst \
').toArray()
```

Error message:
```
JavaScript exception in file '/usr/local/share/arangodb/js/client/modules/@arangodb/arangosh.js' at 98,7: ArangoError 4: Expecting type String (while executing) (exception location: /wrkdirs/usr/ports/databases/arangodb32/work/arangodb-3.2.10/arangod/RestHandler/RestCursorHandler.cpp:134). Please report this error to arangodb.com
!      throw error;
!      ^
stacktrace: ArangoError: Expecting type String (while executing) (exception location: /wrkdirs/usr/ports/databases/arangodb32/work/arangodb-3.2.10/arangod/RestHandler/RestCursorHandler.cpp:134). Please report this error to arangodb.com
    at Object.exports.checkRequestResult (/usr/local/share/arangodb/js/client/modules/@arangodb/arangosh.js:96:21)
    at ArangoStatement.execute (/usr/local/share/arangodb/js/client/modules/@arangodb/arango-statement.js:174:12)
    at ArangoDatabase._query (/usr/local/share/arangodb/js/client/modules/@arangodb/arango-database.js:933:42)
    at <shell command>:1:4
```

Version 3.2.10

**Comment by jsteemann** [comment]
Fixed via https://github.com/arangodb/arangodb/pull/4200

**Comment by dothebart** [comment]
hint: in .js you can use backticks (\`) for multiline strings, you don't need the `\` then.

**Comment by yurivict** [comment]
> hint: in .js you can use backticks (`) for multiline strings, you don't need the \ then.

Thanks! I didn't know that.

**Comment by Simran-B** [comment]
BTW: AQL supports forward ticks, so that you can quote variable and collection names with forward ticks if needed, but still use the backticks in JavaScript for multi-line (template) strings.

https://docs.arangodb.com/3.3/AQL/Fundamentals/Syntax.html#names

```js
db._query(`
  FOR ´inst´ IN ´instructions´
    FILTER
      ´inst´ NOT IN (
        FOR ´inst1´ IN ´instructions´
          RETURN ´inst1´.´arg0´
      )
      AND
      ´inst´.´_func´ IN (
        FOR ´c´ IN ´consts´
          FILTER ´c´.´str´ like "%i32 @close(i32)%"
        RETURN ´c´
      )
    RETURN ´inst´
`).toArray()
```
(I added forward ticks for illustration purposes only, they are not actually needed for your query.)

Regarding template strings, have a look here: https://docs.arangodb.com/3.3/AQL/Invocation/WithArangosh.html#es6-template-strings

And in the NodeJS tutorial, under the Template Strings headline:
https://www.arangodb.com/tutorials/tutorial-node-js/

**Comment by yurivict** [comment]
Thanks!

**Comment by maxkernbach** [comment]
Version 3.3.2 containing the fix is released.
Please reopen this issue if the bug still occurs.

Thanks
