### ISSUE TITLE
inbound traversal and filtering on _to in edge databases seems broken in 3.3

### ISSUE THREAD

**Issue by sdrsdr** [arangodb/arangodb#4355]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

Mode:
- [x] Cluster

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb

### this is an AQL-related issue:
- [x] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS: Linux/Firefox 57.0.1

I got two vertex collections `usr` and `dev` and an edge collection `usr2dev` in them I have:
`RETURN  [DOCUMENT("dev/9837025"),DOCUMENT("usr/657"),DOCUMENT("usr2dev/9014950")]`
```
[
  [
    {
      "_key": "9837025",
      "_id": "dev/9837025",
      "_rev": "_WN6uc22--A",
      "type": "SHPLG-1"
    },
    {
      "_key": "657",
      "_id": "usr/657",
      "_rev": "_WN6uY86--_",
      "lang": "bg",
      "mail_notif_permissions": 1,
      "timezone": "Europe/Sofia"
    },
    {
      "_key": "9014950",
      "_id": "usr2dev/9014950",
      "_from": "usr/657",
      "_to": "dev/9837025",
      "_rev": "_WN7O6L---_",
      "role": 1
    }
  ]
]
```
The outbound traversal is working ok:
`with dev usr for d,e in outbound   DOCUMENT("usr/657") usr2dev return {d,eid:e._id}`
```
[
  {
    "d": {
      "_key": "9837025",
      "_id": "dev/9837025",
      "_rev": "_WN6uc22--A",
      "type": "SHPLG-1"
    },
    "eid": "usr2dev/9014950"
  }
]
```

inbound however fails to select any node:
`with usr dev for u in inbound   DOCUMENT("dev/9837025")  usr2dev  return {u}`
```
[]
```
Also the simple 
```
for e in usr2dev 
filter e._to=="dev/9837025"
return e
```
 results in `[]` the explain seems correct:

```
Query string:
 with usr2dev
 for e in usr2dev 
 filter e._to=="dev/9837025"
 return e
 

Execution plan:
 Id   NodeType        Site       Est.   Comment
  1   SingletonNode   DBS           1   * ROOT
  6   IndexNode       DBS          10     - FOR e IN usr2dev   /* edge index scan */
  9   RemoteNode      COOR         10       - REMOTE
 10   GatherNode      COOR         10       - GATHER 
  5   ReturnNode      COOR         10       - RETURN e

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields               Ranges
  6   edge   usr2dev      false    false            n/a   [ `_from`, `_to` ]   (e.`_to` == "dev/9837025")

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2
  4   scatter-in-cluster
  5   remove-unnecessary-remote-scatter

```

**Comment by jsteemann** [comment]
I have tried to reproduce the problem locally but to no avail.
I have also written a small test to trigger to problem, but it also passes and does not produce the error you reported.

Here is what I came up with:
```js
function simpleInboundOutboundSuite () {
  let db = require("@arangodb").db;
  const gn = 'UnitTestGraph';

  return {

    setUp: function () {
      db._drop(gn + 'v1');
      db._drop(gn + 'v2');
      db._drop(gn + 'e');

      let c;
      c = db._create(gn + 'v1');
      c.insert({ _key: "test" });

      c = db._create(gn + 'v2');
      c.insert({ _key: "test" });
     
      c = db._createEdgeCollection(gn + 'e');
      c.insert({ _from: gn + "v2/test", _to: gn + "v1/test" }); 
    },

    tearDown: function () {
      db._drop(gn + 'v1');
      db._drop(gn + 'v2');
      db._drop(gn + 'e');
    },

    testTheOldInAndOutOut: function () {
      let q = `WITH ${gn + 'v1'} ${gn + 'v2' } FOR v, e IN OUTBOUND DOCUMENT("${gn + 'v2'}/test") ${gn + 'e'} RETURN {v, e}`;
      let res = db._query(q).toArray()[0];

      assertEqual(gn + "v1/test", res.v._id);
      assertEqual("test", res.v._key);
      assertEqual(gn + "v2/test", res.e._from);
      assertEqual(gn + "v1/test", res.e._to);
    },

    testTheOldInAndOutIn: function () {
      let q = `WITH ${gn + 'v1'} ${gn + 'v2' } FOR v, e IN INBOUND DOCUMENT("${gn + 'v1'}/test") ${gn + 'e'} RETURN {v, e}`;
      let res = db._query(q).toArray()[0];

      assertEqual(gn + "v2/test", res.v._id);
      assertEqual("test", res.v._key);
      assertEqual(gn + "v2/test", res.e._from);
      assertEqual(gn + "v1/test", res.e._to);
    }

  };
}
```
I have started a cluster with the RocksDB storage engine using 3.3.2. 
I have tried single-shard collections and collections with different numbers of shards, but still cannot reproduce.
Is there anything special about the collections you have created? Can you share the collections' properties (i.e. the output of `db.<collection-name>.properties();`) and the indexes available for the collections (`db.<collection-name>.getIndexes();`)? Maybe there is something that is present in your setup that is not present in mine.
Thanks!

**Comment by sdrsdr** [comment]
Hi, I got some interesting results to share:
```
/var/run/arangodb3/arangod.socket@shelly> db._useDatabase('shelly')
true

/var/run/arangodb3/arangod.socket@shelly> db._collections() 
[ 
  [ArangoCollection 4010323, "_appbundles" (type document, status loaded)], 
  [ArangoCollection 5010059, "_apps" (type document, status loaded)], 
  [ArangoCollection 4010315, "_aqlfunctions" (type document, status loaded)], 
  [ArangoCollection 4010317, "_frontend" (type document, status loaded)], 
  [ArangoCollection 4010306, "_graphs" (type document, status loaded)], 
  [ArangoCollection 4010321, "_jobs" (type document, status loaded)], 
  [ArangoCollection 4010308, "_modules" (type document, status loaded)], 
  [ArangoCollection 4010319, "_queues" (type document, status loaded)], 
  [ArangoCollection 4010310, "_routing" (type document, status loaded)], 
  [ArangoCollection 9013027, "dev" (type document, status loaded)], 
  [ArangoCollection 9013028, "usr" (type document, status loaded)], 
  [ArangoCollection 9014677, "usr2dev" (type edge, status loaded)] 
]

/var/run/arangodb3/arangod.socket@shelly> db.dev
[ArangoCollection 9013027, "dev" (type document, status loaded)]

/var/run/arangodb3/arangod.socket@shelly> db.dev.properties()
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 98,7: ArangoError 11: cannot access dev
!      throw error;
!      ^
stacktrace: ArangoError: cannot access dev
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:96:21)
    at ArangoCollection.properties (/usr/share/arangodb3/js/client/modules/@arangodb/arango-collection.js:363:14)
    at <shell command>:1:8



/var/run/arangodb3/arangod.socket@shelly> db.dev.getIndexes()
[ 
  { 
    "fields" : [ 
      "_key" 
    ], 
    "id" : "dev/0", 
    "selectivityEstimate" : 1, 
    "sparse" : false, 
    "type" : "primary", 
    "unique" : true 
  } 
]

/var/run/arangodb3/arangod.socket@shelly> 
````

**Comment by sdrsdr** [comment]
This is from arangosh on a dedicated coordinator node

**Comment by sdrsdr** [comment]
OK! So when aranogsh connects to unix socket it assumes it will be able to "check" the files locally .. but in my case this is not really possible as the only thing local is the coordinator that holds not db files .. anyway
here is a properties  this time connecting over tcp:
```
127.0.0.1:8529@shelly> db.dev.properties()
{ 
  "doCompact" : true, 
  "journalSize" : 33554432, 
  "isSystem" : false, 
  "isVolatile" : false, 
  "waitForSync" : false, 
  "shardKeys" : [ 
    "_key" 
  ], 
  "numberOfShards" : 1, 
  "keyOptions" : { 
    "type" : "traditional", 
    "allowUserKeys" : true, 
    "lastValue" : 0 
  }, 
  "indexBuckets" : 8, 
  "replicationFactor" : 1 
}

127.0.0.1:8529@shelly> db.usr.properties()
{ 
  "doCompact" : true, 
  "journalSize" : 33554432, 
  "isSystem" : false, 
  "isVolatile" : false, 
  "waitForSync" : false, 
  "shardKeys" : [ 
    "_key" 
  ], 
  "numberOfShards" : 1, 
  "keyOptions" : { 
    "type" : "traditional", 
    "allowUserKeys" : true, 
    "lastValue" : 0 
  }, 
  "indexBuckets" : 8, 
  "replicationFactor" : 1 
}
db.usr2dev.properties()
{ 
  "doCompact" : true, 
  "journalSize" : 33554432, 
  "isSystem" : false, 
  "isVolatile" : false, 
  "waitForSync" : false, 
  "shardKeys" : [ 
    "_key" 
  ], 
  "numberOfShards" : 1, 
  "keyOptions" : { 
    "type" : "traditional", 
    "allowUserKeys" : true, 
    "lastValue" : 0 
  }, 
  "indexBuckets" : 8, 
  "replicationFactor" : 1 
}


127.0.0.1:8529@shelly> db.dev.getIndexes()
[ 
  { 
    "fields" : [ 
      "_key" 
    ], 
    "id" : "dev/0", 
    "selectivityEstimate" : 1, 
    "sparse" : false, 
    "type" : "primary", 
    "unique" : true 
  } 
]

127.0.0.1:8529@shelly> db.usr.getIndexes()
[ 
  { 
    "fields" : [ 
      "_key" 
    ], 
    "id" : "usr/0", 
    "selectivityEstimate" : 1, 
    "sparse" : false, 
    "type" : "primary", 
    "unique" : true 
  }, 
  { 
    "deduplicate" : false, 
    "fields" : [ 
      "email" 
    ], 
    "id" : "usr/9018106", 
    "selectivityEstimate" : 1, 
    "sparse" : false, 
    "type" : "hash", 
    "unique" : false 
  } 
]

127.0.0.1:8529@shelly> db.usr2dev.getIndexes()
[ 
  { 
    "fields" : [ 
      "_key" 
    ], 
    "id" : "usr2dev/0", 
    "selectivityEstimate" : 1, 
    "sparse" : false, 
    "type" : "primary", 
    "unique" : true 
  }, 
  { 
    "fields" : [ 
      "_from", 
      "_to" 
    ], 
    "id" : "usr2dev/1", 
    "sparse" : false, 
    "type" : "edge", 
    "unique" : false 
  } 
]

127.0.0.1:8529@shelly> db._query('with dev usr for d,e in outbound DOCUMENT("usr/657") usr2dev return {d,eid:e._id}');
[object ArangoQueryCursor, count: 1, cached: false, hasMore: false]


[ 
  { 
    "d" : { 
      "_key" : "9837025", 
      "_id" : "dev/9837025", 
      "_rev" : "_WN6uc22--A", 
      "created_tstamp" : "2017-12-15T18:01:48.000Z", 
      "type" : "SHPLG-1" 
    }, 
    "eid" : "usr2dev/9014950" 
  } 
]



127.0.0.1:8529@shelly> db._query('with usr dev for u in inbound DOCUMENT("dev/9837025") usr2dev return {u}');
[object ArangoQueryCursor, count: 0, cached: false, hasMore: false]



127.0.0.1:8529@shelly> 
```

**Comment by jsteemann** [comment]
I am still struggling to reproduce the original locally. What exact version of ArangoDB are you using?

**Comment by sdrsdr** [comment]
This is strange .. I still got this problem with 3.3.2 it might be some problems with server setup .. the agency is in separated processes and are using mmfiles, the coordinators also use mmfiles but the primary nodes use rocksdb can this be the thing causing problems?

**Comment by sdrsdr** [comment]
@jsteemann if you're interested I can provide you with access to our cluster to have a look at what I've done wrong

**Comment by jsteemann** [comment]
@sdrsdr: I think at least the coordinators and DB servers should use the same storage engine.
Which storage engine the agency is probably not relevant here, but there may be issues if coordinators and DB servers use different types of engines. Can you make these components use the same engine, and check if that fixes the issue? It's probably easier to change the storage engine of the coordinator.

**Comment by sdrsdr** [comment]
it's a "pilot error": As I got the coordinators set to use rocksdb  as the dbservers everything is back to normal. @jsteemann  Thanks for your support and patience to help solve this issue.

I can strongly recommend to put a warning of some kind in the interface or in the logs when the cluster is using mixed engines as this can almost work but not quite

**Comment by jsteemann** [comment]
Thanks for confirming. Yes, I also think it makes much sense to issue an error in case the storage engines are not the same. Will open an internal issue for this.
