### ISSUE TITLE
expect.js missing from Debian packages

### ISSUE THREAD

**Issue by alfalfasprossen** [arangodb/arangodb#4471]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

On this operating system:
- [ ] Linux 
  - [x] Debian .deb

## The Problem

The same problem occurs in 3.2 and 3.3, with both, Debian 8 and Debian 9, installing through apt-get.

```bash
echo 'deb https://www.arangodb.com/repositories/arangodb33/Debian_9.0/ /' | sudo tee /etc/apt/sources.list.d/arangodb.list
sudo apt-get install -y apt-transport-https
sudo apt-get install -y arangodb3=3.3.3
```

When requiring `chai` in foxx tests, the exception `ArangoError: cannot locate module` is raised when it tries to import `expect`.

```
ERROR File: /usr/share/arangodb3/js/node/node_modules/chai/lib/chai.js                                                                                                                    
ERROR     at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:556:11)                                                                                                     
ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:484:16)                                                                                           
ERROR     at require (/usr/share/arangodb3/js/common/bootstrap/modules.js:95:21)                                                                                                          
ERROR     at Object.<anonymous> (/usr/share/arangodb3/js/node/node_modules/chai/index.js:1:272)                                                                                           
ERROR     at Module._compile (/usr/share/arangodb3/js/common/bootstrap/modules.js:598:8)                                                                                                  
ERROR     at Object.Module._extensions..js (/usr/share/arangodb3/js/common/bootstrap/modules.js:616:12)                                                                                   
ERROR     at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:539:36)                                                                                                     
ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:484:16)                                                                                           
ERROR     at require (/usr/share/arangodb3/js/common/bootstrap/modules.js:95:21)                                                                                                          
ERROR     at Object.<anonymous> (/var/lib/arangodb3-apps/_db/datahub/sample_repository/locations/APP/tests/test_locations.js:3:1) via ArangoError: cannot locate module                   
ERROR File: ./chai/interface/expect                                                                                                                                                       
ERROR     at Function.Module._resolveFilename (/usr/share/arangodb3/js/common/bootstrap/modules.js:520:13)                                                                                
ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:439:27)                                                                                           
ERROR     at require (/usr/share/arangodb3/js/common/bootstrap/modules.js:95:21)                                                                                                          
ERROR     at Object.<anonymous> (/usr/share/arangodb3/js/node/node_modules/chai/lib/chai.js:78:14)                                                                                        
ERROR     at Module._compile (/usr/share/arangodb3/js/common/bootstrap/modules.js:598:8)                                                                                                  
ERROR     at Object.Module._extensions..js (/usr/share/arangodb3/js/common/bootstrap/modules.js:616:12)                                                                                   
ERROR     at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:539:36)                                                                                                     
ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:484:16)                                                                                           
ERROR     at require (/usr/share/arangodb3/js/common/bootstrap/modules.js:95:21)                                                                                                          
ERROR     at Object.<anonymous> (/usr/share/arangodb3/js/node/node_modules/chai/index.js:1:272)                                                                                           
```

The file `/usr/share/arangodb3/js/node/node_modules/chai/lib/chai/interface/expect.js` does not exist. Yet, telling from the repository it should be there: https://github.com/arangodb/arangodb/tree/v3.3.3/js/node/node_modules/chai/lib/chai/interface

Manually copying the `expect.js` file into the respective folder will fix the issue.

Might this be a bug in the debian packages?

**Comment by dothebart** [comment]
This issue was due to problems on building the Macos X Bundle package.
This has been resolved with 3.3.6, we now ship expect.js.
Thanks for reporting, closing this now.
