### ISSUE TITLE
ClusterComm::performRequests: got no answer from shard

### ISSUE THREAD

**Issue by kishorel** [arangodb/arangodb#4724]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
-  3.2.9

Mode:
-  Cluster

Storage-Engine:

- rocksdb

On this operating system:
- Linux 
   - RedHat .rpm
  
I'm issuing AQL via:
- this Driver: arangodb java driver 4.3.3

We have a three node Arangodb Cluster having 3 dbservers, 3 agents and 3 coordinatiors on each machine. Each collection having 3 shards and replication factor being 2. This setup worked for us over a month and there after started seeing issues related to shards,saying **_got no answer from shard_**

Please find the logs for the detail.

> 2018-02-28T10:39:17Z [76588] WARNING catch error in historian: ArangoError: AQL: A cluster backend which was required for the operation could not be reached (while optimizing plan)\n    at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:81:16)\n    at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:94:45)\n    at lastEntry (/usr/share/arangodb3/js/server/modules/@arangodb/statistics.js:106:19)\n    at Object.exports.historian (/usr/share/arangodb3/js/server/modules/@arangodb/statistics.js:451:19)\n    at eval (eval at <anonymous> (unknown source), <anonymous>:3:54)\n    at eval (eval at <anonymous> (unknown source), <anonymous>:3:70)

and there after i could see below logs.

> 2018-02-28T12:41:55Z [76769] ERROR {cluster} ClusterComm::performRequests: **got no answer from shard:s14298**:/_db/UDB/_api/collection/s14298/count with error 4
2018-02-28T12:41:55Z [76769] WARNING {queries} slow query: _**'_FOR doc IN @@collection  RETURN doc', bind vars: {"@collection":"_routing"}, took: 120.000369_**_
2018-02-28T12:41:58Z [76769] WARNING {queries} slow query: 'FOR doc IN @@collection  RETURN doc', bind vars: {"@collection":"_routing"}, took: 120.000349
2018-02-28T12:41:58Z [76769] ERROR {cluster} ClusterComm::performRequests: **got no answer from shard:s14298**:/_db/UDB/_api/collection/s14298/count with error 4
2018-02-28T12:41:58Z [76769] WARNING {queries} slow query: 'FOR doc IN @@collection  RETURN doc', bind vars: {"@collection":"_routing"}, took: 119.999786
2018-02-28T12:41:58Z [76769] ERROR {cluster} ClusterComm::performRequests: **got no answer from shard:s14298**:/_db/UDB/_api/collection/s14298/count with error 4
2018-02-28T12:41:58Z [76769] WARNING {queries} slow query: 'FOR doc IN @@collection  RETURN doc', bind vars: {"@collection":"_routing"}, took: 120.000284
2018-02-28T12:42:02Z [76769] ERROR {cluster} ClusterComm::performRequests: **got no answer from shard:s14298**:/_db/UDB/_api/collection/s14298/count with error 4

And from application server, i found this.

> 01/03/18 10:45:33.157 - ERROR [taskExecutor-20] - c.g.u.a.d.ArangoDBOperations.updateUserDuringLogin(576) - Exception occured while updating user : 7462621 during login
com.arangodb.ArangoDBException: Response: 500, Error: 500 - A runtime error occurred while executing an action
ArangoError: AQL: A cluster backend which was required for the operation could not be reached (while optimizing plan)
   at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:81:16)
   at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:80:45)
   at SimpleQueryAll.execute (/usr/share/arangodb3/js/server/modules/@arangodb/simple-query.js:96:42)
   at SimpleQueryAll.SimpleQuery.hasNext (/usr/share/arangodb3/js/common/modules/@arangodb/simple-query-common.js:395:8)
   at buildRouting (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1041:14)
   at Object.routeRequest (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1162:7)
   at Function.callback (/usr/share/arangodb3/js/actions/api-system.js:54:15)
       at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:53)
       at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:116)
       at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:143)
       at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:48)
       at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:100)
       at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:47)
       at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)
       at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:63)
       at com.arangodb.ArangoVertexCollection.updateVertex(ArangoVertexCollection.java:192)
       at com.games24x7.userrelationservice.arango.db.ArangoDBOperations.updateUserDuringLogin(ArangoDBOperations.java:569)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
       at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
       at net.bull.javamelody.MonitoringSpringInterceptor.invoke(MonitoringSpringInterceptor.java:76)
       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
       at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
       at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
       at com.games24x7.userrelationservice.service.UserIdentityService$$EnhancerBySpringCGLIB$$dce28493.login(<generated>)
       at com.games24x7.userrelationservice.mq.MessageHandler.handleLogin(MessageHandler.java:113)
       at com.games24x7.userrelationservice.mq.MessageHandler.handleLoginAndReg(MessageHandler.java:89)
       at com.games24x7.userrelationservice.mq.MessageHandler.onMessage(MessageHandler.java:73)
       at org.springframework.amqp.rabbit.listener.adapter.MessageListenerAdapter.onMessage(MessageListenerAdapter.java:282)
       at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1414)
       at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1337)
       at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1324)
       at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1303)

Could you please explain on which all cases we might get this kind of error.From the logs, i couldn't get any other clue.

The slow_query highlighted in Italic and Bold seems to be internal server query, i wonder why it is taking 120 sec.Also other AQL queries from the application  takes >30sec than usual  time which was in millisec.

We have restarted each coordinator one by one, still the issue was not resolved,then we have  restarted the each node meaning agent,coordinator and dbserver on each node by using **_arangodb_** utility.Then the issue got resolved. 

Please let us know the reason for the issue and suggestions if any to avoid this in future. Also let us know if Arangodb 3.3 will help us in this. Any help would be appreciated.  

-Thanks.

**Comment by arijeetsaha** [comment]
Arango queries used in the above application -

GET -

FOR doc IN @@collection FILTER doc._to == @value COLLECT WITH COUNT INTO length RETURN length

UPDATE -

FOR u in  @@collectionName FILTER u._key == @id UPDATE { _key: @id, lastUpdatedAt: @lastUpdatedAt, noOfAssociation: u.noOfAssociation + 1} IN  @@collectionName  RETURN NEW.noOfAssociation

Please let us know if there is any issue in the above queries.

**Comment by kishorel** [comment]
Hi,

The same issue had been there in 3.1.10, and seems to be fixed which is tracked under below mentioned thread. But we could see similar issue here in 3.2.9

https://github.com/arangodb/arangodb/issues/2231

Please do let us know if this has been fixed permanently.

**Comment by arijeetsaha** [comment]
HI,

Please update on this. Kind of urgent.

-Arijeet

**Comment by kishorel** [comment]
Hi,

Anyone to help us???  This is kind of blocking.

Upgrading to 3.3.4 will solve the issue???

Any help would be appreciated.

-Thanks.

**Comment by dothebart** [comment]
Hi, 
sorry for the late reply. 
Please have a look at [explain](https://docs.arangodb.com/3.3/AQL/ExecutionAndPerformance/Optimizer.html); In order to fix performance penalties you need to strive to reduce the amount of hops that are executed in the cluster, and reduce the number of documents that have to be sent from the DB-Servers to the coordinator by fixing filters & indices available.

**Comment by dothebart** [comment]
Hi, 
ArangoDB 3.7 is Available for download:
https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
closing this as outdated.
