### ISSUE TITLE
Arangodb Coordinators - stuck in  UNKNOWN SyncState and Status GOOD, can't be removed

### ISSUE THREAD

**Issue by calinah** [arangodb/arangodb#4815]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x ] 3.3
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: My cluster is setup up with 3 coordinators but on the UI I can see 6 of them (seems like some coordinators were restarted or temporarily lost, new ones were created and arangodb picked the new ones up but didn't clean the old ones). The old coordinators show Status:GOOD but SyncStatus:UNKNOWN and the CanBeDeleted flag is set to _false_ therefore I cannot clean them up:
<img width="1675" alt="screen shot 2018-03-09 at 18 01 25" src="https://user-images.githubusercontent.com/22074573/37280025-7e0e3e82-25e4-11e8-9395-51d83fbec82f.png">
<img width="1664" alt="screen shot 2018-03-09 at 18 01 39" src="https://user-images.githubusercontent.com/22074573/37280072-9dda5db8-25e4-11e8-8229-d5ad42d3aaa4.png">

Instead I would be expecting: 
For the old nodes to be marked as Unhealthy and with the CanBeDeleted flag set to _true_.

Describe which steps you carried out, what you expected to happen and what actually happened:
1. Described the cluster health using Postman:
<img width="1019" alt="screen shot 2018-03-12 at 11 03 19" src="https://user-images.githubusercontent.com/22074573/37280200-065c5bca-25e5-11e8-8b65-ec8e13b66837.png">
2. When attempting to delete the Coordinators with UNKNOWN state I get the following:
<img width="687" alt="screen shot 2018-03-12 at 11 04 43" src="https://user-images.githubusercontent.com/22074573/37280311-5525e4ec-25e5-11e8-88c2-8905929feba2.png">

Is there any other way to delete these nodes? We are being flooded with error messages due to this.

**Comment by danielhlarkin** [comment]
Hi @calinah, a quick question first: are all six coordinator instances still up and reachable on the specified endpoints? That is, can you connect to them, e.g. with `arangosh`?

**Comment by calinah** [comment]
Hi @danielhlarkin - no so only 3 out of the 6 coordinators exist - as an additional test I've attempted connecting to the ones that no longer exist but I can see on the UI (the ones with SyncStatus UNKNOWN) and I get:
```
Pretty printing values.
Could not connect to endpoint 'http+tcp://10.24.13.24:8529', database: '_system', username: 'root'
Error message: 'Could not connect to 'http+tcp://10.24.13.24:8529' 'connect() failed with #113 - No route to host''
```

**Comment by calinah** [comment]
I'm also getting these errors/ warnings in the agency related to the mentioned Coordinators:
```
2018-03-14T18:12:03.285496051Z 2018-03-14T18:12:03Z [27] WARNING {agency} Malformed object-type precondition was ignored: key: "/arango/Supervision/Health/CRDN-8a5baf01-0297-4b82-9141-6636a0b59edf" value: {"op":"delete"}
2018-03-14T18:12:03.285533884Z 2018-03-14T18:12:03Z [27] ERROR {supervision} Expecting type String /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/Agency/Supervision.cpp 636
```

**Comment by danielhlarkin** [comment]
@calinah Thanks for the clarification. I'll look into this and see if I can figure out what's going on.

**Comment by kvahed** [comment]
Hi @calinah,
could you please do an agency dump for us? I'd love to debug this situation as it does look like a bug I thought was fixed for good. 
`curl <agent-ip:port>/_api/agency/read -sLd'[["/"]]'`
Thx in advance.

**Comment by calinah** [comment]
[agency.txt](https://github.com/arangodb/arangodb/files/1814955/agency.txt)

Hi @kvahed I've attached the agency dump - sorry for the messy doc.

Furthermore I was playing around attempting to figure it out the issue yesterday I decided to delete another coordinator pod (managed through helm chart so a new one was created straight away). So the new coordinator pod came up but it didn't register in the cluster - rather the old coordinator that was removed still shows as serving and working (both on the UI and if I run GET localhost:8529/_admin/cluster/health). The logs of the new coordinator look like this: 
```
2018-03-14T17:51:42.642004117Z 2018-03-14T17:51:42Z [28] INFO {cluster} using heartbeat interval value '1000 ms' from agency
2018-03-14T17:51:43.181514519Z 2018-03-14T17:51:43Z [28] INFO using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
2018-03-14T17:51:45.470002824Z 2018-03-14T17:51:45Z [28] INFO bootstrapped coordinator CRDN-d99ea25a-7253-4637-89c3-ed1414b89843
2018-03-14T17:51:45.470042984Z 2018-03-14T17:51:45Z [28] INFO ArangoDB (version 3.3.3 [linux]) is ready for business. Have fun!
2018-03-14T17:58:13.294325925Z 2018-03-14T17:58:13Z [28] ERROR {cluster} did not find endpoint of server 'CRDN-13ccbd96-8737-4057-a899-0e33048cf643'
2018-03-14T17:58:13.294984569Z 2018-03-14T17:58:13Z [28] ERROR {cluster} cannot create connection to server 'CRDN-13ccbd96-8737-4057-a899-0e33048cf643' at endpoint ''
2018-03-14T17:58:13.344310474Z 2018-03-14T17:58:13Z [28] WARNING {v8} Caught an error while executing an action: JavaScript exception in file '/usr/share/arangodb3/js/actions/api-cluster.js' at 366,32: ArangoError 4: couldn't queue async request\n!    var op = ArangoClusterComm.asyncRequest('GET', 'server:' + serverId, req.database,\n!                               ^\nstacktrace: ArangoError: couldn't queue async request\n    at Function.callback (/usr/share/arangodb3/js/actions/api-cluster.js:366:32)\n
2018-03-14T18:08:57.681011494Z 2018-03-14T18:08:57Z [28] WARNING {heartbeat} Heartbeat: Could not read from agency! status code: 0, incriminating body: , timeout: 1
2018-03-14T19:35:36.696069359Z 2018-03-14T19:35:36Z [28] WARNING {heartbeat} Heartbeat: Could not read from agency! status code: 0, incriminating body: , timeout: 1
2018-03-14T20:16:06.440683969Z 2018-03-14T20:16:06Z [28] WARNING {heartbeat} Heartbeat: Could not read from agency! status code: 0, incriminating body: , timeout: 1
2018-03-14T21:40:58.345187437Z 2018-03-14T21:40:58Z [28] WARNING {heartbeat} Heartbeat: Could not read from agency! status code: 0, incriminating body: , timeout: 1
2018-03-15T01:21:48.51466276Z 2018-03-15T01:21:48Z [28] WARNING {heartbeat} Heartbeat: Could not read from agency! status code: 0, incriminating body: , timeout: 1
2018-03-15T04:02:58.815602527Z 2018-03-15T04:02:58Z [28] WARNING {heartbeat} Heartbeat: Could not read from agency! status code: 0, incriminating body: , timeout: 1
2018-03-15T04:04:18.887746221Z 2018-03-15T04:04:18Z [28] WARNING {heartbeat} Heartbeat: Could not read from agency! status code: 0, incriminating body: , timeout: 1
2018-03-15T06:30:46.587513211Z 2018-03-15T06:30:46Z [28] WARNING {heartbeat} Heartbeat: Could not read from agency! status code: 0, incriminating body: , timeout: 1
2018-03-15T10:32:38.606026097Z 2018-03-15T10:32:38Z [28] WARNING {heartbeat} Heartbeat: Could not read from agency! status code: 0, incriminating body: , timeout: 1
2018-03-15T10:39:06.012073684Z 2018-03-15T10:39:06Z [28] ERROR {cluster} did not find endpoint of server 'CRDN-b63296d5-64e7-4359-8174-894e2f191a8e'
2018-03-15T10:39:06.012232701Z 2018-03-15T10:39:06Z [28] ERROR {cluster} did not find endpoint of server 'CRDN-b63296d5-64e7-4359-8174-894e2f191a8e'
2018-03-15T10:39:06.012289661Z 2018-03-15T10:39:06Z [28] ERROR {cluster} cannot create connection to server 'CRDN-b63296d5-64e7-4359-8174-894e2f191a8e' at endpoint ''
2018-03-15T10:39:06.012963195Z 2018-03-15T10:39:06Z [28] ERROR {cluster} cannot create connection to server 'CRDN-b63296d5-64e7-4359-8174-894e2f191a8e' at endpoint ''
2018-03-15T10:39:06.086235909Z 2018-03-15T10:39:06Z [28] WARNING {v8} Caught an error while executing an action: JavaScript exception in file '/usr/share/arangodb3/js/actions/api-cluster.js' at 308,32: ArangoError 4: couldn't queue async request\n!    var op = ArangoClusterComm.asyncRequest('GET', 'server:' + serverId, req.database,\n!                               ^\nstacktrace: ArangoError: couldn't queue async request\n    at Function.callback (/usr/share/arangodb3/js/actions/api-cluster.js:308:32)\n
2018-03-15T10:39:06.086373776Z 2018-03-15T10:39:06Z [28] WARNING {v8} Caught an error while executing an action: JavaScript exception in file '/usr/share/arangodb3/js/actions/api-cluster.js' at 250,32: ArangoError 4: couldn't queue async request\n!    var op = ArangoClusterComm.asyncRequest('GET', 'server:' + serverId, req.database,\n!                               ^\nstacktrace: ArangoError: couldn't queue async request\n    at Function.callback (/usr/share/arangodb3/js/actions/api-cluster.js:250:32)\n
```
Furthermore even though the new coordinator is not officially recognised by the cluster I can `kubectl exec` into it and run commands such as `curl` to get cluster health(using the IP of the coordinator itself) or connect through `arangosh` to the  cluster and run commands against it.

**Comment by calinah** [comment]
Hiya @kvahed @danielhlarkin have you managed to look further into this? Or do you have any suggestions for fixing the issue?

**Comment by calinah** [comment]
Hiya,

Is this still being analysed? It would be good to receive an update @kvahed @danielhlarkin @sleto-it . Thank you.

**Comment by chriswessels** [comment]
We're seeing this issue, any update?

**Comment by dothebart** [comment]
Hi, 
The used ArangoDB version 3.3 has reached EOL. 
We have put much efforts into improving ArangoDB clustering; Please find the results in the [Arangodb 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model) release.

Closing as outdated.
