### ISSUE TITLE
Unable to import custom file using relative path in foxx

### ISSUE THREAD

**Issue by dilipvamsi** [arangodb/arangodb#5485]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [x] other: manjaro
- [ ] Windows, version: 
- [ ] MacOS, version:

### Foxx

I have written the validator file which uses **joi** internally in **api/validate.js** seems to be working on all my input and output example test cases.
Rest of the code is auto generated using foxx-cli.
But when I'm trying to import in **api/event_handler.js** I'm getting the following error.
Is there a problem with the relative import with foxx.

My project tree
```
.
├── api
│   ├── event_handler.js
│   └── validate.js
├── index.js
├── manifest.json
├── README.md
├── scripts
└── test
```
event_handler.js
```js
'use strict';

const joi = require('joi');
const createRouter = require('@arangodb/foxx/router');

const router = createRouter();
module.exports = router;

const validate = require('./validate');

router.use((req, res, next) => {
  // Manipulate req here before it is handled by a route
  // e.g. req.session = {}
  next();
  // Manipulate res here after it was handled by a route
  // e.g. res.set('x-session-id', 'keyboardcat')
});

router.post('/', (req, res) => {
  res.send({
    is_successful: true
  });
  // Handle the request and generate the response
})
.body(validate.eventSchema.required(), 'the request body')
.response(200, validate.eventResponseSchema.required(), 'the response body');

```

Errors from /var/log/arangodb3/arangod.log
```
2018-05-29T13:28:12Z [674] ERROR Service "/event-handler" encountered an error while being mounted @ /var/lib/arangodb3-apps/_db/test-db/event-handler/APP/api/event_handler.js:9:18
2018-05-29T13:28:12Z [674] ERROR    7 | module.exports = router;
2018-05-29T13:28:12Z [674] ERROR    8 | 
2018-05-29T13:28:12Z [674] ERROR >  9 | const validate = require('./validate');
2018-05-29T13:28:12Z [674] ERROR      |                  ^
2018-05-29T13:28:12Z [674] ERROR   10 | 
2018-05-29T13:28:12Z [674] ERROR   11 | router.use((req, res, next) => {
2018-05-29T13:28:12Z [674] ERROR   12 |   // Manipulate req here before it is handled by a route via ArangoError: failed to invoke module
2018-05-29T13:28:12Z [674] ERROR File: /var/lib/arangodb3-apps/_db/test-db/event-handler/APP/api/validate.js
2018-05-29T13:28:12Z [674] ERROR Line: 233
2018-05-29T13:28:12Z [674] ERROR Column: 0
2018-05-29T13:28:12Z [674] ERROR     at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:559:11)
2018-05-29T13:28:12Z [674] ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:487:16)
2018-05-29T13:28:12Z [674] ERROR     at require (/usr/share/arangodb3/js/common/bootstrap/modules.js:98:21)
2018-05-29T13:28:12Z [674] ERROR     at Object.<anonymous> (/var/lib/arangodb3-apps/_db/test-db/event-handler/APP/api/event_handler.js:9:18)
2018-05-29T13:28:12Z [674] ERROR     at Module._compile (/usr/share/arangodb3/js/common/bootstrap/modules.js:601:8)
2018-05-29T13:28:12Z [674] ERROR     at Object.Module._extensions..js (/usr/share/arangodb3/js/common/bootstrap/modules.js:619:12)
2018-05-29T13:28:12Z [674] ERROR     at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:542:36)
2018-05-29T13:28:12Z [674] ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:487:16)
2018-05-29T13:28:12Z [674] ERROR     at require (/usr/share/arangodb3/js/common/bootstrap/modules.js:98:21)
2018-05-29T13:28:12Z [674] ERROR     at Object.<anonymous> (/var/lib/arangodb3-apps/_db/test-db/event-handler/APP/index.js:3:38) via SyntaxError: Unexpected token export
2018-05-29T13:28:12Z [674] ERROR     at Module._compile (/usr/share/arangodb3/js/common/bootstrap/modules.js:595:23)
2018-05-29T13:28:12Z [674] ERROR     at Object.Module._extensions..js (/usr/share/arangodb3/js/common/bootstrap/modules.js:619:12)
2018-05-29T13:28:12Z [674] ERROR     at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:542:36)
2018-05-29T13:28:12Z [674] ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:487:16)
2018-05-29T13:28:12Z [674] ERROR     at require (/usr/share/arangodb3/js/common/bootstrap/modules.js:98:21)
2018-05-29T13:28:12Z [674] ERROR     at Object.<anonymous> (/var/lib/arangodb3-apps/_db/test-db/event-handler/APP/api/event_handler.js:9:18)
2018-05-29T13:28:12Z [674] ERROR     at Module._compile (/usr/share/arangodb3/js/common/bootstrap/modules.js:601:8)
2018-05-29T13:28:12Z [674] ERROR     at Object.Module._extensions..js (/usr/share/arangodb3/js/common/bootstrap/modules.js:619:12)
2018-05-29T13:28:12Z [674] ERROR     at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:542:36)
2018-05-29T13:28:12Z [674] ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:487:16)
2018-05-29T13:28:12Z [674] ERROR @ /var/lib/arangodb3-apps/_db/test-db/event-handler/APP/api/event_handler.js:9:18
2018-05-29T13:28:12Z [674] ERROR    7 | module.exports = router;
2018-05-29T13:28:12Z [674] ERROR    8 |
2018-05-29T13:28:12Z [674] ERROR >  9 | const validate = require('./validate');
2018-05-29T13:28:12Z [674] ERROR      |                  ^
2018-05-29T13:28:12Z [674] ERROR   10 |
2018-05-29T13:28:12Z [674] ERROR   11 | router.use((req, res, next) => {
2018-05-29T13:28:12Z [674] ERROR   12 |   // Manipulate req here before it is handled by a route ArangoError 3103: failed to invoke module
2018-05-29T13:28:12Z [674] ERROR File: /var/lib/arangodb3-apps/_db/test-db/event-handler/APP/api/validate.js
2018-05-29T13:28:12Z [674] ERROR Line: 233
2018-05-29T13:28:12Z [674] ERROR Column: 0
2018-05-29T13:28:12Z [674] ERROR     at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:559:11)
2018-05-29T13:28:12Z [674] ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:487:16)
2018-05-29T13:28:12Z [674] ERROR     at require (/usr/share/arangodb3/js/common/bootstrap/modules.js:98:21)
2018-05-29T13:28:12Z [674] ERROR     at Object.<anonymous> (/var/lib/arangodb3-apps/_db/test-db/event-handler/APP/api/event_handler.js:9:18)
2018-05-29T13:28:12Z [674] ERROR     at Module._compile (/usr/share/arangodb3/js/common/bootstrap/modules.js:601:8)
2018-05-29T13:28:12Z [674] ERROR     at Object.Module._extensions..js (/usr/share/arangodb3/js/common/bootstrap/modules.js:619:12)
2018-05-29T13:28:12Z [674] ERROR     at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:542:36)
2018-05-29T13:28:12Z [674] ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:487:16)
2018-05-29T13:28:12Z [674] ERROR     at require (/usr/share/arangodb3/js/common/bootstrap/modules.js:98:21)
2018-05-29T13:28:12Z [674] ERROR     at Object.<anonymous> (/var/lib/arangodb3-apps/_db/test-db/event-handler/APP/index.js:3:38) via SyntaxError: Unexpected token export
2018-05-29T13:28:12Z [674] ERROR     at Module._compile (/usr/share/arangodb3/js/common/bootstrap/modules.js:595:23)
2018-05-29T13:28:12Z [674] ERROR     at Object.Module._extensions..js (/usr/share/arangodb3/js/common/bootstrap/modules.js:619:12)
2018-05-29T13:28:12Z [674] ERROR     at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:542:36)
2018-05-29T13:28:12Z [674] ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:487:16)
2018-05-29T13:28:12Z [674] ERROR     at require (/usr/share/arangodb3/js/common/bootstrap/modules.js:98:21)
2018-05-29T13:28:12Z [674] ERROR     at Object.<anonymous> (/var/lib/arangodb3-apps/_db/test-db/event-handler/APP/api/event_handler.js:9:18)
2018-05-29T13:28:12Z [674] ERROR     at Module._compile (/usr/share/arangodb3/js/common/bootstrap/modules.js:601:8)
2018-05-29T13:28:12Z [674] ERROR     at Object.Module._extensions..js (/usr/share/arangodb3/js/common/bootstrap/modules.js:619:12)
2018-05-29T13:28:12Z [674] ERROR     at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:542:36)
2018-05-29T13:28:12Z [674] ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:487:16)
```

Thanks,
Dilip Vamsi.

**Comment by dilipvamsi** [comment]
Hi @pluma ,
Any update on this, we are planning on using foxx for creating few micro services that are needed for faster access to db.
Thanks,
Dilip Vamsi.

**Comment by pluma** [comment]
Could you please check what's in validate.js on line 233? The log indicates the require is failing because of some error on that line. I agree that "failed to invoke module" is a bit unclear but it generally means the require resulted in an error that couldn't be properly handled.

**Comment by dilipvamsi** [comment]
Hi @pluma ,
I'm not sure as I'm able to import the validate.js in node and this only depends on 'joi'

Thanks,
Dilip Vamsi.

**Comment by pluma** [comment]
Node.js and ArangoDB are not identical. Without knowing what's on line 233 of that file (as well as the lines around it) I can't do anything but guess.

**Comment by dilipvamsi** [comment]
I'll look into it.
Thanks
