### ISSUE TITLE
Foxx rest PUT request application/zip returns 500 Internal Server Error

### ISSUE THREAD

**Issue by valrak** [arangodb/arangodb#5736]
## My Environment

* __ArangoDB Version__:        3.3.11
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Configuration__:               nothing special
* __Infrastructure__:               Docker
* __Operating System__:        Ubuntu 18.04
* __Used Package__:             Docker - official Docker library

## Component, Query & Data

__Affected feature__:
Foxx REST service

__Dataset__:
Clean database

## Steps to reproduce

1. Reproducible also with clean database.
2. [foxxPUT.zip](https://github.com/arangodb/arangodb/files/2154431/foxxPUT.zip) contains postZip.py which will call PUT on http://localhost:8529/_db/_system/_api/foxx/service and tries to upload test.zip file (included) with params: "mount": "/test", "force": "true"
3. replace address / port / username / password in the script, run.
4. Server responds with error 500

__Problem__:
```
PUT service returns 500 Internal Server Error.
In arango log:
2018-07-02T08:21:04Z [1] ERROR Service "/_api/foxx" encountered error 500 while handling PUT http://localhost:8529/_db/_system/_api/foxx/service?mount=%2Ftest&force=true via Error: end cannot be longer than parent.length
2018-07-02T08:21:04Z [1] ERROR     at exports.isZipBuffer (/usr/share/arangodb3/js/common/modules/@arangodb/util.js:221:45)
2018-07-02T08:21:04Z [1] ERROR     at _prepareService (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:540:9)
2018-07-02T08:21:04Z [1] ERROR     at Object.replace (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:884:21)
2018-07-02T08:21:04Z [1] ERROR     at serviceRouter.put (/usr/share/arangodb3/js/apps/system/_api/foxx/APP/index.js:188:15)
2018-07-02T08:21:04Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/route.js:53:24)
2018-07-02T08:21:04Z [1] ERROR     at prepareServiceRequestBody (/usr/share/arangodb3/js/apps/system/_api/foxx/APP/index.js:82:3)
2018-07-02T08:21:04Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/route.js:47:28)
2018-07-02T08:21:04Z [1] ERROR     at Route._handler (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/route.js:57:11)
2018-07-02T08:21:04Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:412:15)
2018-07-02T08:21:04Z [1] ERROR     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:10029:25
```
Zip file works when uploaded in Web interface.

__Expected result__:
PUT service returns 200 OK and Foxx microservice published to arangodb.

**Comment by vinaypyati** [comment]
I confirm that this issue is reproducible on Windows with ArangoDB version 3.3.11. On executing the script provided, the server responds with `500 Internal Server Error
{"error":true,"errorNum":500,"errorMessage":"Internal Server Error","code":500}`

The console errors reported are 
```
2018-07-11T12:37:10Z [19072] ERROR Service "/_api/foxx" encountered error 500 while handling PUT http://localhost:8529/_db/_system/_api/foxx/service?mount=%2Ftest&force=true via Error: end cannot be longer than parent.length
2018-07-11T12:37:10Z [19072] ERROR     at exports.isZipBuffer (c:\Users\Vinay\Downloads\ArangoDB3-3.3.11-1_win64\usr\share\arangodb3\js\common\modules\@arangodb\util.js:221:45)
2018-07-11T12:37:10Z [19072] ERROR     at _prepareService (c:\Users\Vinay\Downloads\ArangoDB3-3.3.11-1_win64\usr\share\arangodb3\js\server\modules\@arangodb\foxx\manager.js:540:9)
2018-07-11T12:37:10Z [19072] ERROR     at Object.replace (c:\Users\Vinay\Downloads\ArangoDB3-3.3.11-1_win64\usr\share\arangodb3\js\server\modules\@arangodb\foxx\manager.js:884:21)
2018-07-11T12:37:10Z [19072] ERROR     at serviceRouter.put (C:\Users\Vinay\Downloads\ArangoDB3-3.3.11-1_win64\usr\share\arangodb3\js\apps\system\_api\foxx\APP\index.js:188:15)
2018-07-11T12:37:10Z [19072] ERROR     at next (c:\Users\Vinay\Downloads\ArangoDB3-3.3.11-1_win64\usr\share\arangodb3\js\server\modules\@arangodb\foxx\router\route.js:53:24)
2018-07-11T12:37:10Z [19072] ERROR     at prepareServiceRequestBody (C:\Users\Vinay\Downloads\ArangoDB3-3.3.11-1_win64\usr\share\arangodb3\js\apps\system\_api\foxx\APP\index.js:82:3)
2018-07-11T12:37:10Z [19072] ERROR     at next (c:\Users\Vinay\Downloads\ArangoDB3-3.3.11-1_win64\usr\share\arangodb3\js\server\modules\@arangodb\foxx\router\route.js:47:28)
2018-07-11T12:37:10Z [19072] ERROR     at Route._handler (c:\Users\Vinay\Downloads\ArangoDB3-3.3.11-1_win64\usr\share\arangodb3\js\server\modules\@arangodb\foxx\router\route.js:57:11)
2018-07-11T12:37:10Z [19072] ERROR     at next (c:\Users\Vinay\Downloads\ArangoDB3-3.3.11-1_win64\usr\share\arangodb3\js\server\modules\@arangodb\foxx\router\tree.js:412:15)
2018-07-11T12:37:10Z [19072] ERROR     at c:\Users\Vinay\Downloads\ArangoDB3-3.3.11-1_win64\usr\share\arangodb3\js\node\node_modules\lodash\lodash.js:10029:25
```

**Comment by pluma** [comment]
See #5844 for a fix of the 500 error. I'm pretty sure the 500 error is masking the underlying problem.

**Comment by pluma** [comment]
@valrak The Python script passes the file as a field called `upload_file`. Foxx expects the field to be called `source`. The 500 error you're seeing is the result of Foxx trying to determine whether the non-existent source field is a zip buffer, which fails due to a bug.

You need to adjust the name of the file field to make this work. The bug only results in an incorrect error message.

**Comment by valrak** [comment]
@pluma 
Like this? `files = {'source': open('test.zip','rb')}`
Because when i tried it with source instead of upload_file, I still get the same error.

**Comment by pluma** [comment]
It's definitely a problem with how you're doing the upload. I recall someone else having run into this problem in Python as well but I'm not well-versed enough with the libraries to tell you what the code should look like.

**Comment by valrak** [comment]
I've actually had a problem in the python script, updated version here: [testPutV2.zip](https://github.com/arangodb/arangodb/files/2196696/testPutV2.zip)

Now I get: 
```
400 Bad Request
{"error":true,"errorNum":3101,"errorMessage":"syntax error in module\nFile: /tmp/arangod_VVW5k8/services-tmp-1-4191344740/index.js","code":400}
```
The same test.zip file works when uploaded in arangodb webinterface.

**Comment by pluma** [comment]
@valrak you mentioned a 400 error about a syntax error. This usually indicates the file is not recognized as a zip file and thus assumed to be a bare JS file. As you're not hitting the "isZipBuffer" bug this probably means the source is no longer empty but still not the zip file you're trying to pass through.

Upon re-reading the ticket, I'm a bit confused: it looks like your Python code is setting a MIME type of `application/zip` but not submitting the zip file itself as the request body but instead submitting form data (i.e. a `multipart/form-data` request body but with a MIME type indicating it's a raw zip file rather than a form).

I'd recommend running your script against https://httpbin.org/post (via https://httpbin.org) to determine what's going on with your request body.

**Comment by pluma** [comment]
I've tracked down the `requests` documentation and it confirms my suspicion: the `files` parameter is for multipart forms: http://docs.python-requests.org/en/master/user/quickstart/#post-a-multipart-encoded-file

I think you can pass the file as a byte string via the `data` parameter if you really want to upload via `application/zip` type: http://docs.python-requests.org/en/master/user/quickstart/#more-complicated-post-requests

But the easiest solution is probably to just use `multipart/form-data` because that's what `requests` is for. The raw formats (`application/zip` and `application/javascript`) are mostly intended to help avoid the overhead of multipart encoding when you don't have access to libraries like `requests` to handle that logic for you.

**Comment by valrak** [comment]
@pluma 
Yes,  you are correct, thank you for your support.

**Comment by maxkernbach** [comment]
Hi @valrak,

can we consider this issue as solved or do you have any further questions?

**Comment by valrak** [comment]
Hello @maxkernbach,

Issue is solved. Thanks!
