### ISSUE TITLE
Resuming replication, memory usage and server crash

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#6821]
* __ArangoDB Version__:        3.3.16 (both instances)
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Master/Slave
* __Infrastructure__:               own
* __Operating System__:        Debian 9.5 (master) Ubuntu 16.04 (slave)
* __Used Package__:              Debian .deb / Ubuntu 16.04 .deb

## Component, Query & Data

__Affected feature__:
Continuous replication.

__Dataset__:
14 collections, the biggest having 20 000 000 docs.

## Steps to reproduce

1. Create a database / user on the slave instance

2. Setup a continuous replication using arangosh:
```
require("@arangodb/replication").applier.forget();

require("@arangodb/replication").setupReplication({
  endpoint: "tcp://my.master.host:8529",
  username: "root",
  password: "my_password",
  verbose: true,
  includeSystem: false,
  incremental: true,
  autoResync: true
});
```

3. Wait for initial sync to finish and continuous replication to start. Everything works fine.

4. Stop replication (to be honest, it crashed because of #6738 but that should not change anything).

5. Wait a few days and restart slave server. Restart continuous replication; master has now 10 000 000 more documents in the biggest collection.

6. Wait and watch the slave's memory usage and logs, here's what happens.
```
2018-10-11T10:49:16 [25228] INFO {replication} fetching master state
2018-10-11T10:49:16 [25228] DEBUG connecting to ip endpoint 'http+tcp://my.master.host:8529'
2018-10-11T10:49:16 [25228] INFO {replication} connected to master at tcp://my.master.host:8529, id 237929824883104, version 3.3, last log tick 835695461
2018-10-11T10:49:16 [25228] INFO {replication} sending WAL flush command to url /_admin/wal/flush
2018-10-11T10:49:16 [25228] INFO {replication} sending batch start command to url /_api/replication/batch?serverId=133901239271719
2018-10-11T10:49:16 [25228] INFO {replication} fetching master inventory from /_api/replication/inventory?serverId=133901239271719&batchId=91903119
2018-10-11T10:49:16 [25228] INFO {replication} starting phase validate with 14 collections
2018-10-11T10:49:16 [25228] INFO {replication} starting phase drop-create with 14 collections

-- doing some stuff on many small collections

2018-10-11T10:49:17 [25228] INFO {replication} dumping data for collection 'queries', type document, id 48935
2018-10-11T10:49:17 [25228] INFO {replication} fetching collection keys for collection 'queries' from /_api/replication/keys/keys?collection=hD8655AB191A0%2F48935&to=835695461&serverId=133901239271719&batchId=91903119
2018-10-11T10:49:17 [25228] INFO {replication} collecting local keys for collection 'queries'
2018-10-11T10:49:17 [25228] INFO {replication} fetching remote keys chunks for collection 'queries' from /_api/replication/keys/91903119?chunkSize=5000
2018-10-11T10:49:25 [25228] INFO {replication} processing keys chunk 0 for collection 'queries'
2018-10-11T10:49:26 [25228] INFO {replication} processing keys chunk 1 for collection 'queries'
2018-10-11T10:49:26 [25228] INFO {replication} processing keys chunk 2 for collection 'queries'

-- fast processing of already existing keys chunks 

2018-10-11T10:49:31 [25228] INFO {replication} processing keys chunk 2091 for collection 'queries'
2018-10-11T10:49:31 [25228] INFO {replication} fetching keys chunk 2091 from /_api/replication/keys/91903119?type=keys&chunk=2091&chunkSize=5000&low=10010455001
2018-10-11T10:49:32 [25228] INFO {replication} fetching documents chunk 2091 (374 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2091&chunkSize=5000&low=10010455001&offset=0
2018-10-11T10:49:32 [25228] INFO {replication} processing keys chunk 2092 for collection 'queries'
2018-10-11T10:49:32 [25228] INFO {replication} fetching keys chunk 2092 from /_api/replication/keys/91903119?type=keys&chunk=2092&chunkSize=5000&low=10010460001
2018-10-11T10:49:32 [25228] INFO {replication} fetching documents chunk 2092 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2092&chunkSize=5000&low=10010460001&offset=0

-- getting new chunks from the master. Slave memory usage starts to increase. Eventually RAM ans Swap both get full. Last log entries are

2018-10-11T11:09:38 [25228] INFO {replication} sending batch extend command to url /_api/replication/batch/91903119?serverId=133901239271719
2018-10-11T11:09:38 [25228] INFO {replication} processing keys chunk 2227 for collection 'queries'
2018-10-11T11:09:38 [25228] INFO {replication} fetching keys chunk 2227 from /_api/replication/keys/91903119?type=keys&chunk=2227&chunkSize=5000&low=10011135001
2018-10-11T11:09:38 [25228] INFO {replication} fetching documents chunk 2227 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2227&chunkSize=5000&low=10011135001&offset=0

 -- then nothing
```

In arangosh where the replication was restarted, we can see:
```
-- replication triggering, everything goes fine, until

still synchronizing... last received status: 2018-10-11T09:08:51Z: fetching documents chunk 2225 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2225&chunkSize=5000&low=10011125001&offset=3646
still synchronizing... last received status: 2018-10-11T09:09:00Z: fetching documents chunk 2226 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2226&chunkSize=5000&low=10011130001&offset=0
still synchronizing... last received status: 2018-10-11T09:09:00Z: fetching documents chunk 2226 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2226&chunkSize=5000&low=10011130001&offset=0
still synchronizing... last received status: 2018-10-11T09:09:14Z: fetching documents chunk 2226 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2226&chunkSize=5000&low=10011130001&offset=1880
still synchronizing... last received status: 2018-10-11T09:09:14Z: fetching documents chunk 2226 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2226&chunkSize=5000&low=10011130001&offset=1880
still synchronizing... last received status: 2018-10-11T09:09:29Z: fetching documents chunk 2226 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2226&chunkSize=5000&low=10011130001&offset=3724
still synchronizing... last received status: 2018-10-11T09:09:38Z: fetching documents chunk 2227 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2227&chunkSize=5000&low=10011135001&offset=0
still synchronizing... last received status: 2018-10-11T09:09:38Z: fetching documents chunk 2227 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2227&chunkSize=5000&low=10011135001&offset=0
still synchronizing... last received status: 2018-10-11T09:09:38Z: fetching documents chunk 2227 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2227&chunkSize=5000&low=10011135001&offset=0
still synchronizing... last received status: 2018-10-11T09:09:38Z: fetching documents chunk 2227 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2227&chunkSize=5000&low=10011135001&offset=0
still synchronizing... last received status: 2018-10-11T09:09:38Z: fetching documents chunk 2227 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2227&chunkSize=5000&low=10011135001&offset=0
still synchronizing... last received status: 2018-10-11T09:09:38Z: fetching documents chunk 2227 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2227&chunkSize=5000&low=10011135001&offset=0
still synchronizing... last received status: 2018-10-11T09:09:38Z: fetching documents chunk 2227 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2227&chunkSize=5000&low=10011135001&offset=0
still synchronizing... last received status: 2018-10-11T09:09:38Z: fetching documents chunk 2227 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2227&chunkSize=5000&low=10011135001&offset=0
still synchronizing... last received status: 2018-10-11T09:09:38Z: fetching documents chunk 2227 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2227&chunkSize=5000&low=10011135001&offset=0

-- last chunks retrieval is repeated many times, this corresponds to the moment when the slave memory is getting really full, including Swap

still synchronizing... last received status: 2018-10-11T09:09:38Z: fetching documents chunk 2227 (5000 keys) for collection 'queries' from /_api/replication/keys/91903119?type=docs&chunk=2227&chunkSize=5000&low=10011135001&offset=0

JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/replication.js' at 230,7: ArangoError 2001: Connection closed by remote
!      throw err;
!      ^
stacktrace: ArangoError: Connection closed by remote
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:97:21)
    at waitForResult (/usr/share/arangodb3/js/client/modules/@arangodb/replication.js:228:16)
    at setup (/usr/share/arangodb3/js/client/modules/@arangodb/replication.js:331:10)
    at Object.setupReplication (/usr/share/arangodb3/js/client/modules/@arangodb/replication.js:334:51)
    at <shell command>:1:34
```

At this time, slave server "crashes" in a strange way… process disappears but systemctl says "active (exited)"

Systemctl output:
```
sudo systemctl status arangodb3
● arangodb3.service - LSB: arangodb
   Loaded: loaded (/etc/init.d/arangodb3; bad; vendor preset: enabled)
   Active: active (exited) since jeu. 2018-10-11 10:47:44 CEST; 25min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 25054 ExecStop=/etc/init.d/arangodb3 stop (code=exited, status=0/SUCCESS)
  Process: 25069 ExecStart=/etc/init.d/arangodb3 start (code=exited, status=0/SUCCESS)
```

ps output:
```
ps aux | grep arangod
plantnet 25429  0.0  0.0  14264   908 pts/1    S+   11:12   0:00 grep --color=auto arangod
```

__Problems__:
1. Memory usage when catching up with the master increases a lot
2. When running out of memory, arangod seems to hang in a strange way (not informing systemctl); but maybe this is normal

__Expected result__:
Although the slave has "only" 16 GB RAM and 1 GB swap (I know, this is too little) and it has to catch up with 10 000 000 documents which is huge, maybe the replication algorithm could have a memory-saving strategy so that it can catch up with any number of docs ?
For example save the master's chunks on disk before processing them, or process them directly as they arrive then free memory ?

Note that when restarting server and restarting replication, the chunks retrieval restarts at the previous checkpoint, in this case 2091, thus the problem happens again indefinitely and is not solvable unless we buy more RAM / extend Swap size

Thanks a lot for considering this
Mathias

**Comment by matcho** [comment]
Additional information: I'm currently trying to resume a replication from the same master to another slave, a much bigger machine.

At the moment the replication process has retrieved around 5 000 000 documents (half the total docs to retrieve) and it already consumed around 100 GB of RAM…

**Comment by sleto-it** [comment]
@matcho hi, thanks for opening this bug report

it has been fixed and the fix will be available in next 3.3 hotfix (3.3.18)

We will notify you when 3.3.18 will be published

thanks,

**Comment by matcho** [comment]
Hi @sleto-it 

Yesterday I noticed the 3.3.18 release on GitHub "releases" panel, and the availability of the Ubuntu 16.04 package.
I tried updating and resuming my replication (same as above), and the same issue occurred, memory exhaustion and crash…

Maybe I was too much in a hurry and the 3.3.18 package I installed was not finalized ?

**Comment by matcho** [comment]
OK thank you !

**Comment by sleto-it** [comment]
Hi,

Thanks again for opening this issue

Versions 3.3.19 has been released and it includes a fix for this problem (note that there was no public 3.3.18 - the next release after 3.3.17 is 3.3.19)

I am closing this ticket now. Please feel free to comment if the issue persists

Many thanks,
