### ISSUE TITLE
java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.

### ISSUE THREAD

**Issue by wqxcloud** [arangodb/arangodb#7890]
## My Environment

* __ArangoDB Version__:  3.4.0      
* __Storage Engine__:  RocksDB           
* __Deployment Mode__:  default     
* __Deployment Strategy__: default  
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:  CentOS 7.6.1810      
* __Used Package__:   Linux version 3.10.0-693.2.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Tue Sep 12 22:26:13 UTC 2017
[root@xu arangodb3]# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core) 
Release:	7.6.1810
Codename:	Core
           

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:

dateString=2019-01-06 18:00:28
18:00:33.178 logback [pool-11-thread-1] ERROR c.a.i.v.internal.MessageStore - Reached the end of the stream.
java.io.IOException: Reached the end of the stream.
	at com.arangodb.internal.velocystream.internal.VstConnection.readBytesIntoBuffer(VstConnection.java:262)
	at com.arangodb.internal.velocystream.internal.VstConnection.readBytes(VstConnection.java:254)
	at com.arangodb.internal.velocystream.internal.VstConnection.readChunk(VstConnection.java:231)
	at com.arangodb.internal.velocystream.internal.VstConnection$1.call(VstConnection.java:141)
	at com.arangodb.internal.velocystream.internal.VstConnection$1.call(VstConnection.java:124)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-4" com.arangodb.ArangoDBException: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
	at com.arangodb.internal.velocystream.internal.VstConnectionSync.write(VstConnectionSync.java:100)
	at com.arangodb.internal.velocystream.VstCommunicationSync.send(VstCommunicationSync.java:140)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:126)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:42)
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:132)
	at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:47)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:63)
	at com.arangodb.internal.ArangoCollectionImpl.updateDocument(ArangoCollectionImpl.java:207)
	at com.arangodb.springframework.core.template.ArangoTemplate.update(ArangoTemplate.java:440)
	at com.arangodb.springframework.core.template.ArangoTemplate.update(ArangoTemplate.java:453)
	at com.dowa.service.impl.UserServiceImpl.updateUserStatusInfo(UserServiceImpl.java:313)
	at com.dowa.InItApplicationRunner.processMessage(InItApplicationRunner.java:114)
	at com.dowa.InItApplicationRunner.access$1(InItApplicationRunner.java:99)
	at com.dowa.InItApplicationRunner$2.run(InItApplicationRunner.java:77)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.

__Expected result__:

**Comment by maxkernbach** [comment]
Hi @wqxcloud,

Could you please provide more details on this issue? When did this error occur? Is it reproducible? In case it is, can you share a script (I assume you are using the ArangoDB Java driver)?

The error `Reached the end of the stream` is almost always a sign that the server is not reachable anymore. You should check if you can access the ArangoDB webUI the time your program runs into this error.

**Comment by maxkernbach** [comment]
Hi @wqxcloud,

could you please reply to the latest comment?
We would like to investigate your issue, but require more details.

**Comment by maxkernbach** [comment]
@wqxcloud 

Since we have not heard back from you in a while, I am closing this issue for now.
In case the problem persists, please provide further details and we would be glad to investigate it.

**Comment by kaizensn** [comment]
I have a similar issue, I get it when I try to save a big json (>2Mb).
Our DB is deployed on oasis, I added log on the below 
com.arangodb.ArangoDBException: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
	at com.arangodb.internal.velocystream.internal.VstConnectionSync.write(VstConnectionSync.java:100) ~[arangodb-java-driver-6.16.0.jar:na]
	at com.arangodb.internal.velocystream.VstCommunicationSync.send(VstCommunicationSync.java:164) ~[arangodb-java-driver-6.16.0.jar:na]
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:142) ~[arangodb-java-driver-6.16.0.jar:na]
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:45) ~[arangodb-java-driver-6.16.0.jar:na]
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:149) ~[arangodb-java-driver-6.16.0.jar:na]
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:144) ~[arangodb-java-driver-6.16.0.jar:na]
	at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:46) ~[arangodb-java-driver-6.16.0.jar:na]
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71) ~[arangodb-java-driver-6.16.0.jar:na]
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:57) ~[arangodb-java-driver-6.16.0.jar:na]
	at com.arangodb.internal.ArangoDatabaseImpl.query(ArangoDatabaseImpl.java:171) ~[arangodb-java-driver-6.16.0.jar:na]
	at com.arangodb.springframework.core.template.ArangoTemplate.query(ArangoTemplate.java:358) ~[arangodb-spring-data-3.7.0.jar:3.7.0]
	at com.arangodb.springframework.core.template.ArangoTemplate.query(ArangoTemplate.java:346) ~[arangodb-spring-data-3.7.0.jar:3.7.0]
	at com.arangodb.springframework.core.template.ArangoTemplate.repsert(ArangoTemplate.java:694) ~[arangodb-spring-data-3.7.0.jar:3.7.0]
	at com.arangodb.springframework.repository.SimpleArangoRepository.save(SimpleArangoRepository.java:74) ~[arangodb-spring-data-3.7.0.jar:3.7.0]

**Comment by dothebart** [comment]
English please.

**Comment by dothebart** [comment]
And please use the Oasis helpdesk if you're an Oasis customer.
