### ISSUE TITLE
Apache Spark failed to write edges into ArangoDB - Reached the end of the stream.

### ISSUE THREAD

**Issue by alexyzhou** [arangodb/arangodb#8046]
## My Environment

* __ArangoDB Version__:        3.4
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster (3 nodes)
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               /bin/arangodb --server.storage-engine=rocksdb --starter.data-dir=/var/lib/arangodb3/data --starter.join 10.0.1.202,10.0.1.209,10.0.1.60 --server.threads 16
* __Infrastructure__:               AWS
* __Operating System__:        CentOS
* __Total RAM in your machine__:        16GB
* __Disks in use__:        SSD
* __Used Package__:              rpm

## Component, Query & Data

__Affected feature__:
arangodb-spark-connector

__Dataset__:
Graph Data with 97,720,325 nodes and more than 250 million edges

__Replication Factor & Number of Shards (Cluster only)__:
Number of shards: 9
Replication Factor: 1

## Steps to reproduce

1.     ArangoSpark.save(allEdges.toJSON, collection = "mio_edges", options = writeOptions)
2. 
3. 

__Problem__:
When write nodes, the spark job works file and all nodes are inserted.
When write edges, the spark have the following error:
Caused by: java.io.IOException: Reached the end of the stream.
	at com.arangodb.internal.velocystream.internal.VstConnection.readBytesIntoBuffer(VstConnection.java:262)
	at com.arangodb.internal.velocystream.internal.VstConnection.readBytes(VstConnection.java:254)
	at com.arangodb.internal.velocystream.internal.VstConnection.readChunk(VstConnection.java:231)
	at com.arangodb.internal.velocystream.internal.VstConnection$1.call(VstConnection.java:141)
	... 5 more

And only 12,517,132 edge(s) are inserted. It turns out every attempt will fail at around such number 

__Expected result__:
The edge insertion should finish without errors.

**Comment by alexyzhou** [comment]
A rapid response is appreciated.

**Comment by alexyzhou** [comment]
The hardware spec is: 3 machines with 4 Cores CPU, 16GB Memory each

**Comment by alexyzhou** [comment]
UPDATE: it turns out the arangodb-spark-connector will use the RDD's default partition number to write to edges. And the arangodb crashed due to OOM. If you dig into the code, you can see spark uses insertDocuments to write the edges, which leads to data volume too large for each batch:
        col.insertDocuments(map(p).toList.asJava)

Hence after I change the code:
ArangoSpark.save(allEdges.toJSON, collection = "mio_edges", options = writeOptions)

to:
ArangoSpark.save(allEdges.toJSON.repartition(20000), collection = "mio_edges", options = writeOptions)

The write can pass without issues. However, here the partition number [20000] is a magic number. 

I am thinking whether arangodb has any guidance or limit on the max number of documents that can be inserted per batch by insertDocuments? Then I can calculate a partition number based on the batch size limit.

Thanks.

**Comment by BCaxelbecker** [comment]
@alexyzhou to use the function "toJSON.repartition(X)" is the right way to handle this problem. we dont know the size of one message and so we cant create a correct package for you. 

the max package size for the arango driver is "LONG_BYTES = Long.SIZE / Byte.SIZE"

**Comment by maxkernbach** [comment]
Hi @alexyzhou,

does BCaxelbecker's latest message answer your question, are we set to close this issue?

**Comment by alexyzhou** [comment]
Yes, please close the issue. Thanks

**Comment by josephsahayaraj** [comment]
ArangoSpark is failing with below exception : 
20/06/25 15:50:42 WARN scheduler.TaskSetManager: Lost task 1492.0 in stage 1.0 (TID 3690, datanode1, executor 1): com.arangodb.ArangoDBException: Response: 500, Error: 4 - internal error
	at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:52)
	at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:141)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:126)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:40)
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:124)
	at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:46)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:61)
	at com.arangodb.internal.ArangoCollectionImpl.insertDocuments(ArangoCollectionImpl.java:70)
	at com.arangodb.internal.ArangoCollectionImpl.insertDocuments(ArangoCollectionImpl.java:62)
	at com.arangodb.spark.ArangoSpark$$anonfun$saveRDD$1.apply(ArangoSpark.scala:127)
	at com.arangodb.spark.ArangoSpark$$anonfun$saveRDD$1.apply(ArangoSpark.scala:121)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2113)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2113)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$11.apply(Executor.scala:407)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:413)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by dothebart** [comment]
Hi, please don't resurect old issues. I think this is what you also reported at  https://github.com/arangodb/arangodb/issues/11993 ?
