### ISSUE TITLE
Coordinator Error

### ISSUE THREAD

**Issue by e-moshaya** [arangodb/arangodb#8086]
## My Environment

* __ArangoDB Version__:        3.4.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               
* __Infrastructure__:                AWS
* __Operating System__:        Amazon Linux 2
* __Total RAM in your machine__:        3 x nodes in cluster 4GB RAM each
* __Disks in use__:        SSD
* __Used Package__:              RedHat .rpm
## Component, Query & Data

We have deployed a cluster of Arangodb 3.4.1 using starter for all three nodes with a coordinator, agent and dbserver running in each of the three nodes. We stop the cluster every night to save on AWS costs and start them up each morning. This morning, I noticed one of the nodes in the cluster had errors in the coordinator logs. Please see below:

```
2019-02-01T09:54:42Z [15785] ERROR {cluster} cannot create connection to server: 'PRMR-f60af7f4-57b7-4107-b220-d64ef66fd8ee' at endpoint tcp://10.1.1.2:8530', timeout: 2.000000
2019-02-01T09:54:42Z [15785] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s3010038:/_db/_system/_api/document?collection=s3010038&waitForSync=false&returnNew=false&returnOld=false&isRestore=false&overwrite=false
2019-02-01T09:55:18Z [15785] ERROR {cluster} cannot create connection to server: 'PRMR-f60af7f4-57b7-4107-b220-d64ef66fd8ee' at endpoint tcp://10.1.1.2:8530', timeout: 2.000000
2019-02-01T09:55:18Z [15785] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s3010022:/_db/_system/_api/document/s3010022/4010640?waitForSync=false&ignoreRevs=false&isRestore=false&mergeObjects=true
2019-02-01T09:55:18Z [15785] ERROR Job 4010640 failed:
2019-02-01T09:55:18Z [15785] ERROR ArangoError: service not found
2019-02-01T09:55:18Z [15785] ERROR Mount path: "/heartbeat".
2019-02-01T09:55:18Z [15785] ERROR     at reloadInstalledService (/var/lib/arangodb3/cluster/coordinator8529/data/js/server/modules/@arangodb/foxx/manager.js:477:11)
2019-02-01T09:55:18Z [15785] ERROR     at getServiceInstance (/var/lib/arangodb3/cluster/coordinator8529/data/js/server/modules/@arangodb/foxx/manager.js:457:15)
2019-02-01T09:55:18Z [15785] ERROR     at Object.runScript (/var/lib/arangodb3/cluster/coordinator8529/data/js/server/modules/@arangodb/foxx/manager.js:952:17)
2019-02-01T09:55:18Z [15785] ERROR     at Object.exports.work (/var/lib/arangodb3/cluster/coordinator8529/data/js/server/modules/@arangodb/foxx/queues/worker.js:126:17)
2019-02-01T09:55:18Z [15785] ERROR     at eval (eval at <anonymous> (unknown source), <anonymous>:8:59)
2019-02-01T09:55:18Z [15785] ERROR     at eval (eval at <anonymous> (unknown source), <anonymous>:11:17)
2019-02-01T09:55:18Z [15785] ERROR     at eval (eval at <anonymous> (unknown source), <anonymous>:11:29)
2019-02-01T09:56:19Z [15785] ERROR Job 4010640 failed:
2019-02-01T09:56:19Z [15785] ERROR ArangoError: service not found
2019-02-01T09:56:19Z [15785] ERROR Mount path: "/heartbeat".
2019-02-01T09:56:19Z [15785] ERROR     at reloadInstalledService (/var/lib/arangodb3/cluster/coordinator8529/data/js/server/modules/@arangodb/foxx/manager.js:477:11)
2019-02-01T09:56:19Z [15785] ERROR     at getServiceInstance (/var/lib/arangodb3/cluster/coordinator8529/data/js/server/modules/@arangodb/foxx/manager.js:457:15)
2019-02-01T09:56:19Z [15785] ERROR     at Object.runScript (/var/lib/arangodb3/cluster/coordinator8529/data/js/server/modules/@arangodb/foxx/manager.js:952:17)
2019-02-01T09:56:19Z [15785] ERROR     at Object.exports.work (/var/lib/arangodb3/cluster/coordinator8529/data/js/server/modules/@arangodb/foxx/queues/worker.js:126:17)
2019-02-01T09:56:19Z [15785] ERROR     at eval (eval at <anonymous> (unknown source), <anonymous>:8:59)
2019-02-01T09:56:19Z [15785] ERROR     at eval (eval at <anonymous> (unknown source), <anonymous>:11:17)
2019-02-01T09:56:19Z [15785] ERROR     at eval (eval at <anonymous> (unknown source), <anonymous>:11:29)
2019-02-01T09:57:19Z [15785] ERROR Job 4010640 failed:
2019-02-01T09:57:19Z [15785] ERROR ArangoError: service not found
2019-02-01T09:57:19Z [15785] ERROR Mount path: "/heartbeat".
2019-02-01T09:57:19Z [15785] ERROR     at reloadInstalledService (/var/lib/arangodb3/cluster/coordinator8529/data/js/server/modules/@arangodb/foxx/manager.js:477:11)
2019-02-01T09:57:19Z [15785] ERROR     at getServiceInstance (/var/lib/arangodb3/cluster/coordinator8529/data/js/server/modules/@arangodb/foxx/manager.js:457:15)
2019-02-01T09:57:19Z [15785] ERROR     at Object.runScript (/var/lib/arangodb3/cluster/coordinator8529/data/js/server/modules/@arangodb/foxx/manager.js:952:17)
2019-02-01T09:57:19Z [15785] ERROR     at Object.exports.work (/var/lib/arangodb3/cluster/coordinator8529/data/js/server/modules/@arangodb/foxx/queues/worker.js:126:17)
2019-02-01T09:57:19Z [15785] ERROR     at eval (eval at <anonymous> (unknown source), <anonymous>:8:59)
2019-02-01T09:57:19Z [15785] ERROR     at eval (eval at <anonymous> (unknown source), <anonymous>:11:17)
2019-02-01T09:57:19Z [15785] ERROR     at eval (eval at <anonymous> (unknown source), <anonymous>:11:29)`
```

I would really appreciate some help to fix this.

**Comment by dothebart** [comment]
Hi,
are you using foxx services with foxx queues?

**Comment by dothebart** [comment]
ArangoDB 3.4 is EOLed meanwihle. 
[arangodb options](https://www.arangodb.com/docs/stable/programs-arangod-options.html) can be passed throug by the starter with [Passing through other database options](https://www.arangodb.com/docs/stable/programs-starter-options.html#passing-through-other-database-options).

Closing this as outdated with [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) being available.
