### ISSUE TITLE
Too large result set may cause out of memory

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb#9889]
I'm not sure how to get more information about my issue apart from this error:

```
01:01:52.210 [pool-1-thread-10] ERROR event.Erp - Response: 500, Error: 3 - AQL: out of memory (exception location: D:\c15-windows.build\oskar\work\ArangoDB\lib\V8\v8-vpack.cpp:118) (while executing) (exception location: D:\c15-windows.build\oskar\work\ArangoDB\arangod\RestHandler\RestCursorHandler.cpp:228)
com.arangodb.ArangoDBException: Response: 500, Error: 3 - AQL: out of memory (exception location: D:\c15-windows.build\oskar\work\ArangoDB\lib\V8\v8-vpack.cpp:118) (while executing) (exception location: D:\c15-windows.build\oskar\work\ArangoDB\arangod\RestHandler\RestCursorHandler.cpp:228)
	at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:53)
	at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:149)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:128)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:42)
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:132)
	at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:47)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:53)
	at com.arangodb.internal.ArangoDatabaseImpl.query(ArangoDatabaseImpl.java:197)
```

Because I don't quite understand it (i.e. There is no d: drive on my computer), I'm not sure wether its a bug or if I just need more memory somehow? I use arango 3.4.7. If someone could explain the error, I could create a reproducer or something else what is needed to identify the (maybe) bug.

**[UPDATE]** I figured out that it is caused by a query that generates a huge amount of data before sending it to a UDF. Either the sending to or receving from the UDF causes this error. By reducing the amount of data I could get rid of this error. What seemed strange to me was that the total memory of the arango instance was at 40%. I expected the memory usage to be arround 100% if I get an error like this.

**Please close this issue if this is too specific and not a bug!**

**Comment by graetzer** [comment]
There are memory limits per AQL query, as well as memory limits in V8 (which your user defined function runs in)

**Comment by konsultaner** [comment]
how can I mange the V8 memory limit. there is a setting for the AQL-Limit in the java driver but no configuration vor the V8 limit.

**Comment by dothebart** [comment]
The V8 memory limit is implementation specific and non in arangodb's control. You should strive to make the amount of data transfered into / out of the UDF as lean as possible - i.e. by only picking parts of your full document.
