### ISSUE TITLE
ArangoDB Web Interface not working after taking the latest AUR update

### ISSUE THREAD

**Issue by neel** [arangodb/arangodb#9891]
## My Environment

* __ArangoDB Version__:    3.4.7    
* __Storage Engine__:   RocksDB          
* __Deployment Mode__:  Single Server     
* __Deployment Strategy__:  ArangoDB Starter 
* __Configuration__:               
* __Infrastructure__:  own             
* __Operating System__:  Arch Linux      
* __Total RAM in your machine__:  32GB      
* __Disks in use__:        
* __Used Package__:   AUR            

## Component, Query & Data

__Affected feature__: Web Interface networking

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Install the latest update from AUR
2. 
3. 

__Problem__:
Cannot log in to the web interface (arangosh works)

__Expected result__:
 User will be able to login through the web interface

------------------------------------------------------------------------------
Following is the Error on `/var/log/arangodb3/arangod.log`

```
2019-09-02T12:02:51Z [643] INFO ArangoDB (version 3.4.7 [linux]) is ready for business. Have fun!
2019-09-03T12:13:07Z [643] ERROR Service "/_admin/aardvark" encountered an error while being mounted @ index.js:30:14
2019-09-03T12:13:07Z [643] ERROR   28 | 
2019-09-03T12:13:07Z [643] ERROR   29 | context.use(require('./aardvark'));
2019-09-03T12:13:07Z [643] ERROR > 30 | if (internal.isFoxxApiDisabled()) {
2019-09-03T12:13:07Z [643] ERROR      |              ^
2019-09-03T12:13:07Z [643] ERROR   31 |   context.service.router.all('/foxxes/*', (_req, res) => {
2019-09-03T12:13:07Z [643] ERROR   32 |     res.throw(403, new ArangoError({
2019-09-03T12:13:07Z [643] ERROR   33 |       errorNum: errors.ERROR_SERVICE_API_DISABLED.code, 
2019-09-03T12:13:07Z [643] ERROR 
2019-09-03T12:13:07Z [643] ERROR via ArangoError: failed to invoke module
2019-09-03T12:13:07Z [643] ERROR Reason: TypeError: internal.isFoxxApiDisabled is not a function
2019-09-03T12:13:07Z [643] ERROR File: /usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/index.js
2019-09-03T12:13:07Z [643] ERROR     at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:567:11)
2019-09-03T12:13:07Z [643] ERROR     at FoxxService.run (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/service.js:527:14)
2019-09-03T12:13:07Z [643] ERROR     at exports.routeService (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/routing.js:288:40)
2019-09-03T12:13:07Z [643] ERROR     at Object.ensureServiceLoaded [as ensureRouted] (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:447:10)
2019-09-03T12:13:07Z [643] ERROR     at foxxRouting (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:994:21)
2019-09-03T12:13:07Z [643] ERROR     at execute (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1234:7)
2019-09-03T12:13:07Z [643] ERROR     at Object.routeRequest (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1253:3)
2019-09-03T12:13:07Z [643] ERROR     at Function.callback (/usr/share/arangodb3/js/actions/api-system.js:54:15) 
2019-09-03T12:13:07Z [643] ERROR via TypeError: internal.isFoxxApiDisabled is not a function
2019-09-03T12:13:07Z [643] ERROR     at Object.<anonymous> (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/index.js:30:14)
2019-09-03T12:13:07Z [643] ERROR     at Module._compile (/usr/share/arangodb3/js/common/bootstrap/modules.js:609:8)
2019-09-03T12:13:07Z [643] ERROR     at Object.Module._extensions..js (/usr/share/arangodb3/js/common/bootstrap/modules.js:627:12)
2019-09-03T12:13:07Z [643] ERROR     at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:550:36)
2019-09-03T12:13:07Z [643] ERROR     at FoxxService.run (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/service.js:527:14)
2019-09-03T12:13:07Z [643] ERROR     at exports.routeService (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/routing.js:288:40)
2019-09-03T12:13:07Z [643] ERROR     at Object.ensureServiceLoaded [as ensureRouted] (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:447:10)
2019-09-03T12:13:07Z [643] ERROR     at foxxRouting (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:994:21)
2019-09-03T12:13:07Z [643] ERROR     at execute (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1234:7)
2019-09-03T12:13:07Z [643] ERROR     at Object.routeRequest (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1253:3)
```

**Comment by dothebart** [comment]
Hi, 
You're mixing up a js folder from 3.5 and a binary of ArangoDB 3.4 here. 
The .js code leans on functionality that only 3.5 will have.

**Comment by neel** [comment]
I don't have any such js folder. I have only updated the aur.

**Comment by dothebart** [comment]
Ok, 
With ArangoDB 3.4.8 these options were also added to the 3.4 branch:
```
* Fixed internal issue #3680 by adding two new options to make the server more secure:
  - `--foxx.api`: set to false disables Foxx management API
  - `--foxx.store`: set to false disables Foxx UI
```
Most probably you have a mix in binary / js Version which can be found there.

**Comment by maxkernbach** [comment]
Hi @neel,

Could you please share a status update on this ticket?
Did you manage to solve the issue with the help of dothebart's latest comment?

**Comment by neel** [comment]
@maxkernbach current version 3.5.0 working. I can login.
